# 01.1 — PyTorch Baselines on Test Set (ImageNet Val)

Same sweep as `01_fp32_baselines_sweep` but evaluated on the ImageNet validation split (test set).

Results saved under `resultsv2/test_runs/`.

In [9]:

SPLIT = "val"              # ImageNet val split (= "test" for this project)
OUTPUT_ROOT = "/home/pf4636/code/resnet/quantized_resnets/runs/test_infer"

In [10]:
from pathlib import Path
import sys

PROJECT_ROOT = Path("..").resolve()
PYFILES = PROJECT_ROOT / "pyfiles"
if str(PYFILES) not in sys.path:
    sys.path.insert(0, str(PYFILES))

In [11]:
import json
import time
import torch
import torch.nn as nn
import numpy as np
import pandas as pd

from src.config import ExperimentConfig, with_overrides, set_seed
from src.data import get_dataloader
from src.model import get_model
from src.eval import evaluate
from utils.precision import apply_precision
from utils.utils import load_runs, flatten_runs

pd.set_option("display.max_columns", 200)
print("torch:", torch.__version__, "| cuda:", torch.cuda.is_available())

torch: 2.10.0+cu130 | cuda: True

In [12]:
CKPT_ROOT = PROJECT_ROOT / "checkpoints"
INPUT_BITS = [8, 4, 2, 1]

checkpoints = {}
for bits in INPUT_BITS:
    ckpt_dir = CKPT_ROOT / f"fp32_{bits}bit"
    if not ckpt_dir.exists():
        continue
    for seed_dir in sorted(ckpt_dir.iterdir()):
        if seed_dir.is_dir() and (seed_dir / "best.pth").exists():
            checkpoints[(bits, seed_dir.name)] = str(seed_dir / "best.pth")

print("Checkpoints found:")
for (bits, seed), path in checkpoints.items():
    print(f"  {bits}bit / {seed}: {path}")

Checkpoints found:
  8bit / seed_1: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_8bit/seed_1/best.pth
  8bit / seed_2: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_8bit/seed_2/best.pth
  8bit / seed_42: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_8bit/seed_42/best.pth
  4bit / seed_1: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_4bit/seed_1/best.pth
  4bit / seed_2: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_4bit/seed_2/best.pth
  4bit / seed_42: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_4bit/seed_42/best.pth
  2bit / seed_1: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_2bit/seed_1/best.pth
  2bit / seed_2: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_2bit/seed_2/best.pth
  2bit / seed_42: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_2bit/seed_42/best.pth
  1bit / seed_1: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_1bit/seed_1/best.pth
  1bit / seed_2: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_1bit/seed_2/best.pth
  1bit / seed_42: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_1bit/seed_42/best.pth

In [13]:
def run_test_experiment(cfg, checkpoint_path, split=SPLIT):
    cfg = cfg.normalized()
    cfg.validate()
    set_seed(cfg)

    criterion = nn.CrossEntropyLoss()
    loader = get_dataloader(cfg, split=split)

    model = apply_precision(get_model(cfg, checkpoint_path=checkpoint_path), cfg)
    t0 = time.perf_counter()
    tracker = evaluate(model, loader, cfg, criterion=criterion)
    elapsed = round(time.perf_counter() - t0, 3)

    payload = {
        "status": "ok",
        "run_id": cfg.run_id(),
        "system": cfg.stamp(),
        "config": cfg.to_dict(),
        "results": tracker.summary(),
        "total_eval_time_sec": elapsed,
        "split": split,
        "error": None,
    }

    out_path = Path(cfg.output_root) / cfg.run_id() / "result.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        json.dump(payload, f, indent=2, sort_keys=True)
    print(f"  Saved: {out_path}")

    return payload

## FP32 Full Sweep (b=8, 4, 2, 1)

In [14]:
fp32_records = []

for (bits, seed), ckpt_path in checkpoints.items():
    print(f"\n{'='*60}")
    print(f"  {bits}bit / {seed}  |  precision: fp32")
    print(f"{'='*60}")

    cfg = with_overrides(
        ExperimentConfig(
            backend="pytorch", device="cuda", batch_size=1,
            seed=42, num_eval_batches=None,
            output_root=f"{OUTPUT_ROOT}/fp32_{bits}bit/{seed}",
        ),
        model_precision="fp32", input_quant_bits=bits,
    )
    payload = run_test_experiment(cfg, checkpoint_path=ckpt_path)
    fp32_records.append(payload)
    print(f"  top1={payload['results']['top1_acc']:.2f}%  top5={payload['results']['top5_acc']:.2f}%")

============================================================
  8bit / seed_1  |  precision: fp32
============================================================
[data] Filtered to 5000 samples across 100 classes.
Evaluating on 5000 batches (first 30 are warmup)...
  --- Warmup complete (30 batches) — starting metric collection ---
  Batch [40/5000] Top-1: 90.00% | Top-5: 100.00% | Infer: 2.79 ms/batch
  Batch [50/5000] Top-1: 95.00% | Top-5: 100.00% | Infer: 2.77 ms/batch
  Batch [60/5000] Top-1: 93.33% | Top-5: 100.00% | Infer: 2.66 ms/batch
  Batch [70/5000] Top-1: 90.00% | Top-5: 97.50% | Infer: 2.80 ms/batch
  Batch [80/5000] Top-1: 88.00% | Top-5: 98.00% | Infer: 2.71 ms/batch
  Batch [90/5000] Top-1: 90.00% | Top-5: 98.33% | Infer: 2.74 ms/batch
  Batch [100/5000] Top-1: 88.57% | Top-5: 98.57% | Infer: 2.76 ms/batch
  Batch [110/5000] Top-1: 88.75% | Top-5: 98.75% | Infer: 2.81 ms/batch
  Batch [120/5000] Top-1: 87.78% | Top-5: 97.78% | Infer: 2.91 ms/batch
  Batch [130/5000] Top-1: 89.00% | Top-5: 98.00% | Infer: 2.95 ms/batch
  Batch [140/5000] Top-1: 89.09% | Top-5: 98.18% | Infer: 2.90 ms/batch
  Batch [150/5000] Top-1: 87.50% | Top-5: 97.50% | Infer: 2.89 ms/batch
  Batch [160/5000] Top-1: 86.92% | Top-5: 97.69% | Infer: 2.88 ms/batch
  Batch [170/5000] Top-1: 84.29% | Top-5: 97.86% | Infer: 2.92 ms/batch
  Batch [180/5000] Top-1: 84.00% | Top-5: 97.33% | Infer: 2.95 ms/batch
  Batch [190/5000] Top-1: 83.12% | Top-5: 96.88% | Infer: 2.95 ms/batch
  Batch [200/5000] Top-1: 82.94% | Top-5: 96.47% | Infer: 2.93 ms/batch
  Batch [210/5000] Top-1: 82.78% | Top-5: 96.11% | Infer: 2.95 ms/batch
  Batch [220/5000] Top-1: 83.16% | Top-5: 95.79% | Infer: 2.92 ms/batch
  Batch [230/5000] Top-1: 82.50% | Top-5: 96.00% | Infer: 2.92 ms/batch
  Batch [240/5000] Top-1: 81.90% | Top-5: 96.19% | Infer: 2.89 ms/batch
  Batch [250/5000] Top-1: 81.36% | Top-5: 96.36% | Infer: 2.89 ms/batch
  Batch [260/5000] Top-1: 81.30% | Top-5: 96.52% | Infer: 2.91 ms/batch
  Batch [270/5000] Top-1: 80.00% | Top-5: 95.83% | Infer: 2.91 ms/batch
  Batch [280/5000] Top-1: 80.00% | Top-5: 95.60% | Infer: 2.90 ms/batch
  Batch [290/5000] Top-1: 80.38% | Top-5: 95.77% | Infer: 2.90 ms/batch
  Batch [300/5000] Top-1: 80.00% | Top-5: 95.56% | Infer: 2.88 ms/batch
  Batch [310/5000] Top-1: 79.29% | Top-5: 95.36% | Infer: 2.90 ms/batch
  Batch [320/5000] Top-1: 79.31% | Top-5: 95.52% | Infer: 2.87 ms/batch
  Batch [330/5000] Top-1: 79.33% | Top-5: 95.67% | Infer: 2.85 ms/batch
  Batch [340/5000] Top-1: 78.71% | Top-5: 95.81% | Infer: 2.85 ms/batch
  Batch [350/5000] Top-1: 78.44% | Top-5: 95.62% | Infer: 2.87 ms/batch
  Batch [360/5000] Top-1: 77.58% | Top-5: 95.76% | Infer: 2.87 ms/batch
  Batch [370/5000] Top-1: 76.76% | Top-5: 95.29% | Infer: 2.87 ms/batch
  Batch [380/5000] Top-1: 76.57% | Top-5: 95.43% | Infer: 2.87 ms/batch
  Batch [390/5000] Top-1: 76.94% | Top-5: 95.28% | Infer: 2.87 ms/batch
  Batch [400/5000] Top-1: 76.76% | Top-5: 95.14% | Infer: 2.86 ms/batch
  Batch [410/5000] Top-1: 76.84% | Top-5: 95.00% | Infer: 2.86 ms/batch
  Batch [420/5000] Top-1: 76.92% | Top-5: 95.13% | Infer: 2.86 ms/batch
  Batch [430/5000] Top-1: 77.25% | Top-5: 95.25% | Infer: 2.87 ms/batch
  Batch [440/5000] Top-1: 77.32% | Top-5: 95.37% | Infer: 2.86 ms/batch
  Batch [450/5000] Top-1: 77.62% | Top-5: 95.48% | Infer: 2.85 ms/batch
  Batch [460/5000] Top-1: 78.14% | Top-5: 95.58% | Infer: 2.88 ms/batch
  Batch [470/5000] Top-1: 78.64% | Top-5: 95.68% | Infer: 2.87 ms/batch
  Batch [480/5000] Top-1: 79.11% | Top-5: 95.78% | Infer: 2.88 ms/batch
  Batch [490/5000] Top-1: 79.35% | Top-5: 95.87% | Infer: 2.87 ms/batch
  Batch [500/5000] Top-1: 79.79% | Top-5: 95.96% | Infer: 2.89 ms/batch
  Batch [510/5000] Top-1: 80.00% | Top-5: 95.83% | Infer: 2.88 ms/batch
  Batch [520/5000] Top-1: 80.41% | Top-5: 95.92% | Infer: 2.89 ms/batch
  Batch [530/5000] Top-1: 80.40% | Top-5: 95.80% | Infer: 2.91 ms/batch
  Batch [540/5000] Top-1: 80.59% | Top-5: 95.88% | Infer: 2.91 ms/batch
  Batch [550/5000] Top-1: 80.77% | Top-5: 95.96% | Infer: 2.91 ms/batch
  Batch [560/5000] Top-1: 81.13% | Top-5: 96.04% | Infer: 2.90 ms/batch
  Batch [570/5000] Top-1: 81.48% | Top-5: 96.11% | Infer: 2.90 ms/batch
  Batch [580/5000] Top-1: 81.82% | Top-5: 96.18% | Infer: 2.90 ms/batch
  Batch [590/5000] Top-1: 81.96% | Top-5: 96.25% | Infer: 2.91 ms/batch
  Batch [600/5000] Top-1: 82.11% | Top-5: 96.32% | Infer: 2.92 ms/batch
  Batch [610/5000] Top-1: 82.24% | Top-5: 96.38% | Infer: 2.91 ms/batch
  Batch [620/5000] Top-1: 82.03% | Top-5: 95.93% | Infer: 2.91 ms/batch
  Batch [630/5000] Top-1: 82.33% | Top-5: 96.00% | Infer: 2.91 ms/batch
  Batch [640/5000] Top-1: 82.30% | Top-5: 96.07% | Infer: 2.91 ms/batch
  Batch [650/5000] Top-1: 82.42% | Top-5: 96.13% | Infer: 2.91 ms/batch
  Batch [660/5000] Top-1: 82.70% | Top-5: 96.19% | Infer: 2.91 ms/batch
  Batch [670/5000] Top-1: 82.97% | Top-5: 96.25% | Infer: 2.90 ms/batch
  Batch [680/5000] Top-1: 83.23% | Top-5: 96.31% | Infer: 2.90 ms/batch
  Batch [690/5000] Top-1: 83.48% | Top-5: 96.36% | Infer: 2.89 ms/batch
  Batch [700/5000] Top-1: 83.73% | Top-5: 96.42% | Infer: 2.90 ms/batch
  Batch [710/5000] Top-1: 83.82% | Top-5: 96.47% | Infer: 2.89 ms/batch
  Batch [720/5000] Top-1: 84.06% | Top-5: 96.52% | Infer: 2.89 ms/batch
  Batch [730/5000] Top-1: 84.00% | Top-5: 96.57% | Infer: 2.88 ms/batch
  Batch [740/5000] Top-1: 83.94% | Top-5: 96.62% | Infer: 2.88 ms/batch
  Batch [750/5000] Top-1: 84.17% | Top-5: 96.67% | Infer: 2.89 ms/batch
  Batch [760/5000] Top-1: 84.25% | Top-5: 96.71% | Infer: 2.90 ms/batch
  Batch [770/5000] Top-1: 84.32% | Top-5: 96.76% | Infer: 2.89 ms/batch
  Batch [780/5000] Top-1: 84.53% | Top-5: 96.80% | Infer: 2.90 ms/batch
  Batch [790/5000] Top-1: 84.74% | Top-5: 96.84% | Infer: 2.90 ms/batch
  Batch [800/5000] Top-1: 84.81% | Top-5: 96.75% | Infer: 2.90 ms/batch
  Batch [810/5000] Top-1: 84.87% | Top-5: 96.67% | Infer: 2.90 ms/batch
  Batch [820/5000] Top-1: 84.81% | Top-5: 96.46% | Infer: 2.91 ms/batch
  Batch [830/5000] Top-1: 84.88% | Top-5: 96.50% | Infer: 2.92 ms/batch
  Batch [840/5000] Top-1: 84.94% | Top-5: 96.54% | Infer: 2.92 ms/batch
  Batch [850/5000] Top-1: 84.88% | Top-5: 96.59% | Infer: 2.93 ms/batch
  Batch [860/5000] Top-1: 84.82% | Top-5: 96.51% | Infer: 2.93 ms/batch
  Batch [870/5000] Top-1: 84.88% | Top-5: 96.55% | Infer: 2.94 ms/batch
  Batch [880/5000] Top-1: 84.71% | Top-5: 96.59% | Infer: 2.94 ms/batch
  Batch [890/5000] Top-1: 84.88% | Top-5: 96.63% | Infer: 2.94 ms/batch
  Batch [900/5000] Top-1: 85.06% | Top-5: 96.67% | Infer: 2.94 ms/batch
  Batch [910/5000] Top-1: 85.23% | Top-5: 96.70% | Infer: 2.93 ms/batch
  Batch [920/5000] Top-1: 85.28% | Top-5: 96.63% | Infer: 2.93 ms/batch
  Batch [930/5000] Top-1: 85.22% | Top-5: 96.67% | Infer: 2.93 ms/batch
  Batch [940/5000] Top-1: 85.05% | Top-5: 96.48% | Infer: 2.93 ms/batch
  Batch [950/5000] Top-1: 85.00% | Top-5: 96.41% | Infer: 2.93 ms/batch
  Batch [960/5000] Top-1: 84.95% | Top-5: 96.34% | Infer: 2.93 ms/batch
  Batch [970/5000] Top-1: 85.00% | Top-5: 96.38% | Infer: 2.93 ms/batch
  Batch [980/5000] Top-1: 85.05% | Top-5: 96.42% | Infer: 2.93 ms/batch
  Batch [990/5000] Top-1: 85.21% | Top-5: 96.46% | Infer: 2.93 ms/batch
  Batch [1000/5000] Top-1: 85.26% | Top-5: 96.49% | Infer: 2.93 ms/batch
  Batch [1010/5000] Top-1: 85.31% | Top-5: 96.53% | Infer: 2.94 ms/batch
  Batch [1020/5000] Top-1: 85.35% | Top-5: 96.46% | Infer: 2.93 ms/batch
  Batch [1030/5000] Top-1: 85.30% | Top-5: 96.40% | Infer: 2.94 ms/batch
  Batch [1040/5000] Top-1: 85.35% | Top-5: 96.44% | Infer: 2.94 ms/batch
  Batch [1050/5000] Top-1: 85.39% | Top-5: 96.37% | Infer: 2.94 ms/batch
  Batch [1060/5000] Top-1: 85.24% | Top-5: 96.21% | Infer: 2.94 ms/batch
  Batch [1070/5000] Top-1: 85.10% | Top-5: 96.15% | Infer: 2.94 ms/batch
  Batch [1080/5000] Top-1: 85.05% | Top-5: 96.10% | Infer: 2.94 ms/batch
  Batch [1090/5000] Top-1: 85.09% | Top-5: 96.13% | Infer: 2.95 ms/batch
  Batch [1100/5000] Top-1: 84.95% | Top-5: 96.07% | Infer: 2.95 ms/batch
  Batch [1110/5000] Top-1: 85.00% | Top-5: 96.02% | Infer: 2.95 ms/batch
  Batch [1120/5000] Top-1: 85.05% | Top-5: 96.06% | Infer: 2.95 ms/batch
  Batch [1130/5000] Top-1: 85.18% | Top-5: 96.09% | Infer: 2.96 ms/batch
  Batch [1140/5000] Top-1: 85.23% | Top-5: 96.13% | Infer: 2.96 ms/batch
  Batch [1150/5000] Top-1: 85.36% | Top-5: 96.16% | Infer: 2.97 ms/batch
  Batch [1160/5000] Top-1: 85.40% | Top-5: 96.19% | Infer: 2.98 ms/batch
  Batch [1170/5000] Top-1: 85.35% | Top-5: 96.14% | Infer: 2.99 ms/batch
  Batch [1180/5000] Top-1: 85.39% | Top-5: 96.17% | Infer: 2.98 ms/batch
  Batch [1190/5000] Top-1: 85.34% | Top-5: 96.12% | Infer: 2.99 ms/batch
  Batch [1200/5000] Top-1: 85.21% | Top-5: 96.15% | Infer: 2.99 ms/batch
  Batch [1210/5000] Top-1: 85.25% | Top-5: 96.10% | Infer: 2.99 ms/batch
  Batch [1220/5000] Top-1: 85.38% | Top-5: 96.13% | Infer: 2.99 ms/batch
  Batch [1230/5000] Top-1: 85.50% | Top-5: 96.17% | Infer: 2.98 ms/batch
  Batch [1240/5000] Top-1: 85.62% | Top-5: 96.20% | Infer: 2.98 ms/batch
  Batch [1250/5000] Top-1: 85.74% | Top-5: 96.23% | Infer: 2.98 ms/batch
  Batch [1260/5000] Top-1: 85.77% | Top-5: 96.18% | Infer: 2.98 ms/batch
  Batch [1270/5000] Top-1: 85.89% | Top-5: 96.21% | Infer: 2.98 ms/batch
  Batch [1280/5000] Top-1: 86.00% | Top-5: 96.24% | Infer: 2.99 ms/batch
  Batch [1290/5000] Top-1: 86.11% | Top-5: 96.27% | Infer: 2.99 ms/batch
  Batch [1300/5000] Top-1: 86.22% | Top-5: 96.30% | Infer: 2.99 ms/batch
  Batch [1310/5000] Top-1: 86.02% | Top-5: 96.33% | Infer: 2.99 ms/batch
  Batch [1320/5000] Top-1: 86.05% | Top-5: 96.36% | Infer: 2.99 ms/batch
  Batch [1330/5000] Top-1: 85.62% | Top-5: 96.15% | Infer: 2.98 ms/batch
  Batch [1340/5000] Top-1: 85.27% | Top-5: 96.11% | Infer: 2.98 ms/batch
  Batch [1350/5000] Top-1: 84.77% | Top-5: 95.98% | Infer: 2.98 ms/batch
  Batch [1360/5000] Top-1: 84.74% | Top-5: 95.94% | Infer: 2.98 ms/batch
  Batch [1370/5000] Top-1: 84.70% | Top-5: 95.97% | Infer: 2.97 ms/batch
  Batch [1380/5000] Top-1: 84.52% | Top-5: 95.85% | Infer: 2.97 ms/batch
  Batch [1390/5000] Top-1: 84.34% | Top-5: 95.81% | Infer: 2.97 ms/batch
  Batch [1400/5000] Top-1: 84.38% | Top-5: 95.84% | Infer: 2.97 ms/batch
  Batch [1410/5000] Top-1: 84.28% | Top-5: 95.87% | Infer: 2.97 ms/batch
  Batch [1420/5000] Top-1: 84.39% | Top-5: 95.90% | Infer: 2.98 ms/batch
  Batch [1430/5000] Top-1: 84.43% | Top-5: 95.86% | Infer: 2.98 ms/batch
  Batch [1440/5000] Top-1: 84.54% | Top-5: 95.89% | Infer: 2.97 ms/batch
  Batch [1450/5000] Top-1: 84.58% | Top-5: 95.92% | Infer: 2.97 ms/batch
  Batch [1460/5000] Top-1: 84.62% | Top-5: 95.94% | Infer: 2.97 ms/batch
  Batch [1470/5000] Top-1: 84.58% | Top-5: 95.97% | Infer: 2.97 ms/batch
  Batch [1480/5000] Top-1: 84.62% | Top-5: 95.93% | Infer: 2.98 ms/batch
  Batch [1490/5000] Top-1: 84.66% | Top-5: 95.89% | Infer: 2.98 ms/batch
  Batch [1500/5000] Top-1: 84.56% | Top-5: 95.85% | Infer: 2.98 ms/batch
  Batch [1510/5000] Top-1: 84.46% | Top-5: 95.68% | Infer: 2.99 ms/batch
  Batch [1520/5000] Top-1: 84.50% | Top-5: 95.64% | Infer: 2.99 ms/batch
  Batch [1530/5000] Top-1: 84.47% | Top-5: 95.67% | Infer: 2.99 ms/batch
  Batch [1540/5000] Top-1: 84.44% | Top-5: 95.70% | Infer: 2.99 ms/batch
  Batch [1550/5000] Top-1: 84.41% | Top-5: 95.66% | Infer: 3.00 ms/batch
  Batch [1560/5000] Top-1: 84.38% | Top-5: 95.69% | Infer: 2.99 ms/batch
  Batch [1570/5000] Top-1: 84.29% | Top-5: 95.58% | Infer: 2.99 ms/batch
  Batch [1580/5000] Top-1: 84.26% | Top-5: 95.61% | Infer: 2.99 ms/batch
  Batch [1590/5000] Top-1: 84.17% | Top-5: 95.58% | Infer: 3.00 ms/batch
  Batch [1600/5000] Top-1: 84.14% | Top-5: 95.54% | Infer: 3.00 ms/batch
  Batch [1610/5000] Top-1: 83.80% | Top-5: 95.44% | Infer: 3.00 ms/batch
  Batch [1620/5000] Top-1: 83.58% | Top-5: 95.41% | Infer: 3.00 ms/batch
  Batch [1630/5000] Top-1: 83.50% | Top-5: 95.44% | Infer: 3.00 ms/batch
  Batch [1640/5000] Top-1: 83.11% | Top-5: 95.22% | Infer: 3.00 ms/batch
  Batch [1650/5000] Top-1: 82.78% | Top-5: 94.94% | Infer: 2.99 ms/batch
  Batch [1660/5000] Top-1: 82.76% | Top-5: 94.91% | Infer: 3.00 ms/batch
  Batch [1670/5000] Top-1: 82.80% | Top-5: 94.88% | Infer: 3.00 ms/batch
  Batch [1680/5000] Top-1: 82.79% | Top-5: 94.91% | Infer: 3.00 ms/batch
  Batch [1690/5000] Top-1: 82.83% | Top-5: 94.94% | Infer: 3.00 ms/batch
  Batch [1700/5000] Top-1: 82.75% | Top-5: 94.91% | Infer: 3.00 ms/batch
  Batch [1710/5000] Top-1: 82.68% | Top-5: 94.88% | Infer: 3.00 ms/batch
  Batch [1720/5000] Top-1: 82.60% | Top-5: 94.85% | Infer: 3.00 ms/batch
  Batch [1730/5000] Top-1: 82.41% | Top-5: 94.76% | Infer: 3.00 ms/batch
  Batch [1740/5000] Top-1: 82.28% | Top-5: 94.68% | Infer: 3.00 ms/batch
  Batch [1750/5000] Top-1: 82.33% | Top-5: 94.65% | Infer: 3.01 ms/batch
  Batch [1760/5000] Top-1: 82.08% | Top-5: 94.68% | Infer: 3.01 ms/batch
  Batch [1770/5000] Top-1: 81.90% | Top-5: 94.54% | Infer: 3.01 ms/batch
  Batch [1780/5000] Top-1: 81.89% | Top-5: 94.51% | Infer: 3.01 ms/batch
  Batch [1790/5000] Top-1: 81.65% | Top-5: 94.43% | Infer: 3.00 ms/batch
  Batch [1800/5000] Top-1: 81.58% | Top-5: 94.35% | Infer: 3.00 ms/batch
  Batch [1810/5000] Top-1: 81.24% | Top-5: 94.38% | Infer: 3.00 ms/batch
  Batch [1820/5000] Top-1: 81.12% | Top-5: 94.36% | Infer: 3.00 ms/batch
  Batch [1830/5000] Top-1: 80.94% | Top-5: 94.33% | Infer: 3.00 ms/batch
  Batch [1840/5000] Top-1: 80.83% | Top-5: 94.36% | Infer: 3.00 ms/batch
  Batch [1850/5000] Top-1: 80.82% | Top-5: 94.40% | Infer: 3.00 ms/batch
  Batch [1860/5000] Top-1: 80.77% | Top-5: 94.32% | Infer: 3.00 ms/batch
  Batch [1870/5000] Top-1: 80.82% | Top-5: 94.35% | Infer: 3.00 ms/batch
  Batch [1880/5000] Top-1: 80.81% | Top-5: 94.38% | Infer: 3.00 ms/batch
  Batch [1890/5000] Top-1: 80.81% | Top-5: 94.41% | Infer: 3.00 ms/batch
  Batch [1900/5000] Top-1: 80.75% | Top-5: 94.44% | Infer: 3.00 ms/batch
  Batch [1910/5000] Top-1: 80.69% | Top-5: 94.47% | Infer: 3.00 ms/batch
  Batch [1920/5000] Top-1: 80.63% | Top-5: 94.39% | Infer: 3.00 ms/batch
  Batch [1930/5000] Top-1: 80.68% | Top-5: 94.37% | Infer: 3.00 ms/batch
  Batch [1940/5000] Top-1: 80.58% | Top-5: 94.35% | Infer: 3.00 ms/batch
  Batch [1950/5000] Top-1: 80.47% | Top-5: 94.27% | Infer: 3.00 ms/batch
  Batch [1960/5000] Top-1: 80.47% | Top-5: 94.30% | Infer: 3.00 ms/batch
  Batch [1970/5000] Top-1: 80.52% | Top-5: 94.28% | Infer: 3.00 ms/batch
  Batch [1980/5000] Top-1: 80.46% | Top-5: 94.31% | Infer: 3.00 ms/batch
  Batch [1990/5000] Top-1: 80.56% | Top-5: 94.34% | Infer: 3.00 ms/batch
  Batch [2000/5000] Top-1: 80.46% | Top-5: 94.31% | Infer: 3.00 ms/batch
  Batch [2010/5000] Top-1: 80.40% | Top-5: 94.34% | Infer: 2.99 ms/batch
  Batch [2020/5000] Top-1: 80.25% | Top-5: 94.37% | Infer: 3.00 ms/batch
  Batch [2030/5000] Top-1: 79.95% | Top-5: 94.35% | Infer: 3.00 ms/batch
  Batch [2040/5000] Top-1: 79.80% | Top-5: 94.38% | Infer: 3.00 ms/batch
  Batch [2050/5000] Top-1: 79.65% | Top-5: 94.36% | Infer: 2.99 ms/batch
  Batch [2060/5000] Top-1: 79.61% | Top-5: 94.24% | Infer: 2.99 ms/batch
  Batch [2070/5000] Top-1: 79.66% | Top-5: 94.26% | Infer: 2.99 ms/batch
  Batch [2080/5000] Top-1: 79.66% | Top-5: 94.24% | Infer: 2.99 ms/batch
  Batch [2090/5000] Top-1: 79.61% | Top-5: 94.17% | Infer: 2.99 ms/batch
  Batch [2100/5000] Top-1: 79.66% | Top-5: 94.20% | Infer: 2.99 ms/batch
  Batch [2110/5000] Top-1: 79.52% | Top-5: 94.13% | Infer: 2.99 ms/batch
  Batch [2120/5000] Top-1: 79.43% | Top-5: 94.11% | Infer: 2.99 ms/batch
  Batch [2130/5000] Top-1: 79.48% | Top-5: 94.10% | Infer: 2.98 ms/batch
  Batch [2140/5000] Top-1: 79.48% | Top-5: 94.08% | Infer: 2.98 ms/batch
  Batch [2150/5000] Top-1: 79.48% | Top-5: 94.10% | Infer: 2.98 ms/batch
  Batch [2160/5000] Top-1: 79.48% | Top-5: 94.08% | Infer: 2.98 ms/batch
  Batch [2170/5000] Top-1: 79.39% | Top-5: 94.07% | Infer: 2.99 ms/batch
  Batch [2180/5000] Top-1: 79.40% | Top-5: 94.00% | Infer: 2.98 ms/batch
  Batch [2190/5000] Top-1: 79.44% | Top-5: 94.03% | Infer: 2.98 ms/batch
  Batch [2200/5000] Top-1: 79.45% | Top-5: 94.01% | Infer: 2.98 ms/batch
  Batch [2210/5000] Top-1: 79.45% | Top-5: 93.99% | Infer: 2.98 ms/batch
  Batch [2220/5000] Top-1: 79.27% | Top-5: 93.88% | Infer: 2.98 ms/batch
  Batch [2230/5000] Top-1: 79.23% | Top-5: 93.86% | Infer: 2.98 ms/batch
  Batch [2240/5000] Top-1: 78.96% | Top-5: 93.57% | Infer: 2.98 ms/batch
  Batch [2250/5000] Top-1: 78.96% | Top-5: 93.56% | Infer: 2.99 ms/batch
  Batch [2260/5000] Top-1: 78.79% | Top-5: 93.50% | Infer: 2.99 ms/batch
  Batch [2270/5000] Top-1: 78.88% | Top-5: 93.53% | Infer: 2.99 ms/batch
  Batch [2280/5000] Top-1: 78.93% | Top-5: 93.56% | Infer: 2.99 ms/batch
  Batch [2290/5000] Top-1: 78.94% | Top-5: 93.54% | Infer: 2.99 ms/batch
  Batch [2300/5000] Top-1: 78.94% | Top-5: 93.52% | Infer: 2.99 ms/batch
  Batch [2310/5000] Top-1: 78.77% | Top-5: 93.55% | Infer: 2.99 ms/batch
  Batch [2320/5000] Top-1: 78.69% | Top-5: 93.54% | Infer: 2.99 ms/batch
  Batch [2330/5000] Top-1: 78.52% | Top-5: 93.52% | Infer: 2.99 ms/batch
  Batch [2340/5000] Top-1: 78.53% | Top-5: 93.55% | Infer: 2.99 ms/batch
  Batch [2350/5000] Top-1: 78.36% | Top-5: 93.58% | Infer: 2.99 ms/batch
  Batch [2360/5000] Top-1: 78.33% | Top-5: 93.52% | Infer: 2.99 ms/batch
  Batch [2370/5000] Top-1: 78.33% | Top-5: 93.50% | Infer: 2.99 ms/batch
  Batch [2380/5000] Top-1: 78.21% | Top-5: 93.36% | Infer: 2.99 ms/batch
  Batch [2390/5000] Top-1: 78.18% | Top-5: 93.31% | Infer: 2.99 ms/batch
  Batch [2400/5000] Top-1: 78.27% | Top-5: 93.33% | Infer: 2.99 ms/batch
  Batch [2410/5000] Top-1: 78.32% | Top-5: 93.36% | Infer: 2.99 ms/batch
  Batch [2420/5000] Top-1: 78.37% | Top-5: 93.39% | Infer: 3.00 ms/batch
  Batch [2430/5000] Top-1: 78.42% | Top-5: 93.42% | Infer: 3.00 ms/batch
  Batch [2440/5000] Top-1: 78.46% | Top-5: 93.44% | Infer: 3.00 ms/batch
  Batch [2450/5000] Top-1: 78.55% | Top-5: 93.47% | Infer: 3.00 ms/batch
  Batch [2460/5000] Top-1: 78.52% | Top-5: 93.46% | Infer: 3.00 ms/batch
  Batch [2470/5000] Top-1: 78.36% | Top-5: 93.40% | Infer: 3.00 ms/batch
  Batch [2480/5000] Top-1: 78.33% | Top-5: 93.39% | Infer: 3.00 ms/batch
  Batch [2490/5000] Top-1: 78.25% | Top-5: 93.37% | Infer: 3.00 ms/batch
  Batch [2500/5000] Top-1: 78.22% | Top-5: 93.40% | Infer: 3.00 ms/batch
  Batch [2510/5000] Top-1: 78.27% | Top-5: 93.43% | Infer: 3.00 ms/batch
  Batch [2520/5000] Top-1: 78.19% | Top-5: 93.45% | Infer: 3.00 ms/batch
  Batch [2530/5000] Top-1: 78.16% | Top-5: 93.48% | Infer: 3.00 ms/batch
  Batch [2540/5000] Top-1: 78.17% | Top-5: 93.51% | Infer: 3.00 ms/batch
  Batch [2550/5000] Top-1: 78.17% | Top-5: 93.49% | Infer: 3.00 ms/batch
  Batch [2560/5000] Top-1: 78.18% | Top-5: 93.48% | Infer: 2.99 ms/batch
  Batch [2570/5000] Top-1: 78.19% | Top-5: 93.46% | Infer: 2.99 ms/batch
  Batch [2580/5000] Top-1: 78.27% | Top-5: 93.49% | Infer: 2.99 ms/batch
  Batch [2590/5000] Top-1: 78.28% | Top-5: 93.48% | Infer: 2.99 ms/batch
  Batch [2600/5000] Top-1: 78.37% | Top-5: 93.50% | Infer: 2.99 ms/batch
  Batch [2610/5000] Top-1: 78.37% | Top-5: 93.53% | Infer: 2.99 ms/batch
  Batch [2620/5000] Top-1: 78.46% | Top-5: 93.55% | Infer: 2.99 ms/batch
  Batch [2630/5000] Top-1: 78.46% | Top-5: 93.58% | Infer: 2.99 ms/batch
  Batch [2640/5000] Top-1: 78.31% | Top-5: 93.52% | Infer: 2.99 ms/batch
  Batch [2650/5000] Top-1: 78.21% | Top-5: 93.44% | Infer: 2.99 ms/batch
  Batch [2660/5000] Top-1: 78.25% | Top-5: 93.42% | Infer: 2.99 ms/batch
  Batch [2670/5000] Top-1: 78.22% | Top-5: 93.45% | Infer: 2.99 ms/batch
  Batch [2680/5000] Top-1: 78.23% | Top-5: 93.43% | Infer: 3.00 ms/batch
  Batch [2690/5000] Top-1: 78.20% | Top-5: 93.42% | Infer: 3.00 ms/batch
  Batch [2700/5000] Top-1: 78.13% | Top-5: 93.41% | Infer: 3.00 ms/batch
  Batch [2710/5000] Top-1: 77.99% | Top-5: 93.28% | Infer: 3.00 ms/batch
  Batch [2720/5000] Top-1: 77.92% | Top-5: 93.27% | Infer: 3.00 ms/batch
  Batch [2730/5000] Top-1: 77.81% | Top-5: 93.19% | Infer: 3.00 ms/batch

## FP16 Full Sweep (b=8, 4, 2, 1)

In [15]:
fp16_records = []

for (bits, seed), ckpt_path in checkpoints.items():
    print(f"\n{'='*60}")
    print(f"  {bits}bit / {seed}  |  precision: fp16")
    print(f"{'='*60}")

    cfg = with_overrides(
        ExperimentConfig(
            backend="pytorch", device="cuda", batch_size=1,
            seed=42, num_eval_batches=None,
            output_root=f"{OUTPUT_ROOT}/fp32_{bits}bit/{seed}",
        ),
        model_precision="fp16", input_quant_bits=bits,
    )
    payload = run_test_experiment(cfg, checkpoint_path=ckpt_path)
    fp16_records.append(payload)
    print(f"  top1={payload['results']['top1_acc']:.2f}%  top5={payload['results']['top5_acc']:.2f}%")

============================================================
  8bit / seed_1  |  precision: fp16
============================================================
[data] Filtered to 5000 samples across 100 classes.
Evaluating on 5000 batches (first 30 are warmup)...
  --- Warmup complete (30 batches) — starting metric collection ---
  Batch [40/5000] Top-1: 90.00% | Top-5: 100.00% | Infer: 2.75 ms/batch
  Batch [50/5000] Top-1: 95.00% | Top-5: 100.00% | Infer: 2.64 ms/batch
  Batch [60/5000] Top-1: 93.33% | Top-5: 100.00% | Infer: 2.67 ms/batch
  Batch [70/5000] Top-1: 90.00% | Top-5: 97.50% | Infer: 2.71 ms/batch
  Batch [80/5000] Top-1: 88.00% | Top-5: 98.00% | Infer: 2.78 ms/batch
  Batch [90/5000] Top-1: 90.00% | Top-5: 98.33% | Infer: 2.74 ms/batch
  Batch [100/5000] Top-1: 88.57% | Top-5: 98.57% | Infer: 2.73 ms/batch
  Batch [110/5000] Top-1: 88.75% | Top-5: 98.75% | Infer: 2.67 ms/batch
  Batch [120/5000] Top-1: 87.78% | Top-5: 97.78% | Infer: 2.64 ms/batch
  Batch [130/5000] Top-1: 89.00% | Top-5: 98.00% | Infer: 2.64 ms/batch
  Batch [140/5000] Top-1: 89.09% | Top-5: 98.18% | Infer: 2.70 ms/batch
  Batch [150/5000] Top-1: 87.50% | Top-5: 97.50% | Infer: 2.74 ms/batch
  Batch [160/5000] Top-1: 86.92% | Top-5: 97.69% | Infer: 2.67 ms/batch
  Batch [170/5000] Top-1: 84.29% | Top-5: 97.86% | Infer: 2.71 ms/batch
  Batch [180/5000] Top-1: 84.00% | Top-5: 97.33% | Infer: 2.74 ms/batch
  Batch [190/5000] Top-1: 83.12% | Top-5: 96.88% | Infer: 2.71 ms/batch
  Batch [200/5000] Top-1: 82.94% | Top-5: 96.47% | Infer: 2.74 ms/batch
  Batch [210/5000] Top-1: 82.78% | Top-5: 96.11% | Infer: 2.77 ms/batch
  Batch [220/5000] Top-1: 83.16% | Top-5: 95.79% | Infer: 2.76 ms/batch
  Batch [230/5000] Top-1: 82.50% | Top-5: 96.00% | Infer: 2.75 ms/batch
  Batch [240/5000] Top-1: 81.90% | Top-5: 96.19% | Infer: 2.74 ms/batch
  Batch [250/5000] Top-1: 81.36% | Top-5: 96.36% | Infer: 2.79 ms/batch
  Batch [260/5000] Top-1: 81.30% | Top-5: 96.52% | Infer: 2.79 ms/batch
  Batch [270/5000] Top-1: 80.00% | Top-5: 95.83% | Infer: 2.79 ms/batch
  Batch [280/5000] Top-1: 80.00% | Top-5: 95.60% | Infer: 2.79 ms/batch
  Batch [290/5000] Top-1: 80.38% | Top-5: 95.77% | Infer: 2.84 ms/batch
  Batch [300/5000] Top-1: 80.00% | Top-5: 95.56% | Infer: 2.85 ms/batch
  Batch [310/5000] Top-1: 79.29% | Top-5: 95.36% | Infer: 2.87 ms/batch
  Batch [320/5000] Top-1: 79.31% | Top-5: 95.52% | Infer: 2.87 ms/batch
  Batch [330/5000] Top-1: 79.33% | Top-5: 95.67% | Infer: 2.86 ms/batch
  Batch [340/5000] Top-1: 78.71% | Top-5: 95.81% | Infer: 2.87 ms/batch
  Batch [350/5000] Top-1: 78.44% | Top-5: 95.62% | Infer: 2.85 ms/batch
  Batch [360/5000] Top-1: 77.58% | Top-5: 95.76% | Infer: 2.86 ms/batch
  Batch [370/5000] Top-1: 76.76% | Top-5: 95.29% | Infer: 2.84 ms/batch
  Batch [380/5000] Top-1: 76.57% | Top-5: 95.43% | Infer: 2.83 ms/batch
  Batch [390/5000] Top-1: 76.94% | Top-5: 95.28% | Infer: 2.84 ms/batch
  Batch [400/5000] Top-1: 76.76% | Top-5: 95.14% | Infer: 2.83 ms/batch
  Batch [410/5000] Top-1: 76.84% | Top-5: 95.00% | Infer: 2.82 ms/batch
  Batch [420/5000] Top-1: 76.92% | Top-5: 95.13% | Infer: 2.81 ms/batch
  Batch [430/5000] Top-1: 77.25% | Top-5: 95.25% | Infer: 2.81 ms/batch
  Batch [440/5000] Top-1: 77.32% | Top-5: 95.37% | Infer: 2.82 ms/batch
  Batch [450/5000] Top-1: 77.62% | Top-5: 95.48% | Infer: 2.83 ms/batch
  Batch [460/5000] Top-1: 78.14% | Top-5: 95.58% | Infer: 2.84 ms/batch
  Batch [470/5000] Top-1: 78.64% | Top-5: 95.68% | Infer: 2.83 ms/batch
  Batch [480/5000] Top-1: 79.11% | Top-5: 95.78% | Infer: 2.84 ms/batch
  Batch [490/5000] Top-1: 79.35% | Top-5: 95.87% | Infer: 2.84 ms/batch
  Batch [500/5000] Top-1: 79.79% | Top-5: 95.96% | Infer: 2.82 ms/batch
  Batch [510/5000] Top-1: 80.00% | Top-5: 95.83% | Infer: 2.83 ms/batch
  Batch [520/5000] Top-1: 80.41% | Top-5: 95.92% | Infer: 2.83 ms/batch
  Batch [530/5000] Top-1: 80.40% | Top-5: 95.80% | Infer: 2.83 ms/batch
  Batch [540/5000] Top-1: 80.59% | Top-5: 95.88% | Infer: 2.82 ms/batch
  Batch [550/5000] Top-1: 80.77% | Top-5: 95.96% | Infer: 2.83 ms/batch
  Batch [560/5000] Top-1: 81.13% | Top-5: 96.04% | Infer: 2.83 ms/batch
  Batch [570/5000] Top-1: 81.48% | Top-5: 96.11% | Infer: 2.83 ms/batch
  Batch [580/5000] Top-1: 81.82% | Top-5: 96.18% | Infer: 2.83 ms/batch
  Batch [590/5000] Top-1: 81.96% | Top-5: 96.25% | Infer: 2.82 ms/batch
  Batch [600/5000] Top-1: 82.11% | Top-5: 96.32% | Infer: 2.83 ms/batch
  Batch [610/5000] Top-1: 82.24% | Top-5: 96.38% | Infer: 2.85 ms/batch
  Batch [620/5000] Top-1: 82.03% | Top-5: 95.93% | Infer: 2.85 ms/batch
  Batch [630/5000] Top-1: 82.33% | Top-5: 96.00% | Infer: 2.84 ms/batch
  Batch [640/5000] Top-1: 82.30% | Top-5: 96.07% | Infer: 2.85 ms/batch
  Batch [650/5000] Top-1: 82.42% | Top-5: 96.13% | Infer: 2.85 ms/batch
  Batch [660/5000] Top-1: 82.70% | Top-5: 96.19% | Infer: 2.86 ms/batch
  Batch [670/5000] Top-1: 82.97% | Top-5: 96.25% | Infer: 2.86 ms/batch
  Batch [680/5000] Top-1: 83.23% | Top-5: 96.31% | Infer: 2.84 ms/batch
  Batch [690/5000] Top-1: 83.48% | Top-5: 96.36% | Infer: 2.84 ms/batch
  Batch [700/5000] Top-1: 83.73% | Top-5: 96.42% | Infer: 2.85 ms/batch
  Batch [710/5000] Top-1: 83.82% | Top-5: 96.47% | Infer: 2.85 ms/batch
  Batch [720/5000] Top-1: 84.06% | Top-5: 96.52% | Infer: 2.85 ms/batch
  Batch [730/5000] Top-1: 84.00% | Top-5: 96.57% | Infer: 2.85 ms/batch
  Batch [740/5000] Top-1: 83.94% | Top-5: 96.62% | Infer: 2.85 ms/batch
  Batch [750/5000] Top-1: 84.17% | Top-5: 96.67% | Infer: 2.85 ms/batch
  Batch [760/5000] Top-1: 84.25% | Top-5: 96.71% | Infer: 2.85 ms/batch
  Batch [770/5000] Top-1: 84.32% | Top-5: 96.76% | Infer: 2.86 ms/batch
  Batch [780/5000] Top-1: 84.53% | Top-5: 96.80% | Infer: 2.86 ms/batch
  Batch [790/5000] Top-1: 84.74% | Top-5: 96.84% | Infer: 2.88 ms/batch
  Batch [800/5000] Top-1: 84.81% | Top-5: 96.75% | Infer: 2.88 ms/batch
  Batch [810/5000] Top-1: 84.87% | Top-5: 96.67% | Infer: 2.89 ms/batch
  Batch [820/5000] Top-1: 84.81% | Top-5: 96.46% | Infer: 2.88 ms/batch
  Batch [830/5000] Top-1: 84.88% | Top-5: 96.50% | Infer: 2.88 ms/batch
  Batch [840/5000] Top-1: 84.94% | Top-5: 96.54% | Infer: 2.88 ms/batch
  Batch [850/5000] Top-1: 84.88% | Top-5: 96.59% | Infer: 2.87 ms/batch
  Batch [860/5000] Top-1: 84.82% | Top-5: 96.51% | Infer: 2.87 ms/batch
  Batch [870/5000] Top-1: 84.88% | Top-5: 96.55% | Infer: 2.87 ms/batch
  Batch [880/5000] Top-1: 84.71% | Top-5: 96.59% | Infer: 2.87 ms/batch
  Batch [890/5000] Top-1: 84.88% | Top-5: 96.63% | Infer: 2.87 ms/batch
  Batch [900/5000] Top-1: 85.06% | Top-5: 96.67% | Infer: 2.87 ms/batch
  Batch [910/5000] Top-1: 85.23% | Top-5: 96.70% | Infer: 2.87 ms/batch
  Batch [920/5000] Top-1: 85.28% | Top-5: 96.63% | Infer: 2.87 ms/batch
  Batch [930/5000] Top-1: 85.22% | Top-5: 96.67% | Infer: 2.87 ms/batch
  Batch [940/5000] Top-1: 85.05% | Top-5: 96.48% | Infer: 2.88 ms/batch
  Batch [950/5000] Top-1: 85.00% | Top-5: 96.41% | Infer: 2.88 ms/batch
  Batch [960/5000] Top-1: 84.95% | Top-5: 96.34% | Infer: 2.88 ms/batch
  Batch [970/5000] Top-1: 85.00% | Top-5: 96.38% | Infer: 2.89 ms/batch
  Batch [980/5000] Top-1: 85.05% | Top-5: 96.42% | Infer: 2.89 ms/batch
  Batch [990/5000] Top-1: 85.21% | Top-5: 96.46% | Infer: 2.89 ms/batch
  Batch [1000/5000] Top-1: 85.26% | Top-5: 96.49% | Infer: 2.88 ms/batch
  Batch [1010/5000] Top-1: 85.31% | Top-5: 96.53% | Infer: 2.88 ms/batch
  Batch [1020/5000] Top-1: 85.35% | Top-5: 96.46% | Infer: 2.89 ms/batch
  Batch [1030/5000] Top-1: 85.30% | Top-5: 96.40% | Infer: 2.89 ms/batch
  Batch [1040/5000] Top-1: 85.35% | Top-5: 96.44% | Infer: 2.89 ms/batch
  Batch [1050/5000] Top-1: 85.39% | Top-5: 96.37% | Infer: 2.89 ms/batch
  Batch [1060/5000] Top-1: 85.24% | Top-5: 96.21% | Infer: 2.88 ms/batch
  Batch [1070/5000] Top-1: 85.10% | Top-5: 96.15% | Infer: 2.89 ms/batch
  Batch [1080/5000] Top-1: 85.05% | Top-5: 96.10% | Infer: 2.89 ms/batch
  Batch [1090/5000] Top-1: 85.09% | Top-5: 96.13% | Infer: 2.89 ms/batch
  Batch [1100/5000] Top-1: 84.95% | Top-5: 96.07% | Infer: 2.90 ms/batch
  Batch [1110/5000] Top-1: 85.00% | Top-5: 96.02% | Infer: 2.89 ms/batch
  Batch [1120/5000] Top-1: 85.05% | Top-5: 96.06% | Infer: 2.90 ms/batch
  Batch [1130/5000] Top-1: 85.18% | Top-5: 96.09% | Infer: 2.90 ms/batch
  Batch [1140/5000] Top-1: 85.23% | Top-5: 96.13% | Infer: 2.90 ms/batch
  Batch [1150/5000] Top-1: 85.36% | Top-5: 96.16% | Infer: 2.90 ms/batch
  Batch [1160/5000] Top-1: 85.40% | Top-5: 96.19% | Infer: 2.90 ms/batch
  Batch [1170/5000] Top-1: 85.35% | Top-5: 96.14% | Infer: 2.89 ms/batch
  Batch [1180/5000] Top-1: 85.39% | Top-5: 96.17% | Infer: 2.89 ms/batch
  Batch [1190/5000] Top-1: 85.43% | Top-5: 96.12% | Infer: 2.89 ms/batch
  Batch [1200/5000] Top-1: 85.30% | Top-5: 96.15% | Infer: 2.89 ms/batch
  Batch [1210/5000] Top-1: 85.34% | Top-5: 96.10% | Infer: 2.90 ms/batch
  Batch [1220/5000] Top-1: 85.46% | Top-5: 96.13% | Infer: 2.90 ms/batch
  Batch [1230/5000] Top-1: 85.58% | Top-5: 96.17% | Infer: 2.89 ms/batch
  Batch [1240/5000] Top-1: 85.70% | Top-5: 96.20% | Infer: 2.90 ms/batch
  Batch [1250/5000] Top-1: 85.82% | Top-5: 96.23% | Infer: 2.90 ms/batch
  Batch [1260/5000] Top-1: 85.85% | Top-5: 96.18% | Infer: 2.89 ms/batch
  Batch [1270/5000] Top-1: 85.89% | Top-5: 96.21% | Infer: 2.90 ms/batch
  Batch [1280/5000] Top-1: 86.00% | Top-5: 96.24% | Infer: 2.90 ms/batch
  Batch [1290/5000] Top-1: 86.11% | Top-5: 96.27% | Infer: 2.90 ms/batch
  Batch [1300/5000] Top-1: 86.22% | Top-5: 96.30% | Infer: 2.90 ms/batch
  Batch [1310/5000] Top-1: 86.02% | Top-5: 96.33% | Infer: 2.90 ms/batch
  Batch [1320/5000] Top-1: 86.05% | Top-5: 96.36% | Infer: 2.90 ms/batch
  Batch [1330/5000] Top-1: 85.62% | Top-5: 96.15% | Infer: 2.90 ms/batch
  Batch [1340/5000] Top-1: 85.27% | Top-5: 96.11% | Infer: 2.90 ms/batch
  Batch [1350/5000] Top-1: 84.77% | Top-5: 95.98% | Infer: 2.90 ms/batch
  Batch [1360/5000] Top-1: 84.74% | Top-5: 95.94% | Infer: 2.90 ms/batch
  Batch [1370/5000] Top-1: 84.70% | Top-5: 95.97% | Infer: 2.90 ms/batch
  Batch [1380/5000] Top-1: 84.52% | Top-5: 95.85% | Infer: 2.89 ms/batch
  Batch [1390/5000] Top-1: 84.34% | Top-5: 95.81% | Infer: 2.89 ms/batch
  Batch [1400/5000] Top-1: 84.38% | Top-5: 95.84% | Infer: 2.89 ms/batch
  Batch [1410/5000] Top-1: 84.28% | Top-5: 95.87% | Infer: 2.89 ms/batch
  Batch [1420/5000] Top-1: 84.39% | Top-5: 95.90% | Infer: 2.89 ms/batch
  Batch [1430/5000] Top-1: 84.43% | Top-5: 95.86% | Infer: 2.89 ms/batch
  Batch [1440/5000] Top-1: 84.54% | Top-5: 95.89% | Infer: 2.89 ms/batch
  Batch [1450/5000] Top-1: 84.58% | Top-5: 95.92% | Infer: 2.89 ms/batch
  Batch [1460/5000] Top-1: 84.62% | Top-5: 95.94% | Infer: 2.88 ms/batch
  Batch [1470/5000] Top-1: 84.58% | Top-5: 95.97% | Infer: 2.88 ms/batch
  Batch [1480/5000] Top-1: 84.62% | Top-5: 95.93% | Infer: 2.88 ms/batch
  Batch [1490/5000] Top-1: 84.66% | Top-5: 95.89% | Infer: 2.88 ms/batch
  Batch [1500/5000] Top-1: 84.56% | Top-5: 95.85% | Infer: 2.88 ms/batch
  Batch [1510/5000] Top-1: 84.46% | Top-5: 95.68% | Infer: 2.88 ms/batch
  Batch [1520/5000] Top-1: 84.50% | Top-5: 95.64% | Infer: 2.88 ms/batch
  Batch [1530/5000] Top-1: 84.47% | Top-5: 95.67% | Infer: 2.88 ms/batch
  Batch [1540/5000] Top-1: 84.44% | Top-5: 95.70% | Infer: 2.88 ms/batch
  Batch [1550/5000] Top-1: 84.41% | Top-5: 95.66% | Infer: 2.88 ms/batch
  Batch [1560/5000] Top-1: 84.38% | Top-5: 95.69% | Infer: 2.88 ms/batch
  Batch [1570/5000] Top-1: 84.29% | Top-5: 95.58% | Infer: 2.88 ms/batch
  Batch [1580/5000] Top-1: 84.32% | Top-5: 95.61% | Infer: 2.88 ms/batch
  Batch [1590/5000] Top-1: 84.23% | Top-5: 95.58% | Infer: 2.88 ms/batch
  Batch [1600/5000] Top-1: 84.20% | Top-5: 95.54% | Infer: 2.89 ms/batch
  Batch [1610/5000] Top-1: 83.86% | Top-5: 95.44% | Infer: 2.89 ms/batch
  Batch [1620/5000] Top-1: 83.65% | Top-5: 95.41% | Infer: 2.89 ms/batch
  Batch [1630/5000] Top-1: 83.56% | Top-5: 95.44% | Infer: 2.88 ms/batch
  Batch [1640/5000] Top-1: 83.17% | Top-5: 95.22% | Infer: 2.88 ms/batch
  Batch [1650/5000] Top-1: 82.84% | Top-5: 94.94% | Infer: 2.88 ms/batch
  Batch [1660/5000] Top-1: 82.82% | Top-5: 94.91% | Infer: 2.88 ms/batch
  Batch [1670/5000] Top-1: 82.87% | Top-5: 94.88% | Infer: 2.88 ms/batch
  Batch [1680/5000] Top-1: 82.85% | Top-5: 94.91% | Infer: 2.88 ms/batch
  Batch [1690/5000] Top-1: 82.89% | Top-5: 94.94% | Infer: 2.88 ms/batch
  Batch [1700/5000] Top-1: 82.81% | Top-5: 94.91% | Infer: 2.88 ms/batch
  Batch [1710/5000] Top-1: 82.74% | Top-5: 94.88% | Infer: 2.88 ms/batch
  Batch [1720/5000] Top-1: 82.66% | Top-5: 94.85% | Infer: 2.88 ms/batch
  Batch [1730/5000] Top-1: 82.47% | Top-5: 94.76% | Infer: 2.88 ms/batch
  Batch [1740/5000] Top-1: 82.34% | Top-5: 94.68% | Infer: 2.88 ms/batch
  Batch [1750/5000] Top-1: 82.38% | Top-5: 94.65% | Infer: 2.88 ms/batch
  Batch [1760/5000] Top-1: 82.14% | Top-5: 94.68% | Infer: 2.88 ms/batch
  Batch [1770/5000] Top-1: 81.95% | Top-5: 94.54% | Infer: 2.88 ms/batch
  Batch [1780/5000] Top-1: 81.94% | Top-5: 94.51% | Infer: 2.88 ms/batch
  Batch [1790/5000] Top-1: 81.70% | Top-5: 94.43% | Infer: 2.88 ms/batch
  Batch [1800/5000] Top-1: 81.64% | Top-5: 94.35% | Infer: 2.87 ms/batch
  Batch [1810/5000] Top-1: 81.29% | Top-5: 94.38% | Infer: 2.87 ms/batch
  Batch [1820/5000] Top-1: 81.17% | Top-5: 94.36% | Infer: 2.87 ms/batch
  Batch [1830/5000] Top-1: 81.00% | Top-5: 94.33% | Infer: 2.87 ms/batch
  Batch [1840/5000] Top-1: 80.88% | Top-5: 94.36% | Infer: 2.87 ms/batch
  Batch [1850/5000] Top-1: 80.88% | Top-5: 94.40% | Infer: 2.86 ms/batch
  Batch [1860/5000] Top-1: 80.82% | Top-5: 94.32% | Infer: 2.86 ms/batch
  Batch [1870/5000] Top-1: 80.87% | Top-5: 94.35% | Infer: 2.87 ms/batch
  Batch [1880/5000] Top-1: 80.86% | Top-5: 94.38% | Infer: 2.86 ms/batch
  Batch [1890/5000] Top-1: 80.86% | Top-5: 94.41% | Infer: 2.87 ms/batch
  Batch [1900/5000] Top-1: 80.80% | Top-5: 94.44% | Infer: 2.86 ms/batch
  Batch [1910/5000] Top-1: 80.74% | Top-5: 94.47% | Infer: 2.87 ms/batch
  Batch [1920/5000] Top-1: 80.69% | Top-5: 94.39% | Infer: 2.86 ms/batch
  Batch [1930/5000] Top-1: 80.74% | Top-5: 94.37% | Infer: 2.86 ms/batch
  Batch [1940/5000] Top-1: 80.63% | Top-5: 94.35% | Infer: 2.86 ms/batch
  Batch [1950/5000] Top-1: 80.52% | Top-5: 94.27% | Infer: 2.87 ms/batch
  Batch [1960/5000] Top-1: 80.52% | Top-5: 94.30% | Infer: 2.86 ms/batch
  Batch [1970/5000] Top-1: 80.57% | Top-5: 94.28% | Infer: 2.86 ms/batch
  Batch [1980/5000] Top-1: 80.51% | Top-5: 94.31% | Infer: 2.86 ms/batch
  Batch [1990/5000] Top-1: 80.61% | Top-5: 94.34% | Infer: 2.86 ms/batch
  Batch [2000/5000] Top-1: 80.51% | Top-5: 94.31% | Infer: 2.86 ms/batch
  Batch [2010/5000] Top-1: 80.45% | Top-5: 94.34% | Infer: 2.87 ms/batch
  Batch [2020/5000] Top-1: 80.30% | Top-5: 94.37% | Infer: 2.86 ms/batch
  Batch [2030/5000] Top-1: 80.00% | Top-5: 94.35% | Infer: 2.86 ms/batch
  Batch [2040/5000] Top-1: 79.85% | Top-5: 94.38% | Infer: 2.87 ms/batch
  Batch [2050/5000] Top-1: 79.70% | Top-5: 94.36% | Infer: 2.87 ms/batch
  Batch [2060/5000] Top-1: 79.66% | Top-5: 94.24% | Infer: 2.87 ms/batch
  Batch [2070/5000] Top-1: 79.71% | Top-5: 94.26% | Infer: 2.88 ms/batch
  Batch [2080/5000] Top-1: 79.71% | Top-5: 94.24% | Infer: 2.88 ms/batch
  Batch [2090/5000] Top-1: 79.66% | Top-5: 94.17% | Infer: 2.88 ms/batch
  Batch [2100/5000] Top-1: 79.71% | Top-5: 94.20% | Infer: 2.88 ms/batch
  Batch [2110/5000] Top-1: 79.57% | Top-5: 94.13% | Infer: 2.88 ms/batch
  Batch [2120/5000] Top-1: 79.47% | Top-5: 94.11% | Infer: 2.88 ms/batch
  Batch [2130/5000] Top-1: 79.52% | Top-5: 94.10% | Infer: 2.88 ms/batch
  Batch [2140/5000] Top-1: 79.53% | Top-5: 94.08% | Infer: 2.89 ms/batch
  Batch [2150/5000] Top-1: 79.53% | Top-5: 94.10% | Infer: 2.88 ms/batch
  Batch [2160/5000] Top-1: 79.53% | Top-5: 94.08% | Infer: 2.88 ms/batch
  Batch [2170/5000] Top-1: 79.44% | Top-5: 94.07% | Infer: 2.88 ms/batch
  Batch [2180/5000] Top-1: 79.44% | Top-5: 94.00% | Infer: 2.89 ms/batch
  Batch [2190/5000] Top-1: 79.49% | Top-5: 94.03% | Infer: 2.89 ms/batch
  Batch [2200/5000] Top-1: 79.49% | Top-5: 94.01% | Infer: 2.89 ms/batch
  Batch [2210/5000] Top-1: 79.50% | Top-5: 93.99% | Infer: 2.89 ms/batch
  Batch [2220/5000] Top-1: 79.32% | Top-5: 93.88% | Infer: 2.89 ms/batch
  Batch [2230/5000] Top-1: 79.27% | Top-5: 93.86% | Infer: 2.88 ms/batch
  Batch [2240/5000] Top-1: 79.00% | Top-5: 93.57% | Infer: 2.89 ms/batch
  Batch [2250/5000] Top-1: 79.01% | Top-5: 93.56% | Infer: 2.89 ms/batch
  Batch [2260/5000] Top-1: 78.83% | Top-5: 93.50% | Infer: 2.89 ms/batch
  Batch [2270/5000] Top-1: 78.93% | Top-5: 93.53% | Infer: 2.89 ms/batch
  Batch [2280/5000] Top-1: 78.98% | Top-5: 93.56% | Infer: 2.89 ms/batch
  Batch [2290/5000] Top-1: 78.98% | Top-5: 93.54% | Infer: 2.90 ms/batch
  Batch [2300/5000] Top-1: 78.99% | Top-5: 93.52% | Infer: 2.90 ms/batch
  Batch [2310/5000] Top-1: 78.82% | Top-5: 93.55% | Infer: 2.91 ms/batch
  Batch [2320/5000] Top-1: 78.73% | Top-5: 93.54% | Infer: 2.91 ms/batch
  Batch [2330/5000] Top-1: 78.57% | Top-5: 93.52% | Infer: 2.90 ms/batch
  Batch [2340/5000] Top-1: 78.57% | Top-5: 93.55% | Infer: 2.90 ms/batch
  Batch [2350/5000] Top-1: 78.41% | Top-5: 93.58% | Infer: 2.90 ms/batch
  Batch [2360/5000] Top-1: 78.37% | Top-5: 93.52% | Infer: 2.91 ms/batch
  Batch [2370/5000] Top-1: 78.38% | Top-5: 93.50% | Infer: 2.91 ms/batch
  Batch [2380/5000] Top-1: 78.26% | Top-5: 93.36% | Infer: 2.91 ms/batch
  Batch [2390/5000] Top-1: 78.22% | Top-5: 93.31% | Infer: 2.91 ms/batch
  Batch [2400/5000] Top-1: 78.31% | Top-5: 93.33% | Infer: 2.91 ms/batch
  Batch [2410/5000] Top-1: 78.36% | Top-5: 93.36% | Infer: 2.91 ms/batch
  Batch [2420/5000] Top-1: 78.41% | Top-5: 93.39% | Infer: 2.91 ms/batch
  Batch [2430/5000] Top-1: 78.46% | Top-5: 93.42% | Infer: 2.91 ms/batch
  Batch [2440/5000] Top-1: 78.51% | Top-5: 93.44% | Infer: 2.91 ms/batch
  Batch [2450/5000] Top-1: 78.60% | Top-5: 93.47% | Infer: 2.92 ms/batch
  Batch [2460/5000] Top-1: 78.56% | Top-5: 93.46% | Infer: 2.93 ms/batch
  Batch [2470/5000] Top-1: 78.40% | Top-5: 93.40% | Infer: 2.93 ms/batch
  Batch [2480/5000] Top-1: 78.37% | Top-5: 93.39% | Infer: 2.93 ms/batch
  Batch [2490/5000] Top-1: 78.29% | Top-5: 93.37% | Infer: 2.92 ms/batch
  Batch [2500/5000] Top-1: 78.26% | Top-5: 93.40% | Infer: 2.93 ms/batch
  Batch [2510/5000] Top-1: 78.31% | Top-5: 93.43% | Infer: 2.93 ms/batch
  Batch [2520/5000] Top-1: 78.23% | Top-5: 93.45% | Infer: 2.93 ms/batch
  Batch [2530/5000] Top-1: 78.20% | Top-5: 93.48% | Infer: 2.93 ms/batch
  Batch [2540/5000] Top-1: 78.21% | Top-5: 93.51% | Infer: 2.94 ms/batch
  Batch [2550/5000] Top-1: 78.21% | Top-5: 93.49% | Infer: 2.94 ms/batch
  Batch [2560/5000] Top-1: 78.22% | Top-5: 93.48% | Infer: 2.93 ms/batch
  Batch [2570/5000] Top-1: 78.23% | Top-5: 93.46% | Infer: 2.94 ms/batch
  Batch [2580/5000] Top-1: 78.31% | Top-5: 93.49% | Infer: 2.94 ms/batch
  Batch [2590/5000] Top-1: 78.32% | Top-5: 93.48% | Infer: 2.94 ms/batch
  Batch [2600/5000] Top-1: 78.40% | Top-5: 93.50% | Infer: 2.94 ms/batch
  Batch [2610/5000] Top-1: 78.41% | Top-5: 93.53% | Infer: 2.95 ms/batch
  Batch [2620/5000] Top-1: 78.49% | Top-5: 93.55% | Infer: 2.95 ms/batch
  Batch [2630/5000] Top-1: 78.50% | Top-5: 93.58% | Infer: 2.95 ms/batch
  Batch [2640/5000] Top-1: 78.35% | Top-5: 93.52% | Infer: 2.95 ms/batch
  Batch [2650/5000] Top-1: 78.24% | Top-5: 93.44% | Infer: 2.95 ms/batch
  Batch [2660/5000] Top-1: 78.29% | Top-5: 93.42% | Infer: 2.95 ms/batch
  Batch [2670/5000] Top-1: 78.26% | Top-5: 93.45% | Infer: 2.96 ms/batch
  Batch [2680/5000] Top-1: 78.26% | Top-5: 93.43% | Infer: 2.96 ms/batch
  Batch [2690/5000] Top-1: 78.23% | Top-5: 93.42% | Infer: 2.96 ms/batch
  Batch [2700/5000] Top-1: 78.16% | Top-5: 93.41% | Infer: 2.96 ms/batch
  Batch [2710/5000] Top-1: 78.02% | Top-5: 93.28% | Infer: 2.96 ms/batch
  Batch [2720/5000] Top-1: 77.96% | Top-5: 93.27% | Infer: 2.96 ms/batch
  Batch [2730/5000] Top-1: 77.85% | Top-5: 93.19% | Infer: 2.96 ms/batch

## Results Summary

In [16]:
all_rows = []
for bits in INPUT_BITS:
    ckpt_dir = CKPT_ROOT / f"fp32_{bits}bit"
    if not ckpt_dir.exists():
        continue
    for seed_dir in sorted(ckpt_dir.iterdir()):
        if not seed_dir.is_dir():
            continue
        run_dir = f"{OUTPUT_ROOT}/fp32_{bits}bit/{seed_dir.name}"
        runs = load_runs(run_dir, status="ok")
        for r in flatten_runs(runs):
            r["seed"] = seed_dir.name
            r["input_bits_trained"] = bits
            all_rows.append(r)

df = pd.DataFrame(all_rows)

display_cols = [
    "seed", "input_bits_trained", "run_id",
    "cfg.model_precision", "cfg.input_quant_bits",
    "res.top1_acc", "res.top5_acc",
    "res.infer_ms_avg", "res.throughput_infer_sps", "res.total_samples",
]

df[display_cols].sort_values(
    ["input_bits_trained", "seed", "cfg.model_precision", "cfg.input_quant_bits"],
    ascending=[False, True, True, False],
)

,seed,input_bits_trained,run_id,cfg.model_precision,cfg.input_quant_bits,res.top1_acc,res.top5_acc,res.infer_ms_avg,res.throughput_infer_sps,res.total_samples
0,seed_1,8,resnet18_pytorch_fp16_in8b_cuda_bs1,fp16,8,77.867203,93.380282,3.042169,328.712801,4970
1,seed_1,8,resnet18_pytorch_fp32_in8b_cuda_bs1,fp32,8,77.847082,93.400402,3.073514,325.360470,4970
2,seed_2,8,resnet18_pytorch_fp16_in8b_cuda_bs1,fp16,8,77.987928,93.843058,3.101329,322.442400,4970
3,seed_2,8,resnet18_pytorch_fp32_in8b_cuda_bs1,fp32,8,78.008048,93.843058,2.968521,336.868108,4970
4,seed_42,8,resnet18_pytorch_fp16_in8b_cuda_bs1,fp16,8,78.068410,93.521127,3.001022,333.219810,4970
5,seed_42,8,resnet18_pytorch_fp32_in8b_cuda_bs1,fp32,8,78.108652,93.501006,3.086705,323.970087,4970
6,seed_1,4,resnet18_pytorch_fp16_in4b_cuda_bs1,fp16,4,78.410463,93.641851,3.053762,327.464955,4970
7,seed_1,4,resnet18_pytorch_fp32_in4b_cuda_bs1,fp32,4,78.430584,93.682093,3.102357,322.335551,4970
8,seed_2,4,resnet18_pytorch_fp16_in4b_cuda_bs1,fp16,4,77.927565,93.742455,3.104329,322.130790,4970
9,seed_2,4,resnet18_pytorch_fp32_in4b_cuda_bs1,fp32,4,77.967807,93.742455,3.077610,324.927476,4970
10,seed_42,4,resnet18_pytorch_fp16_in4b_cuda_bs1,fp16,4,78.651911,93.541247,3.102868,322.282500,4970
11,seed_42,4,resnet18_pytorch_fp32_in4b_cuda_bs1,fp32,4,78.611670,93.541247,3.065845,326.174316,4970
12,seed_1,2,resnet18_pytorch_fp16_in2b_cuda_bs1,fp16,2,76.941650,93.078471,3.062611,326.518782,4970
13,seed_1,2,resnet18_pytorch_fp32_in2b_cuda_bs1,fp32,2,76.881288,93.078471,2.967691,336.962281,4970
14,seed_2,2,resnet18_pytorch_fp16_in2b_cuda_bs1,fp16,2,77.283702,93.158954,3.126495,319.846969,4970
15,seed_2,2,resnet18_pytorch_fp32_in2b_cuda_bs1,fp32,2,77.263581,93.158954,2.961868,337.624727,4970
16,seed_42,2,resnet18_pytorch_fp16_in2b_cuda_bs1,fp16,2,76.438632,93.179074,3.036123,329.367430,4970
17,seed_42,2,resnet18_pytorch_fp32_in2b_cuda_bs1,fp32,2,76.438632,93.179074,3.023005,330.796686,4970
18,seed_1,1,resnet18_pytorch_fp16_in1b_cuda_bs1,fp16,1,69.718310,89.376258,3.006065,332.660781,4970
19,seed_1,1,resnet18_pytorch_fp32_in1b_cuda_bs1,fp32,1,69.678068,89.376258,2.967595,336.973236,4970
20,seed_2,1,resnet18_pytorch_fp16_in1b_cuda_bs1,fp16,1,69.919517,89.617706,3.122658,320.239993,4970
21,seed_2,1,resnet18_pytorch_fp32_in1b_cuda_bs1,fp32,1,69.939638,89.617706,2.993921,334.010129,4970
22,seed_42,1,resnet18_pytorch_fp16_in1b_cuda_bs1,fp16,1,69.014085,89.436620,3.066621,326.091828,4970
23,seed_42,1,resnet18_pytorch_fp32_in1b_cuda_bs1,fp32,1,69.034205,89.416499,2.979154,335.665712,4970

In [17]:
avg_df = df[df["cfg.backend"] == "pytorch"].groupby(
    ["cfg.backend", "cfg.model_precision", "input_bits_trained"]
).agg(
    top1_mean=("res.top1_acc", "mean"),
    top1_std=("res.top1_acc", "std"),
    top5_mean=("res.top5_acc", "mean"),
    top5_std=("res.top5_acc", "std"),
    infer_ms_mean=("res.infer_ms_avg", "mean"),
    infer_ms_std=("res.infer_ms_avg", "std"),
    throughput_mean=("res.throughput_infer_sps", "mean"),
).round(3).reset_index()

avg_df = avg_df.sort_values(
    ["cfg.model_precision", "input_bits_trained"],
    ascending=[True, True],
).reset_index(drop=True)
avg_df

,cfg.backend,cfg.model_precision,input_bits_trained,top1_mean,top1_std,top5_mean,top5_std,infer_ms_mean,infer_ms_std,throughput_mean
0,pytorch,fp16,1,69.551,0.475,89.477,0.126,3.065,0.058,326.331
1,pytorch,fp16,2,76.888,0.425,93.139,0.053,3.075,0.046,325.244
2,pytorch,fp16,4,78.330,0.369,93.642,0.101,3.087,0.029,323.959
3,pytorch,fp16,8,77.975,0.101,93.581,0.237,3.048,0.050,328.125
4,pytorch,fp32,1,69.551,0.466,89.470,0.129,2.980,0.013,335.550
5,pytorch,fp32,2,76.861,0.413,93.139,0.053,2.984,0.034,335.128
6,pytorch,fp32,4,78.337,0.332,93.655,0.103,3.082,0.019,324.479
7,pytorch,fp32,8,77.988,0.132,93.581,0.232,3.043,0.065,328.733

In [18]:
bench_path = PROJECT_ROOT / "results" / "latency_bench" / "pytorch_fp32_in8b_cuda_bs1.json"
with open(bench_path) as f:
    bench = json.load(f)
bench_std = np.std(bench["latencies_ms"], ddof=1)

avg_df[["cfg.model_precision", "input_bits_trained",
        "top1_mean", "top1_std", "top5_mean", "top5_std",
        "infer_ms_mean"]].assign(
    top1=lambda d: d.apply(lambda r: f"{r['top1_mean']:.2f} ± {r['top1_std']:.2f}", axis=1),
    top5=lambda d: d.apply(lambda r: f"{r['top5_mean']:.2f} ± {r['top5_std']:.2f}", axis=1),
    infer_ms=lambda d: d.apply(lambda r: f"{r['infer_ms_mean']:.3f} ± {bench_std:.3f}", axis=1),
)[["cfg.model_precision", "input_bits_trained", "top1", "top5", "infer_ms"]]

,cfg.model_precision,input_bits_trained,top1,top5,infer_ms
0,fp16,1,69.55 ± 0.47,89.48 ± 0.13,3.065 ± 1.244
1,fp16,2,76.89 ± 0.42,93.14 ± 0.05,3.075 ± 1.244
2,fp16,4,78.33 ± 0.37,93.64 ± 0.10,3.087 ± 1.244
3,fp16,8,77.97 ± 0.10,93.58 ± 0.24,3.048 ± 1.244
4,fp32,1,69.55 ± 0.47,89.47 ± 0.13,2.980 ± 1.244
5,fp32,2,76.86 ± 0.41,93.14 ± 0.05,2.984 ± 1.244
6,fp32,4,78.34 ± 0.33,93.66 ± 0.10,3.082 ± 1.244
7,fp32,8,77.99 ± 0.13,93.58 ± 0.23,3.043 ± 1.244

In [ ]:
out_path = PROJECT_ROOT / "resultsv2" / "test_runs" / "pytorch_avg_results_test.json"
out_path.parent.mkdir(parents=True, exist_ok=True)
avg_df.to_json(out_path, orient="records", indent=2)
print(f"Saved to {out_path}")