# 01 — FP32 Baselines & Input Bit-Depth Sweep

For each trained checkpoint (`seed_1`, `seed_2`, `seed_42`):

1. **FP32 baseline** — `input_quant_bits=8`
2. **FP32 reduced bit-depth** — `input_quant_bits` ∈ {4, 2, 1}
3. **FP16 full sweep** — `input_quant_bits` ∈ {8, 4, 2, 1}

Results are saved under `runs/val_infer/<seed>/`.

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path("..").resolve()
PYFILES = PROJECT_ROOT / "pyfiles"
if str(PYFILES) not in sys.path:
    sys.path.insert(0, str(PYFILES))

In [2]:
import torch
import pandas as pd

from src.config import ExperimentConfig, with_overrides
from src.runner import run_experiment
from utils.utils import load_runs, flatten_runs

pd.set_option("display.max_columns", 200)
print("torch:", torch.__version__, "| cuda:", torch.cuda.is_available())

torch: 2.10.0+cu130 | cuda: True

In [ ]:
CKPT_ROOT = PROJECT_ROOT / "checkpoints"
INPUT_BITS = [8, 4, 2, 1]

checkpoints = {}
for bits in INPUT_BITS:
    ckpt_dir = CKPT_ROOT / f"fp32_{bits}bit"
    if not ckpt_dir.exists():
        continue
    for seed_dir in sorted(ckpt_dir.iterdir()):
        if seed_dir.is_dir() and (seed_dir / "best.pth").exists():
            checkpoints[(bits, seed_dir.name)] = str(seed_dir / "best.pth")

print("Checkpoints found:")
for (bits, seed), path in checkpoints.items():
    print(f"  {bits}bit / {seed}: {path}")

Checkpoints found:
  seed_1: /home/pf4636/code/resnet/quantized_resnets/training/checkpoints/fp32/seed_1/best.pth
  seed_2: /home/pf4636/code/resnet/quantized_resnets/training/checkpoints/fp32/seed_2/best.pth
  seed_42: /home/pf4636/code/resnet/quantized_resnets/training/checkpoints/fp32/seed_42/best.pth

## FP32 Full Sweep (b=8, 4, 2, 1)

In [ ]:
fp32_records = []

for (bits, seed), ckpt_path in checkpoints.items():
    print(f"\n{'='*60}")
    print(f"  {bits}bit / {seed}  |  precision: fp32")
    print(f"{'='*60}")

    base = ExperimentConfig(
        backend="pytorch",
        device="cuda",
        batch_size=1,
        seed=42,
        num_eval_batches=500,
        output_root=f"../runs/val_infer/fp32_{bits}bit/{seed}",
    )

    cfg = with_overrides(base, model_precision="fp32", input_quant_bits=bits)
    print(f"\n--- fp32 | input_bits={bits} ---")
    payload, _ = run_experiment(cfg, save_results_flag=True, checkpoint_path=ckpt_path)
    fp32_records.append(payload)
    print(f"  top1={payload['results']['top1_acc']:.2f}%  top5={payload['results']['top5_acc']:.2f}%")

============================================================
  SEED: seed_1  |  precision: fp32
============================================================

--- fp32 | input_bits=8 ---
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
Evaluating on 500 batches (first 30 are warmup)...
  --- Warmup complete (30 batches) — starting metric collection ---
  Batch [40/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 2.86 ms/batch
  Batch [50/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.47 ms/batch
  Batch [60/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.47 ms/batch
  Batch [70/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.27 ms/batch
  Batch [80/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.23 ms/batch
  Batch [90/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.35 ms/batch
  Batch [100/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.32 ms/batch
  Batch [110/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.28 ms/batch
  Batch [120/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.18 ms/batch
  Batch [130/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.16 ms/batch
  Batch [140/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.19 ms/batch
  Batch [150/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.12 ms/batch
  Batch [160/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.12 ms/batch
  Batch [170/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.13 ms/batch
  Batch [180/500] Top-1: 99.33% | Top-5: 100.00% | Infer: 3.14 ms/batch
  Batch [190/500] Top-1: 99.38% | Top-5: 100.00% | Infer: 3.15 ms/batch
  Batch [200/500] Top-1: 99.41% | Top-5: 100.00% | Infer: 3.12 ms/batch
  Batch [210/500] Top-1: 99.44% | Top-5: 100.00% | Infer: 3.15 ms/batch
  Batch [220/500] Top-1: 99.47% | Top-5: 100.00% | Infer: 3.14 ms/batch
  Batch [230/500] Top-1: 99.50% | Top-5: 100.00% | Infer: 3.15 ms/batch
  Batch [240/500] Top-1: 99.52% | Top-5: 100.00% | Infer: 3.13 ms/batch
  Batch [250/500] Top-1: 99.55% | Top-5: 100.00% | Infer: 3.12 ms/batch
  Batch [260/500] Top-1: 99.57% | Top-5: 100.00% | Infer: 3.11 ms/batch
  Batch [270/500] Top-1: 99.58% | Top-5: 100.00% | Infer: 3.13 ms/batch
  Batch [280/500] Top-1: 99.60% | Top-5: 100.00% | Infer: 3.13 ms/batch
  Batch [290/500] Top-1: 99.62% | Top-5: 100.00% | Infer: 3.12 ms/batch
  Batch [300/500] Top-1: 99.63% | Top-5: 100.00% | Infer: 3.12 ms/batch
  Batch [310/500] Top-1: 99.64% | Top-5: 100.00% | Infer: 3.13 ms/batch
  Batch [320/500] Top-1: 99.66% | Top-5: 100.00% | Infer: 3.12 ms/batch
  Batch [330/500] Top-1: 99.67% | Top-5: 100.00% | Infer: 3.14 ms/batch
  Batch [340/500] Top-1: 99.68% | Top-5: 100.00% | Infer: 3.14 ms/batch
  Batch [350/500] Top-1: 99.69% | Top-5: 100.00% | Infer: 3.14 ms/batch
  Batch [360/500] Top-1: 99.70% | Top-5: 100.00% | Infer: 3.13 ms/batch
  Batch [370/500] Top-1: 99.71% | Top-5: 100.00% | Infer: 3.12 ms/batch
  Batch [380/500] Top-1: 99.71% | Top-5: 100.00% | Infer: 3.11 ms/batch
  Batch [390/500] Top-1: 99.72% | Top-5: 100.00% | Infer: 3.10 ms/batch
  Batch [400/500] Top-1: 99.73% | Top-5: 100.00% | Infer: 3.08 ms/batch
  Batch [410/500] Top-1: 99.47% | Top-5: 100.00% | Infer: 3.09 ms/batch
  Batch [420/500] Top-1: 98.97% | Top-5: 100.00% | Infer: 3.10 ms/batch
  Batch [430/500] Top-1: 99.00% | Top-5: 100.00% | Infer: 3.11 ms/batch
  Batch [440/500] Top-1: 98.78% | Top-5: 100.00% | Infer: 3.12 ms/batch
  Batch [450/500] Top-1: 98.81% | Top-5: 100.00% | Infer: 3.13 ms/batch
  Batch [460/500] Top-1: 98.84% | Top-5: 100.00% | Infer: 3.12 ms/batch
  Batch [470/500] Top-1: 98.86% | Top-5: 100.00% | Infer: 3.15 ms/batch
  Batch [480/500] Top-1: 98.89% | Top-5: 100.00% | Infer: 3.15 ms/batch
  Batch [490/500] Top-1: 98.91% | Top-5: 100.00% | Infer: 3.14 ms/batch
  Batch [500/500] Top-1: 98.94% | Top-5: 100.00% | Infer: 3.15 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_pytorch_fp32_in8b_cuda_bs1/result.json
  top1=98.94%  top5=100.00%

--- fp32 | input_bits=4 ---
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
Evaluating on 500 batches (first 30 are warmup)...
  --- Warmup complete (30 batches) — starting metric collection ---
  Batch [40/500] Top-1: 90.00% | Top-5: 100.00% | Infer: 2.42 ms/batch
  Batch [50/500] Top-1: 95.00% | Top-5: 100.00% | Infer: 2.73 ms/batch
  Batch [60/500] Top-1: 96.67% | Top-5: 100.00% | Infer: 2.73 ms/batch
  Batch [70/500] Top-1: 97.50% | Top-5: 100.00% | Infer: 2.76 ms/batch
  Batch [80/500] Top-1: 98.00% | Top-5: 100.00% | Infer: 2.67 ms/batch
  Batch [90/500] Top-1: 98.33% | Top-5: 100.00% | Infer: 2.65 ms/batch
  Batch [100/500] Top-1: 98.57% | Top-5: 100.00% | Infer: 2.67 ms/batch
  Batch [110/500] Top-1: 98.75% | Top-5: 100.00% | Infer: 2.64 ms/batch
  Batch [120/500] Top-1: 98.89% | Top-5: 100.00% | Infer: 2.64 ms/batch
  Batch [130/500] Top-1: 99.00% | Top-5: 100.00% | Infer: 2.65 ms/batch
  Batch [140/500] Top-1: 99.09% | Top-5: 100.00% | Infer: 2.64 ms/batch
  Batch [150/500] Top-1: 98.33% | Top-5: 100.00% | Infer: 2.71 ms/batch
  Batch [160/500] Top-1: 98.46% | Top-5: 100.00% | Infer: 2.68 ms/batch
  Batch [170/500] Top-1: 98.57% | Top-5: 100.00% | Infer: 2.70 ms/batch
  Batch [180/500] Top-1: 98.00% | Top-5: 100.00% | Infer: 2.68 ms/batch
  Batch [190/500] Top-1: 98.12% | Top-5: 100.00% | Infer: 2.66 ms/batch
  Batch [200/500] Top-1: 98.24% | Top-5: 100.00% | Infer: 2.67 ms/batch
  Batch [210/500] Top-1: 97.78% | Top-5: 100.00% | Infer: 2.73 ms/batch
  Batch [220/500] Top-1: 97.37% | Top-5: 100.00% | Infer: 2.75 ms/batch
  Batch [230/500] Top-1: 97.50% | Top-5: 100.00% | Infer: 2.73 ms/batch
  Batch [240/500] Top-1: 97.62% | Top-5: 100.00% | Infer: 2.71 ms/batch
  Batch [250/500] Top-1: 97.73% | Top-5: 100.00% | Infer: 2.72 ms/batch
  Batch [260/500] Top-1: 97.83% | Top-5: 100.00% | Infer: 2.72 ms/batch
  Batch [270/500] Top-1: 97.92% | Top-5: 100.00% | Infer: 2.73 ms/batch
  Batch [280/500] Top-1: 97.60% | Top-5: 100.00% | Infer: 2.72 ms/batch
  Batch [290/500] Top-1: 97.31% | Top-5: 100.00% | Infer: 2.72 ms/batch
  Batch [300/500] Top-1: 97.04% | Top-5: 100.00% | Infer: 2.74 ms/batch
  Batch [310/500] Top-1: 96.79% | Top-5: 100.00% | Infer: 2.76 ms/batch
  Batch [320/500] Top-1: 96.90% | Top-5: 100.00% | Infer: 2.77 ms/batch
  Batch [330/500] Top-1: 97.00% | Top-5: 100.00% | Infer: 2.79 ms/batch
  Batch [340/500] Top-1: 97.10% | Top-5: 100.00% | Infer: 2.78 ms/batch
  Batch [350/500] Top-1: 97.19% | Top-5: 100.00% | Infer: 2.79 ms/batch
  Batch [360/500] Top-1: 97.27% | Top-5: 100.00% | Infer: 2.78 ms/batch
  Batch [370/500] Top-1: 97.35% | Top-5: 100.00% | Infer: 2.79 ms/batch
  Batch [380/500] Top-1: 97.14% | Top-5: 100.00% | Infer: 2.79 ms/batch
  Batch [390/500] Top-1: 97.22% | Top-5: 100.00% | Infer: 2.79 ms/batch
  Batch [400/500] Top-1: 97.30% | Top-5: 100.00% | Infer: 2.79 ms/batch
  Batch [410/500] Top-1: 97.11% | Top-5: 100.00% | Infer: 2.79 ms/batch
  Batch [420/500] Top-1: 96.92% | Top-5: 100.00% | Infer: 2.79 ms/batch
  Batch [430/500] Top-1: 97.00% | Top-5: 100.00% | Infer: 2.79 ms/batch
  Batch [440/500] Top-1: 96.83% | Top-5: 100.00% | Infer: 2.78 ms/batch
  Batch [450/500] Top-1: 96.90% | Top-5: 100.00% | Infer: 2.78 ms/batch
  Batch [460/500] Top-1: 96.98% | Top-5: 100.00% | Infer: 2.79 ms/batch
  Batch [470/500] Top-1: 97.05% | Top-5: 100.00% | Infer: 2.78 ms/batch
  Batch [480/500] Top-1: 97.11% | Top-5: 100.00% | Infer: 2.79 ms/batch
  Batch [490/500] Top-1: 97.17% | Top-5: 100.00% | Infer: 2.79 ms/batch
  Batch [500/500] Top-1: 97.23% | Top-5: 100.00% | Infer: 2.79 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_pytorch_fp32_in4b_cuda_bs1/result.json
  top1=97.23%  top5=100.00%

--- fp32 | input_bits=2 ---
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
Evaluating on 500 batches (first 30 are warmup)...
  --- Warmup complete (30 batches) — starting metric collection ---
  Batch [40/500] Top-1: 70.00% | Top-5: 70.00% | Infer: 2.59 ms/batch
  Batch [50/500] Top-1: 70.00% | Top-5: 80.00% | Infer: 2.54 ms/batch
  Batch [60/500] Top-1: 80.00% | Top-5: 86.67% | Infer: 2.72 ms/batch
  Batch [70/500] Top-1: 85.00% | Top-5: 90.00% | Infer: 2.70 ms/batch
  Batch [80/500] Top-1: 88.00% | Top-5: 92.00% | Infer: 2.76 ms/batch
  Batch [90/500] Top-1: 85.00% | Top-5: 93.33% | Infer: 2.70 ms/batch
  Batch [100/500] Top-1: 84.29% | Top-5: 94.29% | Infer: 2.73 ms/batch
  Batch [110/500] Top-1: 80.00% | Top-5: 92.50% | Infer: 2.73 ms/batch
  Batch [120/500] Top-1: 77.78% | Top-5: 90.00% | Infer: 2.72 ms/batch
  Batch [130/500] Top-1: 73.00% | Top-5: 90.00% | Infer: 2.68 ms/batch
  Batch [140/500] Top-1: 70.00% | Top-5: 89.09% | Infer: 2.69 ms/batch
  Batch [150/500] Top-1: 68.33% | Top-5: 88.33% | Infer: 2.71 ms/batch
  Batch [160/500] Top-1: 67.69% | Top-5: 88.46% | Infer: 2.75 ms/batch
  Batch [170/500] Top-1: 66.43% | Top-5: 88.57% | Infer: 2.78 ms/batch
  Batch [180/500] Top-1: 63.33% | Top-5: 86.67% | Infer: 2.78 ms/batch
  Batch [190/500] Top-1: 61.88% | Top-5: 85.00% | Infer: 2.83 ms/batch
  Batch [200/500] Top-1: 61.18% | Top-5: 84.12% | Infer: 2.80 ms/batch
  Batch [210/500] Top-1: 62.22% | Top-5: 84.44% | Infer: 2.83 ms/batch
  Batch [220/500] Top-1: 61.05% | Top-5: 84.74% | Infer: 2.87 ms/batch
  Batch [230/500] Top-1: 59.00% | Top-5: 85.50% | Infer: 2.91 ms/batch
  Batch [240/500] Top-1: 59.52% | Top-5: 86.19% | Infer: 2.91 ms/batch
  Batch [250/500] Top-1: 59.09% | Top-5: 85.91% | Infer: 2.93 ms/batch
  Batch [260/500] Top-1: 58.26% | Top-5: 84.78% | Infer: 2.92 ms/batch
  Batch [270/500] Top-1: 57.50% | Top-5: 83.75% | Infer: 2.93 ms/batch
  Batch [280/500] Top-1: 56.80% | Top-5: 83.20% | Infer: 2.97 ms/batch
  Batch [290/500] Top-1: 55.38% | Top-5: 82.31% | Infer: 2.99 ms/batch
  Batch [300/500] Top-1: 54.07% | Top-5: 81.11% | Infer: 2.98 ms/batch
  Batch [310/500] Top-1: 54.29% | Top-5: 81.07% | Infer: 2.99 ms/batch
  Batch [320/500] Top-1: 54.14% | Top-5: 80.34% | Infer: 3.01 ms/batch
  Batch [330/500] Top-1: 53.33% | Top-5: 80.00% | Infer: 3.05 ms/batch
  Batch [340/500] Top-1: 52.90% | Top-5: 80.32% | Infer: 3.07 ms/batch
  Batch [350/500] Top-1: 52.19% | Top-5: 79.69% | Infer: 3.07 ms/batch
  Batch [360/500] Top-1: 53.33% | Top-5: 80.30% | Infer: 3.09 ms/batch
  Batch [370/500] Top-1: 54.71% | Top-5: 80.88% | Infer: 3.08 ms/batch
  Batch [380/500] Top-1: 56.00% | Top-5: 81.43% | Infer: 3.08 ms/batch
  Batch [390/500] Top-1: 56.67% | Top-5: 81.94% | Infer: 3.06 ms/batch
  Batch [400/500] Top-1: 57.30% | Top-5: 82.16% | Infer: 3.06 ms/batch
  Batch [410/500] Top-1: 57.89% | Top-5: 82.63% | Infer: 3.05 ms/batch
  Batch [420/500] Top-1: 57.69% | Top-5: 82.31% | Infer: 3.06 ms/batch
  Batch [430/500] Top-1: 57.25% | Top-5: 81.75% | Infer: 3.07 ms/batch
  Batch [440/500] Top-1: 57.07% | Top-5: 81.71% | Infer: 3.06 ms/batch
  Batch [450/500] Top-1: 56.90% | Top-5: 81.43% | Infer: 3.05 ms/batch
  Batch [460/500] Top-1: 57.21% | Top-5: 81.63% | Infer: 3.05 ms/batch
  Batch [470/500] Top-1: 57.50% | Top-5: 81.82% | Infer: 3.05 ms/batch
  Batch [480/500] Top-1: 58.00% | Top-5: 81.78% | Infer: 3.05 ms/batch
  Batch [490/500] Top-1: 58.48% | Top-5: 82.17% | Infer: 3.05 ms/batch
  Batch [500/500] Top-1: 58.94% | Top-5: 82.13% | Infer: 3.04 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_pytorch_fp32_in2b_cuda_bs1/result.json
  top1=58.94%  top5=82.13%

--- fp32 | input_bits=1 ---
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
Evaluating on 500 batches (first 30 are warmup)...
  --- Warmup complete (30 batches) — starting metric collection ---
  Batch [40/500] Top-1: 30.00% | Top-5: 60.00% | Infer: 2.75 ms/batch
  Batch [50/500] Top-1: 30.00% | Top-5: 55.00% | Infer: 2.54 ms/batch
  Batch [60/500] Top-1: 36.67% | Top-5: 66.67% | Infer: 2.66 ms/batch
  Batch [70/500] Top-1: 42.50% | Top-5: 75.00% | Infer: 2.57 ms/batch
  Batch [80/500] Top-1: 54.00% | Top-5: 80.00% | Infer: 2.59 ms/batch
  Batch [90/500] Top-1: 55.00% | Top-5: 81.67% | Infer: 2.60 ms/batch
  Batch [100/500] Top-1: 58.57% | Top-5: 82.86% | Infer: 2.65 ms/batch
  Batch [110/500] Top-1: 56.25% | Top-5: 78.75% | Infer: 2.69 ms/batch
  Batch [120/500] Top-1: 51.11% | Top-5: 77.78% | Infer: 2.68 ms/batch
  Batch [130/500] Top-1: 49.00% | Top-5: 74.00% | Infer: 2.67 ms/batch
  Batch [140/500] Top-1: 46.36% | Top-5: 70.91% | Infer: 2.73 ms/batch
  Batch [150/500] Top-1: 45.83% | Top-5: 69.17% | Infer: 2.75 ms/batch
  Batch [160/500] Top-1: 42.31% | Top-5: 66.92% | Infer: 2.78 ms/batch
  Batch [170/500] Top-1: 40.00% | Top-5: 65.00% | Infer: 2.76 ms/batch
  Batch [180/500] Top-1: 37.33% | Top-5: 61.33% | Infer: 2.75 ms/batch
  Batch [190/500] Top-1: 35.00% | Top-5: 58.75% | Infer: 2.76 ms/batch
  Batch [200/500] Top-1: 34.12% | Top-5: 57.06% | Infer: 2.72 ms/batch
  Batch [210/500] Top-1: 34.44% | Top-5: 56.67% | Infer: 2.71 ms/batch
  Batch [220/500] Top-1: 33.68% | Top-5: 56.84% | Infer: 2.70 ms/batch
  Batch [230/500] Top-1: 33.00% | Top-5: 57.50% | Infer: 2.71 ms/batch
  Batch [240/500] Top-1: 32.86% | Top-5: 58.10% | Infer: 2.71 ms/batch
  Batch [250/500] Top-1: 32.27% | Top-5: 58.64% | Infer: 2.71 ms/batch
  Batch [260/500] Top-1: 32.17% | Top-5: 57.83% | Infer: 2.73 ms/batch
  Batch [270/500] Top-1: 32.08% | Top-5: 57.92% | Infer: 2.73 ms/batch
  Batch [280/500] Top-1: 31.20% | Top-5: 56.40% | Infer: 2.73 ms/batch
  Batch [290/500] Top-1: 30.77% | Top-5: 55.77% | Infer: 2.73 ms/batch
  Batch [300/500] Top-1: 30.37% | Top-5: 55.19% | Infer: 2.73 ms/batch
  Batch [310/500] Top-1: 30.36% | Top-5: 55.36% | Infer: 2.74 ms/batch
  Batch [320/500] Top-1: 30.00% | Top-5: 55.17% | Infer: 2.74 ms/batch
  Batch [330/500] Top-1: 29.00% | Top-5: 55.33% | Infer: 2.77 ms/batch
  Batch [340/500] Top-1: 29.68% | Top-5: 55.81% | Infer: 2.76 ms/batch
  Batch [350/500] Top-1: 29.69% | Top-5: 55.00% | Infer: 2.76 ms/batch
  Batch [360/500] Top-1: 30.30% | Top-5: 56.36% | Infer: 2.77 ms/batch
  Batch [370/500] Top-1: 31.47% | Top-5: 57.35% | Infer: 2.77 ms/batch
  Batch [380/500] Top-1: 32.57% | Top-5: 58.57% | Infer: 2.77 ms/batch
  Batch [390/500] Top-1: 34.44% | Top-5: 59.72% | Infer: 2.77 ms/batch
  Batch [400/500] Top-1: 34.86% | Top-5: 60.81% | Infer: 2.77 ms/batch
  Batch [410/500] Top-1: 34.47% | Top-5: 60.53% | Infer: 2.80 ms/batch
  Batch [420/500] Top-1: 33.85% | Top-5: 60.26% | Infer: 2.82 ms/batch
  Batch [430/500] Top-1: 33.25% | Top-5: 60.00% | Infer: 2.86 ms/batch
  Batch [440/500] Top-1: 32.93% | Top-5: 59.76% | Infer: 2.85 ms/batch
  Batch [450/500] Top-1: 32.14% | Top-5: 59.52% | Infer: 2.85 ms/batch
  Batch [460/500] Top-1: 32.56% | Top-5: 60.00% | Infer: 2.84 ms/batch
  Batch [470/500] Top-1: 32.73% | Top-5: 60.00% | Infer: 2.83 ms/batch
  Batch [480/500] Top-1: 33.33% | Top-5: 60.44% | Infer: 2.82 ms/batch
  Batch [490/500] Top-1: 33.70% | Top-5: 60.43% | Infer: 2.81 ms/batch
  Batch [500/500] Top-1: 33.83% | Top-5: 60.64% | Infer: 2.80 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_pytorch_fp32_in1b_cuda_bs1/result.json
  top1=33.83%  top5=60.64%

============================================================
  SEED: seed_2  |  precision: fp32
============================================================

--- fp32 | input_bits=8 ---
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
Evaluating on 500 batches (first 30 are warmup)...
  --- Warmup complete (30 batches) — starting metric collection ---
  Batch [40/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 2.77 ms/batch
  Batch [50/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 2.85 ms/batch
  Batch [60/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.24 ms/batch
  Batch [70/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.10 ms/batch
  Batch [80/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.11 ms/batch
  Batch [90/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.09 ms/batch
  Batch [100/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.05 ms/batch
  Batch [110/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.05 ms/batch
  Batch [120/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.01 ms/batch
  Batch [130/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.08 ms/batch
  Batch [140/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.09 ms/batch
  Batch [150/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.10 ms/batch
  Batch [160/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.14 ms/batch
  Batch [170/500] Top-1: 99.29% | Top-5: 100.00% | Infer: 3.11 ms/batch
  Batch [180/500] Top-1: 98.67% | Top-5: 100.00% | Infer: 3.13 ms/batch
  Batch [190/500] Top-1: 98.75% | Top-5: 100.00% | Infer: 3.12 ms/batch
  Batch [200/500] Top-1: 98.82% | Top-5: 100.00% | Infer: 3.10 ms/batch
  Batch [210/500] Top-1: 98.89% | Top-5: 100.00% | Infer: 3.09 ms/batch
  Batch [220/500] Top-1: 98.95% | Top-5: 100.00% | Infer: 3.09 ms/batch
  Batch [230/500] Top-1: 99.00% | Top-5: 100.00% | Infer: 3.05 ms/batch
  Batch [240/500] Top-1: 99.05% | Top-5: 100.00% | Infer: 3.05 ms/batch
  Batch [250/500] Top-1: 99.09% | Top-5: 100.00% | Infer: 3.05 ms/batch
  Batch [260/500] Top-1: 99.13% | Top-5: 100.00% | Infer: 3.07 ms/batch
  Batch [270/500] Top-1: 99.17% | Top-5: 100.00% | Infer: 3.05 ms/batch
  Batch [280/500] Top-1: 99.20% | Top-5: 100.00% | Infer: 3.05 ms/batch
  Batch [290/500] Top-1: 98.46% | Top-5: 100.00% | Infer: 3.07 ms/batch
  Batch [300/500] Top-1: 98.52% | Top-5: 100.00% | Infer: 3.06 ms/batch
  Batch [310/500] Top-1: 98.21% | Top-5: 100.00% | Infer: 3.06 ms/batch
  Batch [320/500] Top-1: 98.28% | Top-5: 100.00% | Infer: 3.04 ms/batch
  Batch [330/500] Top-1: 98.33% | Top-5: 100.00% | Infer: 3.03 ms/batch
  Batch [340/500] Top-1: 98.39% | Top-5: 100.00% | Infer: 3.04 ms/batch
  Batch [350/500] Top-1: 98.44% | Top-5: 100.00% | Infer: 3.03 ms/batch
  Batch [360/500] Top-1: 98.48% | Top-5: 100.00% | Infer: 3.03 ms/batch
  Batch [370/500] Top-1: 98.53% | Top-5: 100.00% | Infer: 3.04 ms/batch
  Batch [380/500] Top-1: 98.57% | Top-5: 100.00% | Infer: 3.03 ms/batch
  Batch [390/500] Top-1: 98.61% | Top-5: 100.00% | Infer: 3.03 ms/batch
  Batch [400/500] Top-1: 98.65% | Top-5: 100.00% | Infer: 3.04 ms/batch
  Batch [410/500] Top-1: 98.16% | Top-5: 100.00% | Infer: 3.04 ms/batch
  Batch [420/500] Top-1: 97.95% | Top-5: 100.00% | Infer: 3.04 ms/batch
  Batch [430/500] Top-1: 97.75% | Top-5: 100.00% | Infer: 3.05 ms/batch
  Batch [440/500] Top-1: 97.80% | Top-5: 100.00% | Infer: 3.05 ms/batch
  Batch [450/500] Top-1: 97.86% | Top-5: 100.00% | Infer: 3.04 ms/batch
  Batch [460/500] Top-1: 97.91% | Top-5: 100.00% | Infer: 3.03 ms/batch
  Batch [470/500] Top-1: 97.95% | Top-5: 100.00% | Infer: 3.04 ms/batch
  Batch [480/500] Top-1: 98.00% | Top-5: 100.00% | Infer: 3.02 ms/batch
  Batch [490/500] Top-1: 98.04% | Top-5: 100.00% | Infer: 3.04 ms/batch
  Batch [500/500] Top-1: 98.09% | Top-5: 100.00% | Infer: 3.05 ms/batch
[runner] Results saved: ../runs/val_infer/seed_2/resnet18_pytorch_fp32_in8b_cuda_bs1/result.json
  top1=98.09%  top5=100.00%

--- fp32 | input_bits=4 ---
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
Evaluating on 500 batches (first 30 are warmup)...
  --- Warmup complete (30 batches) — starting metric collection ---
  Batch [40/500] Top-1: 90.00% | Top-5: 100.00% | Infer: 4.29 ms/batch
  Batch [50/500] Top-1: 95.00% | Top-5: 100.00% | Infer: 3.42 ms/batch
  Batch [60/500] Top-1: 96.67% | Top-5: 100.00% | Infer: 3.18 ms/batch
  Batch [70/500] Top-1: 97.50% | Top-5: 100.00% | Infer: 2.93 ms/batch
  Batch [80/500] Top-1: 98.00% | Top-5: 100.00% | Infer: 2.91 ms/batch
  Batch [90/500] Top-1: 98.33% | Top-5: 100.00% | Infer: 2.89 ms/batch
  Batch [100/500] Top-1: 98.57% | Top-5: 100.00% | Infer: 2.88 ms/batch
  Batch [110/500] Top-1: 98.75% | Top-5: 100.00% | Infer: 2.90 ms/batch
  Batch [120/500] Top-1: 98.89% | Top-5: 100.00% | Infer: 2.85 ms/batch
  Batch [130/500] Top-1: 99.00% | Top-5: 100.00% | Infer: 2.82 ms/batch
  Batch [140/500] Top-1: 99.09% | Top-5: 100.00% | Infer: 2.81 ms/batch

## FP16 Full Sweep (b=8, 4, 2, 1)

In [ ]:
fp16_records = []

for (bits, seed), ckpt_path in checkpoints.items():
    print(f"\n{'='*60}")
    print(f"  {bits}bit / {seed}  |  precision: fp16")
    print(f"{'='*60}")

    base = ExperimentConfig(
        backend="pytorch",
        device="cuda",
        batch_size=1,
        seed=42,
        num_eval_batches=500,
        output_root=f"../runs/val_infer/fp32_{bits}bit/{seed}",
    )

    cfg = with_overrides(base, model_precision="fp16", input_quant_bits=bits)
    print(f"\n--- fp16 | input_bits={bits} ---")
    payload, _ = run_experiment(cfg, save_results_flag=True, checkpoint_path=ckpt_path)
    fp16_records.append(payload)
    print(f"  top1={payload['results']['top1_acc']:.2f}%  top5={payload['results']['top5_acc']:.2f}%")

============================================================
  SEED: seed_1  |  precision: fp16
============================================================

--- fp16 | input_bits=8 ---
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
Evaluating on 500 batches (first 30 are warmup)...
  --- Warmup complete (30 batches) — starting metric collection ---
  Batch [40/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.22 ms/batch
  Batch [50/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 2.41 ms/batch
  Batch [60/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 2.66 ms/batch
  Batch [70/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 2.56 ms/batch
  Batch [80/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 2.63 ms/batch
  Batch [90/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 2.80 ms/batch
  Batch [100/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 2.91 ms/batch
  Batch [110/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 2.96 ms/batch
  Batch [120/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 2.99 ms/batch
  Batch [130/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.02 ms/batch
  Batch [140/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.01 ms/batch
  Batch [150/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 2.98 ms/batch
  Batch [160/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 2.94 ms/batch
  Batch [170/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 2.97 ms/batch
  Batch [180/500] Top-1: 99.33% | Top-5: 100.00% | Infer: 2.96 ms/batch
  Batch [190/500] Top-1: 99.38% | Top-5: 100.00% | Infer: 2.98 ms/batch
  Batch [200/500] Top-1: 99.41% | Top-5: 100.00% | Infer: 2.96 ms/batch
  Batch [210/500] Top-1: 99.44% | Top-5: 100.00% | Infer: 2.96 ms/batch
  Batch [220/500] Top-1: 99.47% | Top-5: 100.00% | Infer: 2.97 ms/batch
  Batch [230/500] Top-1: 99.50% | Top-5: 100.00% | Infer: 3.04 ms/batch
  Batch [240/500] Top-1: 99.52% | Top-5: 100.00% | Infer: 3.04 ms/batch
  Batch [250/500] Top-1: 99.55% | Top-5: 100.00% | Infer: 3.01 ms/batch
  Batch [260/500] Top-1: 99.57% | Top-5: 100.00% | Infer: 3.04 ms/batch
  Batch [270/500] Top-1: 99.58% | Top-5: 100.00% | Infer: 3.03 ms/batch
  Batch [280/500] Top-1: 99.60% | Top-5: 100.00% | Infer: 3.02 ms/batch
  Batch [290/500] Top-1: 99.62% | Top-5: 100.00% | Infer: 3.04 ms/batch
  Batch [300/500] Top-1: 99.63% | Top-5: 100.00% | Infer: 3.07 ms/batch
  Batch [310/500] Top-1: 99.64% | Top-5: 100.00% | Infer: 3.05 ms/batch
  Batch [320/500] Top-1: 99.66% | Top-5: 100.00% | Infer: 3.05 ms/batch
  Batch [330/500] Top-1: 99.67% | Top-5: 100.00% | Infer: 3.05 ms/batch
  Batch [340/500] Top-1: 99.68% | Top-5: 100.00% | Infer: 3.04 ms/batch
  Batch [350/500] Top-1: 99.69% | Top-5: 100.00% | Infer: 3.05 ms/batch
  Batch [360/500] Top-1: 99.70% | Top-5: 100.00% | Infer: 3.06 ms/batch
  Batch [370/500] Top-1: 99.71% | Top-5: 100.00% | Infer: 3.05 ms/batch
  Batch [380/500] Top-1: 99.71% | Top-5: 100.00% | Infer: 3.04 ms/batch
  Batch [390/500] Top-1: 99.72% | Top-5: 100.00% | Infer: 3.03 ms/batch
  Batch [400/500] Top-1: 99.73% | Top-5: 100.00% | Infer: 3.02 ms/batch
  Batch [410/500] Top-1: 99.47% | Top-5: 100.00% | Infer: 3.04 ms/batch
  Batch [420/500] Top-1: 98.97% | Top-5: 100.00% | Infer: 3.02 ms/batch
  Batch [430/500] Top-1: 99.00% | Top-5: 100.00% | Infer: 3.00 ms/batch
  Batch [440/500] Top-1: 98.78% | Top-5: 100.00% | Infer: 3.00 ms/batch
  Batch [450/500] Top-1: 98.81% | Top-5: 100.00% | Infer: 3.02 ms/batch
  Batch [460/500] Top-1: 98.84% | Top-5: 100.00% | Infer: 3.03 ms/batch
  Batch [470/500] Top-1: 98.86% | Top-5: 100.00% | Infer: 3.02 ms/batch
  Batch [480/500] Top-1: 98.89% | Top-5: 100.00% | Infer: 3.00 ms/batch
  Batch [490/500] Top-1: 98.91% | Top-5: 100.00% | Infer: 2.99 ms/batch
  Batch [500/500] Top-1: 98.94% | Top-5: 100.00% | Infer: 3.00 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_pytorch_fp16_in8b_cuda_bs1/result.json
  top1=98.94%  top5=100.00%

--- fp16 | input_bits=4 ---
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
Evaluating on 500 batches (first 30 are warmup)...
  --- Warmup complete (30 batches) — starting metric collection ---
  Batch [40/500] Top-1: 90.00% | Top-5: 100.00% | Infer: 3.23 ms/batch
  Batch [50/500] Top-1: 95.00% | Top-5: 100.00% | Infer: 3.06 ms/batch
  Batch [60/500] Top-1: 96.67% | Top-5: 100.00% | Infer: 3.10 ms/batch
  Batch [70/500] Top-1: 97.50% | Top-5: 100.00% | Infer: 3.18 ms/batch
  Batch [80/500] Top-1: 98.00% | Top-5: 100.00% | Infer: 2.94 ms/batch
  Batch [90/500] Top-1: 98.33% | Top-5: 100.00% | Infer: 2.87 ms/batch
  Batch [100/500] Top-1: 98.57% | Top-5: 100.00% | Infer: 2.89 ms/batch
  Batch [110/500] Top-1: 98.75% | Top-5: 100.00% | Infer: 2.91 ms/batch
  Batch [120/500] Top-1: 98.89% | Top-5: 100.00% | Infer: 2.83 ms/batch
  Batch [130/500] Top-1: 99.00% | Top-5: 100.00% | Infer: 2.83 ms/batch
  Batch [140/500] Top-1: 99.09% | Top-5: 100.00% | Infer: 2.85 ms/batch
  Batch [150/500] Top-1: 98.33% | Top-5: 100.00% | Infer: 2.82 ms/batch
  Batch [160/500] Top-1: 98.46% | Top-5: 100.00% | Infer: 2.84 ms/batch
  Batch [170/500] Top-1: 98.57% | Top-5: 100.00% | Infer: 2.89 ms/batch
  Batch [180/500] Top-1: 98.00% | Top-5: 100.00% | Infer: 2.93 ms/batch
  Batch [190/500] Top-1: 98.12% | Top-5: 100.00% | Infer: 2.94 ms/batch
  Batch [200/500] Top-1: 98.24% | Top-5: 100.00% | Infer: 3.00 ms/batch
  Batch [210/500] Top-1: 97.78% | Top-5: 100.00% | Infer: 3.07 ms/batch
  Batch [220/500] Top-1: 97.37% | Top-5: 100.00% | Infer: 3.07 ms/batch
  Batch [230/500] Top-1: 97.50% | Top-5: 100.00% | Infer: 3.11 ms/batch
  Batch [240/500] Top-1: 97.62% | Top-5: 100.00% | Infer: 3.15 ms/batch
  Batch [250/500] Top-1: 97.73% | Top-5: 100.00% | Infer: 3.15 ms/batch
  Batch [260/500] Top-1: 97.83% | Top-5: 100.00% | Infer: 3.13 ms/batch
  Batch [270/500] Top-1: 97.92% | Top-5: 100.00% | Infer: 3.12 ms/batch
  Batch [280/500] Top-1: 97.60% | Top-5: 100.00% | Infer: 3.15 ms/batch
  Batch [290/500] Top-1: 97.31% | Top-5: 100.00% | Infer: 3.19 ms/batch
  Batch [300/500] Top-1: 97.04% | Top-5: 100.00% | Infer: 3.15 ms/batch
  Batch [310/500] Top-1: 96.79% | Top-5: 100.00% | Infer: 3.13 ms/batch
  Batch [320/500] Top-1: 96.90% | Top-5: 100.00% | Infer: 3.10 ms/batch
  Batch [330/500] Top-1: 97.00% | Top-5: 100.00% | Infer: 3.11 ms/batch
  Batch [340/500] Top-1: 97.10% | Top-5: 100.00% | Infer: 3.14 ms/batch
  Batch [350/500] Top-1: 97.19% | Top-5: 100.00% | Infer: 3.11 ms/batch
  Batch [360/500] Top-1: 97.27% | Top-5: 100.00% | Infer: 3.11 ms/batch
  Batch [370/500] Top-1: 97.35% | Top-5: 100.00% | Infer: 3.13 ms/batch
  Batch [380/500] Top-1: 97.14% | Top-5: 100.00% | Infer: 3.14 ms/batch
  Batch [390/500] Top-1: 97.22% | Top-5: 100.00% | Infer: 3.12 ms/batch
  Batch [400/500] Top-1: 97.30% | Top-5: 100.00% | Infer: 3.11 ms/batch
  Batch [410/500] Top-1: 97.11% | Top-5: 100.00% | Infer: 3.10 ms/batch
  Batch [420/500] Top-1: 96.92% | Top-5: 100.00% | Infer: 3.09 ms/batch
  Batch [430/500] Top-1: 97.00% | Top-5: 100.00% | Infer: 3.08 ms/batch
  Batch [440/500] Top-1: 96.83% | Top-5: 100.00% | Infer: 3.07 ms/batch
  Batch [450/500] Top-1: 96.90% | Top-5: 100.00% | Infer: 3.06 ms/batch
  Batch [460/500] Top-1: 96.98% | Top-5: 100.00% | Infer: 3.05 ms/batch
  Batch [470/500] Top-1: 97.05% | Top-5: 100.00% | Infer: 3.03 ms/batch
  Batch [480/500] Top-1: 97.11% | Top-5: 100.00% | Infer: 3.03 ms/batch
  Batch [490/500] Top-1: 97.17% | Top-5: 100.00% | Infer: 3.04 ms/batch
  Batch [500/500] Top-1: 97.23% | Top-5: 100.00% | Infer: 3.03 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_pytorch_fp16_in4b_cuda_bs1/result.json
  top1=97.23%  top5=100.00%

--- fp16 | input_bits=2 ---
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
Evaluating on 500 batches (first 30 are warmup)...
  --- Warmup complete (30 batches) — starting metric collection ---
  Batch [40/500] Top-1: 70.00% | Top-5: 70.00% | Infer: 4.64 ms/batch
  Batch [50/500] Top-1: 70.00% | Top-5: 80.00% | Infer: 3.95 ms/batch
  Batch [60/500] Top-1: 80.00% | Top-5: 86.67% | Infer: 3.93 ms/batch
  Batch [70/500] Top-1: 85.00% | Top-5: 90.00% | Infer: 3.85 ms/batch
  Batch [80/500] Top-1: 88.00% | Top-5: 92.00% | Infer: 3.47 ms/batch
  Batch [90/500] Top-1: 85.00% | Top-5: 93.33% | Infer: 3.44 ms/batch
  Batch [100/500] Top-1: 84.29% | Top-5: 94.29% | Infer: 3.31 ms/batch
  Batch [110/500] Top-1: 80.00% | Top-5: 92.50% | Infer: 3.24 ms/batch
  Batch [120/500] Top-1: 77.78% | Top-5: 90.00% | Infer: 3.20 ms/batch
  Batch [130/500] Top-1: 73.00% | Top-5: 90.00% | Infer: 3.15 ms/batch
  Batch [140/500] Top-1: 70.00% | Top-5: 89.09% | Infer: 3.15 ms/batch
  Batch [150/500] Top-1: 68.33% | Top-5: 88.33% | Infer: 3.20 ms/batch
  Batch [160/500] Top-1: 67.69% | Top-5: 88.46% | Infer: 3.18 ms/batch
  Batch [170/500] Top-1: 66.43% | Top-5: 88.57% | Infer: 3.20 ms/batch
  Batch [180/500] Top-1: 63.33% | Top-5: 86.67% | Infer: 3.23 ms/batch
  Batch [190/500] Top-1: 61.88% | Top-5: 85.00% | Infer: 3.27 ms/batch
  Batch [200/500] Top-1: 61.18% | Top-5: 84.12% | Infer: 3.28 ms/batch
  Batch [210/500] Top-1: 62.22% | Top-5: 84.44% | Infer: 3.32 ms/batch
  Batch [220/500] Top-1: 61.05% | Top-5: 84.74% | Infer: 3.38 ms/batch
  Batch [230/500] Top-1: 59.00% | Top-5: 85.50% | Infer: 3.33 ms/batch
  Batch [240/500] Top-1: 59.52% | Top-5: 86.19% | Infer: 3.29 ms/batch
  Batch [250/500] Top-1: 59.09% | Top-5: 85.91% | Infer: 3.26 ms/batch
  Batch [260/500] Top-1: 58.26% | Top-5: 84.78% | Infer: 3.26 ms/batch
  Batch [270/500] Top-1: 57.50% | Top-5: 83.75% | Infer: 3.30 ms/batch
  Batch [280/500] Top-1: 56.80% | Top-5: 83.20% | Infer: 3.27 ms/batch
  Batch [290/500] Top-1: 55.38% | Top-5: 82.31% | Infer: 3.25 ms/batch
  Batch [300/500] Top-1: 54.07% | Top-5: 81.11% | Infer: 3.25 ms/batch
  Batch [310/500] Top-1: 54.29% | Top-5: 81.07% | Infer: 3.24 ms/batch
  Batch [320/500] Top-1: 54.14% | Top-5: 80.34% | Infer: 3.20 ms/batch
  Batch [330/500] Top-1: 53.33% | Top-5: 80.00% | Infer: 3.20 ms/batch
  Batch [340/500] Top-1: 52.90% | Top-5: 80.32% | Infer: 3.17 ms/batch
  Batch [350/500] Top-1: 52.19% | Top-5: 79.69% | Infer: 3.16 ms/batch
  Batch [360/500] Top-1: 53.33% | Top-5: 80.30% | Infer: 3.14 ms/batch
  Batch [370/500] Top-1: 54.71% | Top-5: 80.88% | Infer: 3.14 ms/batch
  Batch [380/500] Top-1: 56.00% | Top-5: 81.43% | Infer: 3.13 ms/batch
  Batch [390/500] Top-1: 56.67% | Top-5: 81.94% | Infer: 3.11 ms/batch
  Batch [400/500] Top-1: 57.30% | Top-5: 82.16% | Infer: 3.11 ms/batch
  Batch [410/500] Top-1: 57.89% | Top-5: 82.63% | Infer: 3.08 ms/batch
  Batch [420/500] Top-1: 57.69% | Top-5: 82.31% | Infer: 3.08 ms/batch
  Batch [430/500] Top-1: 57.25% | Top-5: 81.75% | Infer: 3.07 ms/batch
  Batch [440/500] Top-1: 57.07% | Top-5: 81.71% | Infer: 3.08 ms/batch
  Batch [450/500] Top-1: 56.90% | Top-5: 81.43% | Infer: 3.05 ms/batch
  Batch [460/500] Top-1: 57.21% | Top-5: 81.63% | Infer: 3.05 ms/batch
  Batch [470/500] Top-1: 57.50% | Top-5: 81.82% | Infer: 3.05 ms/batch
  Batch [480/500] Top-1: 58.00% | Top-5: 81.78% | Infer: 3.07 ms/batch
  Batch [490/500] Top-1: 58.48% | Top-5: 82.17% | Infer: 3.08 ms/batch
  Batch [500/500] Top-1: 58.94% | Top-5: 82.13% | Infer: 3.10 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_pytorch_fp16_in2b_cuda_bs1/result.json
  top1=58.94%  top5=82.13%

--- fp16 | input_bits=1 ---
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
Evaluating on 500 batches (first 30 are warmup)...
  --- Warmup complete (30 batches) — starting metric collection ---
  Batch [40/500] Top-1: 30.00% | Top-5: 60.00% | Infer: 2.47 ms/batch
  Batch [50/500] Top-1: 30.00% | Top-5: 55.00% | Infer: 2.58 ms/batch
  Batch [60/500] Top-1: 36.67% | Top-5: 66.67% | Infer: 2.47 ms/batch
  Batch [70/500] Top-1: 42.50% | Top-5: 75.00% | Infer: 2.62 ms/batch
  Batch [80/500] Top-1: 54.00% | Top-5: 80.00% | Infer: 2.61 ms/batch
  Batch [90/500] Top-1: 55.00% | Top-5: 81.67% | Infer: 2.80 ms/batch
  Batch [100/500] Top-1: 58.57% | Top-5: 82.86% | Infer: 2.98 ms/batch
  Batch [110/500] Top-1: 56.25% | Top-5: 78.75% | Infer: 2.95 ms/batch
  Batch [120/500] Top-1: 51.11% | Top-5: 77.78% | Infer: 2.98 ms/batch
  Batch [130/500] Top-1: 49.00% | Top-5: 74.00% | Infer: 3.06 ms/batch
  Batch [140/500] Top-1: 46.36% | Top-5: 70.91% | Infer: 3.07 ms/batch
  Batch [150/500] Top-1: 45.83% | Top-5: 69.17% | Infer: 3.08 ms/batch
  Batch [160/500] Top-1: 42.31% | Top-5: 66.92% | Infer: 3.06 ms/batch
  Batch [170/500] Top-1: 40.00% | Top-5: 65.00% | Infer: 3.12 ms/batch
  Batch [180/500] Top-1: 37.33% | Top-5: 61.33% | Infer: 3.11 ms/batch
  Batch [190/500] Top-1: 35.00% | Top-5: 58.75% | Infer: 3.06 ms/batch
  Batch [200/500] Top-1: 34.12% | Top-5: 57.06% | Infer: 3.11 ms/batch
  Batch [210/500] Top-1: 34.44% | Top-5: 56.67% | Infer: 3.11 ms/batch
  Batch [220/500] Top-1: 33.68% | Top-5: 56.84% | Infer: 3.10 ms/batch
  Batch [230/500] Top-1: 33.00% | Top-5: 57.50% | Infer: 3.07 ms/batch
  Batch [240/500] Top-1: 32.86% | Top-5: 58.10% | Infer: 3.10 ms/batch
  Batch [250/500] Top-1: 32.27% | Top-5: 58.64% | Infer: 3.09 ms/batch
  Batch [260/500] Top-1: 32.17% | Top-5: 57.83% | Infer: 3.13 ms/batch
  Batch [270/500] Top-1: 32.08% | Top-5: 57.92% | Infer: 3.12 ms/batch
  Batch [280/500] Top-1: 31.20% | Top-5: 56.40% | Infer: 3.16 ms/batch
  Batch [290/500] Top-1: 30.77% | Top-5: 55.77% | Infer: 3.15 ms/batch
  Batch [300/500] Top-1: 30.37% | Top-5: 55.19% | Infer: 3.14 ms/batch
  Batch [310/500] Top-1: 30.36% | Top-5: 55.36% | Infer: 3.13 ms/batch
  Batch [320/500] Top-1: 30.00% | Top-5: 55.17% | Infer: 3.12 ms/batch
  Batch [330/500] Top-1: 29.00% | Top-5: 55.33% | Infer: 3.11 ms/batch
  Batch [340/500] Top-1: 29.68% | Top-5: 55.81% | Infer: 3.11 ms/batch
  Batch [350/500] Top-1: 29.69% | Top-5: 55.00% | Infer: 3.11 ms/batch
  Batch [360/500] Top-1: 30.30% | Top-5: 56.36% | Infer: 3.09 ms/batch
  Batch [370/500] Top-1: 31.47% | Top-5: 57.35% | Infer: 3.09 ms/batch
  Batch [380/500] Top-1: 32.57% | Top-5: 58.57% | Infer: 3.08 ms/batch
  Batch [390/500] Top-1: 34.44% | Top-5: 59.72% | Infer: 3.06 ms/batch
  Batch [400/500] Top-1: 34.86% | Top-5: 60.81% | Infer: 3.05 ms/batch
  Batch [410/500] Top-1: 34.47% | Top-5: 60.53% | Infer: 3.06 ms/batch
  Batch [420/500] Top-1: 33.85% | Top-5: 60.26% | Infer: 3.05 ms/batch
  Batch [430/500] Top-1: 33.25% | Top-5: 60.00% | Infer: 3.03 ms/batch
  Batch [440/500] Top-1: 32.93% | Top-5: 59.76% | Infer: 3.03 ms/batch
  Batch [450/500] Top-1: 32.14% | Top-5: 59.52% | Infer: 3.04 ms/batch
  Batch [460/500] Top-1: 32.56% | Top-5: 60.00% | Infer: 3.04 ms/batch
  Batch [470/500] Top-1: 32.73% | Top-5: 60.00% | Infer: 3.06 ms/batch
  Batch [480/500] Top-1: 33.33% | Top-5: 60.44% | Infer: 3.08 ms/batch
  Batch [490/500] Top-1: 33.70% | Top-5: 60.43% | Infer: 3.08 ms/batch
  Batch [500/500] Top-1: 33.83% | Top-5: 60.64% | Infer: 3.08 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_pytorch_fp16_in1b_cuda_bs1/result.json
  top1=33.83%  top5=60.64%

============================================================
  SEED: seed_2  |  precision: fp16
============================================================

--- fp16 | input_bits=8 ---
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
Evaluating on 500 batches (first 30 are warmup)...
  --- Warmup complete (30 batches) — starting metric collection ---
  Batch [40/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.31 ms/batch
  Batch [50/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.21 ms/batch
  Batch [60/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.37 ms/batch
  Batch [70/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.23 ms/batch
  Batch [80/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.24 ms/batch
  Batch [90/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.12 ms/batch
  Batch [100/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.08 ms/batch
  Batch [110/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 3.05 ms/batch
  Batch [120/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 2.96 ms/batch
  Batch [130/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 2.92 ms/batch
  Batch [140/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 2.90 ms/batch
  Batch [150/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 2.95 ms/batch
  Batch [160/500] Top-1: 100.00% | Top-5: 100.00% | Infer: 2.94 ms/batch
  Batch [170/500] Top-1: 99.29% | Top-5: 100.00% | Infer: 2.91 ms/batch
  Batch [180/500] Top-1: 98.67% | Top-5: 100.00% | Infer: 2.90 ms/batch
  Batch [190/500] Top-1: 98.75% | Top-5: 100.00% | Infer: 2.92 ms/batch
  Batch [200/500] Top-1: 98.82% | Top-5: 100.00% | Infer: 2.93 ms/batch
  Batch [210/500] Top-1: 98.89% | Top-5: 100.00% | Infer: 2.92 ms/batch
  Batch [220/500] Top-1: 98.95% | Top-5: 100.00% | Infer: 2.89 ms/batch
  Batch [230/500] Top-1: 99.00% | Top-5: 100.00% | Infer: 2.89 ms/batch
  Batch [240/500] Top-1: 99.05% | Top-5: 100.00% | Infer: 2.85 ms/batch
  Batch [250/500] Top-1: 99.09% | Top-5: 100.00% | Infer: 2.81 ms/batch
  Batch [260/500] Top-1: 99.13% | Top-5: 100.00% | Infer: 2.82 ms/batch
  Batch [270/500] Top-1: 99.17% | Top-5: 100.00% | Infer: 2.78 ms/batch
  Batch [280/500] Top-1: 99.20% | Top-5: 100.00% | Infer: 2.79 ms/batch
  Batch [290/500] Top-1: 98.46% | Top-5: 100.00% | Infer: 2.77 ms/batch
  Batch [300/500] Top-1: 98.52% | Top-5: 100.00% | Infer: 2.80 ms/batch
  Batch [310/500] Top-1: 98.21% | Top-5: 100.00% | Infer: 2.77 ms/batch
  Batch [320/500] Top-1: 98.28% | Top-5: 100.00% | Infer: 2.78 ms/batch
  Batch [330/500] Top-1: 98.33% | Top-5: 100.00% | Infer: 2.78 ms/batch
  Batch [340/500] Top-1: 98.39% | Top-5: 100.00% | Infer: 2.76 ms/batch
  Batch [350/500] Top-1: 98.44% | Top-5: 100.00% | Infer: 2.75 ms/batch
  Batch [360/500] Top-1: 98.48% | Top-5: 100.00% | Infer: 2.76 ms/batch
  Batch [370/500] Top-1: 98.53% | Top-5: 100.00% | Infer: 2.76 ms/batch
  Batch [380/500] Top-1: 98.57% | Top-5: 100.00% | Infer: 2.76 ms/batch
  Batch [390/500] Top-1: 98.61% | Top-5: 100.00% | Infer: 2.74 ms/batch
  Batch [400/500] Top-1: 98.65% | Top-5: 100.00% | Infer: 2.76 ms/batch
  Batch [410/500] Top-1: 98.16% | Top-5: 100.00% | Infer: 2.75 ms/batch
  Batch [420/500] Top-1: 97.95% | Top-5: 100.00% | Infer: 2.73 ms/batch
  Batch [430/500] Top-1: 97.75% | Top-5: 100.00% | Infer: 2.72 ms/batch
  Batch [440/500] Top-1: 97.80% | Top-5: 100.00% | Infer: 2.72 ms/batch
  Batch [450/500] Top-1: 97.86% | Top-5: 100.00% | Infer: 2.71 ms/batch
  Batch [460/500] Top-1: 97.91% | Top-5: 100.00% | Infer: 2.71 ms/batch
  Batch [470/500] Top-1: 97.95% | Top-5: 100.00% | Infer: 2.71 ms/batch
  Batch [480/500] Top-1: 98.00% | Top-5: 100.00% | Infer: 2.72 ms/batch
  Batch [490/500] Top-1: 98.04% | Top-5: 100.00% | Infer: 2.71 ms/batch
  Batch [500/500] Top-1: 98.09% | Top-5: 100.00% | Infer: 2.69 ms/batch
[runner] Results saved: ../runs/val_infer/seed_2/resnet18_pytorch_fp16_in8b_cuda_bs1/result.json
  top1=98.09%  top5=100.00%

--- fp16 | input_bits=4 ---
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
Evaluating on 500 batches (first 30 are warmup)...
  --- Warmup complete (30 batches) — starting metric collection ---
  Batch [40/500] Top-1: 90.00% | Top-5: 100.00% | Infer: 3.35 ms/batch
  Batch [50/500] Top-1: 95.00% | Top-5: 100.00% | Infer: 3.33 ms/batch
  Batch [60/500] Top-1: 96.67% | Top-5: 100.00% | Infer: 3.04 ms/batch
  Batch [70/500] Top-1: 97.50% | Top-5: 100.00% | Infer: 2.90 ms/batch
  Batch [80/500] Top-1: 98.00% | Top-5: 100.00% | Infer: 2.93 ms/batch
  Batch [90/500] Top-1: 98.33% | Top-5: 100.00% | Infer: 2.89 ms/batch
  Batch [100/500] Top-1: 98.57% | Top-5: 100.00% | Infer: 2.86 ms/batch
  Batch [110/500] Top-1: 98.75% | Top-5: 100.00% | Infer: 2.78 ms/batch
  Batch [120/500] Top-1: 98.89% | Top-5: 100.00% | Infer: 2.79 ms/batch
  Batch [130/500] Top-1: 99.00% | Top-5: 100.00% | Infer: 2.85 ms/batch
  Batch [140/500] Top-1: 99.09% | Top-5: 100.00% | Infer: 2.92 ms/batch

## Results Summary

In [ ]:
all_rows = []
for bits in INPUT_BITS:
    ckpt_dir = CKPT_ROOT / f"fp32_{bits}bit"
    if not ckpt_dir.exists():
        continue
    for seed_dir in sorted(ckpt_dir.iterdir()):
        if not seed_dir.is_dir():
            continue
        run_dir = f"../runs/val_infer/fp32_{bits}bit/{seed_dir.name}"
        runs = load_runs(run_dir, status="ok")
        for r in flatten_runs(runs):
            r["seed"] = seed_dir.name
            r["input_bits_trained"] = bits
            all_rows.append(r)

df = pd.DataFrame(all_rows)

display_cols = [
    "seed",
    "input_bits_trained",
    "run_id",
    "cfg.model_precision",
    "cfg.input_quant_bits",
    "res.top1_acc",
    "res.top5_acc",
    "res.infer_ms_avg",
    "res.throughput_infer_sps",
    "res.total_samples",
]

df[display_cols].sort_values(
    ["input_bits_trained", "seed", "cfg.model_precision", "cfg.input_quant_bits"],
    ascending=[False, True, True, False],
)

,seed,run_id,cfg.model_precision,cfg.input_quant_bits,res.top1_acc,res.top5_acc,res.infer_ms_avg,res.throughput_infer_sps,res.total_samples
3,seed_1,resnet18_pytorch_fp16_in8b_cuda_bs1,fp16,8,98.936170,100.000000,2.996082,333.769231,470
2,seed_1,resnet18_pytorch_fp16_in4b_cuda_bs1,fp16,4,97.234043,100.000000,3.025733,330.498440,470
1,seed_1,resnet18_pytorch_fp16_in2b_cuda_bs1,fp16,2,58.936170,82.127660,3.097284,322.863540,470
0,seed_1,resnet18_pytorch_fp16_in1b_cuda_bs1,fp16,1,33.829787,60.638298,3.082136,324.450368,470
7,seed_1,resnet18_pytorch_fp32_in8b_cuda_bs1,fp32,8,98.936170,100.000000,3.151437,317.315589,470
6,seed_1,resnet18_pytorch_fp32_in4b_cuda_bs1,fp32,4,97.234043,100.000000,2.787812,358.704183,470
5,seed_1,resnet18_pytorch_fp32_in2b_cuda_bs1,fp32,2,58.936170,82.127660,3.035384,329.447618,470
4,seed_1,resnet18_pytorch_fp32_in1b_cuda_bs1,fp32,1,33.829787,60.638298,2.801803,356.913054,470
11,seed_2,resnet18_pytorch_fp16_in8b_cuda_bs1,fp16,8,98.085106,100.000000,2.693583,371.252731,470
10,seed_2,resnet18_pytorch_fp16_in4b_cuda_bs1,fp16,4,96.595745,100.000000,2.918227,342.673840,470
9,seed_2,resnet18_pytorch_fp16_in2b_cuda_bs1,fp16,2,57.659574,80.638298,2.998871,333.458838,470
8,seed_2,resnet18_pytorch_fp16_in1b_cuda_bs1,fp16,1,32.553191,56.808511,3.139030,318.569768,470
15,seed_2,resnet18_pytorch_fp32_in8b_cuda_bs1,fp32,8,98.085106,100.000000,3.045674,328.334536,470
14,seed_2,resnet18_pytorch_fp32_in4b_cuda_bs1,fp32,4,96.595745,100.000000,2.796899,357.538785,470
13,seed_2,resnet18_pytorch_fp32_in2b_cuda_bs1,fp32,2,57.446809,80.638298,2.781270,359.548017,470
12,seed_2,resnet18_pytorch_fp32_in1b_cuda_bs1,fp32,1,32.340426,56.808511,2.980425,335.522642,470
19,seed_42,resnet18_pytorch_fp16_in8b_cuda_bs1,fp16,8,86.382979,98.723404,3.214743,311.066851,470
18,seed_42,resnet18_pytorch_fp16_in4b_cuda_bs1,fp16,4,85.744681,97.872340,2.787178,358.785885,470
17,seed_42,resnet18_pytorch_fp16_in2b_cuda_bs1,fp16,2,51.489362,78.297872,2.895504,345.363001,470
16,seed_42,resnet18_pytorch_fp16_in1b_cuda_bs1,fp16,1,30.851064,58.936170,3.178187,314.644749,470
23,seed_42,resnet18_pytorch_fp32_in8b_cuda_bs1,fp32,8,86.382979,98.723404,3.070231,325.708420,470
22,seed_42,resnet18_pytorch_fp32_in4b_cuda_bs1,fp32,4,85.744681,97.872340,2.937677,340.405023,470
21,seed_42,resnet18_pytorch_fp32_in2b_cuda_bs1,fp32,2,51.489362,78.297872,3.036082,329.371844,470
20,seed_42,resnet18_pytorch_fp32_in1b_cuda_bs1,fp32,1,30.851064,58.936170,2.736989,365.365026,470

In [ ]:
avg_df = df[df["cfg.backend"] == "pytorch"].groupby(
    ["cfg.backend", "cfg.model_precision", "input_bits_trained"]
).agg(
    top1_mean=("res.top1_acc", "mean"),
    top1_std=("res.top1_acc", "std"),
    top5_mean=("res.top5_acc", "mean"),
    top5_std=("res.top5_acc", "std"),
    infer_ms_mean=("res.infer_ms_avg", "mean"),
    infer_ms_std=("res.infer_ms_avg", "std"),
    throughput_mean=("res.throughput_infer_sps", "mean"),
).round(3).reset_index()

avg_df = avg_df.sort_values(
    ["cfg.model_precision", "input_bits_trained"],
    ascending=[True, False],
).reset_index(drop=True)
avg_df

,cfg.backend,cfg.model_precision,cfg.input_quant_bits,top1_mean,top1_std,top5_mean,top5_std,infer_ms_mean,infer_ms_std,throughput_mean
0,pytorch,fp16,8,94.468,7.015,99.574,0.737,2.968,0.262,338.696
1,pytorch,fp16,4,93.191,6.457,99.291,1.228,2.910,0.119,343.986
2,pytorch,fp16,2,56.028,3.982,80.355,1.931,2.997,0.101,333.895
3,pytorch,fp16,1,32.411,1.494,58.794,1.919,3.133,0.048,319.222
4,pytorch,fp32,8,94.468,7.015,99.574,0.737,3.089,0.055,323.786
5,pytorch,fp32,4,93.191,6.457,99.291,1.228,2.841,0.084,352.216
6,pytorch,fp32,2,55.957,3.940,80.355,1.931,2.951,0.147,339.456
7,pytorch,fp32,1,32.340,1.489,58.794,1.919,2.840,0.126,352.600

In [ ]:
avg_df[["cfg.model_precision", "input_bits_trained",
        "top1_mean", "top1_std", "top5_mean", "top5_std",
        "infer_ms_mean", "infer_ms_std"]].assign(
    top1=lambda d: d.apply(lambda r: f"{r['top1_mean']:.2f} ± {r['top1_std']:.2f}", axis=1),
    top5=lambda d: d.apply(lambda r: f"{r['top5_mean']:.2f} ± {r['top5_std']:.2f}", axis=1),
    infer_ms=lambda d: d.apply(lambda r: f"{r['infer_ms_mean']:.3f} ± {r['infer_ms_std']:.3f}", axis=1),
)[["cfg.model_precision", "input_bits_trained", "top1", "top5", "infer_ms"]]

,cfg.model_precision,cfg.input_quant_bits,top1,top5,infer_ms
0,fp16,8,94.47 ± 7.01,99.57 ± 0.74,2.968 ± 0.262
1,fp16,4,93.19 ± 6.46,99.29 ± 1.23,2.910 ± 0.119
2,fp16,2,56.03 ± 3.98,80.36 ± 1.93,2.997 ± 0.101
3,fp16,1,32.41 ± 1.49,58.79 ± 1.92,3.133 ± 0.048
4,fp32,8,94.47 ± 7.01,99.57 ± 0.74,3.089 ± 0.055
5,fp32,4,93.19 ± 6.46,99.29 ± 1.23,2.841 ± 0.084
6,fp32,2,55.96 ± 3.94,80.36 ± 1.93,2.951 ± 0.147
7,fp32,1,32.34 ± 1.49,58.79 ± 1.92,2.840 ± 0.126

In [13]:
out_path = PROJECT_ROOT / "results" / "pytorch_avg_results_val.json"
avg_df.to_json(out_path, orient="records", indent=2)
print(f"Saved to {out_path}")

Saved to /home/pf4636/code/resnet/quantized_resnets/results/pytorch_avg_results_val.json