# 02.1 — TensorRT Inference on Test Set (ImageNet Val)

Same sweep as `02_tensorrt_inference` but evaluated on the ImageNet validation split (test set).

ONNX exports and TRT engines are assumed to already exist.

Results saved under `resultsv2/test_runs/`.

In [1]:
# ── Toggle dataset here ──────────────────────────────────────────
SPLIT = "val"              # ImageNet val split (= "test" for this project)
OUTPUT_ROOT = "/home/pf4636/code/resnet/quantized_resnets/runs/test_infer"

In [2]:
from pathlib import Path
import sys

PROJECT_ROOT = Path("..").resolve()
PYFILES = PROJECT_ROOT / "pyfiles"
if str(PYFILES) not in sys.path:
    sys.path.insert(0, str(PYFILES))

In [3]:
import json
import time
import torch
import torch.nn as nn
import numpy as np
import pandas as pd

from src.config import ExperimentConfig, with_overrides, set_seed
from src.data import get_dataloader
from src.runner import _get_trt_paths
from trt.trt_infer import trt_evaluate
from utils.utils import load_runs, flatten_runs

pd.set_option("display.max_columns", 200)
pd.set_option("display.float_format", "{:.3f}".format)
print("torch:", torch.__version__, "| cuda:", torch.cuda.is_available())

torch: 2.10.0+cu130 | cuda: True

In [4]:
CKPT_ROOT = PROJECT_ROOT / "checkpoints"
ONNX_ROOT = PROJECT_ROOT / "onnx"
INPUT_BITS = [8, 4, 2, 1]
TRT_PRECISIONS = ["fp32", "fp16", "int8", "fp8", "int4"]

experiments = {}
for bits in INPUT_BITS:
    ckpt_dir = CKPT_ROOT / f"fp32_{bits}bit"
    if not ckpt_dir.exists():
        continue
    for seed_dir in sorted(ckpt_dir.iterdir()):
        if seed_dir.is_dir() and (seed_dir / "best.pth").exists():
            seed = seed_dir.name
            seed_num = seed.split("_")[-1]
            experiments[(bits, seed)] = {
                "ckpt": str(seed_dir / "best.pth"),
                "seed_num": seed_num,
            }

def make_base(bits, seed, seed_num):
    return ExperimentConfig(
        backend="tensorrt",
        device="cuda",
        batch_size=1,
        seed=42,
        num_eval_batches=None,
        trt_static_shape=True,
        trt_workspace_mb=2048,
        onnx_root=str(ONNX_ROOT / f"fp32_{bits}bit"),
        engine_root=str(PROJECT_ROOT / "engines" / f"fp32_{bits}bit" / seed),
        trt_onnx_prefix=f"resnet_{seed_num}",
        output_root=f"{OUTPUT_ROOT}/fp32_{bits}bit/{seed}",
    )

print("Experiments found:")
for (bits, seed), info in experiments.items():
    print(f"  {bits}bit / {seed}: {info['ckpt']}")

Experiments found:
  8bit / seed_1: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_8bit/seed_1/best.pth
  8bit / seed_2: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_8bit/seed_2/best.pth
  8bit / seed_42: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_8bit/seed_42/best.pth
  4bit / seed_1: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_4bit/seed_1/best.pth
  4bit / seed_2: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_4bit/seed_2/best.pth
  4bit / seed_42: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_4bit/seed_42/best.pth
  2bit / seed_1: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_2bit/seed_1/best.pth
  2bit / seed_2: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_2bit/seed_2/best.pth
  2bit / seed_42: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_2bit/seed_42/best.pth
  1bit / seed_1: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_1bit/seed_1/best.pth
  1bit / seed_2: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_1bit/seed_2/best.pth
  1bit / seed_42: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_1bit/seed_42/best.pth

In [5]:
def run_trt_test_experiment(cfg, split=SPLIT):
    cfg = cfg.normalized()
    cfg.validate()
    set_seed(cfg)

    criterion = nn.CrossEntropyLoss()
    loader = get_dataloader(cfg, split=split)

    _, engine_path, _ = _get_trt_paths(cfg)
    if not engine_path.exists():
        raise FileNotFoundError(f"Engine not found: {engine_path}")

    t0 = time.perf_counter()
    tracker = trt_evaluate(engine_path, cfg, loader, criterion)
    elapsed = round(time.perf_counter() - t0, 3)

    payload = {
        "status": "ok",
        "run_id": cfg.run_id(),
        "system": cfg.stamp(),
        "config": cfg.to_dict(),
        "results": tracker.summary(),
        "total_eval_time_sec": elapsed,
        "split": split,
        "error": None,
    }

    out_path = Path(cfg.output_root) / cfg.run_id() / "result.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        json.dump(payload, f, indent=2, sort_keys=True)
    print(f"  Saved: {out_path}")

    return payload

## FP32

In [6]:
fp32_records = []
print("TRT Precision: fp32")
for (bits, seed), info in experiments.items():
    base = make_base(bits, seed, info["seed_num"])
    cfg = with_overrides(base, model_precision="fp32", input_quant_bits=bits)

    if cfg.result_json_path().exists():
        print(f"  SKIP {bits}bit / {seed} (result exists)")
        continue

    print(f"\n  {bits}bit / {seed}:")
    payload = run_trt_test_experiment(cfg)
    fp32_records.append(payload)
    r = payload["results"]
    print(f"    top1={r['top1_acc']:.2f}%  top5={r['top5_acc']:.2f}%  infer={r['infer_ms_avg']:.2f}ms")

TRT Precision: fp32

  8bit / seed_1:
[data] Filtered to 5000 samples across 100 classes.
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/fp32_8bit/seed_1/resnet18_tensorrt_fp32_in8b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 5000 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/5000]  Top-1: 90.00%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [50/5000]  Top-1: 95.00%  Top-5: 100.00%  Infer: 0.94 ms/batch
  [60/5000]  Top-1: 93.33%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [70/5000]  Top-1: 90.00%  Top-5: 97.50%  Infer: 0.93 ms/batch
  [80/5000]  Top-1: 88.00%  Top-5: 98.00%  Infer: 0.95 ms/batch
  [90/5000]  Top-1: 90.00%  Top-5: 98.33%  Infer: 0.95 ms/batch
  [100/5000]  Top-1: 88.57%  Top-5: 98.57%  Infer: 0.94 ms/batch
  [110/5000]  Top-1: 88.75%  Top-5: 98.75%  Infer: 0.94 ms/batch
  [120/5000]  Top-1: 87.78%  Top-5: 97.78%  Infer: 0.94 ms/batch
  [130/5000]  Top-1: 89.00%  Top-5: 98.00%  Infer: 0.95 ms/batch
  [140/5000]  Top-1: 89.09%  Top-5: 98.18%  Infer: 0.95 ms/batch
  [150/5000]  Top-1: 87.50%  Top-5: 97.50%  Infer: 0.95 ms/batch
  [160/5000]  Top-1: 86.92%  Top-5: 97.69%  Infer: 0.95 ms/batch
  [170/5000]  Top-1: 84.29%  Top-5: 97.86%  Infer: 0.94 ms/batch
  [180/5000]  Top-1: 84.00%  Top-5: 97.33%  Infer: 0.94 ms/batch
  [190/5000]  Top-1: 83.12%  Top-5: 96.88%  Infer: 0.94 ms/batch
  [200/5000]  Top-1: 82.94%  Top-5: 96.47%  Infer: 0.94 ms/batch
  [210/5000]  Top-1: 82.78%  Top-5: 96.11%  Infer: 0.94 ms/batch
  [220/5000]  Top-1: 83.16%  Top-5: 95.79%  Infer: 0.94 ms/batch
  [230/5000]  Top-1: 82.50%  Top-5: 96.00%  Infer: 0.94 ms/batch
  [240/5000]  Top-1: 81.90%  Top-5: 96.19%  Infer: 0.94 ms/batch
  [250/5000]  Top-1: 81.36%  Top-5: 96.36%  Infer: 0.94 ms/batch
  [260/5000]  Top-1: 81.30%  Top-5: 96.52%  Infer: 0.95 ms/batch
  [270/5000]  Top-1: 80.00%  Top-5: 95.83%  Infer: 0.95 ms/batch
  [280/5000]  Top-1: 80.00%  Top-5: 95.60%  Infer: 0.95 ms/batch
  [290/5000]  Top-1: 80.38%  Top-5: 95.77%  Infer: 0.96 ms/batch
  [300/5000]  Top-1: 80.00%  Top-5: 95.56%  Infer: 0.96 ms/batch
  [310/5000]  Top-1: 79.29%  Top-5: 95.36%  Infer: 0.96 ms/batch
  [320/5000]  Top-1: 79.31%  Top-5: 95.52%  Infer: 0.95 ms/batch
  [330/5000]  Top-1: 79.33%  Top-5: 95.67%  Infer: 0.95 ms/batch
  [340/5000]  Top-1: 78.71%  Top-5: 95.81%  Infer: 0.95 ms/batch
  [350/5000]  Top-1: 78.44%  Top-5: 95.62%  Infer: 0.95 ms/batch
  [360/5000]  Top-1: 77.58%  Top-5: 95.76%  Infer: 0.95 ms/batch
  [370/5000]  Top-1: 76.76%  Top-5: 95.29%  Infer: 0.95 ms/batch
  [380/5000]  Top-1: 76.57%  Top-5: 95.43%  Infer: 0.95 ms/batch
  [390/5000]  Top-1: 76.94%  Top-5: 95.28%  Infer: 0.95 ms/batch
  [400/5000]  Top-1: 76.76%  Top-5: 95.14%  Infer: 0.95 ms/batch
  [410/5000]  Top-1: 76.84%  Top-5: 95.00%  Infer: 0.95 ms/batch
  [420/5000]  Top-1: 76.92%  Top-5: 95.13%  Infer: 0.95 ms/batch
  [430/5000]  Top-1: 77.25%  Top-5: 95.25%  Infer: 0.95 ms/batch
  [440/5000]  Top-1: 77.32%  Top-5: 95.37%  Infer: 0.95 ms/batch
  [450/5000]  Top-1: 77.62%  Top-5: 95.48%  Infer: 0.95 ms/batch
  [460/5000]  Top-1: 78.14%  Top-5: 95.58%  Infer: 0.95 ms/batch
  [470/5000]  Top-1: 78.64%  Top-5: 95.68%  Infer: 0.95 ms/batch
  [480/5000]  Top-1: 79.11%  Top-5: 95.78%  Infer: 0.95 ms/batch
  [490/5000]  Top-1: 79.35%  Top-5: 95.87%  Infer: 0.95 ms/batch
  [500/5000]  Top-1: 79.79%  Top-5: 95.96%  Infer: 0.95 ms/batch
  [510/5000]  Top-1: 80.00%  Top-5: 95.83%  Infer: 0.96 ms/batch
  [520/5000]  Top-1: 80.41%  Top-5: 95.92%  Infer: 0.96 ms/batch
  [530/5000]  Top-1: 80.40%  Top-5: 95.80%  Infer: 0.96 ms/batch
  [540/5000]  Top-1: 80.59%  Top-5: 95.88%  Infer: 0.96 ms/batch
  [550/5000]  Top-1: 80.77%  Top-5: 95.96%  Infer: 0.96 ms/batch
  [560/5000]  Top-1: 81.13%  Top-5: 96.04%  Infer: 0.96 ms/batch
  [570/5000]  Top-1: 81.48%  Top-5: 96.11%  Infer: 0.96 ms/batch
  [580/5000]  Top-1: 81.82%  Top-5: 96.18%  Infer: 0.96 ms/batch
  [590/5000]  Top-1: 81.96%  Top-5: 96.25%  Infer: 0.96 ms/batch
  [600/5000]  Top-1: 82.11%  Top-5: 96.32%  Infer: 0.96 ms/batch
  [610/5000]  Top-1: 82.24%  Top-5: 96.38%  Infer: 0.96 ms/batch
  [620/5000]  Top-1: 82.03%  Top-5: 95.93%  Infer: 0.96 ms/batch
  [630/5000]  Top-1: 82.33%  Top-5: 96.00%  Infer: 0.96 ms/batch
  [640/5000]  Top-1: 82.30%  Top-5: 96.07%  Infer: 0.96 ms/batch
  [650/5000]  Top-1: 82.42%  Top-5: 96.13%  Infer: 0.96 ms/batch
  [660/5000]  Top-1: 82.70%  Top-5: 96.19%  Infer: 0.96 ms/batch
  [670/5000]  Top-1: 82.97%  Top-5: 96.25%  Infer: 0.96 ms/batch
  [680/5000]  Top-1: 83.23%  Top-5: 96.31%  Infer: 0.96 ms/batch
  [690/5000]  Top-1: 83.48%  Top-5: 96.36%  Infer: 0.96 ms/batch
  [700/5000]  Top-1: 83.73%  Top-5: 96.42%  Infer: 0.96 ms/batch
  [710/5000]  Top-1: 83.82%  Top-5: 96.47%  Infer: 0.96 ms/batch
  [720/5000]  Top-1: 84.06%  Top-5: 96.52%  Infer: 0.96 ms/batch
  [730/5000]  Top-1: 84.00%  Top-5: 96.57%  Infer: 0.96 ms/batch
  [740/5000]  Top-1: 83.94%  Top-5: 96.62%  Infer: 0.96 ms/batch
  [750/5000]  Top-1: 84.17%  Top-5: 96.67%  Infer: 0.96 ms/batch
  [760/5000]  Top-1: 84.25%  Top-5: 96.71%  Infer: 0.96 ms/batch
  [770/5000]  Top-1: 84.32%  Top-5: 96.76%  Infer: 0.96 ms/batch
  [780/5000]  Top-1: 84.53%  Top-5: 96.80%  Infer: 0.96 ms/batch
  [790/5000]  Top-1: 84.74%  Top-5: 96.84%  Infer: 0.96 ms/batch
  [800/5000]  Top-1: 84.81%  Top-5: 96.75%  Infer: 0.96 ms/batch
  [810/5000]  Top-1: 84.87%  Top-5: 96.67%  Infer: 0.96 ms/batch
  [820/5000]  Top-1: 84.81%  Top-5: 96.46%  Infer: 0.96 ms/batch
  [830/5000]  Top-1: 84.88%  Top-5: 96.50%  Infer: 0.96 ms/batch
  [840/5000]  Top-1: 84.94%  Top-5: 96.54%  Infer: 0.96 ms/batch
  [850/5000]  Top-1: 84.88%  Top-5: 96.59%  Infer: 0.96 ms/batch
  [860/5000]  Top-1: 84.82%  Top-5: 96.51%  Infer: 0.96 ms/batch
  [870/5000]  Top-1: 84.88%  Top-5: 96.55%  Infer: 0.96 ms/batch
  [880/5000]  Top-1: 84.71%  Top-5: 96.59%  Infer: 0.96 ms/batch
  [890/5000]  Top-1: 84.88%  Top-5: 96.63%  Infer: 0.95 ms/batch
  [900/5000]  Top-1: 85.06%  Top-5: 96.67%  Infer: 0.96 ms/batch
  [910/5000]  Top-1: 85.23%  Top-5: 96.70%  Infer: 0.95 ms/batch
  [920/5000]  Top-1: 85.28%  Top-5: 96.63%  Infer: 0.95 ms/batch
  [930/5000]  Top-1: 85.22%  Top-5: 96.67%  Infer: 0.96 ms/batch
  [940/5000]  Top-1: 85.05%  Top-5: 96.48%  Infer: 0.96 ms/batch
  [950/5000]  Top-1: 85.00%  Top-5: 96.41%  Infer: 0.96 ms/batch
  [960/5000]  Top-1: 84.95%  Top-5: 96.34%  Infer: 0.96 ms/batch
  [970/5000]  Top-1: 85.00%  Top-5: 96.38%  Infer: 0.96 ms/batch
  [980/5000]  Top-1: 85.05%  Top-5: 96.42%  Infer: 0.96 ms/batch
  [990/5000]  Top-1: 85.21%  Top-5: 96.46%  Infer: 0.95 ms/batch
  [1000/5000]  Top-1: 85.26%  Top-5: 96.49%  Infer: 0.95 ms/batch
  [1010/5000]  Top-1: 85.31%  Top-5: 96.53%  Infer: 0.96 ms/batch
  [1020/5000]  Top-1: 85.35%  Top-5: 96.46%  Infer: 0.96 ms/batch
  [1030/5000]  Top-1: 85.30%  Top-5: 96.40%  Infer: 0.96 ms/batch
  [1040/5000]  Top-1: 85.35%  Top-5: 96.44%  Infer: 0.95 ms/batch
  [1050/5000]  Top-1: 85.39%  Top-5: 96.37%  Infer: 0.95 ms/batch
  [1060/5000]  Top-1: 85.24%  Top-5: 96.21%  Infer: 0.95 ms/batch
  [1070/5000]  Top-1: 85.10%  Top-5: 96.15%  Infer: 0.95 ms/batch
  [1080/5000]  Top-1: 85.05%  Top-5: 96.10%  Infer: 0.95 ms/batch
  [1090/5000]  Top-1: 85.09%  Top-5: 96.13%  Infer: 0.95 ms/batch
  [1100/5000]  Top-1: 84.95%  Top-5: 96.07%  Infer: 0.95 ms/batch
  [1110/5000]  Top-1: 85.00%  Top-5: 96.02%  Infer: 0.95 ms/batch
  [1120/5000]  Top-1: 85.05%  Top-5: 96.06%  Infer: 0.95 ms/batch
  [1130/5000]  Top-1: 85.18%  Top-5: 96.09%  Infer: 0.96 ms/batch
  [1140/5000]  Top-1: 85.23%  Top-5: 96.13%  Infer: 0.95 ms/batch
  [1150/5000]  Top-1: 85.36%  Top-5: 96.16%  Infer: 0.95 ms/batch
  [1160/5000]  Top-1: 85.40%  Top-5: 96.19%  Infer: 0.95 ms/batch
  [1170/5000]  Top-1: 85.35%  Top-5: 96.14%  Infer: 0.95 ms/batch
  [1180/5000]  Top-1: 85.39%  Top-5: 96.17%  Infer: 0.95 ms/batch
  [1190/5000]  Top-1: 85.43%  Top-5: 96.12%  Infer: 0.95 ms/batch
  [1200/5000]  Top-1: 85.30%  Top-5: 96.15%  Infer: 0.95 ms/batch
  [1210/5000]  Top-1: 85.34%  Top-5: 96.10%  Infer: 0.95 ms/batch
  [1220/5000]  Top-1: 85.46%  Top-5: 96.13%  Infer: 0.95 ms/batch
  [1230/5000]  Top-1: 85.58%  Top-5: 96.17%  Infer: 0.95 ms/batch
  [1240/5000]  Top-1: 85.70%  Top-5: 96.20%  Infer: 0.95 ms/batch
  [1250/5000]  Top-1: 85.82%  Top-5: 96.23%  Infer: 0.95 ms/batch
  [1260/5000]  Top-1: 85.85%  Top-5: 96.18%  Infer: 0.95 ms/batch
  [1270/5000]  Top-1: 85.97%  Top-5: 96.21%  Infer: 0.95 ms/batch
  [1280/5000]  Top-1: 86.08%  Top-5: 96.24%  Infer: 0.95 ms/batch
  [1290/5000]  Top-1: 86.19%  Top-5: 96.27%  Infer: 0.95 ms/batch
  [1300/5000]  Top-1: 86.30%  Top-5: 96.30%  Infer: 0.95 ms/batch
  [1310/5000]  Top-1: 86.09%  Top-5: 96.33%  Infer: 0.95 ms/batch
  [1320/5000]  Top-1: 86.12%  Top-5: 96.36%  Infer: 0.95 ms/batch
  [1330/5000]  Top-1: 85.69%  Top-5: 96.15%  Infer: 0.95 ms/batch
  [1340/5000]  Top-1: 85.34%  Top-5: 96.11%  Infer: 0.95 ms/batch
  [1350/5000]  Top-1: 84.85%  Top-5: 95.98%  Infer: 0.95 ms/batch
  [1360/5000]  Top-1: 84.81%  Top-5: 95.94%  Infer: 0.95 ms/batch
  [1370/5000]  Top-1: 84.78%  Top-5: 95.97%  Infer: 0.95 ms/batch
  [1380/5000]  Top-1: 84.59%  Top-5: 95.85%  Infer: 0.95 ms/batch
  [1390/5000]  Top-1: 84.41%  Top-5: 95.81%  Infer: 0.95 ms/batch
  [1400/5000]  Top-1: 84.45%  Top-5: 95.84%  Infer: 0.95 ms/batch
  [1410/5000]  Top-1: 84.35%  Top-5: 95.87%  Infer: 0.95 ms/batch
  [1420/5000]  Top-1: 84.46%  Top-5: 95.90%  Infer: 0.95 ms/batch
  [1430/5000]  Top-1: 84.50%  Top-5: 95.86%  Infer: 0.95 ms/batch
  [1440/5000]  Top-1: 84.61%  Top-5: 95.89%  Infer: 0.95 ms/batch
  [1450/5000]  Top-1: 84.65%  Top-5: 95.92%  Infer: 0.95 ms/batch
  [1460/5000]  Top-1: 84.69%  Top-5: 95.94%  Infer: 0.95 ms/batch
  [1470/5000]  Top-1: 84.65%  Top-5: 95.97%  Infer: 0.95 ms/batch
  [1480/5000]  Top-1: 84.69%  Top-5: 95.93%  Infer: 0.95 ms/batch
  [1490/5000]  Top-1: 84.73%  Top-5: 95.89%  Infer: 0.95 ms/batch
  [1500/5000]  Top-1: 84.63%  Top-5: 95.85%  Infer: 0.95 ms/batch
  [1510/5000]  Top-1: 84.53%  Top-5: 95.68%  Infer: 0.95 ms/batch
  [1520/5000]  Top-1: 84.56%  Top-5: 95.64%  Infer: 0.95 ms/batch
  [1530/5000]  Top-1: 84.53%  Top-5: 95.67%  Infer: 0.95 ms/batch
  [1540/5000]  Top-1: 84.50%  Top-5: 95.70%  Infer: 0.95 ms/batch
  [1550/5000]  Top-1: 84.47%  Top-5: 95.66%  Infer: 0.95 ms/batch
  [1560/5000]  Top-1: 84.44%  Top-5: 95.69%  Infer: 0.95 ms/batch
  [1570/5000]  Top-1: 84.35%  Top-5: 95.58%  Infer: 0.95 ms/batch
  [1580/5000]  Top-1: 84.32%  Top-5: 95.61%  Infer: 0.95 ms/batch
  [1590/5000]  Top-1: 84.23%  Top-5: 95.58%  Infer: 0.95 ms/batch
  [1600/5000]  Top-1: 84.20%  Top-5: 95.54%  Infer: 0.95 ms/batch
  [1610/5000]  Top-1: 83.86%  Top-5: 95.44%  Infer: 0.95 ms/batch
  [1620/5000]  Top-1: 83.65%  Top-5: 95.41%  Infer: 0.95 ms/batch
  [1630/5000]  Top-1: 83.56%  Top-5: 95.44%  Infer: 0.95 ms/batch
  [1640/5000]  Top-1: 83.17%  Top-5: 95.22%  Infer: 0.95 ms/batch
  [1650/5000]  Top-1: 82.84%  Top-5: 94.94%  Infer: 0.96 ms/batch
  [1660/5000]  Top-1: 82.82%  Top-5: 94.91%  Infer: 0.96 ms/batch
  [1670/5000]  Top-1: 82.87%  Top-5: 94.88%  Infer: 0.96 ms/batch
  [1680/5000]  Top-1: 82.85%  Top-5: 94.91%  Infer: 0.96 ms/batch
  [1690/5000]  Top-1: 82.89%  Top-5: 94.94%  Infer: 0.96 ms/batch
  [1700/5000]  Top-1: 82.81%  Top-5: 94.91%  Infer: 0.96 ms/batch
  [1710/5000]  Top-1: 82.74%  Top-5: 94.88%  Infer: 0.96 ms/batch
  [1720/5000]  Top-1: 82.66%  Top-5: 94.85%  Infer: 0.96 ms/batch
  [1730/5000]  Top-1: 82.47%  Top-5: 94.76%  Infer: 0.96 ms/batch
  [1740/5000]  Top-1: 82.34%  Top-5: 94.68%  Infer: 0.96 ms/batch
  [1750/5000]  Top-1: 82.38%  Top-5: 94.65%  Infer: 0.96 ms/batch
  [1760/5000]  Top-1: 82.14%  Top-5: 94.68%  Infer: 0.96 ms/batch
  [1770/5000]  Top-1: 81.95%  Top-5: 94.54%  Infer: 0.96 ms/batch
  [1780/5000]  Top-1: 81.94%  Top-5: 94.51%  Infer: 0.96 ms/batch
  [1790/5000]  Top-1: 81.70%  Top-5: 94.43%  Infer: 0.96 ms/batch
  [1800/5000]  Top-1: 81.64%  Top-5: 94.35%  Infer: 0.96 ms/batch
  [1810/5000]  Top-1: 81.29%  Top-5: 94.38%  Infer: 0.96 ms/batch
  [1820/5000]  Top-1: 81.17%  Top-5: 94.36%  Infer: 0.96 ms/batch
  [1830/5000]  Top-1: 81.00%  Top-5: 94.33%  Infer: 0.95 ms/batch
  [1840/5000]  Top-1: 80.88%  Top-5: 94.36%  Infer: 0.95 ms/batch
  [1850/5000]  Top-1: 80.88%  Top-5: 94.40%  Infer: 0.95 ms/batch
  [1860/5000]  Top-1: 80.82%  Top-5: 94.32%  Infer: 0.96 ms/batch
  [1870/5000]  Top-1: 80.87%  Top-5: 94.35%  Infer: 0.96 ms/batch
  [1880/5000]  Top-1: 80.86%  Top-5: 94.38%  Infer: 0.95 ms/batch
  [1890/5000]  Top-1: 80.86%  Top-5: 94.41%  Infer: 0.96 ms/batch
  [1900/5000]  Top-1: 80.80%  Top-5: 94.44%  Infer: 0.96 ms/batch
  [1910/5000]  Top-1: 80.74%  Top-5: 94.47%  Infer: 0.96 ms/batch
  [1920/5000]  Top-1: 80.69%  Top-5: 94.39%  Infer: 0.96 ms/batch
  [1930/5000]  Top-1: 80.74%  Top-5: 94.37%  Infer: 0.96 ms/batch
  [1940/5000]  Top-1: 80.63%  Top-5: 94.35%  Infer: 0.96 ms/batch
  [1950/5000]  Top-1: 80.52%  Top-5: 94.27%  Infer: 0.96 ms/batch
  [1960/5000]  Top-1: 80.52%  Top-5: 94.30%  Infer: 0.96 ms/batch
  [1970/5000]  Top-1: 80.57%  Top-5: 94.28%  Infer: 0.96 ms/batch
  [1980/5000]  Top-1: 80.51%  Top-5: 94.31%  Infer: 0.96 ms/batch
  [1990/5000]  Top-1: 80.61%  Top-5: 94.34%  Infer: 0.96 ms/batch
  [2000/5000]  Top-1: 80.51%  Top-5: 94.31%  Infer: 0.96 ms/batch
  [2010/5000]  Top-1: 80.45%  Top-5: 94.34%  Infer: 0.96 ms/batch
  [2020/5000]  Top-1: 80.30%  Top-5: 94.37%  Infer: 0.96 ms/batch
  [2030/5000]  Top-1: 80.00%  Top-5: 94.35%  Infer: 0.96 ms/batch
  [2040/5000]  Top-1: 79.85%  Top-5: 94.38%  Infer: 0.96 ms/batch
  [2050/5000]  Top-1: 79.70%  Top-5: 94.36%  Infer: 0.96 ms/batch
  [2060/5000]  Top-1: 79.66%  Top-5: 94.24%  Infer: 0.96 ms/batch
  [2070/5000]  Top-1: 79.71%  Top-5: 94.26%  Infer: 0.96 ms/batch
  [2080/5000]  Top-1: 79.71%  Top-5: 94.24%  Infer: 0.96 ms/batch
  [2090/5000]  Top-1: 79.66%  Top-5: 94.17%  Infer: 0.96 ms/batch
  [2100/5000]  Top-1: 79.71%  Top-5: 94.20%  Infer: 0.96 ms/batch
  [2110/5000]  Top-1: 79.57%  Top-5: 94.13%  Infer: 0.95 ms/batch
  [2120/5000]  Top-1: 79.47%  Top-5: 94.11%  Infer: 0.95 ms/batch
  [2130/5000]  Top-1: 79.52%  Top-5: 94.10%  Infer: 0.95 ms/batch
  [2140/5000]  Top-1: 79.53%  Top-5: 94.08%  Infer: 0.95 ms/batch
  [2150/5000]  Top-1: 79.53%  Top-5: 94.10%  Infer: 0.95 ms/batch
  [2160/5000]  Top-1: 79.53%  Top-5: 94.08%  Infer: 0.95 ms/batch
  [2170/5000]  Top-1: 79.44%  Top-5: 94.07%  Infer: 0.95 ms/batch
  [2180/5000]  Top-1: 79.44%  Top-5: 94.00%  Infer: 0.95 ms/batch
  [2190/5000]  Top-1: 79.49%  Top-5: 94.03%  Infer: 0.95 ms/batch
  [2200/5000]  Top-1: 79.49%  Top-5: 94.01%  Infer: 0.95 ms/batch
  [2210/5000]  Top-1: 79.50%  Top-5: 93.99%  Infer: 0.95 ms/batch
  [2220/5000]  Top-1: 79.32%  Top-5: 93.88%  Infer: 0.95 ms/batch
  [2230/5000]  Top-1: 79.27%  Top-5: 93.86%  Infer: 0.95 ms/batch
  [2240/5000]  Top-1: 79.00%  Top-5: 93.57%  Infer: 0.95 ms/batch
  [2250/5000]  Top-1: 79.01%  Top-5: 93.56%  Infer: 0.95 ms/batch
  [2260/5000]  Top-1: 78.83%  Top-5: 93.50%  Infer: 0.95 ms/batch
  [2270/5000]  Top-1: 78.93%  Top-5: 93.53%  Infer: 0.95 ms/batch
  [2280/5000]  Top-1: 78.98%  Top-5: 93.56%  Infer: 0.95 ms/batch
  [2290/5000]  Top-1: 78.98%  Top-5: 93.54%  Infer: 0.95 ms/batch
  [2300/5000]  Top-1: 78.99%  Top-5: 93.52%  Infer: 0.95 ms/batch
  [2310/5000]  Top-1: 78.82%  Top-5: 93.55%  Infer: 0.95 ms/batch
  [2320/5000]  Top-1: 78.73%  Top-5: 93.54%  Infer: 0.95 ms/batch
  [2330/5000]  Top-1: 78.57%  Top-5: 93.52%  Infer: 0.95 ms/batch
  [2340/5000]  Top-1: 78.57%  Top-5: 93.55%  Infer: 0.95 ms/batch
  [2350/5000]  Top-1: 78.41%  Top-5: 93.58%  Infer: 0.95 ms/batch
  [2360/5000]  Top-1: 78.37%  Top-5: 93.52%  Infer: 0.95 ms/batch
  [2370/5000]  Top-1: 78.38%  Top-5: 93.50%  Infer: 0.95 ms/batch
  [2380/5000]  Top-1: 78.26%  Top-5: 93.36%  Infer: 0.95 ms/batch
  [2390/5000]  Top-1: 78.22%  Top-5: 93.31%  Infer: 0.95 ms/batch
  [2400/5000]  Top-1: 78.31%  Top-5: 93.33%  Infer: 0.95 ms/batch
  [2410/5000]  Top-1: 78.36%  Top-5: 93.36%  Infer: 0.95 ms/batch
  [2420/5000]  Top-1: 78.41%  Top-5: 93.35%  Infer: 0.95 ms/batch
  [2430/5000]  Top-1: 78.46%  Top-5: 93.38%  Infer: 0.95 ms/batch
  [2440/5000]  Top-1: 78.51%  Top-5: 93.40%  Infer: 0.95 ms/batch
  [2450/5000]  Top-1: 78.60%  Top-5: 93.43%  Infer: 0.95 ms/batch
  [2460/5000]  Top-1: 78.56%  Top-5: 93.42%  Infer: 0.95 ms/batch
  [2470/5000]  Top-1: 78.40%  Top-5: 93.36%  Infer: 0.95 ms/batch
  [2480/5000]  Top-1: 78.37%  Top-5: 93.35%  Infer: 0.95 ms/batch
  [2490/5000]  Top-1: 78.29%  Top-5: 93.33%  Infer: 0.95 ms/batch
  [2500/5000]  Top-1: 78.26%  Top-5: 93.36%  Infer: 0.95 ms/batch
  [2510/5000]  Top-1: 78.31%  Top-5: 93.39%  Infer: 0.95 ms/batch
  [2520/5000]  Top-1: 78.23%  Top-5: 93.41%  Infer: 0.95 ms/batch
  [2530/5000]  Top-1: 78.20%  Top-5: 93.44%  Infer: 0.95 ms/batch
  [2540/5000]  Top-1: 78.21%  Top-5: 93.47%  Infer: 0.95 ms/batch
  [2550/5000]  Top-1: 78.21%  Top-5: 93.45%  Infer: 0.95 ms/batch
  [2560/5000]  Top-1: 78.22%  Top-5: 93.44%  Infer: 0.95 ms/batch
  [2570/5000]  Top-1: 78.23%  Top-5: 93.43%  Infer: 0.95 ms/batch
  [2580/5000]  Top-1: 78.31%  Top-5: 93.45%  Infer: 0.95 ms/batch
  [2590/5000]  Top-1: 78.32%  Top-5: 93.44%  Infer: 0.95 ms/batch
  [2600/5000]  Top-1: 78.40%  Top-5: 93.46%  Infer: 0.95 ms/batch
  [2610/5000]  Top-1: 78.41%  Top-5: 93.49%  Infer: 0.95 ms/batch
  [2620/5000]  Top-1: 78.49%  Top-5: 93.51%  Infer: 0.95 ms/batch
  [2630/5000]  Top-1: 78.50%  Top-5: 93.54%  Infer: 0.95 ms/batch
  [2640/5000]  Top-1: 78.35%  Top-5: 93.49%  Infer: 0.95 ms/batch
  [2650/5000]  Top-1: 78.24%  Top-5: 93.40%  Infer: 0.95 ms/batch
  [2660/5000]  Top-1: 78.29%  Top-5: 93.38%  Infer: 0.95 ms/batch
  [2670/5000]  Top-1: 78.26%  Top-5: 93.41%  Infer: 0.95 ms/batch
  [2680/5000]  Top-1: 78.26%  Top-5: 93.40%  Infer: 0.95 ms/batch
  [2690/5000]  Top-1: 78.23%  Top-5: 93.38%  Infer: 0.95 ms/batch
  [2700/5000]  Top-1: 78.16%  Top-5: 93.37%  Infer: 0.95 ms/batch
  [2710/5000]  Top-1: 78.02%  Top-5: 93.25%  Infer: 0.95 ms/batch
  [2720/5000]  Top-1: 77.96%  Top-5: 93.23%  Infer: 0.95 ms/batch
  [2730/5000]  Top-1: 77.85%  Top-5: 93.15%  Infer: 0.95 ms/batch
  [2740/5000]  Top-1: 77.71%  Top-5: 92.99%  Infer: 0.95 ms/batch
  [2750/5000]  Top-1: 77.65%  Top-5: 93.01%  Infer: 0.95 ms/batch
  [2760/5000]  Top-1: 77.62%  Top-5: 93.04%  Infer: 0.95 ms/batch
  [2770/5000]  Top-1: 77.55%  Top-5: 93.07%  Infer: 0.95 ms/batch
  [2780/5000]  Top-1: 77.42%  Top-5: 93.05%  Infer: 0.95 ms/batch
  [2790/5000]  Top-1: 77.36%  Top-5: 93.08%  Infer: 0.95 ms/batch
  [2800/5000]  Top-1: 77.33%  Top-5: 93.10%  Infer: 0.96 ms/batch
  [2810/5000]  Top-1: 77.41%  Top-5: 93.13%  Infer: 0.95 ms/batch
  [2820/5000]  Top-1: 77.38%  Top-5: 93.08%  Infer: 0.95 ms/batch
  [2830/5000]  Top-1: 77.39%  Top-5: 93.07%  Infer: 0.95 ms/batch
  [2840/5000]  Top-1: 77.40%  Top-5: 93.02%  Infer: 0.96 ms/batch
  [2850/5000]  Top-1: 77.48%  Top-5: 93.05%  Infer: 0.96 ms/batch
  [2860/5000]  Top-1: 77.49%  Top-5: 93.07%  Infer: 0.96 ms/batch
  [2870/5000]  Top-1: 77.57%  Top-5: 93.10%  Infer: 0.96 ms/batch
  [2880/5000]  Top-1: 77.58%  Top-5: 93.12%  Infer: 0.96 ms/batch
  [2890/5000]  Top-1: 77.55%  Top-5: 93.15%  Infer: 0.96 ms/batch
  [2900/5000]  Top-1: 77.63%  Top-5: 93.17%  Infer: 0.96 ms/batch
  [2910/5000]  Top-1: 77.57%  Top-5: 93.12%  Infer: 0.96 ms/batch
  [2920/5000]  Top-1: 77.54%  Top-5: 93.11%  Infer: 0.96 ms/batch
  [2930/5000]  Top-1: 77.55%  Top-5: 93.10%  Infer: 0.96 ms/batch
  [2940/5000]  Top-1: 77.49%  Top-5: 93.09%  Infer: 0.96 ms/batch
  [2950/5000]  Top-1: 77.50%  Top-5: 93.08%  Infer: 0.96 ms/batch
  [2960/5000]  Top-1: 77.41%  Top-5: 93.07%  Infer: 0.96 ms/batch
  [2970/5000]  Top-1: 77.38%  Top-5: 92.99%  Infer: 0.96 ms/batch
  [2980/5000]  Top-1: 77.25%  Top-5: 92.88%  Infer: 0.96 ms/batch
  [2990/5000]  Top-1: 77.13%  Top-5: 92.80%  Infer: 0.96 ms/batch
  [3000/5000]  Top-1: 77.10%  Top-5: 92.76%  Infer: 0.96 ms/batch
  [3010/5000]  Top-1: 76.98%  Top-5: 92.72%  Infer: 0.96 ms/batch

## FP16

In [7]:
fp16_records = []
print("TRT Precision: fp16")
for (bits, seed), info in experiments.items():
    base = make_base(bits, seed, info["seed_num"])
    cfg = with_overrides(base, model_precision="fp16", input_quant_bits=bits)

    if cfg.result_json_path().exists():
        print(f"  SKIP {bits}bit / {seed} (result exists)")
        continue

    print(f"\n  {bits}bit / {seed}:")
    payload = run_trt_test_experiment(cfg)
    fp16_records.append(payload)
    r = payload["results"]
    print(f"    top1={r['top1_acc']:.2f}%  top5={r['top5_acc']:.2f}%  infer={r['infer_ms_avg']:.2f}ms")

TRT Precision: fp16

  8bit / seed_1:
[data] Filtered to 5000 samples across 100 classes.
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/fp32_8bit/seed_1/resnet18_tensorrt_fp16_in8b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 5000 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/5000]  Top-1: 90.00%  Top-5: 100.00%  Infer: 0.46 ms/batch
  [50/5000]  Top-1: 95.00%  Top-5: 100.00%  Infer: 0.55 ms/batch
  [60/5000]  Top-1: 93.33%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [70/5000]  Top-1: 90.00%  Top-5: 97.50%  Infer: 0.50 ms/batch
  [80/5000]  Top-1: 88.00%  Top-5: 98.00%  Infer: 0.49 ms/batch
  [90/5000]  Top-1: 90.00%  Top-5: 98.33%  Infer: 0.48 ms/batch
  [100/5000]  Top-1: 88.57%  Top-5: 98.57%  Infer: 0.51 ms/batch
  [110/5000]  Top-1: 88.75%  Top-5: 98.75%  Infer: 0.51 ms/batch
  [120/5000]  Top-1: 87.78%  Top-5: 97.78%  Infer: 0.50 ms/batch
  [130/5000]  Top-1: 89.00%  Top-5: 98.00%  Infer: 0.51 ms/batch
  [140/5000]  Top-1: 89.09%  Top-5: 98.18%  Infer: 0.51 ms/batch
  [150/5000]  Top-1: 87.50%  Top-5: 97.50%  Infer: 0.50 ms/batch
  [160/5000]  Top-1: 86.92%  Top-5: 97.69%  Infer: 0.50 ms/batch
  [170/5000]  Top-1: 84.29%  Top-5: 97.86%  Infer: 0.50 ms/batch
  [180/5000]  Top-1: 84.00%  Top-5: 97.33%  Infer: 0.50 ms/batch
  [190/5000]  Top-1: 83.12%  Top-5: 96.88%  Infer: 0.49 ms/batch
  [200/5000]  Top-1: 82.94%  Top-5: 96.47%  Infer: 0.49 ms/batch
  [210/5000]  Top-1: 82.78%  Top-5: 96.11%  Infer: 0.49 ms/batch
  [220/5000]  Top-1: 83.16%  Top-5: 95.79%  Infer: 0.49 ms/batch
  [230/5000]  Top-1: 82.50%  Top-5: 96.00%  Infer: 0.48 ms/batch
  [240/5000]  Top-1: 81.90%  Top-5: 96.19%  Infer: 0.48 ms/batch
  [250/5000]  Top-1: 81.36%  Top-5: 96.36%  Infer: 0.49 ms/batch
  [260/5000]  Top-1: 81.30%  Top-5: 96.52%  Infer: 0.49 ms/batch
  [270/5000]  Top-1: 80.00%  Top-5: 95.83%  Infer: 0.49 ms/batch
  [280/5000]  Top-1: 80.00%  Top-5: 95.60%  Infer: 0.49 ms/batch
  [290/5000]  Top-1: 80.38%  Top-5: 95.77%  Infer: 0.50 ms/batch
  [300/5000]  Top-1: 80.00%  Top-5: 95.56%  Infer: 0.49 ms/batch
  [310/5000]  Top-1: 79.29%  Top-5: 95.36%  Infer: 0.49 ms/batch
  [320/5000]  Top-1: 79.31%  Top-5: 95.52%  Infer: 0.50 ms/batch
  [330/5000]  Top-1: 79.67%  Top-5: 95.67%  Infer: 0.50 ms/batch
  [340/5000]  Top-1: 79.03%  Top-5: 95.81%  Infer: 0.50 ms/batch
  [350/5000]  Top-1: 78.75%  Top-5: 95.62%  Infer: 0.50 ms/batch
  [360/5000]  Top-1: 77.88%  Top-5: 95.76%  Infer: 0.50 ms/batch
  [370/5000]  Top-1: 77.06%  Top-5: 95.29%  Infer: 0.49 ms/batch
  [380/5000]  Top-1: 76.86%  Top-5: 95.43%  Infer: 0.49 ms/batch
  [390/5000]  Top-1: 77.22%  Top-5: 95.28%  Infer: 0.49 ms/batch
  [400/5000]  Top-1: 77.03%  Top-5: 95.14%  Infer: 0.49 ms/batch
  [410/5000]  Top-1: 77.11%  Top-5: 95.00%  Infer: 0.49 ms/batch
  [420/5000]  Top-1: 77.18%  Top-5: 95.13%  Infer: 0.49 ms/batch
  [430/5000]  Top-1: 77.50%  Top-5: 95.25%  Infer: 0.49 ms/batch
  [440/5000]  Top-1: 77.56%  Top-5: 95.37%  Infer: 0.49 ms/batch
  [450/5000]  Top-1: 77.86%  Top-5: 95.48%  Infer: 0.49 ms/batch
  [460/5000]  Top-1: 78.37%  Top-5: 95.58%  Infer: 0.49 ms/batch
  [470/5000]  Top-1: 78.86%  Top-5: 95.68%  Infer: 0.50 ms/batch
  [480/5000]  Top-1: 79.33%  Top-5: 95.78%  Infer: 0.49 ms/batch
  [490/5000]  Top-1: 79.57%  Top-5: 95.87%  Infer: 0.49 ms/batch
  [500/5000]  Top-1: 80.00%  Top-5: 95.96%  Infer: 0.49 ms/batch
  [510/5000]  Top-1: 80.21%  Top-5: 95.83%  Infer: 0.49 ms/batch
  [520/5000]  Top-1: 80.61%  Top-5: 95.92%  Infer: 0.49 ms/batch
  [530/5000]  Top-1: 80.60%  Top-5: 95.80%  Infer: 0.49 ms/batch
  [540/5000]  Top-1: 80.78%  Top-5: 95.88%  Infer: 0.49 ms/batch
  [550/5000]  Top-1: 80.96%  Top-5: 95.96%  Infer: 0.49 ms/batch
  [560/5000]  Top-1: 81.32%  Top-5: 96.04%  Infer: 0.49 ms/batch
  [570/5000]  Top-1: 81.67%  Top-5: 96.11%  Infer: 0.49 ms/batch
  [580/5000]  Top-1: 82.00%  Top-5: 96.18%  Infer: 0.49 ms/batch
  [590/5000]  Top-1: 82.14%  Top-5: 96.25%  Infer: 0.49 ms/batch
  [600/5000]  Top-1: 82.28%  Top-5: 96.32%  Infer: 0.49 ms/batch
  [610/5000]  Top-1: 82.41%  Top-5: 96.38%  Infer: 0.49 ms/batch
  [620/5000]  Top-1: 82.20%  Top-5: 95.93%  Infer: 0.49 ms/batch
  [630/5000]  Top-1: 82.50%  Top-5: 96.00%  Infer: 0.49 ms/batch
  [640/5000]  Top-1: 82.46%  Top-5: 96.07%  Infer: 0.49 ms/batch
  [650/5000]  Top-1: 82.58%  Top-5: 96.13%  Infer: 0.49 ms/batch
  [660/5000]  Top-1: 82.86%  Top-5: 96.19%  Infer: 0.49 ms/batch
  [670/5000]  Top-1: 83.12%  Top-5: 96.25%  Infer: 0.49 ms/batch
  [680/5000]  Top-1: 83.38%  Top-5: 96.31%  Infer: 0.49 ms/batch
  [690/5000]  Top-1: 83.64%  Top-5: 96.36%  Infer: 0.49 ms/batch
  [700/5000]  Top-1: 83.88%  Top-5: 96.42%  Infer: 0.49 ms/batch
  [710/5000]  Top-1: 83.97%  Top-5: 96.47%  Infer: 0.49 ms/batch
  [720/5000]  Top-1: 84.20%  Top-5: 96.52%  Infer: 0.49 ms/batch
  [730/5000]  Top-1: 84.14%  Top-5: 96.57%  Infer: 0.49 ms/batch
  [740/5000]  Top-1: 84.08%  Top-5: 96.62%  Infer: 0.49 ms/batch
  [750/5000]  Top-1: 84.31%  Top-5: 96.67%  Infer: 0.49 ms/batch
  [760/5000]  Top-1: 84.38%  Top-5: 96.71%  Infer: 0.49 ms/batch
  [770/5000]  Top-1: 84.46%  Top-5: 96.76%  Infer: 0.49 ms/batch
  [780/5000]  Top-1: 84.67%  Top-5: 96.80%  Infer: 0.49 ms/batch
  [790/5000]  Top-1: 84.87%  Top-5: 96.84%  Infer: 0.49 ms/batch
  [800/5000]  Top-1: 84.94%  Top-5: 96.75%  Infer: 0.49 ms/batch
  [810/5000]  Top-1: 85.00%  Top-5: 96.67%  Infer: 0.49 ms/batch
  [820/5000]  Top-1: 84.94%  Top-5: 96.46%  Infer: 0.49 ms/batch
  [830/5000]  Top-1: 85.00%  Top-5: 96.50%  Infer: 0.49 ms/batch
  [840/5000]  Top-1: 85.06%  Top-5: 96.54%  Infer: 0.49 ms/batch
  [850/5000]  Top-1: 85.00%  Top-5: 96.59%  Infer: 0.49 ms/batch
  [860/5000]  Top-1: 84.94%  Top-5: 96.51%  Infer: 0.49 ms/batch
  [870/5000]  Top-1: 85.00%  Top-5: 96.55%  Infer: 0.49 ms/batch
  [880/5000]  Top-1: 84.82%  Top-5: 96.59%  Infer: 0.49 ms/batch
  [890/5000]  Top-1: 85.00%  Top-5: 96.63%  Infer: 0.49 ms/batch
  [900/5000]  Top-1: 85.17%  Top-5: 96.67%  Infer: 0.49 ms/batch
  [910/5000]  Top-1: 85.34%  Top-5: 96.70%  Infer: 0.49 ms/batch
  [920/5000]  Top-1: 85.39%  Top-5: 96.63%  Infer: 0.49 ms/batch
  [930/5000]  Top-1: 85.33%  Top-5: 96.67%  Infer: 0.49 ms/batch
  [940/5000]  Top-1: 85.16%  Top-5: 96.48%  Infer: 0.49 ms/batch
  [950/5000]  Top-1: 85.11%  Top-5: 96.41%  Infer: 0.49 ms/batch
  [960/5000]  Top-1: 85.05%  Top-5: 96.34%  Infer: 0.49 ms/batch
  [970/5000]  Top-1: 85.11%  Top-5: 96.38%  Infer: 0.49 ms/batch
  [980/5000]  Top-1: 85.16%  Top-5: 96.42%  Infer: 0.49 ms/batch
  [990/5000]  Top-1: 85.31%  Top-5: 96.46%  Infer: 0.49 ms/batch
  [1000/5000]  Top-1: 85.36%  Top-5: 96.49%  Infer: 0.49 ms/batch
  [1010/5000]  Top-1: 85.41%  Top-5: 96.53%  Infer: 0.49 ms/batch
  [1020/5000]  Top-1: 85.45%  Top-5: 96.46%  Infer: 0.48 ms/batch
  [1030/5000]  Top-1: 85.40%  Top-5: 96.40%  Infer: 0.48 ms/batch
  [1040/5000]  Top-1: 85.45%  Top-5: 96.44%  Infer: 0.48 ms/batch
  [1050/5000]  Top-1: 85.49%  Top-5: 96.37%  Infer: 0.48 ms/batch
  [1060/5000]  Top-1: 85.34%  Top-5: 96.21%  Infer: 0.48 ms/batch
  [1070/5000]  Top-1: 85.19%  Top-5: 96.15%  Infer: 0.48 ms/batch
  [1080/5000]  Top-1: 85.14%  Top-5: 96.10%  Infer: 0.48 ms/batch
  [1090/5000]  Top-1: 85.19%  Top-5: 96.13%  Infer: 0.48 ms/batch
  [1100/5000]  Top-1: 85.05%  Top-5: 96.07%  Infer: 0.48 ms/batch
  [1110/5000]  Top-1: 85.09%  Top-5: 96.02%  Infer: 0.48 ms/batch
  [1120/5000]  Top-1: 85.14%  Top-5: 96.06%  Infer: 0.48 ms/batch
  [1130/5000]  Top-1: 85.27%  Top-5: 96.09%  Infer: 0.48 ms/batch
  [1140/5000]  Top-1: 85.32%  Top-5: 96.13%  Infer: 0.48 ms/batch
  [1150/5000]  Top-1: 85.45%  Top-5: 96.16%  Infer: 0.48 ms/batch
  [1160/5000]  Top-1: 85.49%  Top-5: 96.19%  Infer: 0.48 ms/batch
  [1170/5000]  Top-1: 85.44%  Top-5: 96.14%  Infer: 0.48 ms/batch
  [1180/5000]  Top-1: 85.48%  Top-5: 96.17%  Infer: 0.48 ms/batch
  [1190/5000]  Top-1: 85.43%  Top-5: 96.12%  Infer: 0.48 ms/batch
  [1200/5000]  Top-1: 85.30%  Top-5: 96.15%  Infer: 0.48 ms/batch
  [1210/5000]  Top-1: 85.34%  Top-5: 96.10%  Infer: 0.48 ms/batch
  [1220/5000]  Top-1: 85.46%  Top-5: 96.13%  Infer: 0.48 ms/batch
  [1230/5000]  Top-1: 85.58%  Top-5: 96.17%  Infer: 0.48 ms/batch
  [1240/5000]  Top-1: 85.70%  Top-5: 96.20%  Infer: 0.48 ms/batch
  [1250/5000]  Top-1: 85.82%  Top-5: 96.23%  Infer: 0.48 ms/batch
  [1260/5000]  Top-1: 85.85%  Top-5: 96.18%  Infer: 0.48 ms/batch
  [1270/5000]  Top-1: 85.89%  Top-5: 96.21%  Infer: 0.48 ms/batch
  [1280/5000]  Top-1: 86.00%  Top-5: 96.24%  Infer: 0.48 ms/batch
  [1290/5000]  Top-1: 86.11%  Top-5: 96.27%  Infer: 0.48 ms/batch
  [1300/5000]  Top-1: 86.22%  Top-5: 96.30%  Infer: 0.48 ms/batch
  [1310/5000]  Top-1: 86.02%  Top-5: 96.33%  Infer: 0.48 ms/batch
  [1320/5000]  Top-1: 86.05%  Top-5: 96.36%  Infer: 0.48 ms/batch
  [1330/5000]  Top-1: 85.62%  Top-5: 96.15%  Infer: 0.48 ms/batch
  [1340/5000]  Top-1: 85.27%  Top-5: 96.11%  Infer: 0.48 ms/batch
  [1350/5000]  Top-1: 84.77%  Top-5: 95.98%  Infer: 0.48 ms/batch
  [1360/5000]  Top-1: 84.74%  Top-5: 95.94%  Infer: 0.48 ms/batch
  [1370/5000]  Top-1: 84.70%  Top-5: 95.97%  Infer: 0.48 ms/batch
  [1380/5000]  Top-1: 84.52%  Top-5: 95.85%  Infer: 0.48 ms/batch
  [1390/5000]  Top-1: 84.34%  Top-5: 95.81%  Infer: 0.48 ms/batch
  [1400/5000]  Top-1: 84.38%  Top-5: 95.84%  Infer: 0.48 ms/batch
  [1410/5000]  Top-1: 84.28%  Top-5: 95.87%  Infer: 0.48 ms/batch
  [1420/5000]  Top-1: 84.39%  Top-5: 95.90%  Infer: 0.48 ms/batch
  [1430/5000]  Top-1: 84.43%  Top-5: 95.86%  Infer: 0.48 ms/batch
  [1440/5000]  Top-1: 84.54%  Top-5: 95.89%  Infer: 0.48 ms/batch
  [1450/5000]  Top-1: 84.58%  Top-5: 95.92%  Infer: 0.48 ms/batch
  [1460/5000]  Top-1: 84.62%  Top-5: 95.94%  Infer: 0.48 ms/batch
  [1470/5000]  Top-1: 84.58%  Top-5: 95.97%  Infer: 0.48 ms/batch
  [1480/5000]  Top-1: 84.62%  Top-5: 95.93%  Infer: 0.48 ms/batch
  [1490/5000]  Top-1: 84.66%  Top-5: 95.89%  Infer: 0.48 ms/batch
  [1500/5000]  Top-1: 84.56%  Top-5: 95.85%  Infer: 0.48 ms/batch
  [1510/5000]  Top-1: 84.46%  Top-5: 95.68%  Infer: 0.48 ms/batch
  [1520/5000]  Top-1: 84.50%  Top-5: 95.64%  Infer: 0.48 ms/batch
  [1530/5000]  Top-1: 84.47%  Top-5: 95.67%  Infer: 0.48 ms/batch
  [1540/5000]  Top-1: 84.44%  Top-5: 95.70%  Infer: 0.48 ms/batch
  [1550/5000]  Top-1: 84.41%  Top-5: 95.66%  Infer: 0.48 ms/batch
  [1560/5000]  Top-1: 84.38%  Top-5: 95.69%  Infer: 0.48 ms/batch
  [1570/5000]  Top-1: 84.29%  Top-5: 95.58%  Infer: 0.48 ms/batch
  [1580/5000]  Top-1: 84.32%  Top-5: 95.61%  Infer: 0.48 ms/batch
  [1590/5000]  Top-1: 84.23%  Top-5: 95.58%  Infer: 0.48 ms/batch
  [1600/5000]  Top-1: 84.20%  Top-5: 95.54%  Infer: 0.48 ms/batch
  [1610/5000]  Top-1: 83.86%  Top-5: 95.44%  Infer: 0.48 ms/batch
  [1620/5000]  Top-1: 83.65%  Top-5: 95.41%  Infer: 0.48 ms/batch
  [1630/5000]  Top-1: 83.56%  Top-5: 95.44%  Infer: 0.48 ms/batch
  [1640/5000]  Top-1: 83.17%  Top-5: 95.22%  Infer: 0.48 ms/batch
  [1650/5000]  Top-1: 82.84%  Top-5: 94.94%  Infer: 0.48 ms/batch
  [1660/5000]  Top-1: 82.82%  Top-5: 94.91%  Infer: 0.48 ms/batch
  [1670/5000]  Top-1: 82.87%  Top-5: 94.88%  Infer: 0.48 ms/batch
  [1680/5000]  Top-1: 82.85%  Top-5: 94.91%  Infer: 0.48 ms/batch
  [1690/5000]  Top-1: 82.89%  Top-5: 94.94%  Infer: 0.48 ms/batch
  [1700/5000]  Top-1: 82.81%  Top-5: 94.91%  Infer: 0.48 ms/batch
  [1710/5000]  Top-1: 82.74%  Top-5: 94.88%  Infer: 0.48 ms/batch
  [1720/5000]  Top-1: 82.66%  Top-5: 94.85%  Infer: 0.48 ms/batch
  [1730/5000]  Top-1: 82.47%  Top-5: 94.76%  Infer: 0.48 ms/batch
  [1740/5000]  Top-1: 82.34%  Top-5: 94.68%  Infer: 0.47 ms/batch
  [1750/5000]  Top-1: 82.38%  Top-5: 94.65%  Infer: 0.47 ms/batch
  [1760/5000]  Top-1: 82.14%  Top-5: 94.68%  Infer: 0.47 ms/batch
  [1770/5000]  Top-1: 81.95%  Top-5: 94.54%  Infer: 0.47 ms/batch
  [1780/5000]  Top-1: 81.94%  Top-5: 94.51%  Infer: 0.47 ms/batch
  [1790/5000]  Top-1: 81.70%  Top-5: 94.43%  Infer: 0.47 ms/batch
  [1800/5000]  Top-1: 81.64%  Top-5: 94.35%  Infer: 0.47 ms/batch
  [1810/5000]  Top-1: 81.29%  Top-5: 94.38%  Infer: 0.47 ms/batch
  [1820/5000]  Top-1: 81.17%  Top-5: 94.36%  Infer: 0.47 ms/batch
  [1830/5000]  Top-1: 81.00%  Top-5: 94.33%  Infer: 0.47 ms/batch
  [1840/5000]  Top-1: 80.88%  Top-5: 94.36%  Infer: 0.48 ms/batch
  [1850/5000]  Top-1: 80.88%  Top-5: 94.40%  Infer: 0.48 ms/batch
  [1860/5000]  Top-1: 80.82%  Top-5: 94.32%  Infer: 0.48 ms/batch
  [1870/5000]  Top-1: 80.87%  Top-5: 94.35%  Infer: 0.48 ms/batch
  [1880/5000]  Top-1: 80.86%  Top-5: 94.38%  Infer: 0.48 ms/batch
  [1890/5000]  Top-1: 80.86%  Top-5: 94.41%  Infer: 0.48 ms/batch
  [1900/5000]  Top-1: 80.80%  Top-5: 94.44%  Infer: 0.48 ms/batch
  [1910/5000]  Top-1: 80.74%  Top-5: 94.47%  Infer: 0.48 ms/batch
  [1920/5000]  Top-1: 80.69%  Top-5: 94.39%  Infer: 0.48 ms/batch
  [1930/5000]  Top-1: 80.74%  Top-5: 94.37%  Infer: 0.48 ms/batch
  [1940/5000]  Top-1: 80.63%  Top-5: 94.35%  Infer: 0.48 ms/batch
  [1950/5000]  Top-1: 80.52%  Top-5: 94.27%  Infer: 0.48 ms/batch
  [1960/5000]  Top-1: 80.52%  Top-5: 94.30%  Infer: 0.48 ms/batch
  [1970/5000]  Top-1: 80.57%  Top-5: 94.28%  Infer: 0.48 ms/batch
  [1980/5000]  Top-1: 80.51%  Top-5: 94.31%  Infer: 0.48 ms/batch
  [1990/5000]  Top-1: 80.61%  Top-5: 94.34%  Infer: 0.48 ms/batch
  [2000/5000]  Top-1: 80.51%  Top-5: 94.31%  Infer: 0.48 ms/batch
  [2010/5000]  Top-1: 80.45%  Top-5: 94.34%  Infer: 0.48 ms/batch
  [2020/5000]  Top-1: 80.30%  Top-5: 94.37%  Infer: 0.48 ms/batch
  [2030/5000]  Top-1: 80.00%  Top-5: 94.35%  Infer: 0.48 ms/batch
  [2040/5000]  Top-1: 79.85%  Top-5: 94.38%  Infer: 0.48 ms/batch
  [2050/5000]  Top-1: 79.70%  Top-5: 94.36%  Infer: 0.48 ms/batch
  [2060/5000]  Top-1: 79.66%  Top-5: 94.24%  Infer: 0.48 ms/batch
  [2070/5000]  Top-1: 79.71%  Top-5: 94.26%  Infer: 0.48 ms/batch
  [2080/5000]  Top-1: 79.71%  Top-5: 94.24%  Infer: 0.48 ms/batch
  [2090/5000]  Top-1: 79.66%  Top-5: 94.17%  Infer: 0.48 ms/batch
  [2100/5000]  Top-1: 79.71%  Top-5: 94.20%  Infer: 0.48 ms/batch
  [2110/5000]  Top-1: 79.57%  Top-5: 94.13%  Infer: 0.48 ms/batch
  [2120/5000]  Top-1: 79.47%  Top-5: 94.11%  Infer: 0.48 ms/batch
  [2130/5000]  Top-1: 79.52%  Top-5: 94.10%  Infer: 0.48 ms/batch
  [2140/5000]  Top-1: 79.53%  Top-5: 94.08%  Infer: 0.48 ms/batch
  [2150/5000]  Top-1: 79.53%  Top-5: 94.10%  Infer: 0.48 ms/batch
  [2160/5000]  Top-1: 79.53%  Top-5: 94.08%  Infer: 0.48 ms/batch
  [2170/5000]  Top-1: 79.44%  Top-5: 94.07%  Infer: 0.48 ms/batch
  [2180/5000]  Top-1: 79.44%  Top-5: 94.00%  Infer: 0.48 ms/batch
  [2190/5000]  Top-1: 79.49%  Top-5: 94.03%  Infer: 0.48 ms/batch
  [2200/5000]  Top-1: 79.49%  Top-5: 94.01%  Infer: 0.48 ms/batch
  [2210/5000]  Top-1: 79.50%  Top-5: 93.99%  Infer: 0.48 ms/batch
  [2220/5000]  Top-1: 79.32%  Top-5: 93.88%  Infer: 0.48 ms/batch
  [2230/5000]  Top-1: 79.27%  Top-5: 93.86%  Infer: 0.48 ms/batch
  [2240/5000]  Top-1: 79.00%  Top-5: 93.57%  Infer: 0.47 ms/batch
  [2250/5000]  Top-1: 79.01%  Top-5: 93.56%  Infer: 0.48 ms/batch
  [2260/5000]  Top-1: 78.83%  Top-5: 93.50%  Infer: 0.48 ms/batch
  [2270/5000]  Top-1: 78.93%  Top-5: 93.53%  Infer: 0.48 ms/batch
  [2280/5000]  Top-1: 78.98%  Top-5: 93.56%  Infer: 0.48 ms/batch
  [2290/5000]  Top-1: 78.98%  Top-5: 93.54%  Infer: 0.48 ms/batch
  [2300/5000]  Top-1: 78.99%  Top-5: 93.52%  Infer: 0.47 ms/batch
  [2310/5000]  Top-1: 78.82%  Top-5: 93.55%  Infer: 0.47 ms/batch
  [2320/5000]  Top-1: 78.73%  Top-5: 93.54%  Infer: 0.47 ms/batch
  [2330/5000]  Top-1: 78.57%  Top-5: 93.52%  Infer: 0.48 ms/batch
  [2340/5000]  Top-1: 78.57%  Top-5: 93.55%  Infer: 0.47 ms/batch
  [2350/5000]  Top-1: 78.41%  Top-5: 93.58%  Infer: 0.47 ms/batch
  [2360/5000]  Top-1: 78.37%  Top-5: 93.52%  Infer: 0.47 ms/batch
  [2370/5000]  Top-1: 78.38%  Top-5: 93.50%  Infer: 0.47 ms/batch
  [2380/5000]  Top-1: 78.26%  Top-5: 93.36%  Infer: 0.47 ms/batch
  [2390/5000]  Top-1: 78.22%  Top-5: 93.31%  Infer: 0.47 ms/batch
  [2400/5000]  Top-1: 78.31%  Top-5: 93.33%  Infer: 0.47 ms/batch
  [2410/5000]  Top-1: 78.36%  Top-5: 93.36%  Infer: 0.47 ms/batch
  [2420/5000]  Top-1: 78.41%  Top-5: 93.39%  Infer: 0.47 ms/batch
  [2430/5000]  Top-1: 78.46%  Top-5: 93.42%  Infer: 0.47 ms/batch
  [2440/5000]  Top-1: 78.51%  Top-5: 93.44%  Infer: 0.47 ms/batch
  [2450/5000]  Top-1: 78.60%  Top-5: 93.47%  Infer: 0.47 ms/batch
  [2460/5000]  Top-1: 78.56%  Top-5: 93.46%  Infer: 0.47 ms/batch
  [2470/5000]  Top-1: 78.40%  Top-5: 93.40%  Infer: 0.47 ms/batch
  [2480/5000]  Top-1: 78.37%  Top-5: 93.39%  Infer: 0.47 ms/batch
  [2490/5000]  Top-1: 78.29%  Top-5: 93.37%  Infer: 0.47 ms/batch
  [2500/5000]  Top-1: 78.26%  Top-5: 93.40%  Infer: 0.47 ms/batch
  [2510/5000]  Top-1: 78.31%  Top-5: 93.43%  Infer: 0.47 ms/batch
  [2520/5000]  Top-1: 78.23%  Top-5: 93.45%  Infer: 0.47 ms/batch
  [2530/5000]  Top-1: 78.20%  Top-5: 93.48%  Infer: 0.47 ms/batch
  [2540/5000]  Top-1: 78.21%  Top-5: 93.51%  Infer: 0.47 ms/batch
  [2550/5000]  Top-1: 78.21%  Top-5: 93.49%  Infer: 0.47 ms/batch
  [2560/5000]  Top-1: 78.22%  Top-5: 93.48%  Infer: 0.47 ms/batch
  [2570/5000]  Top-1: 78.23%  Top-5: 93.46%  Infer: 0.47 ms/batch
  [2580/5000]  Top-1: 78.31%  Top-5: 93.49%  Infer: 0.47 ms/batch
  [2590/5000]  Top-1: 78.32%  Top-5: 93.48%  Infer: 0.47 ms/batch
  [2600/5000]  Top-1: 78.40%  Top-5: 93.50%  Infer: 0.47 ms/batch
  [2610/5000]  Top-1: 78.41%  Top-5: 93.53%  Infer: 0.47 ms/batch
  [2620/5000]  Top-1: 78.49%  Top-5: 93.55%  Infer: 0.47 ms/batch
  [2630/5000]  Top-1: 78.50%  Top-5: 93.58%  Infer: 0.47 ms/batch
  [2640/5000]  Top-1: 78.35%  Top-5: 93.52%  Infer: 0.47 ms/batch
  [2650/5000]  Top-1: 78.24%  Top-5: 93.44%  Infer: 0.47 ms/batch
  [2660/5000]  Top-1: 78.29%  Top-5: 93.42%  Infer: 0.47 ms/batch
  [2670/5000]  Top-1: 78.26%  Top-5: 93.45%  Infer: 0.47 ms/batch
  [2680/5000]  Top-1: 78.26%  Top-5: 93.43%  Infer: 0.47 ms/batch
  [2690/5000]  Top-1: 78.23%  Top-5: 93.42%  Infer: 0.47 ms/batch
  [2700/5000]  Top-1: 78.16%  Top-5: 93.41%  Infer: 0.47 ms/batch
  [2710/5000]  Top-1: 78.02%  Top-5: 93.28%  Infer: 0.47 ms/batch
  [2720/5000]  Top-1: 77.96%  Top-5: 93.27%  Infer: 0.47 ms/batch
  [2730/5000]  Top-1: 77.85%  Top-5: 93.19%  Infer: 0.47 ms/batch
  [2740/5000]  Top-1: 77.71%  Top-5: 93.03%  Infer: 0.47 ms/batch
  [2750/5000]  Top-1: 77.65%  Top-5: 93.05%  Infer: 0.47 ms/batch
  [2760/5000]  Top-1: 77.62%  Top-5: 93.08%  Infer: 0.47 ms/batch
  [2770/5000]  Top-1: 77.55%  Top-5: 93.10%  Infer: 0.47 ms/batch
  [2780/5000]  Top-1: 77.42%  Top-5: 93.09%  Infer: 0.47 ms/batch
  [2790/5000]  Top-1: 77.36%  Top-5: 93.12%  Infer: 0.47 ms/batch
  [2800/5000]  Top-1: 77.33%  Top-5: 93.14%  Infer: 0.48 ms/batch
  [2810/5000]  Top-1: 77.41%  Top-5: 93.17%  Infer: 0.47 ms/batch
  [2820/5000]  Top-1: 77.38%  Top-5: 93.12%  Infer: 0.47 ms/batch
  [2830/5000]  Top-1: 77.39%  Top-5: 93.11%  Infer: 0.47 ms/batch
  [2840/5000]  Top-1: 77.40%  Top-5: 93.06%  Infer: 0.47 ms/batch
  [2850/5000]  Top-1: 77.48%  Top-5: 93.09%  Infer: 0.47 ms/batch
  [2860/5000]  Top-1: 77.49%  Top-5: 93.11%  Infer: 0.47 ms/batch
  [2870/5000]  Top-1: 77.57%  Top-5: 93.13%  Infer: 0.47 ms/batch
  [2880/5000]  Top-1: 77.58%  Top-5: 93.16%  Infer: 0.47 ms/batch
  [2890/5000]  Top-1: 77.55%  Top-5: 93.18%  Infer: 0.47 ms/batch
  [2900/5000]  Top-1: 77.63%  Top-5: 93.21%  Infer: 0.47 ms/batch
  [2910/5000]  Top-1: 77.57%  Top-5: 93.16%  Infer: 0.47 ms/batch
  [2920/5000]  Top-1: 77.54%  Top-5: 93.15%  Infer: 0.47 ms/batch
  [2930/5000]  Top-1: 77.55%  Top-5: 93.14%  Infer: 0.47 ms/batch
  [2940/5000]  Top-1: 77.49%  Top-5: 93.13%  Infer: 0.47 ms/batch
  [2950/5000]  Top-1: 77.50%  Top-5: 93.12%  Infer: 0.47 ms/batch
  [2960/5000]  Top-1: 77.41%  Top-5: 93.11%  Infer: 0.47 ms/batch
  [2970/5000]  Top-1: 77.38%  Top-5: 93.03%  Infer: 0.47 ms/batch
  [2980/5000]  Top-1: 77.25%  Top-5: 92.92%  Infer: 0.47 ms/batch
  [2990/5000]  Top-1: 77.13%  Top-5: 92.84%  Infer: 0.47 ms/batch
  [3000/5000]  Top-1: 77.10%  Top-5: 92.79%  Infer: 0.47 ms/batch
  [3010/5000]  Top-1: 76.98%  Top-5: 92.75%  Infer: 0.47 ms/batch

## INT8

In [8]:
int8_records = []
print("TRT Precision: int8")
for (bits, seed), info in experiments.items():
    base = make_base(bits, seed, info["seed_num"])
    cfg = with_overrides(base, model_precision="int8", input_quant_bits=bits)

    if cfg.result_json_path().exists():
        print(f"  SKIP {bits}bit / {seed} (result exists)")
        continue

    print(f"\n  {bits}bit / {seed}:")
    payload = run_trt_test_experiment(cfg)
    int8_records.append(payload)
    r = payload["results"]
    print(f"    top1={r['top1_acc']:.2f}%  top5={r['top5_acc']:.2f}%  infer={r['infer_ms_avg']:.2f}ms")

TRT Precision: int8

  8bit / seed_1:
[data] Filtered to 5000 samples across 100 classes.
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/fp32_8bit/seed_1/resnet18_tensorrt_int8_in8b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 5000 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/5000]  Top-1: 90.00%  Top-5: 100.00%  Infer: 0.59 ms/batch
  [50/5000]  Top-1: 95.00%  Top-5: 100.00%  Infer: 0.64 ms/batch
  [60/5000]  Top-1: 93.33%  Top-5: 100.00%  Infer: 0.63 ms/batch
  [70/5000]  Top-1: 90.00%  Top-5: 97.50%  Infer: 0.62 ms/batch
  [80/5000]  Top-1: 88.00%  Top-5: 98.00%  Infer: 0.63 ms/batch
  [90/5000]  Top-1: 90.00%  Top-5: 98.33%  Infer: 0.65 ms/batch
  [100/5000]  Top-1: 90.00%  Top-5: 98.57%  Infer: 0.68 ms/batch
  [110/5000]  Top-1: 90.00%  Top-5: 98.75%  Infer: 0.69 ms/batch
  [120/5000]  Top-1: 88.89%  Top-5: 97.78%  Infer: 0.67 ms/batch
  [130/5000]  Top-1: 90.00%  Top-5: 98.00%  Infer: 0.66 ms/batch
  [140/5000]  Top-1: 90.00%  Top-5: 98.18%  Infer: 0.66 ms/batch
  [150/5000]  Top-1: 88.33%  Top-5: 97.50%  Infer: 0.65 ms/batch
  [160/5000]  Top-1: 88.46%  Top-5: 97.69%  Infer: 0.64 ms/batch
  [170/5000]  Top-1: 85.71%  Top-5: 97.14%  Infer: 0.64 ms/batch
  [180/5000]  Top-1: 85.33%  Top-5: 96.67%  Infer: 0.64 ms/batch
  [190/5000]  Top-1: 84.38%  Top-5: 96.25%  Infer: 0.64 ms/batch
  [200/5000]  Top-1: 84.12%  Top-5: 96.47%  Infer: 0.65 ms/batch
  [210/5000]  Top-1: 83.89%  Top-5: 96.11%  Infer: 0.65 ms/batch
  [220/5000]  Top-1: 84.21%  Top-5: 95.79%  Infer: 0.64 ms/batch
  [230/5000]  Top-1: 84.00%  Top-5: 96.00%  Infer: 0.65 ms/batch
  [240/5000]  Top-1: 83.33%  Top-5: 96.19%  Infer: 0.65 ms/batch
  [250/5000]  Top-1: 82.73%  Top-5: 96.36%  Infer: 0.65 ms/batch
  [260/5000]  Top-1: 82.61%  Top-5: 96.52%  Infer: 0.65 ms/batch
  [270/5000]  Top-1: 81.25%  Top-5: 95.83%  Infer: 0.65 ms/batch
  [280/5000]  Top-1: 81.20%  Top-5: 95.60%  Infer: 0.65 ms/batch
  [290/5000]  Top-1: 81.54%  Top-5: 95.77%  Infer: 0.65 ms/batch
  [300/5000]  Top-1: 81.11%  Top-5: 95.56%  Infer: 0.65 ms/batch
  [310/5000]  Top-1: 80.36%  Top-5: 95.36%  Infer: 0.65 ms/batch
  [320/5000]  Top-1: 80.34%  Top-5: 95.52%  Infer: 0.66 ms/batch
  [330/5000]  Top-1: 80.33%  Top-5: 95.67%  Infer: 0.65 ms/batch
  [340/5000]  Top-1: 79.68%  Top-5: 95.81%  Infer: 0.66 ms/batch
  [350/5000]  Top-1: 79.38%  Top-5: 95.62%  Infer: 0.65 ms/batch
  [360/5000]  Top-1: 78.48%  Top-5: 95.76%  Infer: 0.65 ms/batch
  [370/5000]  Top-1: 77.65%  Top-5: 95.29%  Infer: 0.65 ms/batch
  [380/5000]  Top-1: 77.43%  Top-5: 95.43%  Infer: 0.65 ms/batch
  [390/5000]  Top-1: 77.78%  Top-5: 95.28%  Infer: 0.65 ms/batch
  [400/5000]  Top-1: 77.57%  Top-5: 95.14%  Infer: 0.65 ms/batch
  [410/5000]  Top-1: 77.63%  Top-5: 95.00%  Infer: 0.66 ms/batch
  [420/5000]  Top-1: 77.69%  Top-5: 95.13%  Infer: 0.66 ms/batch
  [430/5000]  Top-1: 78.00%  Top-5: 95.25%  Infer: 0.66 ms/batch
  [440/5000]  Top-1: 78.05%  Top-5: 95.37%  Infer: 0.66 ms/batch
  [450/5000]  Top-1: 78.33%  Top-5: 95.48%  Infer: 0.66 ms/batch
  [460/5000]  Top-1: 78.84%  Top-5: 95.58%  Infer: 0.66 ms/batch
  [470/5000]  Top-1: 79.32%  Top-5: 95.68%  Infer: 0.66 ms/batch
  [480/5000]  Top-1: 79.78%  Top-5: 95.78%  Infer: 0.66 ms/batch
  [490/5000]  Top-1: 80.00%  Top-5: 95.87%  Infer: 0.66 ms/batch
  [500/5000]  Top-1: 80.43%  Top-5: 95.96%  Infer: 0.66 ms/batch
  [510/5000]  Top-1: 80.62%  Top-5: 95.83%  Infer: 0.66 ms/batch
  [520/5000]  Top-1: 81.02%  Top-5: 95.92%  Infer: 0.66 ms/batch
  [530/5000]  Top-1: 81.00%  Top-5: 95.80%  Infer: 0.67 ms/batch
  [540/5000]  Top-1: 81.18%  Top-5: 95.88%  Infer: 0.67 ms/batch
  [550/5000]  Top-1: 81.35%  Top-5: 95.96%  Infer: 0.67 ms/batch
  [560/5000]  Top-1: 81.70%  Top-5: 96.04%  Infer: 0.67 ms/batch
  [570/5000]  Top-1: 82.04%  Top-5: 96.11%  Infer: 0.67 ms/batch
  [580/5000]  Top-1: 82.36%  Top-5: 96.18%  Infer: 0.67 ms/batch
  [590/5000]  Top-1: 82.50%  Top-5: 96.25%  Infer: 0.66 ms/batch
  [600/5000]  Top-1: 82.63%  Top-5: 96.32%  Infer: 0.66 ms/batch
  [610/5000]  Top-1: 82.59%  Top-5: 96.38%  Infer: 0.67 ms/batch
  [620/5000]  Top-1: 82.37%  Top-5: 95.93%  Infer: 0.66 ms/batch
  [630/5000]  Top-1: 82.67%  Top-5: 96.00%  Infer: 0.66 ms/batch
  [640/5000]  Top-1: 82.62%  Top-5: 96.07%  Infer: 0.66 ms/batch
  [650/5000]  Top-1: 82.74%  Top-5: 96.13%  Infer: 0.66 ms/batch
  [660/5000]  Top-1: 83.02%  Top-5: 96.19%  Infer: 0.66 ms/batch
  [670/5000]  Top-1: 83.28%  Top-5: 96.25%  Infer: 0.66 ms/batch
  [680/5000]  Top-1: 83.54%  Top-5: 96.31%  Infer: 0.66 ms/batch
  [690/5000]  Top-1: 83.79%  Top-5: 96.36%  Infer: 0.66 ms/batch
  [700/5000]  Top-1: 84.03%  Top-5: 96.42%  Infer: 0.66 ms/batch
  [710/5000]  Top-1: 84.26%  Top-5: 96.47%  Infer: 0.66 ms/batch
  [720/5000]  Top-1: 84.49%  Top-5: 96.52%  Infer: 0.66 ms/batch
  [730/5000]  Top-1: 84.43%  Top-5: 96.57%  Infer: 0.66 ms/batch
  [740/5000]  Top-1: 84.37%  Top-5: 96.62%  Infer: 0.67 ms/batch
  [750/5000]  Top-1: 84.58%  Top-5: 96.67%  Infer: 0.67 ms/batch
  [760/5000]  Top-1: 84.66%  Top-5: 96.71%  Infer: 0.67 ms/batch
  [770/5000]  Top-1: 84.73%  Top-5: 96.76%  Infer: 0.67 ms/batch
  [780/5000]  Top-1: 84.93%  Top-5: 96.80%  Infer: 0.67 ms/batch
  [790/5000]  Top-1: 85.13%  Top-5: 96.84%  Infer: 0.67 ms/batch
  [800/5000]  Top-1: 85.06%  Top-5: 96.75%  Infer: 0.67 ms/batch
  [810/5000]  Top-1: 85.13%  Top-5: 96.67%  Infer: 0.67 ms/batch
  [820/5000]  Top-1: 85.06%  Top-5: 96.46%  Infer: 0.67 ms/batch
  [830/5000]  Top-1: 85.12%  Top-5: 96.50%  Infer: 0.67 ms/batch
  [840/5000]  Top-1: 85.19%  Top-5: 96.54%  Infer: 0.67 ms/batch
  [850/5000]  Top-1: 85.00%  Top-5: 96.59%  Infer: 0.67 ms/batch
  [860/5000]  Top-1: 84.94%  Top-5: 96.51%  Infer: 0.67 ms/batch
  [870/5000]  Top-1: 85.00%  Top-5: 96.55%  Infer: 0.67 ms/batch
  [880/5000]  Top-1: 84.82%  Top-5: 96.47%  Infer: 0.67 ms/batch
  [890/5000]  Top-1: 85.00%  Top-5: 96.51%  Infer: 0.68 ms/batch
  [900/5000]  Top-1: 85.17%  Top-5: 96.55%  Infer: 0.68 ms/batch
  [910/5000]  Top-1: 85.23%  Top-5: 96.59%  Infer: 0.68 ms/batch
  [920/5000]  Top-1: 85.28%  Top-5: 96.52%  Infer: 0.68 ms/batch
  [930/5000]  Top-1: 85.11%  Top-5: 96.56%  Infer: 0.68 ms/batch
  [940/5000]  Top-1: 84.95%  Top-5: 96.37%  Infer: 0.68 ms/batch
  [950/5000]  Top-1: 84.89%  Top-5: 96.30%  Infer: 0.68 ms/batch
  [960/5000]  Top-1: 84.84%  Top-5: 96.24%  Infer: 0.68 ms/batch
  [970/5000]  Top-1: 84.89%  Top-5: 96.28%  Infer: 0.67 ms/batch
  [980/5000]  Top-1: 85.05%  Top-5: 96.32%  Infer: 0.67 ms/batch
  [990/5000]  Top-1: 85.21%  Top-5: 96.35%  Infer: 0.67 ms/batch
  [1000/5000]  Top-1: 85.26%  Top-5: 96.29%  Infer: 0.67 ms/batch
  [1010/5000]  Top-1: 85.31%  Top-5: 96.33%  Infer: 0.67 ms/batch
  [1020/5000]  Top-1: 85.35%  Top-5: 96.26%  Infer: 0.67 ms/batch
  [1030/5000]  Top-1: 85.30%  Top-5: 96.20%  Infer: 0.67 ms/batch
  [1040/5000]  Top-1: 85.25%  Top-5: 96.24%  Infer: 0.67 ms/batch
  [1050/5000]  Top-1: 85.29%  Top-5: 96.18%  Infer: 0.67 ms/batch
  [1060/5000]  Top-1: 85.15%  Top-5: 96.02%  Infer: 0.67 ms/batch
  [1070/5000]  Top-1: 85.00%  Top-5: 95.96%  Infer: 0.67 ms/batch
  [1080/5000]  Top-1: 84.95%  Top-5: 95.90%  Infer: 0.67 ms/batch
  [1090/5000]  Top-1: 85.00%  Top-5: 95.94%  Infer: 0.67 ms/batch
  [1100/5000]  Top-1: 84.86%  Top-5: 95.89%  Infer: 0.67 ms/batch
  [1110/5000]  Top-1: 84.91%  Top-5: 95.83%  Infer: 0.67 ms/batch
  [1120/5000]  Top-1: 84.95%  Top-5: 95.87%  Infer: 0.67 ms/batch
  [1130/5000]  Top-1: 85.09%  Top-5: 95.91%  Infer: 0.66 ms/batch
  [1140/5000]  Top-1: 85.14%  Top-5: 95.95%  Infer: 0.66 ms/batch
  [1150/5000]  Top-1: 85.27%  Top-5: 95.98%  Infer: 0.66 ms/batch
  [1160/5000]  Top-1: 85.31%  Top-5: 96.02%  Infer: 0.66 ms/batch
  [1170/5000]  Top-1: 85.26%  Top-5: 95.96%  Infer: 0.66 ms/batch
  [1180/5000]  Top-1: 85.22%  Top-5: 96.00%  Infer: 0.66 ms/batch
  [1190/5000]  Top-1: 85.26%  Top-5: 95.95%  Infer: 0.66 ms/batch
  [1200/5000]  Top-1: 85.13%  Top-5: 95.98%  Infer: 0.66 ms/batch
  [1210/5000]  Top-1: 85.17%  Top-5: 95.93%  Infer: 0.66 ms/batch
  [1220/5000]  Top-1: 85.29%  Top-5: 95.97%  Infer: 0.66 ms/batch
  [1230/5000]  Top-1: 85.42%  Top-5: 96.00%  Infer: 0.66 ms/batch
  [1240/5000]  Top-1: 85.54%  Top-5: 96.03%  Infer: 0.66 ms/batch
  [1250/5000]  Top-1: 85.66%  Top-5: 96.07%  Infer: 0.66 ms/batch
  [1260/5000]  Top-1: 85.69%  Top-5: 96.02%  Infer: 0.66 ms/batch
  [1270/5000]  Top-1: 85.81%  Top-5: 96.05%  Infer: 0.66 ms/batch
  [1280/5000]  Top-1: 85.92%  Top-5: 96.08%  Infer: 0.66 ms/batch
  [1290/5000]  Top-1: 86.03%  Top-5: 96.11%  Infer: 0.66 ms/batch
  [1300/5000]  Top-1: 86.14%  Top-5: 96.14%  Infer: 0.66 ms/batch
  [1310/5000]  Top-1: 85.94%  Top-5: 96.17%  Infer: 0.66 ms/batch
  [1320/5000]  Top-1: 85.97%  Top-5: 96.20%  Infer: 0.66 ms/batch
  [1330/5000]  Top-1: 85.54%  Top-5: 96.00%  Infer: 0.66 ms/batch
  [1340/5000]  Top-1: 85.19%  Top-5: 95.95%  Infer: 0.66 ms/batch
  [1350/5000]  Top-1: 84.70%  Top-5: 95.83%  Infer: 0.66 ms/batch
  [1360/5000]  Top-1: 84.66%  Top-5: 95.79%  Infer: 0.66 ms/batch
  [1370/5000]  Top-1: 84.63%  Top-5: 95.82%  Infer: 0.66 ms/batch
  [1380/5000]  Top-1: 84.44%  Top-5: 95.70%  Infer: 0.66 ms/batch
  [1390/5000]  Top-1: 84.26%  Top-5: 95.66%  Infer: 0.66 ms/batch
  [1400/5000]  Top-1: 84.31%  Top-5: 95.69%  Infer: 0.66 ms/batch
  [1410/5000]  Top-1: 84.20%  Top-5: 95.72%  Infer: 0.66 ms/batch
  [1420/5000]  Top-1: 84.24%  Top-5: 95.76%  Infer: 0.66 ms/batch
  [1430/5000]  Top-1: 84.29%  Top-5: 95.71%  Infer: 0.66 ms/batch
  [1440/5000]  Top-1: 84.40%  Top-5: 95.74%  Infer: 0.66 ms/batch
  [1450/5000]  Top-1: 84.44%  Top-5: 95.77%  Infer: 0.66 ms/batch
  [1460/5000]  Top-1: 84.48%  Top-5: 95.80%  Infer: 0.66 ms/batch
  [1470/5000]  Top-1: 84.44%  Top-5: 95.83%  Infer: 0.66 ms/batch
  [1480/5000]  Top-1: 84.48%  Top-5: 95.79%  Infer: 0.66 ms/batch
  [1490/5000]  Top-1: 84.52%  Top-5: 95.75%  Infer: 0.66 ms/batch
  [1500/5000]  Top-1: 84.42%  Top-5: 95.71%  Infer: 0.66 ms/batch
  [1510/5000]  Top-1: 84.32%  Top-5: 95.54%  Infer: 0.66 ms/batch
  [1520/5000]  Top-1: 84.36%  Top-5: 95.50%  Infer: 0.66 ms/batch
  [1530/5000]  Top-1: 84.33%  Top-5: 95.53%  Infer: 0.66 ms/batch
  [1540/5000]  Top-1: 84.30%  Top-5: 95.56%  Infer: 0.66 ms/batch
  [1550/5000]  Top-1: 84.28%  Top-5: 95.53%  Infer: 0.66 ms/batch
  [1560/5000]  Top-1: 84.25%  Top-5: 95.56%  Infer: 0.66 ms/batch
  [1570/5000]  Top-1: 84.16%  Top-5: 95.45%  Infer: 0.66 ms/batch
  [1580/5000]  Top-1: 84.13%  Top-5: 95.48%  Infer: 0.66 ms/batch
  [1590/5000]  Top-1: 84.04%  Top-5: 95.45%  Infer: 0.66 ms/batch
  [1600/5000]  Top-1: 84.01%  Top-5: 95.41%  Infer: 0.66 ms/batch
  [1610/5000]  Top-1: 83.67%  Top-5: 95.32%  Infer: 0.65 ms/batch
  [1620/5000]  Top-1: 83.46%  Top-5: 95.28%  Infer: 0.66 ms/batch
  [1630/5000]  Top-1: 83.38%  Top-5: 95.31%  Infer: 0.66 ms/batch
  [1640/5000]  Top-1: 82.98%  Top-5: 95.09%  Infer: 0.66 ms/batch
  [1650/5000]  Top-1: 82.59%  Top-5: 94.75%  Infer: 0.66 ms/batch
  [1660/5000]  Top-1: 82.58%  Top-5: 94.72%  Infer: 0.66 ms/batch
  [1670/5000]  Top-1: 82.62%  Top-5: 94.70%  Infer: 0.66 ms/batch
  [1680/5000]  Top-1: 82.61%  Top-5: 94.73%  Infer: 0.66 ms/batch
  [1690/5000]  Top-1: 82.65%  Top-5: 94.76%  Infer: 0.66 ms/batch
  [1700/5000]  Top-1: 82.63%  Top-5: 94.73%  Infer: 0.66 ms/batch
  [1710/5000]  Top-1: 82.56%  Top-5: 94.70%  Infer: 0.66 ms/batch
  [1720/5000]  Top-1: 82.49%  Top-5: 94.67%  Infer: 0.65 ms/batch
  [1730/5000]  Top-1: 82.29%  Top-5: 94.59%  Infer: 0.65 ms/batch
  [1740/5000]  Top-1: 82.16%  Top-5: 94.50%  Infer: 0.65 ms/batch
  [1750/5000]  Top-1: 82.21%  Top-5: 94.48%  Infer: 0.65 ms/batch
  [1760/5000]  Top-1: 81.97%  Top-5: 94.51%  Infer: 0.65 ms/batch
  [1770/5000]  Top-1: 81.78%  Top-5: 94.37%  Infer: 0.65 ms/batch
  [1780/5000]  Top-1: 81.77%  Top-5: 94.34%  Infer: 0.65 ms/batch
  [1790/5000]  Top-1: 81.53%  Top-5: 94.26%  Infer: 0.65 ms/batch
  [1800/5000]  Top-1: 81.47%  Top-5: 94.24%  Infer: 0.65 ms/batch
  [1810/5000]  Top-1: 81.12%  Top-5: 94.27%  Infer: 0.65 ms/batch
  [1820/5000]  Top-1: 81.01%  Top-5: 94.25%  Infer: 0.65 ms/batch
  [1830/5000]  Top-1: 80.83%  Top-5: 94.22%  Infer: 0.65 ms/batch
  [1840/5000]  Top-1: 80.72%  Top-5: 94.25%  Infer: 0.65 ms/batch
  [1850/5000]  Top-1: 80.71%  Top-5: 94.29%  Infer: 0.65 ms/batch
  [1860/5000]  Top-1: 80.66%  Top-5: 94.21%  Infer: 0.65 ms/batch
  [1870/5000]  Top-1: 80.71%  Top-5: 94.24%  Infer: 0.65 ms/batch
  [1880/5000]  Top-1: 80.70%  Top-5: 94.27%  Infer: 0.65 ms/batch
  [1890/5000]  Top-1: 80.70%  Top-5: 94.30%  Infer: 0.65 ms/batch
  [1900/5000]  Top-1: 80.70%  Top-5: 94.33%  Infer: 0.65 ms/batch
  [1910/5000]  Top-1: 80.64%  Top-5: 94.36%  Infer: 0.65 ms/batch
  [1920/5000]  Top-1: 80.53%  Top-5: 94.29%  Infer: 0.65 ms/batch
  [1930/5000]  Top-1: 80.58%  Top-5: 94.26%  Infer: 0.65 ms/batch
  [1940/5000]  Top-1: 80.52%  Top-5: 94.24%  Infer: 0.65 ms/batch
  [1950/5000]  Top-1: 80.42%  Top-5: 94.17%  Infer: 0.65 ms/batch
  [1960/5000]  Top-1: 80.41%  Top-5: 94.20%  Infer: 0.65 ms/batch
  [1970/5000]  Top-1: 80.46%  Top-5: 94.23%  Infer: 0.65 ms/batch
  [1980/5000]  Top-1: 80.41%  Top-5: 94.26%  Infer: 0.65 ms/batch
  [1990/5000]  Top-1: 80.51%  Top-5: 94.29%  Infer: 0.65 ms/batch
  [2000/5000]  Top-1: 80.41%  Top-5: 94.21%  Infer: 0.65 ms/batch
  [2010/5000]  Top-1: 80.35%  Top-5: 94.24%  Infer: 0.65 ms/batch
  [2020/5000]  Top-1: 80.20%  Top-5: 94.27%  Infer: 0.65 ms/batch
  [2030/5000]  Top-1: 79.90%  Top-5: 94.25%  Infer: 0.64 ms/batch
  [2040/5000]  Top-1: 79.75%  Top-5: 94.28%  Infer: 0.64 ms/batch
  [2050/5000]  Top-1: 79.60%  Top-5: 94.26%  Infer: 0.65 ms/batch
  [2060/5000]  Top-1: 79.56%  Top-5: 94.14%  Infer: 0.64 ms/batch
  [2070/5000]  Top-1: 79.56%  Top-5: 94.17%  Infer: 0.64 ms/batch
  [2080/5000]  Top-1: 79.56%  Top-5: 94.15%  Infer: 0.65 ms/batch
  [2090/5000]  Top-1: 79.51%  Top-5: 94.08%  Infer: 0.64 ms/batch
  [2100/5000]  Top-1: 79.57%  Top-5: 94.11%  Infer: 0.64 ms/batch
  [2110/5000]  Top-1: 79.42%  Top-5: 94.04%  Infer: 0.65 ms/batch
  [2120/5000]  Top-1: 79.33%  Top-5: 94.02%  Infer: 0.65 ms/batch
  [2130/5000]  Top-1: 79.38%  Top-5: 94.00%  Infer: 0.64 ms/batch
  [2140/5000]  Top-1: 79.38%  Top-5: 93.98%  Infer: 0.65 ms/batch
  [2150/5000]  Top-1: 79.39%  Top-5: 94.01%  Infer: 0.64 ms/batch
  [2160/5000]  Top-1: 79.39%  Top-5: 93.99%  Infer: 0.64 ms/batch
  [2170/5000]  Top-1: 79.30%  Top-5: 93.93%  Infer: 0.64 ms/batch
  [2180/5000]  Top-1: 79.30%  Top-5: 93.86%  Infer: 0.65 ms/batch
  [2190/5000]  Top-1: 79.35%  Top-5: 93.89%  Infer: 0.64 ms/batch
  [2200/5000]  Top-1: 79.35%  Top-5: 93.87%  Infer: 0.64 ms/batch
  [2210/5000]  Top-1: 79.31%  Top-5: 93.85%  Infer: 0.64 ms/batch
  [2220/5000]  Top-1: 79.13%  Top-5: 93.74%  Infer: 0.64 ms/batch
  [2230/5000]  Top-1: 79.09%  Top-5: 93.73%  Infer: 0.64 ms/batch
  [2240/5000]  Top-1: 78.82%  Top-5: 93.44%  Infer: 0.64 ms/batch
  [2250/5000]  Top-1: 78.83%  Top-5: 93.42%  Infer: 0.64 ms/batch
  [2260/5000]  Top-1: 78.65%  Top-5: 93.36%  Infer: 0.64 ms/batch
  [2270/5000]  Top-1: 78.75%  Top-5: 93.39%  Infer: 0.64 ms/batch
  [2280/5000]  Top-1: 78.80%  Top-5: 93.42%  Infer: 0.64 ms/batch
  [2290/5000]  Top-1: 78.81%  Top-5: 93.41%  Infer: 0.64 ms/batch
  [2300/5000]  Top-1: 78.81%  Top-5: 93.39%  Infer: 0.64 ms/batch
  [2310/5000]  Top-1: 78.64%  Top-5: 93.42%  Infer: 0.64 ms/batch
  [2320/5000]  Top-1: 78.56%  Top-5: 93.41%  Infer: 0.64 ms/batch
  [2330/5000]  Top-1: 78.35%  Top-5: 93.39%  Infer: 0.64 ms/batch
  [2340/5000]  Top-1: 78.31%  Top-5: 93.42%  Infer: 0.64 ms/batch
  [2350/5000]  Top-1: 78.15%  Top-5: 93.45%  Infer: 0.64 ms/batch
  [2360/5000]  Top-1: 78.11%  Top-5: 93.39%  Infer: 0.64 ms/batch
  [2370/5000]  Top-1: 78.12%  Top-5: 93.38%  Infer: 0.64 ms/batch
  [2380/5000]  Top-1: 78.00%  Top-5: 93.23%  Infer: 0.64 ms/batch
  [2390/5000]  Top-1: 77.97%  Top-5: 93.18%  Infer: 0.64 ms/batch
  [2400/5000]  Top-1: 78.02%  Top-5: 93.21%  Infer: 0.64 ms/batch
  [2410/5000]  Top-1: 78.07%  Top-5: 93.24%  Infer: 0.64 ms/batch
  [2420/5000]  Top-1: 78.12%  Top-5: 93.26%  Infer: 0.64 ms/batch
  [2430/5000]  Top-1: 78.17%  Top-5: 93.29%  Infer: 0.64 ms/batch
  [2440/5000]  Top-1: 78.22%  Top-5: 93.32%  Infer: 0.64 ms/batch
  [2450/5000]  Top-1: 78.31%  Top-5: 93.35%  Infer: 0.64 ms/batch
  [2460/5000]  Top-1: 78.27%  Top-5: 93.33%  Infer: 0.64 ms/batch
  [2470/5000]  Top-1: 78.11%  Top-5: 93.28%  Infer: 0.64 ms/batch
  [2480/5000]  Top-1: 78.08%  Top-5: 93.27%  Infer: 0.64 ms/batch
  [2490/5000]  Top-1: 78.05%  Top-5: 93.25%  Infer: 0.64 ms/batch
  [2500/5000]  Top-1: 77.98%  Top-5: 93.28%  Infer: 0.64 ms/batch
  [2510/5000]  Top-1: 78.02%  Top-5: 93.31%  Infer: 0.64 ms/batch
  [2520/5000]  Top-1: 77.91%  Top-5: 93.33%  Infer: 0.64 ms/batch
  [2530/5000]  Top-1: 77.84%  Top-5: 93.36%  Infer: 0.64 ms/batch
  [2540/5000]  Top-1: 77.89%  Top-5: 93.39%  Infer: 0.64 ms/batch
  [2550/5000]  Top-1: 77.94%  Top-5: 93.37%  Infer: 0.64 ms/batch
  [2560/5000]  Top-1: 77.94%  Top-5: 93.36%  Infer: 0.64 ms/batch
  [2570/5000]  Top-1: 77.95%  Top-5: 93.35%  Infer: 0.64 ms/batch
  [2580/5000]  Top-1: 78.04%  Top-5: 93.37%  Infer: 0.64 ms/batch
  [2590/5000]  Top-1: 78.05%  Top-5: 93.36%  Infer: 0.64 ms/batch
  [2600/5000]  Top-1: 78.13%  Top-5: 93.39%  Infer: 0.64 ms/batch
  [2610/5000]  Top-1: 78.14%  Top-5: 93.41%  Infer: 0.64 ms/batch
  [2620/5000]  Top-1: 78.22%  Top-5: 93.44%  Infer: 0.64 ms/batch
  [2630/5000]  Top-1: 78.23%  Top-5: 93.46%  Infer: 0.64 ms/batch
  [2640/5000]  Top-1: 78.08%  Top-5: 93.41%  Infer: 0.64 ms/batch
  [2650/5000]  Top-1: 77.98%  Top-5: 93.28%  Infer: 0.64 ms/batch
  [2660/5000]  Top-1: 78.02%  Top-5: 93.27%  Infer: 0.64 ms/batch
  [2670/5000]  Top-1: 77.99%  Top-5: 93.30%  Infer: 0.64 ms/batch
  [2680/5000]  Top-1: 78.00%  Top-5: 93.28%  Infer: 0.64 ms/batch
  [2690/5000]  Top-1: 77.97%  Top-5: 93.27%  Infer: 0.64 ms/batch
  [2700/5000]  Top-1: 77.90%  Top-5: 93.22%  Infer: 0.64 ms/batch
  [2710/5000]  Top-1: 77.76%  Top-5: 93.10%  Infer: 0.64 ms/batch
  [2720/5000]  Top-1: 77.70%  Top-5: 93.09%  Infer: 0.64 ms/batch
  [2730/5000]  Top-1: 77.63%  Top-5: 93.00%  Infer: 0.64 ms/batch
  [2740/5000]  Top-1: 77.49%  Top-5: 92.84%  Infer: 0.64 ms/batch
  [2750/5000]  Top-1: 77.43%  Top-5: 92.87%  Infer: 0.64 ms/batch
  [2760/5000]  Top-1: 77.40%  Top-5: 92.89%  Infer: 0.64 ms/batch
  [2770/5000]  Top-1: 77.34%  Top-5: 92.92%  Infer: 0.64 ms/batch
  [2780/5000]  Top-1: 77.20%  Top-5: 92.91%  Infer: 0.65 ms/batch
  [2790/5000]  Top-1: 77.14%  Top-5: 92.93%  Infer: 0.65 ms/batch
  [2800/5000]  Top-1: 77.11%  Top-5: 92.96%  Infer: 0.65 ms/batch
  [2810/5000]  Top-1: 77.19%  Top-5: 92.99%  Infer: 0.64 ms/batch
  [2820/5000]  Top-1: 77.17%  Top-5: 92.94%  Infer: 0.64 ms/batch
  [2830/5000]  Top-1: 77.18%  Top-5: 92.93%  Infer: 0.65 ms/batch
  [2840/5000]  Top-1: 77.19%  Top-5: 92.88%  Infer: 0.65 ms/batch
  [2850/5000]  Top-1: 77.27%  Top-5: 92.91%  Infer: 0.65 ms/batch
  [2860/5000]  Top-1: 77.28%  Top-5: 92.93%  Infer: 0.64 ms/batch
  [2870/5000]  Top-1: 77.36%  Top-5: 92.96%  Infer: 0.65 ms/batch
  [2880/5000]  Top-1: 77.33%  Top-5: 92.98%  Infer: 0.64 ms/batch
  [2890/5000]  Top-1: 77.31%  Top-5: 93.01%  Infer: 0.64 ms/batch
  [2900/5000]  Top-1: 77.39%  Top-5: 93.03%  Infer: 0.64 ms/batch
  [2910/5000]  Top-1: 77.33%  Top-5: 92.99%  Infer: 0.64 ms/batch
  [2920/5000]  Top-1: 77.30%  Top-5: 92.98%  Infer: 0.64 ms/batch
  [2930/5000]  Top-1: 77.31%  Top-5: 92.97%  Infer: 0.64 ms/batch
  [2940/5000]  Top-1: 77.22%  Top-5: 92.96%  Infer: 0.64 ms/batch
  [2950/5000]  Top-1: 77.19%  Top-5: 92.95%  Infer: 0.64 ms/batch
  [2960/5000]  Top-1: 77.10%  Top-5: 92.94%  Infer: 0.64 ms/batch
  [2970/5000]  Top-1: 77.07%  Top-5: 92.86%  Infer: 0.64 ms/batch
  [2980/5000]  Top-1: 76.95%  Top-5: 92.71%  Infer: 0.64 ms/batch
  [2990/5000]  Top-1: 76.82%  Top-5: 92.64%  Infer: 0.64 ms/batch
  [3000/5000]  Top-1: 76.80%  Top-5: 92.59%  Infer: 0.64 ms/batch
  [3010/5000]  Top-1: 76.68%  Top-5: 92.55%  Infer: 0.64 ms/batch

## FP8

In [9]:
fp8_records = []
print("TRT Precision: fp8")
for (bits, seed), info in experiments.items():
    base = make_base(bits, seed, info["seed_num"])
    cfg = with_overrides(base, model_precision="fp8", input_quant_bits=bits)

    if cfg.result_json_path().exists():
        print(f"  SKIP {bits}bit / {seed} (result exists)")
        continue

    print(f"\n  {bits}bit / {seed}:")
    payload = run_trt_test_experiment(cfg)
    fp8_records.append(payload)
    r = payload["results"]
    print(f"    top1={r['top1_acc']:.2f}%  top5={r['top5_acc']:.2f}%  infer={r['infer_ms_avg']:.2f}ms")

TRT Precision: fp8

  8bit / seed_1:
[data] Filtered to 5000 samples across 100 classes.
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/fp32_8bit/seed_1/resnet18_tensorrt_fp8_in8b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 5000 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/5000]  Top-1: 90.00%  Top-5: 100.00%  Infer: 0.61 ms/batch
  [50/5000]  Top-1: 95.00%  Top-5: 100.00%  Infer: 0.60 ms/batch
  [60/5000]  Top-1: 93.33%  Top-5: 100.00%  Infer: 0.65 ms/batch
  [70/5000]  Top-1: 90.00%  Top-5: 97.50%  Infer: 0.64 ms/batch
  [80/5000]  Top-1: 88.00%  Top-5: 98.00%  Infer: 0.63 ms/batch
  [90/5000]  Top-1: 90.00%  Top-5: 98.33%  Infer: 0.63 ms/batch
  [100/5000]  Top-1: 88.57%  Top-5: 98.57%  Infer: 0.62 ms/batch
  [110/5000]  Top-1: 88.75%  Top-5: 98.75%  Infer: 0.61 ms/batch
  [120/5000]  Top-1: 87.78%  Top-5: 97.78%  Infer: 0.63 ms/batch
  [130/5000]  Top-1: 89.00%  Top-5: 98.00%  Infer: 0.62 ms/batch
  [140/5000]  Top-1: 89.09%  Top-5: 98.18%  Infer: 0.62 ms/batch
  [150/5000]  Top-1: 87.50%  Top-5: 97.50%  Infer: 0.62 ms/batch
  [160/5000]  Top-1: 86.92%  Top-5: 97.69%  Infer: 0.64 ms/batch
  [170/5000]  Top-1: 84.29%  Top-5: 97.86%  Infer: 0.63 ms/batch
  [180/5000]  Top-1: 84.00%  Top-5: 97.33%  Infer: 0.64 ms/batch
  [190/5000]  Top-1: 83.12%  Top-5: 96.88%  Infer: 0.63 ms/batch
  [200/5000]  Top-1: 82.94%  Top-5: 96.47%  Infer: 0.64 ms/batch
  [210/5000]  Top-1: 82.78%  Top-5: 96.11%  Infer: 0.64 ms/batch
  [220/5000]  Top-1: 83.16%  Top-5: 95.79%  Infer: 0.64 ms/batch
  [230/5000]  Top-1: 82.50%  Top-5: 96.00%  Infer: 0.65 ms/batch
  [240/5000]  Top-1: 81.90%  Top-5: 96.19%  Infer: 0.65 ms/batch
  [250/5000]  Top-1: 81.36%  Top-5: 96.36%  Infer: 0.66 ms/batch
  [260/5000]  Top-1: 81.30%  Top-5: 96.52%  Infer: 0.65 ms/batch
  [270/5000]  Top-1: 80.00%  Top-5: 95.83%  Infer: 0.65 ms/batch
  [280/5000]  Top-1: 80.00%  Top-5: 95.60%  Infer: 0.65 ms/batch
  [290/5000]  Top-1: 80.38%  Top-5: 95.77%  Infer: 0.65 ms/batch
  [300/5000]  Top-1: 80.00%  Top-5: 95.56%  Infer: 0.65 ms/batch
  [310/5000]  Top-1: 78.93%  Top-5: 95.36%  Infer: 0.65 ms/batch
  [320/5000]  Top-1: 78.97%  Top-5: 95.52%  Infer: 0.65 ms/batch
  [330/5000]  Top-1: 79.00%  Top-5: 95.67%  Infer: 0.65 ms/batch
  [340/5000]  Top-1: 78.39%  Top-5: 95.81%  Infer: 0.65 ms/batch
  [350/5000]  Top-1: 78.12%  Top-5: 95.62%  Infer: 0.64 ms/batch
  [360/5000]  Top-1: 77.27%  Top-5: 95.76%  Infer: 0.64 ms/batch
  [370/5000]  Top-1: 76.47%  Top-5: 95.29%  Infer: 0.64 ms/batch
  [380/5000]  Top-1: 76.57%  Top-5: 95.43%  Infer: 0.64 ms/batch
  [390/5000]  Top-1: 76.94%  Top-5: 95.28%  Infer: 0.64 ms/batch
  [400/5000]  Top-1: 76.76%  Top-5: 95.14%  Infer: 0.64 ms/batch
  [410/5000]  Top-1: 76.84%  Top-5: 95.00%  Infer: 0.64 ms/batch
  [420/5000]  Top-1: 76.92%  Top-5: 95.13%  Infer: 0.64 ms/batch
  [430/5000]  Top-1: 77.25%  Top-5: 95.25%  Infer: 0.63 ms/batch
  [440/5000]  Top-1: 77.32%  Top-5: 95.37%  Infer: 0.63 ms/batch
  [450/5000]  Top-1: 77.62%  Top-5: 95.48%  Infer: 0.63 ms/batch
  [460/5000]  Top-1: 78.14%  Top-5: 95.58%  Infer: 0.63 ms/batch
  [470/5000]  Top-1: 78.64%  Top-5: 95.68%  Infer: 0.63 ms/batch
  [480/5000]  Top-1: 79.11%  Top-5: 95.78%  Infer: 0.63 ms/batch
  [490/5000]  Top-1: 79.35%  Top-5: 95.87%  Infer: 0.63 ms/batch
  [500/5000]  Top-1: 79.79%  Top-5: 95.96%  Infer: 0.63 ms/batch
  [510/5000]  Top-1: 80.00%  Top-5: 95.83%  Infer: 0.63 ms/batch
  [520/5000]  Top-1: 80.41%  Top-5: 95.92%  Infer: 0.63 ms/batch
  [530/5000]  Top-1: 80.40%  Top-5: 95.80%  Infer: 0.63 ms/batch
  [540/5000]  Top-1: 80.59%  Top-5: 95.88%  Infer: 0.63 ms/batch
  [550/5000]  Top-1: 80.77%  Top-5: 95.96%  Infer: 0.63 ms/batch
  [560/5000]  Top-1: 81.13%  Top-5: 96.04%  Infer: 0.63 ms/batch
  [570/5000]  Top-1: 81.48%  Top-5: 96.11%  Infer: 0.63 ms/batch
  [580/5000]  Top-1: 81.82%  Top-5: 96.18%  Infer: 0.62 ms/batch
  [590/5000]  Top-1: 81.96%  Top-5: 96.25%  Infer: 0.62 ms/batch
  [600/5000]  Top-1: 82.11%  Top-5: 96.32%  Infer: 0.62 ms/batch
  [610/5000]  Top-1: 82.24%  Top-5: 96.38%  Infer: 0.62 ms/batch
  [620/5000]  Top-1: 82.03%  Top-5: 95.93%  Infer: 0.62 ms/batch
  [630/5000]  Top-1: 82.33%  Top-5: 96.00%  Infer: 0.63 ms/batch
  [640/5000]  Top-1: 82.30%  Top-5: 96.07%  Infer: 0.63 ms/batch
  [650/5000]  Top-1: 82.42%  Top-5: 96.13%  Infer: 0.62 ms/batch
  [660/5000]  Top-1: 82.70%  Top-5: 96.19%  Infer: 0.62 ms/batch
  [670/5000]  Top-1: 82.97%  Top-5: 96.25%  Infer: 0.63 ms/batch
  [680/5000]  Top-1: 83.23%  Top-5: 96.31%  Infer: 0.63 ms/batch
  [690/5000]  Top-1: 83.48%  Top-5: 96.36%  Infer: 0.63 ms/batch
  [700/5000]  Top-1: 83.73%  Top-5: 96.42%  Infer: 0.63 ms/batch
  [710/5000]  Top-1: 83.82%  Top-5: 96.47%  Infer: 0.63 ms/batch
  [720/5000]  Top-1: 83.91%  Top-5: 96.52%  Infer: 0.63 ms/batch
  [730/5000]  Top-1: 83.86%  Top-5: 96.57%  Infer: 0.63 ms/batch
  [740/5000]  Top-1: 83.80%  Top-5: 96.62%  Infer: 0.63 ms/batch
  [750/5000]  Top-1: 84.03%  Top-5: 96.67%  Infer: 0.62 ms/batch
  [760/5000]  Top-1: 84.11%  Top-5: 96.71%  Infer: 0.62 ms/batch
  [770/5000]  Top-1: 84.19%  Top-5: 96.76%  Infer: 0.62 ms/batch
  [780/5000]  Top-1: 84.40%  Top-5: 96.80%  Infer: 0.62 ms/batch
  [790/5000]  Top-1: 84.61%  Top-5: 96.84%  Infer: 0.62 ms/batch
  [800/5000]  Top-1: 84.55%  Top-5: 96.75%  Infer: 0.62 ms/batch
  [810/5000]  Top-1: 84.62%  Top-5: 96.67%  Infer: 0.62 ms/batch
  [820/5000]  Top-1: 84.56%  Top-5: 96.46%  Infer: 0.62 ms/batch
  [830/5000]  Top-1: 84.62%  Top-5: 96.38%  Infer: 0.62 ms/batch
  [840/5000]  Top-1: 84.69%  Top-5: 96.42%  Infer: 0.62 ms/batch
  [850/5000]  Top-1: 84.63%  Top-5: 96.46%  Infer: 0.62 ms/batch
  [860/5000]  Top-1: 84.58%  Top-5: 96.39%  Infer: 0.62 ms/batch
  [870/5000]  Top-1: 84.52%  Top-5: 96.43%  Infer: 0.62 ms/batch
  [880/5000]  Top-1: 84.35%  Top-5: 96.47%  Infer: 0.62 ms/batch
  [890/5000]  Top-1: 84.53%  Top-5: 96.51%  Infer: 0.62 ms/batch
  [900/5000]  Top-1: 84.71%  Top-5: 96.55%  Infer: 0.62 ms/batch
  [910/5000]  Top-1: 84.89%  Top-5: 96.59%  Infer: 0.62 ms/batch
  [920/5000]  Top-1: 84.94%  Top-5: 96.63%  Infer: 0.62 ms/batch
  [930/5000]  Top-1: 84.89%  Top-5: 96.67%  Infer: 0.62 ms/batch
  [940/5000]  Top-1: 84.73%  Top-5: 96.48%  Infer: 0.62 ms/batch
  [950/5000]  Top-1: 84.67%  Top-5: 96.41%  Infer: 0.62 ms/batch
  [960/5000]  Top-1: 84.62%  Top-5: 96.34%  Infer: 0.62 ms/batch
  [970/5000]  Top-1: 84.68%  Top-5: 96.38%  Infer: 0.62 ms/batch
  [980/5000]  Top-1: 84.84%  Top-5: 96.42%  Infer: 0.62 ms/batch
  [990/5000]  Top-1: 85.00%  Top-5: 96.46%  Infer: 0.62 ms/batch
  [1000/5000]  Top-1: 85.05%  Top-5: 96.49%  Infer: 0.62 ms/batch
  [1010/5000]  Top-1: 85.10%  Top-5: 96.53%  Infer: 0.62 ms/batch
  [1020/5000]  Top-1: 85.15%  Top-5: 96.46%  Infer: 0.62 ms/batch
  [1030/5000]  Top-1: 85.00%  Top-5: 96.30%  Infer: 0.63 ms/batch
  [1040/5000]  Top-1: 85.05%  Top-5: 96.34%  Infer: 0.63 ms/batch
  [1050/5000]  Top-1: 85.10%  Top-5: 96.27%  Infer: 0.63 ms/batch
  [1060/5000]  Top-1: 84.95%  Top-5: 96.12%  Infer: 0.63 ms/batch
  [1070/5000]  Top-1: 84.81%  Top-5: 96.15%  Infer: 0.63 ms/batch
  [1080/5000]  Top-1: 84.76%  Top-5: 96.10%  Infer: 0.63 ms/batch
  [1090/5000]  Top-1: 84.81%  Top-5: 96.13%  Infer: 0.63 ms/batch
  [1100/5000]  Top-1: 84.67%  Top-5: 96.07%  Infer: 0.63 ms/batch
  [1110/5000]  Top-1: 84.72%  Top-5: 96.02%  Infer: 0.63 ms/batch
  [1120/5000]  Top-1: 84.77%  Top-5: 96.06%  Infer: 0.63 ms/batch
  [1130/5000]  Top-1: 84.91%  Top-5: 96.09%  Infer: 0.63 ms/batch
  [1140/5000]  Top-1: 84.95%  Top-5: 96.13%  Infer: 0.63 ms/batch
  [1150/5000]  Top-1: 85.09%  Top-5: 96.16%  Infer: 0.63 ms/batch
  [1160/5000]  Top-1: 85.13%  Top-5: 96.19%  Infer: 0.63 ms/batch
  [1170/5000]  Top-1: 85.09%  Top-5: 96.14%  Infer: 0.63 ms/batch
  [1180/5000]  Top-1: 85.13%  Top-5: 96.17%  Infer: 0.63 ms/batch
  [1190/5000]  Top-1: 85.00%  Top-5: 96.12%  Infer: 0.63 ms/batch
  [1200/5000]  Top-1: 84.87%  Top-5: 96.07%  Infer: 0.63 ms/batch
  [1210/5000]  Top-1: 84.92%  Top-5: 96.02%  Infer: 0.63 ms/batch
  [1220/5000]  Top-1: 85.04%  Top-5: 96.05%  Infer: 0.63 ms/batch
  [1230/5000]  Top-1: 85.17%  Top-5: 96.08%  Infer: 0.63 ms/batch
  [1240/5000]  Top-1: 85.29%  Top-5: 96.12%  Infer: 0.63 ms/batch
  [1250/5000]  Top-1: 85.41%  Top-5: 96.15%  Infer: 0.63 ms/batch
  [1260/5000]  Top-1: 85.45%  Top-5: 96.10%  Infer: 0.63 ms/batch
  [1270/5000]  Top-1: 85.56%  Top-5: 96.13%  Infer: 0.63 ms/batch
  [1280/5000]  Top-1: 85.68%  Top-5: 96.16%  Infer: 0.63 ms/batch
  [1290/5000]  Top-1: 85.79%  Top-5: 96.19%  Infer: 0.63 ms/batch
  [1300/5000]  Top-1: 85.91%  Top-5: 96.22%  Infer: 0.63 ms/batch
  [1310/5000]  Top-1: 85.70%  Top-5: 96.25%  Infer: 0.63 ms/batch
  [1320/5000]  Top-1: 85.74%  Top-5: 96.28%  Infer: 0.63 ms/batch
  [1330/5000]  Top-1: 85.31%  Top-5: 96.08%  Infer: 0.63 ms/batch
  [1340/5000]  Top-1: 84.89%  Top-5: 96.11%  Infer: 0.63 ms/batch
  [1350/5000]  Top-1: 84.39%  Top-5: 95.98%  Infer: 0.63 ms/batch
  [1360/5000]  Top-1: 84.36%  Top-5: 95.94%  Infer: 0.63 ms/batch
  [1370/5000]  Top-1: 84.25%  Top-5: 95.97%  Infer: 0.63 ms/batch
  [1380/5000]  Top-1: 84.07%  Top-5: 95.85%  Infer: 0.63 ms/batch
  [1390/5000]  Top-1: 83.90%  Top-5: 95.81%  Infer: 0.63 ms/batch
  [1400/5000]  Top-1: 83.94%  Top-5: 95.84%  Infer: 0.63 ms/batch
  [1410/5000]  Top-1: 83.91%  Top-5: 95.87%  Infer: 0.63 ms/batch
  [1420/5000]  Top-1: 84.03%  Top-5: 95.90%  Infer: 0.63 ms/batch
  [1430/5000]  Top-1: 84.07%  Top-5: 95.86%  Infer: 0.63 ms/batch
  [1440/5000]  Top-1: 84.18%  Top-5: 95.89%  Infer: 0.63 ms/batch
  [1450/5000]  Top-1: 84.23%  Top-5: 95.92%  Infer: 0.63 ms/batch
  [1460/5000]  Top-1: 84.27%  Top-5: 95.94%  Infer: 0.63 ms/batch
  [1470/5000]  Top-1: 84.24%  Top-5: 95.97%  Infer: 0.63 ms/batch
  [1480/5000]  Top-1: 84.28%  Top-5: 95.93%  Infer: 0.63 ms/batch
  [1490/5000]  Top-1: 84.32%  Top-5: 95.89%  Infer: 0.63 ms/batch
  [1500/5000]  Top-1: 84.15%  Top-5: 95.85%  Infer: 0.63 ms/batch
  [1510/5000]  Top-1: 84.05%  Top-5: 95.68%  Infer: 0.63 ms/batch
  [1520/5000]  Top-1: 84.09%  Top-5: 95.64%  Infer: 0.63 ms/batch
  [1530/5000]  Top-1: 84.07%  Top-5: 95.67%  Infer: 0.63 ms/batch
  [1540/5000]  Top-1: 84.04%  Top-5: 95.70%  Infer: 0.63 ms/batch
  [1550/5000]  Top-1: 84.01%  Top-5: 95.66%  Infer: 0.63 ms/batch
  [1560/5000]  Top-1: 83.92%  Top-5: 95.69%  Infer: 0.63 ms/batch
  [1570/5000]  Top-1: 83.83%  Top-5: 95.58%  Infer: 0.63 ms/batch
  [1580/5000]  Top-1: 83.87%  Top-5: 95.61%  Infer: 0.63 ms/batch
  [1590/5000]  Top-1: 83.78%  Top-5: 95.58%  Infer: 0.63 ms/batch
  [1600/5000]  Top-1: 83.69%  Top-5: 95.54%  Infer: 0.63 ms/batch
  [1610/5000]  Top-1: 83.35%  Top-5: 95.38%  Infer: 0.63 ms/batch
  [1620/5000]  Top-1: 83.21%  Top-5: 95.35%  Infer: 0.63 ms/batch
  [1630/5000]  Top-1: 83.12%  Top-5: 95.38%  Infer: 0.63 ms/batch
  [1640/5000]  Top-1: 82.73%  Top-5: 95.16%  Infer: 0.63 ms/batch
  [1650/5000]  Top-1: 82.35%  Top-5: 94.81%  Infer: 0.63 ms/batch
  [1660/5000]  Top-1: 82.33%  Top-5: 94.85%  Infer: 0.63 ms/batch
  [1670/5000]  Top-1: 82.38%  Top-5: 94.82%  Infer: 0.63 ms/batch
  [1680/5000]  Top-1: 82.36%  Top-5: 94.85%  Infer: 0.63 ms/batch
  [1690/5000]  Top-1: 82.47%  Top-5: 94.88%  Infer: 0.63 ms/batch
  [1700/5000]  Top-1: 82.40%  Top-5: 94.85%  Infer: 0.63 ms/batch
  [1710/5000]  Top-1: 82.32%  Top-5: 94.82%  Infer: 0.63 ms/batch
  [1720/5000]  Top-1: 82.25%  Top-5: 94.79%  Infer: 0.63 ms/batch
  [1730/5000]  Top-1: 82.06%  Top-5: 94.71%  Infer: 0.63 ms/batch
  [1740/5000]  Top-1: 81.93%  Top-5: 94.62%  Infer: 0.63 ms/batch
  [1750/5000]  Top-1: 81.92%  Top-5: 94.59%  Infer: 0.63 ms/batch
  [1760/5000]  Top-1: 81.68%  Top-5: 94.62%  Infer: 0.63 ms/batch
  [1770/5000]  Top-1: 81.49%  Top-5: 94.48%  Infer: 0.63 ms/batch
  [1780/5000]  Top-1: 81.49%  Top-5: 94.46%  Infer: 0.63 ms/batch
  [1790/5000]  Top-1: 81.25%  Top-5: 94.38%  Infer: 0.63 ms/batch
  [1800/5000]  Top-1: 81.19%  Top-5: 94.35%  Infer: 0.63 ms/batch
  [1810/5000]  Top-1: 80.84%  Top-5: 94.38%  Infer: 0.63 ms/batch
  [1820/5000]  Top-1: 80.73%  Top-5: 94.36%  Infer: 0.63 ms/batch
  [1830/5000]  Top-1: 80.56%  Top-5: 94.33%  Infer: 0.63 ms/batch
  [1840/5000]  Top-1: 80.44%  Top-5: 94.36%  Infer: 0.63 ms/batch
  [1850/5000]  Top-1: 80.44%  Top-5: 94.40%  Infer: 0.63 ms/batch
  [1860/5000]  Top-1: 80.38%  Top-5: 94.37%  Infer: 0.63 ms/batch
  [1870/5000]  Top-1: 80.49%  Top-5: 94.40%  Infer: 0.63 ms/batch
  [1880/5000]  Top-1: 80.49%  Top-5: 94.43%  Infer: 0.63 ms/batch
  [1890/5000]  Top-1: 80.48%  Top-5: 94.46%  Infer: 0.63 ms/batch
  [1900/5000]  Top-1: 80.43%  Top-5: 94.49%  Infer: 0.63 ms/batch
  [1910/5000]  Top-1: 80.43%  Top-5: 94.52%  Infer: 0.63 ms/batch
  [1920/5000]  Top-1: 80.42%  Top-5: 94.44%  Infer: 0.63 ms/batch
  [1930/5000]  Top-1: 80.47%  Top-5: 94.42%  Infer: 0.63 ms/batch
  [1940/5000]  Top-1: 80.37%  Top-5: 94.40%  Infer: 0.63 ms/batch
  [1950/5000]  Top-1: 80.26%  Top-5: 94.32%  Infer: 0.63 ms/batch
  [1960/5000]  Top-1: 80.26%  Top-5: 94.35%  Infer: 0.63 ms/batch
  [1970/5000]  Top-1: 80.31%  Top-5: 94.33%  Infer: 0.63 ms/batch
  [1980/5000]  Top-1: 80.26%  Top-5: 94.31%  Infer: 0.63 ms/batch
  [1990/5000]  Top-1: 80.36%  Top-5: 94.34%  Infer: 0.63 ms/batch
  [2000/5000]  Top-1: 80.25%  Top-5: 94.31%  Infer: 0.63 ms/batch
  [2010/5000]  Top-1: 80.20%  Top-5: 94.34%  Infer: 0.63 ms/batch
  [2020/5000]  Top-1: 80.05%  Top-5: 94.37%  Infer: 0.63 ms/batch
  [2030/5000]  Top-1: 79.75%  Top-5: 94.35%  Infer: 0.63 ms/batch
  [2040/5000]  Top-1: 79.55%  Top-5: 94.38%  Infer: 0.63 ms/batch
  [2050/5000]  Top-1: 79.41%  Top-5: 94.36%  Infer: 0.63 ms/batch
  [2060/5000]  Top-1: 79.36%  Top-5: 94.29%  Infer: 0.63 ms/batch
  [2070/5000]  Top-1: 79.41%  Top-5: 94.31%  Infer: 0.63 ms/batch
  [2080/5000]  Top-1: 79.37%  Top-5: 94.29%  Infer: 0.63 ms/batch
  [2090/5000]  Top-1: 79.37%  Top-5: 94.22%  Infer: 0.63 ms/batch
  [2100/5000]  Top-1: 79.42%  Top-5: 94.25%  Infer: 0.63 ms/batch
  [2110/5000]  Top-1: 79.28%  Top-5: 94.18%  Infer: 0.63 ms/batch
  [2120/5000]  Top-1: 79.19%  Top-5: 94.16%  Infer: 0.63 ms/batch
  [2130/5000]  Top-1: 79.19%  Top-5: 94.14%  Infer: 0.63 ms/batch
  [2140/5000]  Top-1: 79.19%  Top-5: 94.12%  Infer: 0.63 ms/batch
  [2150/5000]  Top-1: 79.20%  Top-5: 94.15%  Infer: 0.63 ms/batch
  [2160/5000]  Top-1: 79.20%  Top-5: 94.13%  Infer: 0.63 ms/batch
  [2170/5000]  Top-1: 79.11%  Top-5: 94.07%  Infer: 0.63 ms/batch
  [2180/5000]  Top-1: 79.07%  Top-5: 94.00%  Infer: 0.63 ms/batch
  [2190/5000]  Top-1: 79.12%  Top-5: 94.03%  Infer: 0.63 ms/batch
  [2200/5000]  Top-1: 79.12%  Top-5: 93.96%  Infer: 0.63 ms/batch
  [2210/5000]  Top-1: 79.08%  Top-5: 93.94%  Infer: 0.63 ms/batch
  [2220/5000]  Top-1: 78.90%  Top-5: 93.84%  Infer: 0.63 ms/batch
  [2230/5000]  Top-1: 78.86%  Top-5: 93.82%  Infer: 0.63 ms/batch
  [2240/5000]  Top-1: 78.60%  Top-5: 93.53%  Infer: 0.62 ms/batch
  [2250/5000]  Top-1: 78.60%  Top-5: 93.51%  Infer: 0.62 ms/batch
  [2260/5000]  Top-1: 78.43%  Top-5: 93.45%  Infer: 0.62 ms/batch
  [2270/5000]  Top-1: 78.53%  Top-5: 93.48%  Infer: 0.63 ms/batch
  [2280/5000]  Top-1: 78.58%  Top-5: 93.51%  Infer: 0.63 ms/batch
  [2290/5000]  Top-1: 78.58%  Top-5: 93.50%  Infer: 0.63 ms/batch
  [2300/5000]  Top-1: 78.59%  Top-5: 93.48%  Infer: 0.63 ms/batch
  [2310/5000]  Top-1: 78.42%  Top-5: 93.51%  Infer: 0.63 ms/batch
  [2320/5000]  Top-1: 78.34%  Top-5: 93.49%  Infer: 0.63 ms/batch
  [2330/5000]  Top-1: 78.13%  Top-5: 93.48%  Infer: 0.63 ms/batch
  [2340/5000]  Top-1: 78.18%  Top-5: 93.51%  Infer: 0.63 ms/batch
  [2350/5000]  Top-1: 78.02%  Top-5: 93.53%  Infer: 0.63 ms/batch
  [2360/5000]  Top-1: 77.98%  Top-5: 93.48%  Infer: 0.63 ms/batch
  [2370/5000]  Top-1: 77.99%  Top-5: 93.46%  Infer: 0.63 ms/batch
  [2380/5000]  Top-1: 77.87%  Top-5: 93.32%  Infer: 0.63 ms/batch
  [2390/5000]  Top-1: 77.84%  Top-5: 93.26%  Infer: 0.63 ms/batch
  [2400/5000]  Top-1: 77.93%  Top-5: 93.29%  Infer: 0.63 ms/batch
  [2410/5000]  Top-1: 77.98%  Top-5: 93.32%  Infer: 0.63 ms/batch
  [2420/5000]  Top-1: 77.99%  Top-5: 93.35%  Infer: 0.63 ms/batch
  [2430/5000]  Top-1: 78.04%  Top-5: 93.38%  Infer: 0.63 ms/batch
  [2440/5000]  Top-1: 78.09%  Top-5: 93.40%  Infer: 0.62 ms/batch
  [2450/5000]  Top-1: 78.18%  Top-5: 93.43%  Infer: 0.62 ms/batch
  [2460/5000]  Top-1: 78.15%  Top-5: 93.42%  Infer: 0.62 ms/batch
  [2470/5000]  Top-1: 77.99%  Top-5: 93.32%  Infer: 0.63 ms/batch
  [2480/5000]  Top-1: 77.96%  Top-5: 93.31%  Infer: 0.62 ms/batch
  [2490/5000]  Top-1: 77.97%  Top-5: 93.29%  Infer: 0.62 ms/batch
  [2500/5000]  Top-1: 77.89%  Top-5: 93.32%  Infer: 0.62 ms/batch
  [2510/5000]  Top-1: 77.94%  Top-5: 93.35%  Infer: 0.62 ms/batch
  [2520/5000]  Top-1: 77.83%  Top-5: 93.37%  Infer: 0.63 ms/batch
  [2530/5000]  Top-1: 77.80%  Top-5: 93.40%  Infer: 0.62 ms/batch
  [2540/5000]  Top-1: 77.81%  Top-5: 93.43%  Infer: 0.62 ms/batch
  [2550/5000]  Top-1: 77.86%  Top-5: 93.41%  Infer: 0.62 ms/batch
  [2560/5000]  Top-1: 77.87%  Top-5: 93.40%  Infer: 0.62 ms/batch
  [2570/5000]  Top-1: 77.87%  Top-5: 93.39%  Infer: 0.62 ms/batch
  [2580/5000]  Top-1: 77.96%  Top-5: 93.41%  Infer: 0.62 ms/batch
  [2590/5000]  Top-1: 78.01%  Top-5: 93.40%  Infer: 0.62 ms/batch
  [2600/5000]  Top-1: 78.09%  Top-5: 93.42%  Infer: 0.62 ms/batch
  [2610/5000]  Top-1: 78.10%  Top-5: 93.45%  Infer: 0.62 ms/batch
  [2620/5000]  Top-1: 78.19%  Top-5: 93.47%  Infer: 0.62 ms/batch
  [2630/5000]  Top-1: 78.19%  Top-5: 93.50%  Infer: 0.62 ms/batch
  [2640/5000]  Top-1: 78.05%  Top-5: 93.45%  Infer: 0.62 ms/batch
  [2650/5000]  Top-1: 77.94%  Top-5: 93.36%  Infer: 0.62 ms/batch
  [2660/5000]  Top-1: 77.98%  Top-5: 93.35%  Infer: 0.62 ms/batch
  [2670/5000]  Top-1: 77.95%  Top-5: 93.37%  Infer: 0.62 ms/batch
  [2680/5000]  Top-1: 77.96%  Top-5: 93.36%  Infer: 0.62 ms/batch
  [2690/5000]  Top-1: 77.93%  Top-5: 93.35%  Infer: 0.62 ms/batch
  [2700/5000]  Top-1: 77.87%  Top-5: 93.33%  Infer: 0.62 ms/batch
  [2710/5000]  Top-1: 77.69%  Top-5: 93.21%  Infer: 0.62 ms/batch
  [2720/5000]  Top-1: 77.62%  Top-5: 93.20%  Infer: 0.62 ms/batch
  [2730/5000]  Top-1: 77.56%  Top-5: 93.11%  Infer: 0.62 ms/batch
  [2740/5000]  Top-1: 77.42%  Top-5: 92.99%  Infer: 0.62 ms/batch
  [2750/5000]  Top-1: 77.35%  Top-5: 93.01%  Infer: 0.62 ms/batch
  [2760/5000]  Top-1: 77.29%  Top-5: 93.04%  Infer: 0.62 ms/batch
  [2770/5000]  Top-1: 77.23%  Top-5: 93.07%  Infer: 0.62 ms/batch
  [2780/5000]  Top-1: 77.09%  Top-5: 93.05%  Infer: 0.62 ms/batch
  [2790/5000]  Top-1: 77.03%  Top-5: 93.08%  Infer: 0.62 ms/batch
  [2800/5000]  Top-1: 77.00%  Top-5: 93.10%  Infer: 0.62 ms/batch
  [2810/5000]  Top-1: 77.09%  Top-5: 93.13%  Infer: 0.62 ms/batch
  [2820/5000]  Top-1: 77.06%  Top-5: 93.08%  Infer: 0.62 ms/batch
  [2830/5000]  Top-1: 77.07%  Top-5: 93.07%  Infer: 0.62 ms/batch
  [2840/5000]  Top-1: 77.08%  Top-5: 93.02%  Infer: 0.62 ms/batch
  [2850/5000]  Top-1: 77.16%  Top-5: 93.05%  Infer: 0.62 ms/batch
  [2860/5000]  Top-1: 77.17%  Top-5: 93.07%  Infer: 0.62 ms/batch
  [2870/5000]  Top-1: 77.25%  Top-5: 93.10%  Infer: 0.62 ms/batch
  [2880/5000]  Top-1: 77.23%  Top-5: 93.12%  Infer: 0.62 ms/batch
  [2890/5000]  Top-1: 77.20%  Top-5: 93.15%  Infer: 0.62 ms/batch
  [2900/5000]  Top-1: 77.28%  Top-5: 93.17%  Infer: 0.62 ms/batch
  [2910/5000]  Top-1: 77.22%  Top-5: 93.12%  Infer: 0.62 ms/batch
  [2920/5000]  Top-1: 77.20%  Top-5: 93.11%  Infer: 0.62 ms/batch
  [2930/5000]  Top-1: 77.21%  Top-5: 93.10%  Infer: 0.62 ms/batch
  [2940/5000]  Top-1: 77.11%  Top-5: 93.09%  Infer: 0.62 ms/batch
  [2950/5000]  Top-1: 77.12%  Top-5: 93.08%  Infer: 0.62 ms/batch
  [2960/5000]  Top-1: 77.03%  Top-5: 93.07%  Infer: 0.62 ms/batch
  [2970/5000]  Top-1: 77.01%  Top-5: 92.99%  Infer: 0.62 ms/batch
  [2980/5000]  Top-1: 76.88%  Top-5: 92.92%  Infer: 0.62 ms/batch
  [2990/5000]  Top-1: 76.76%  Top-5: 92.84%  Infer: 0.62 ms/batch
  [3000/5000]  Top-1: 76.73%  Top-5: 92.79%  Infer: 0.62 ms/batch
  [3010/5000]  Top-1: 76.61%  Top-5: 92.75%  Infer: 0.62 ms/batch

## INT4

In [10]:
int4_records = []
print("TRT Precision: int4")
for (bits, seed), info in experiments.items():
    base = make_base(bits, seed, info["seed_num"])
    cfg = with_overrides(base, model_precision="int4", input_quant_bits=bits)

    if cfg.result_json_path().exists():
        print(f"  SKIP {bits}bit / {seed} (result exists)")
        continue

    print(f"\n  {bits}bit / {seed}:")
    payload = run_trt_test_experiment(cfg)
    int4_records.append(payload)
    r = payload["results"]
    print(f"    top1={r['top1_acc']:.2f}%  top5={r['top5_acc']:.2f}%  infer={r['infer_ms_avg']:.2f}ms")

TRT Precision: int4

  8bit / seed_1:
[data] Filtered to 5000 samples across 100 classes.
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/fp32_8bit/seed_1/resnet18_tensorrt_int4_in8b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 5000 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/5000]  Top-1: 90.00%  Top-5: 100.00%  Infer: 0.58 ms/batch
  [50/5000]  Top-1: 95.00%  Top-5: 100.00%  Infer: 0.60 ms/batch
  [60/5000]  Top-1: 93.33%  Top-5: 100.00%  Infer: 0.54 ms/batch
  [70/5000]  Top-1: 90.00%  Top-5: 97.50%  Infer: 0.54 ms/batch
  [80/5000]  Top-1: 88.00%  Top-5: 98.00%  Infer: 0.51 ms/batch
  [90/5000]  Top-1: 90.00%  Top-5: 98.33%  Infer: 0.51 ms/batch
  [100/5000]  Top-1: 88.57%  Top-5: 98.57%  Infer: 0.50 ms/batch
  [110/5000]  Top-1: 86.25%  Top-5: 98.75%  Infer: 0.50 ms/batch
  [120/5000]  Top-1: 85.56%  Top-5: 97.78%  Infer: 0.50 ms/batch
  [130/5000]  Top-1: 85.00%  Top-5: 98.00%  Infer: 0.51 ms/batch
  [140/5000]  Top-1: 84.55%  Top-5: 98.18%  Infer: 0.51 ms/batch
  [150/5000]  Top-1: 83.33%  Top-5: 96.67%  Infer: 0.51 ms/batch
  [160/5000]  Top-1: 84.62%  Top-5: 96.92%  Infer: 0.50 ms/batch
  [170/5000]  Top-1: 82.14%  Top-5: 97.14%  Infer: 0.50 ms/batch
  [180/5000]  Top-1: 82.00%  Top-5: 96.67%  Infer: 0.50 ms/batch
  [190/5000]  Top-1: 81.25%  Top-5: 96.25%  Infer: 0.51 ms/batch
  [200/5000]  Top-1: 81.18%  Top-5: 95.88%  Infer: 0.51 ms/batch
  [210/5000]  Top-1: 81.11%  Top-5: 95.56%  Infer: 0.51 ms/batch
  [220/5000]  Top-1: 81.58%  Top-5: 95.26%  Infer: 0.52 ms/batch
  [230/5000]  Top-1: 81.50%  Top-5: 95.50%  Infer: 0.52 ms/batch
  [240/5000]  Top-1: 80.95%  Top-5: 95.71%  Infer: 0.52 ms/batch
  [250/5000]  Top-1: 80.91%  Top-5: 95.91%  Infer: 0.52 ms/batch
  [260/5000]  Top-1: 80.87%  Top-5: 96.09%  Infer: 0.52 ms/batch
  [270/5000]  Top-1: 79.58%  Top-5: 95.42%  Infer: 0.51 ms/batch
  [280/5000]  Top-1: 79.60%  Top-5: 95.20%  Infer: 0.51 ms/batch
  [290/5000]  Top-1: 80.00%  Top-5: 95.38%  Infer: 0.51 ms/batch
  [300/5000]  Top-1: 79.63%  Top-5: 95.19%  Infer: 0.51 ms/batch
  [310/5000]  Top-1: 78.93%  Top-5: 95.00%  Infer: 0.50 ms/batch
  [320/5000]  Top-1: 79.31%  Top-5: 95.17%  Infer: 0.50 ms/batch
  [330/5000]  Top-1: 79.67%  Top-5: 95.33%  Infer: 0.50 ms/batch
  [340/5000]  Top-1: 79.03%  Top-5: 95.48%  Infer: 0.50 ms/batch
  [350/5000]  Top-1: 79.06%  Top-5: 95.31%  Infer: 0.50 ms/batch
  [360/5000]  Top-1: 78.48%  Top-5: 95.45%  Infer: 0.50 ms/batch
  [370/5000]  Top-1: 77.65%  Top-5: 95.00%  Infer: 0.50 ms/batch
  [380/5000]  Top-1: 77.43%  Top-5: 95.14%  Infer: 0.50 ms/batch
  [390/5000]  Top-1: 77.50%  Top-5: 95.00%  Infer: 0.50 ms/batch
  [400/5000]  Top-1: 77.30%  Top-5: 94.86%  Infer: 0.50 ms/batch
  [410/5000]  Top-1: 77.37%  Top-5: 94.74%  Infer: 0.50 ms/batch
  [420/5000]  Top-1: 77.44%  Top-5: 94.87%  Infer: 0.50 ms/batch
  [430/5000]  Top-1: 77.75%  Top-5: 95.00%  Infer: 0.49 ms/batch
  [440/5000]  Top-1: 77.80%  Top-5: 95.12%  Infer: 0.49 ms/batch
  [450/5000]  Top-1: 78.10%  Top-5: 95.24%  Infer: 0.49 ms/batch
  [460/5000]  Top-1: 78.60%  Top-5: 95.35%  Infer: 0.49 ms/batch
  [470/5000]  Top-1: 79.09%  Top-5: 95.45%  Infer: 0.49 ms/batch
  [480/5000]  Top-1: 79.56%  Top-5: 95.56%  Infer: 0.49 ms/batch
  [490/5000]  Top-1: 79.78%  Top-5: 95.65%  Infer: 0.50 ms/batch
  [500/5000]  Top-1: 80.21%  Top-5: 95.74%  Infer: 0.50 ms/batch
  [510/5000]  Top-1: 80.42%  Top-5: 95.62%  Infer: 0.50 ms/batch
  [520/5000]  Top-1: 80.82%  Top-5: 95.71%  Infer: 0.50 ms/batch
  [530/5000]  Top-1: 80.80%  Top-5: 95.60%  Infer: 0.50 ms/batch
  [540/5000]  Top-1: 80.98%  Top-5: 95.69%  Infer: 0.50 ms/batch
  [550/5000]  Top-1: 81.15%  Top-5: 95.77%  Infer: 0.50 ms/batch
  [560/5000]  Top-1: 81.51%  Top-5: 95.85%  Infer: 0.50 ms/batch
  [570/5000]  Top-1: 81.85%  Top-5: 95.93%  Infer: 0.50 ms/batch
  [580/5000]  Top-1: 82.18%  Top-5: 96.00%  Infer: 0.50 ms/batch
  [590/5000]  Top-1: 82.32%  Top-5: 96.07%  Infer: 0.50 ms/batch
  [600/5000]  Top-1: 82.46%  Top-5: 96.14%  Infer: 0.50 ms/batch
  [610/5000]  Top-1: 82.41%  Top-5: 96.21%  Infer: 0.50 ms/batch
  [620/5000]  Top-1: 82.20%  Top-5: 95.76%  Infer: 0.50 ms/batch
  [630/5000]  Top-1: 82.50%  Top-5: 95.83%  Infer: 0.50 ms/batch
  [640/5000]  Top-1: 82.46%  Top-5: 95.90%  Infer: 0.50 ms/batch
  [650/5000]  Top-1: 82.58%  Top-5: 95.97%  Infer: 0.50 ms/batch
  [660/5000]  Top-1: 82.86%  Top-5: 96.03%  Infer: 0.50 ms/batch
  [670/5000]  Top-1: 83.12%  Top-5: 96.09%  Infer: 0.50 ms/batch
  [680/5000]  Top-1: 83.38%  Top-5: 96.15%  Infer: 0.50 ms/batch
  [690/5000]  Top-1: 83.64%  Top-5: 96.21%  Infer: 0.50 ms/batch
  [700/5000]  Top-1: 83.88%  Top-5: 96.27%  Infer: 0.50 ms/batch
  [710/5000]  Top-1: 83.97%  Top-5: 96.32%  Infer: 0.50 ms/batch
  [720/5000]  Top-1: 84.20%  Top-5: 96.38%  Infer: 0.50 ms/batch
  [730/5000]  Top-1: 84.14%  Top-5: 96.43%  Infer: 0.50 ms/batch
  [740/5000]  Top-1: 84.08%  Top-5: 96.48%  Infer: 0.50 ms/batch
  [750/5000]  Top-1: 84.31%  Top-5: 96.53%  Infer: 0.50 ms/batch
  [760/5000]  Top-1: 84.38%  Top-5: 96.58%  Infer: 0.50 ms/batch
  [770/5000]  Top-1: 84.46%  Top-5: 96.62%  Infer: 0.50 ms/batch
  [780/5000]  Top-1: 84.67%  Top-5: 96.67%  Infer: 0.50 ms/batch
  [790/5000]  Top-1: 84.87%  Top-5: 96.71%  Infer: 0.50 ms/batch
  [800/5000]  Top-1: 84.81%  Top-5: 96.62%  Infer: 0.50 ms/batch
  [810/5000]  Top-1: 84.87%  Top-5: 96.54%  Infer: 0.50 ms/batch
  [820/5000]  Top-1: 84.81%  Top-5: 96.33%  Infer: 0.50 ms/batch
  [830/5000]  Top-1: 84.88%  Top-5: 96.38%  Infer: 0.50 ms/batch
  [840/5000]  Top-1: 85.06%  Top-5: 96.42%  Infer: 0.50 ms/batch
  [850/5000]  Top-1: 85.12%  Top-5: 96.46%  Infer: 0.51 ms/batch
  [860/5000]  Top-1: 85.06%  Top-5: 96.39%  Infer: 0.51 ms/batch
  [870/5000]  Top-1: 85.12%  Top-5: 96.43%  Infer: 0.50 ms/batch
  [880/5000]  Top-1: 84.94%  Top-5: 96.47%  Infer: 0.51 ms/batch
  [890/5000]  Top-1: 85.12%  Top-5: 96.51%  Infer: 0.51 ms/batch
  [900/5000]  Top-1: 85.29%  Top-5: 96.55%  Infer: 0.50 ms/batch
  [910/5000]  Top-1: 85.45%  Top-5: 96.59%  Infer: 0.50 ms/batch
  [920/5000]  Top-1: 85.51%  Top-5: 96.63%  Infer: 0.50 ms/batch
  [930/5000]  Top-1: 85.44%  Top-5: 96.67%  Infer: 0.50 ms/batch
  [940/5000]  Top-1: 85.27%  Top-5: 96.48%  Infer: 0.50 ms/batch
  [950/5000]  Top-1: 85.22%  Top-5: 96.41%  Infer: 0.50 ms/batch
  [960/5000]  Top-1: 85.16%  Top-5: 96.34%  Infer: 0.50 ms/batch
  [970/5000]  Top-1: 85.21%  Top-5: 96.38%  Infer: 0.50 ms/batch
  [980/5000]  Top-1: 85.26%  Top-5: 96.42%  Infer: 0.50 ms/batch
  [990/5000]  Top-1: 85.42%  Top-5: 96.46%  Infer: 0.50 ms/batch
  [1000/5000]  Top-1: 85.46%  Top-5: 96.49%  Infer: 0.50 ms/batch
  [1010/5000]  Top-1: 85.51%  Top-5: 96.53%  Infer: 0.50 ms/batch
  [1020/5000]  Top-1: 85.56%  Top-5: 96.46%  Infer: 0.50 ms/batch
  [1030/5000]  Top-1: 85.50%  Top-5: 96.40%  Infer: 0.50 ms/batch
  [1040/5000]  Top-1: 85.45%  Top-5: 96.44%  Infer: 0.50 ms/batch
  [1050/5000]  Top-1: 85.49%  Top-5: 96.37%  Infer: 0.50 ms/batch
  [1060/5000]  Top-1: 85.34%  Top-5: 96.21%  Infer: 0.50 ms/batch
  [1070/5000]  Top-1: 85.19%  Top-5: 96.15%  Infer: 0.50 ms/batch
  [1080/5000]  Top-1: 85.14%  Top-5: 96.10%  Infer: 0.50 ms/batch
  [1090/5000]  Top-1: 85.19%  Top-5: 96.13%  Infer: 0.50 ms/batch
  [1100/5000]  Top-1: 85.05%  Top-5: 96.07%  Infer: 0.50 ms/batch
  [1110/5000]  Top-1: 85.09%  Top-5: 96.02%  Infer: 0.50 ms/batch
  [1120/5000]  Top-1: 85.14%  Top-5: 96.06%  Infer: 0.50 ms/batch
  [1130/5000]  Top-1: 85.27%  Top-5: 96.09%  Infer: 0.50 ms/batch
  [1140/5000]  Top-1: 85.32%  Top-5: 96.13%  Infer: 0.50 ms/batch
  [1150/5000]  Top-1: 85.45%  Top-5: 96.16%  Infer: 0.50 ms/batch
  [1160/5000]  Top-1: 85.49%  Top-5: 96.19%  Infer: 0.50 ms/batch
  [1170/5000]  Top-1: 85.44%  Top-5: 96.14%  Infer: 0.50 ms/batch
  [1180/5000]  Top-1: 85.48%  Top-5: 96.17%  Infer: 0.50 ms/batch
  [1190/5000]  Top-1: 85.43%  Top-5: 96.12%  Infer: 0.50 ms/batch
  [1200/5000]  Top-1: 85.30%  Top-5: 96.15%  Infer: 0.50 ms/batch
  [1210/5000]  Top-1: 85.34%  Top-5: 96.10%  Infer: 0.50 ms/batch
  [1220/5000]  Top-1: 85.46%  Top-5: 96.13%  Infer: 0.50 ms/batch
  [1230/5000]  Top-1: 85.58%  Top-5: 96.17%  Infer: 0.50 ms/batch
  [1240/5000]  Top-1: 85.70%  Top-5: 96.20%  Infer: 0.50 ms/batch
  [1250/5000]  Top-1: 85.82%  Top-5: 96.23%  Infer: 0.50 ms/batch
  [1260/5000]  Top-1: 85.85%  Top-5: 96.18%  Infer: 0.50 ms/batch
  [1270/5000]  Top-1: 85.89%  Top-5: 96.21%  Infer: 0.50 ms/batch
  [1280/5000]  Top-1: 86.00%  Top-5: 96.24%  Infer: 0.50 ms/batch
  [1290/5000]  Top-1: 86.11%  Top-5: 96.27%  Infer: 0.50 ms/batch
  [1300/5000]  Top-1: 86.22%  Top-5: 96.30%  Infer: 0.50 ms/batch
  [1310/5000]  Top-1: 86.02%  Top-5: 96.33%  Infer: 0.50 ms/batch
  [1320/5000]  Top-1: 86.05%  Top-5: 96.36%  Infer: 0.50 ms/batch
  [1330/5000]  Top-1: 85.69%  Top-5: 96.15%  Infer: 0.50 ms/batch
  [1340/5000]  Top-1: 85.34%  Top-5: 96.11%  Infer: 0.50 ms/batch
  [1350/5000]  Top-1: 84.85%  Top-5: 95.98%  Infer: 0.50 ms/batch
  [1360/5000]  Top-1: 84.81%  Top-5: 95.94%  Infer: 0.50 ms/batch
  [1370/5000]  Top-1: 84.78%  Top-5: 95.97%  Infer: 0.50 ms/batch
  [1380/5000]  Top-1: 84.59%  Top-5: 95.85%  Infer: 0.50 ms/batch
  [1390/5000]  Top-1: 84.41%  Top-5: 95.81%  Infer: 0.50 ms/batch
  [1400/5000]  Top-1: 84.45%  Top-5: 95.84%  Infer: 0.50 ms/batch
  [1410/5000]  Top-1: 84.42%  Top-5: 95.87%  Infer: 0.50 ms/batch
  [1420/5000]  Top-1: 84.53%  Top-5: 95.90%  Infer: 0.50 ms/batch
  [1430/5000]  Top-1: 84.57%  Top-5: 95.86%  Infer: 0.50 ms/batch
  [1440/5000]  Top-1: 84.68%  Top-5: 95.89%  Infer: 0.50 ms/batch
  [1450/5000]  Top-1: 84.72%  Top-5: 95.92%  Infer: 0.50 ms/batch
  [1460/5000]  Top-1: 84.76%  Top-5: 95.94%  Infer: 0.50 ms/batch
  [1470/5000]  Top-1: 84.72%  Top-5: 95.97%  Infer: 0.50 ms/batch
  [1480/5000]  Top-1: 84.76%  Top-5: 95.93%  Infer: 0.50 ms/batch
  [1490/5000]  Top-1: 84.79%  Top-5: 95.96%  Infer: 0.50 ms/batch
  [1500/5000]  Top-1: 84.69%  Top-5: 95.92%  Infer: 0.50 ms/batch
  [1510/5000]  Top-1: 84.59%  Top-5: 95.74%  Infer: 0.50 ms/batch
  [1520/5000]  Top-1: 84.63%  Top-5: 95.70%  Infer: 0.50 ms/batch
  [1530/5000]  Top-1: 84.60%  Top-5: 95.73%  Infer: 0.50 ms/batch
  [1540/5000]  Top-1: 84.57%  Top-5: 95.76%  Infer: 0.50 ms/batch
  [1550/5000]  Top-1: 84.54%  Top-5: 95.72%  Infer: 0.50 ms/batch
  [1560/5000]  Top-1: 84.51%  Top-5: 95.75%  Infer: 0.50 ms/batch
  [1570/5000]  Top-1: 84.42%  Top-5: 95.65%  Infer: 0.50 ms/batch
  [1580/5000]  Top-1: 84.45%  Top-5: 95.68%  Infer: 0.50 ms/batch
  [1590/5000]  Top-1: 84.36%  Top-5: 95.64%  Infer: 0.50 ms/batch
  [1600/5000]  Top-1: 84.33%  Top-5: 95.61%  Infer: 0.50 ms/batch
  [1610/5000]  Top-1: 83.99%  Top-5: 95.44%  Infer: 0.50 ms/batch
  [1620/5000]  Top-1: 83.77%  Top-5: 95.41%  Infer: 0.50 ms/batch
  [1630/5000]  Top-1: 83.69%  Top-5: 95.44%  Infer: 0.51 ms/batch
  [1640/5000]  Top-1: 83.29%  Top-5: 95.22%  Infer: 0.51 ms/batch
  [1650/5000]  Top-1: 82.96%  Top-5: 95.00%  Infer: 0.50 ms/batch
  [1660/5000]  Top-1: 82.94%  Top-5: 95.03%  Infer: 0.50 ms/batch
  [1670/5000]  Top-1: 82.99%  Top-5: 95.00%  Infer: 0.50 ms/batch
  [1680/5000]  Top-1: 83.03%  Top-5: 95.03%  Infer: 0.50 ms/batch
  [1690/5000]  Top-1: 83.13%  Top-5: 95.06%  Infer: 0.50 ms/batch
  [1700/5000]  Top-1: 83.05%  Top-5: 95.03%  Infer: 0.50 ms/batch
  [1710/5000]  Top-1: 82.98%  Top-5: 95.00%  Infer: 0.50 ms/batch
  [1720/5000]  Top-1: 82.90%  Top-5: 94.97%  Infer: 0.50 ms/batch
  [1730/5000]  Top-1: 82.71%  Top-5: 94.88%  Infer: 0.50 ms/batch
  [1740/5000]  Top-1: 82.57%  Top-5: 94.80%  Infer: 0.50 ms/batch
  [1750/5000]  Top-1: 82.62%  Top-5: 94.77%  Infer: 0.50 ms/batch
  [1760/5000]  Top-1: 82.37%  Top-5: 94.80%  Infer: 0.50 ms/batch
  [1770/5000]  Top-1: 82.18%  Top-5: 94.66%  Infer: 0.50 ms/batch
  [1780/5000]  Top-1: 82.17%  Top-5: 94.63%  Infer: 0.50 ms/batch
  [1790/5000]  Top-1: 81.93%  Top-5: 94.55%  Infer: 0.50 ms/batch
  [1800/5000]  Top-1: 81.86%  Top-5: 94.58%  Infer: 0.50 ms/batch
  [1810/5000]  Top-1: 81.57%  Top-5: 94.61%  Infer: 0.50 ms/batch
  [1820/5000]  Top-1: 81.40%  Top-5: 94.58%  Infer: 0.50 ms/batch
  [1830/5000]  Top-1: 81.22%  Top-5: 94.56%  Infer: 0.50 ms/batch
  [1840/5000]  Top-1: 81.05%  Top-5: 94.59%  Infer: 0.50 ms/batch
  [1850/5000]  Top-1: 81.10%  Top-5: 94.62%  Infer: 0.50 ms/batch
  [1860/5000]  Top-1: 81.04%  Top-5: 94.54%  Infer: 0.50 ms/batch
  [1870/5000]  Top-1: 81.09%  Top-5: 94.57%  Infer: 0.50 ms/batch
  [1880/5000]  Top-1: 81.08%  Top-5: 94.59%  Infer: 0.51 ms/batch
  [1890/5000]  Top-1: 81.02%  Top-5: 94.62%  Infer: 0.51 ms/batch
  [1900/5000]  Top-1: 80.96%  Top-5: 94.65%  Infer: 0.51 ms/batch
  [1910/5000]  Top-1: 80.90%  Top-5: 94.68%  Infer: 0.50 ms/batch
  [1920/5000]  Top-1: 80.85%  Top-5: 94.60%  Infer: 0.50 ms/batch
  [1930/5000]  Top-1: 80.89%  Top-5: 94.58%  Infer: 0.50 ms/batch
  [1940/5000]  Top-1: 80.79%  Top-5: 94.50%  Infer: 0.50 ms/batch
  [1950/5000]  Top-1: 80.68%  Top-5: 94.43%  Infer: 0.51 ms/batch
  [1960/5000]  Top-1: 80.67%  Top-5: 94.46%  Infer: 0.50 ms/batch
  [1970/5000]  Top-1: 80.72%  Top-5: 94.43%  Infer: 0.51 ms/batch
  [1980/5000]  Top-1: 80.67%  Top-5: 94.46%  Infer: 0.51 ms/batch
  [1990/5000]  Top-1: 80.77%  Top-5: 94.49%  Infer: 0.50 ms/batch
  [2000/5000]  Top-1: 80.66%  Top-5: 94.47%  Infer: 0.50 ms/batch
  [2010/5000]  Top-1: 80.66%  Top-5: 94.49%  Infer: 0.51 ms/batch
  [2020/5000]  Top-1: 80.50%  Top-5: 94.52%  Infer: 0.51 ms/batch
  [2030/5000]  Top-1: 80.15%  Top-5: 94.50%  Infer: 0.51 ms/batch
  [2040/5000]  Top-1: 80.00%  Top-5: 94.53%  Infer: 0.50 ms/batch
  [2050/5000]  Top-1: 79.80%  Top-5: 94.50%  Infer: 0.50 ms/batch
  [2060/5000]  Top-1: 79.75%  Top-5: 94.38%  Infer: 0.50 ms/batch
  [2070/5000]  Top-1: 79.80%  Top-5: 94.41%  Infer: 0.51 ms/batch
  [2080/5000]  Top-1: 79.80%  Top-5: 94.39%  Infer: 0.51 ms/batch
  [2090/5000]  Top-1: 79.76%  Top-5: 94.32%  Infer: 0.51 ms/batch
  [2100/5000]  Top-1: 79.81%  Top-5: 94.35%  Infer: 0.51 ms/batch
  [2110/5000]  Top-1: 79.66%  Top-5: 94.28%  Infer: 0.51 ms/batch
  [2120/5000]  Top-1: 79.62%  Top-5: 94.26%  Infer: 0.51 ms/batch
  [2130/5000]  Top-1: 79.62%  Top-5: 94.24%  Infer: 0.51 ms/batch
  [2140/5000]  Top-1: 79.62%  Top-5: 94.22%  Infer: 0.51 ms/batch
  [2150/5000]  Top-1: 79.62%  Top-5: 94.25%  Infer: 0.51 ms/batch
  [2160/5000]  Top-1: 79.62%  Top-5: 94.23%  Infer: 0.51 ms/batch
  [2170/5000]  Top-1: 79.53%  Top-5: 94.16%  Infer: 0.51 ms/batch
  [2180/5000]  Top-1: 79.49%  Top-5: 94.09%  Infer: 0.51 ms/batch
  [2190/5000]  Top-1: 79.49%  Top-5: 94.12%  Infer: 0.50 ms/batch
  [2200/5000]  Top-1: 79.49%  Top-5: 94.06%  Infer: 0.50 ms/batch
  [2210/5000]  Top-1: 79.45%  Top-5: 94.04%  Infer: 0.50 ms/batch
  [2220/5000]  Top-1: 79.27%  Top-5: 93.93%  Infer: 0.50 ms/batch
  [2230/5000]  Top-1: 79.23%  Top-5: 93.91%  Infer: 0.50 ms/batch
  [2240/5000]  Top-1: 78.96%  Top-5: 93.62%  Infer: 0.50 ms/batch
  [2250/5000]  Top-1: 78.92%  Top-5: 93.60%  Infer: 0.50 ms/batch
  [2260/5000]  Top-1: 78.74%  Top-5: 93.54%  Infer: 0.50 ms/batch
  [2270/5000]  Top-1: 78.84%  Top-5: 93.57%  Infer: 0.50 ms/batch
  [2280/5000]  Top-1: 78.89%  Top-5: 93.60%  Infer: 0.50 ms/batch
  [2290/5000]  Top-1: 78.94%  Top-5: 93.58%  Infer: 0.50 ms/batch
  [2300/5000]  Top-1: 78.94%  Top-5: 93.57%  Infer: 0.50 ms/batch
  [2310/5000]  Top-1: 78.82%  Top-5: 93.60%  Infer: 0.50 ms/batch
  [2320/5000]  Top-1: 78.73%  Top-5: 93.58%  Infer: 0.50 ms/batch
  [2330/5000]  Top-1: 78.57%  Top-5: 93.57%  Infer: 0.50 ms/batch
  [2340/5000]  Top-1: 78.57%  Top-5: 93.59%  Infer: 0.50 ms/batch
  [2350/5000]  Top-1: 78.41%  Top-5: 93.62%  Infer: 0.50 ms/batch
  [2360/5000]  Top-1: 78.33%  Top-5: 93.52%  Infer: 0.50 ms/batch
  [2370/5000]  Top-1: 78.33%  Top-5: 93.50%  Infer: 0.50 ms/batch
  [2380/5000]  Top-1: 78.21%  Top-5: 93.36%  Infer: 0.50 ms/batch
  [2390/5000]  Top-1: 78.14%  Top-5: 93.31%  Infer: 0.50 ms/batch
  [2400/5000]  Top-1: 78.23%  Top-5: 93.33%  Infer: 0.50 ms/batch
  [2410/5000]  Top-1: 78.28%  Top-5: 93.36%  Infer: 0.50 ms/batch
  [2420/5000]  Top-1: 78.37%  Top-5: 93.39%  Infer: 0.50 ms/batch
  [2430/5000]  Top-1: 78.42%  Top-5: 93.42%  Infer: 0.50 ms/batch
  [2440/5000]  Top-1: 78.46%  Top-5: 93.44%  Infer: 0.50 ms/batch
  [2450/5000]  Top-1: 78.55%  Top-5: 93.47%  Infer: 0.50 ms/batch
  [2460/5000]  Top-1: 78.52%  Top-5: 93.46%  Infer: 0.50 ms/batch
  [2470/5000]  Top-1: 78.36%  Top-5: 93.40%  Infer: 0.50 ms/batch
  [2480/5000]  Top-1: 78.33%  Top-5: 93.39%  Infer: 0.50 ms/batch
  [2490/5000]  Top-1: 78.25%  Top-5: 93.37%  Infer: 0.50 ms/batch
  [2500/5000]  Top-1: 78.18%  Top-5: 93.40%  Infer: 0.50 ms/batch
  [2510/5000]  Top-1: 78.23%  Top-5: 93.43%  Infer: 0.50 ms/batch
  [2520/5000]  Top-1: 78.19%  Top-5: 93.45%  Infer: 0.50 ms/batch
  [2530/5000]  Top-1: 78.16%  Top-5: 93.48%  Infer: 0.50 ms/batch
  [2540/5000]  Top-1: 78.21%  Top-5: 93.51%  Infer: 0.50 ms/batch
  [2550/5000]  Top-1: 78.25%  Top-5: 93.49%  Infer: 0.50 ms/batch
  [2560/5000]  Top-1: 78.26%  Top-5: 93.48%  Infer: 0.50 ms/batch
  [2570/5000]  Top-1: 78.27%  Top-5: 93.46%  Infer: 0.50 ms/batch
  [2580/5000]  Top-1: 78.31%  Top-5: 93.49%  Infer: 0.50 ms/batch
  [2590/5000]  Top-1: 78.32%  Top-5: 93.48%  Infer: 0.50 ms/batch
  [2600/5000]  Top-1: 78.40%  Top-5: 93.50%  Infer: 0.50 ms/batch
  [2610/5000]  Top-1: 78.41%  Top-5: 93.53%  Infer: 0.50 ms/batch
  [2620/5000]  Top-1: 78.46%  Top-5: 93.55%  Infer: 0.50 ms/batch
  [2630/5000]  Top-1: 78.46%  Top-5: 93.58%  Infer: 0.50 ms/batch
  [2640/5000]  Top-1: 78.31%  Top-5: 93.52%  Infer: 0.50 ms/batch
  [2650/5000]  Top-1: 78.21%  Top-5: 93.44%  Infer: 0.50 ms/batch
  [2660/5000]  Top-1: 78.25%  Top-5: 93.42%  Infer: 0.50 ms/batch
  [2670/5000]  Top-1: 78.26%  Top-5: 93.45%  Infer: 0.50 ms/batch
  [2680/5000]  Top-1: 78.26%  Top-5: 93.43%  Infer: 0.50 ms/batch
  [2690/5000]  Top-1: 78.23%  Top-5: 93.42%  Infer: 0.50 ms/batch
  [2700/5000]  Top-1: 78.16%  Top-5: 93.41%  Infer: 0.50 ms/batch
  [2710/5000]  Top-1: 78.02%  Top-5: 93.28%  Infer: 0.50 ms/batch
  [2720/5000]  Top-1: 77.96%  Top-5: 93.27%  Infer: 0.50 ms/batch
  [2730/5000]  Top-1: 77.89%  Top-5: 93.19%  Infer: 0.50 ms/batch
  [2740/5000]  Top-1: 77.75%  Top-5: 93.06%  Infer: 0.50 ms/batch
  [2750/5000]  Top-1: 77.68%  Top-5: 93.09%  Infer: 0.50 ms/batch
  [2760/5000]  Top-1: 77.66%  Top-5: 93.11%  Infer: 0.50 ms/batch
  [2770/5000]  Top-1: 77.59%  Top-5: 93.14%  Infer: 0.50 ms/batch
  [2780/5000]  Top-1: 77.45%  Top-5: 93.13%  Infer: 0.50 ms/batch
  [2790/5000]  Top-1: 77.39%  Top-5: 93.15%  Infer: 0.50 ms/batch
  [2800/5000]  Top-1: 77.36%  Top-5: 93.18%  Infer: 0.50 ms/batch
  [2810/5000]  Top-1: 77.45%  Top-5: 93.20%  Infer: 0.50 ms/batch
  [2820/5000]  Top-1: 77.42%  Top-5: 93.15%  Infer: 0.50 ms/batch
  [2830/5000]  Top-1: 77.43%  Top-5: 93.14%  Infer: 0.50 ms/batch
  [2840/5000]  Top-1: 77.44%  Top-5: 93.10%  Infer: 0.50 ms/batch
  [2850/5000]  Top-1: 77.52%  Top-5: 93.12%  Infer: 0.50 ms/batch
  [2860/5000]  Top-1: 77.53%  Top-5: 93.14%  Infer: 0.50 ms/batch
  [2870/5000]  Top-1: 77.61%  Top-5: 93.17%  Infer: 0.50 ms/batch
  [2880/5000]  Top-1: 77.58%  Top-5: 93.19%  Infer: 0.50 ms/batch
  [2890/5000]  Top-1: 77.55%  Top-5: 93.22%  Infer: 0.50 ms/batch
  [2900/5000]  Top-1: 77.63%  Top-5: 93.24%  Infer: 0.50 ms/batch
  [2910/5000]  Top-1: 77.57%  Top-5: 93.19%  Infer: 0.50 ms/batch
  [2920/5000]  Top-1: 77.54%  Top-5: 93.18%  Infer: 0.50 ms/batch
  [2930/5000]  Top-1: 77.55%  Top-5: 93.17%  Infer: 0.50 ms/batch
  [2940/5000]  Top-1: 77.46%  Top-5: 93.16%  Infer: 0.50 ms/batch
  [2950/5000]  Top-1: 77.43%  Top-5: 93.15%  Infer: 0.50 ms/batch
  [2960/5000]  Top-1: 77.34%  Top-5: 93.14%  Infer: 0.50 ms/batch
  [2970/5000]  Top-1: 77.28%  Top-5: 93.06%  Infer: 0.50 ms/batch
  [2980/5000]  Top-1: 77.15%  Top-5: 92.95%  Infer: 0.50 ms/batch
  [2990/5000]  Top-1: 77.03%  Top-5: 92.87%  Infer: 0.50 ms/batch
  [3000/5000]  Top-1: 77.00%  Top-5: 92.83%  Infer: 0.50 ms/batch
  [3010/5000]  Top-1: 76.88%  Top-5: 92.79%  Infer: 0.50 ms/batch

## All Results (per seed)

In [11]:
all_rows = []
for bits in INPUT_BITS:
    ckpt_dir = CKPT_ROOT / f"fp32_{bits}bit"
    if not ckpt_dir.exists():
        continue
    for seed_dir in sorted(ckpt_dir.iterdir()):
        if not seed_dir.is_dir():
            continue
        run_dir = f"{OUTPUT_ROOT}/fp32_{bits}bit/{seed_dir.name}"
        runs = load_runs(run_dir, status="ok")
        for r in flatten_runs(runs):
            r["seed"] = seed_dir.name
            r["input_bits_trained"] = bits
            all_rows.append(r)

df = pd.DataFrame(all_rows)
df_trt = df[df["cfg.backend"] == "tensorrt"]

display_cols = [
    "seed", "input_bits_trained", "cfg.model_precision",
    "res.top1_acc", "res.top5_acc", "res.infer_ms_avg", "res.throughput_infer_sps",
]
df_trt[display_cols].sort_values(
    ["input_bits_trained", "seed", "cfg.model_precision"],
    ascending=[False, True, True],
).reset_index(drop=True)

,seed,input_bits_trained,cfg.model_precision,res.top1_acc,res.top5_acc,res.infer_ms_avg,res.throughput_infer_sps
0,seed_1,8,fp16,77.867,93.400,0.470,2125.540
1,seed_1,8,fp32,77.867,93.380,0.954,1048.534
2,seed_1,8,fp8,77.706,93.421,0.627,1596.042
3,seed_1,8,int4,77.706,93.340,0.490,2042.174
4,seed_1,8,int8,77.646,93.280,0.642,1558.384
5,seed_2,8,fp16,78.008,93.843,0.472,2117.554
6,seed_2,8,fp32,78.008,93.863,0.952,1049.882
7,seed_2,8,fp8,78.068,93.763,0.645,1551.314
8,seed_2,8,int4,77.606,93.662,0.497,2013.092
9,seed_2,8,int8,78.189,93.924,0.705,1418.124
10,seed_42,8,fp16,78.089,93.521,0.518,1931.049
11,seed_42,8,fp32,78.068,93.501,0.959,1042.956
12,seed_42,8,fp8,78.048,93.521,0.648,1543.517
13,seed_42,8,int4,78.028,93.400,0.479,2086.024
14,seed_42,8,int8,77.746,93.380,0.671,1490.588
15,seed_1,4,fp16,78.431,93.642,0.473,2112.640
16,seed_1,4,fp32,78.431,93.662,0.941,1062.594
17,seed_1,4,fp8,78.612,93.642,0.677,1477.578
18,seed_1,4,int4,78.511,93.541,0.500,2001.049
19,seed_1,4,int8,78.491,93.642,0.756,1322.949
20,seed_2,4,fp16,77.948,93.742,0.466,2147.008
21,seed_2,4,fp32,77.948,93.742,0.943,1060.045
22,seed_2,4,fp8,77.847,93.742,0.624,1603.140
23,seed_2,4,int4,77.726,93.662,0.491,2035.920
24,seed_2,4,int8,77.948,93.722,0.705,1418.645
25,seed_42,4,fp16,78.652,93.521,0.475,2103.062
26,seed_42,4,fp32,78.652,93.541,0.958,1044.063
27,seed_42,4,fp8,78.652,93.541,0.646,1548.575
28,seed_42,4,int4,78.270,93.219,0.501,1994.515
29,seed_42,4,int8,78.612,93.421,0.695,1439.527
30,seed_1,2,fp16,76.901,93.078,0.491,2035.675
31,seed_1,2,fp32,76.901,93.058,0.959,1043.293
32,seed_1,2,fp8,76.781,93.099,0.624,1603.077
33,seed_1,2,int4,76.459,92.817,0.479,2086.026
34,seed_1,2,int8,76.600,93.099,0.734,1362.785
35,seed_2,2,fp16,77.264,93.139,0.487,2051.338
36,seed_2,2,fp32,77.264,93.139,0.947,1055.475
37,seed_2,2,fp8,76.982,93.421,0.630,1587.458
38,seed_2,2,int4,77.143,93.340,0.492,2034.295
39,seed_2,2,int8,77.243,93.300,0.638,1566.290
40,seed_42,2,fp16,76.439,93.199,0.474,2111.644
41,seed_42,2,fp32,76.419,93.199,0.934,1070.762
42,seed_42,2,fp8,76.298,93.260,0.647,1545.931
43,seed_42,2,int4,75.755,93.078,0.483,2070.638
44,seed_42,2,int8,76.378,93.300,0.685,1459.760
45,seed_1,1,fp16,69.678,89.376,0.477,2097.839
46,seed_1,1,fp32,69.698,89.376,0.949,1054.192
47,seed_1,1,fp8,69.517,89.376,0.632,1583.309
48,seed_1,1,int4,68.954,89.155,0.496,2017.765
49,seed_1,1,int8,69.316,89.497,0.709,1411.009
50,seed_2,1,fp16,69.960,89.618,0.473,2115.101
51,seed_2,1,fp32,69.940,89.618,0.943,1060.235
52,seed_2,1,fp8,69.980,89.658,0.646,1548.724
53,seed_2,1,int4,69.074,89.557,0.490,2039.567
54,seed_2,1,int8,69.598,89.638,0.734,1362.413
55,seed_42,1,fp16,69.034,89.416,0.475,2103.637
56,seed_42,1,fp32,69.034,89.416,0.931,1074.402
57,seed_42,1,fp8,68.994,89.598,0.634,1576.355
58,seed_42,1,int4,68.169,89.376,0.496,2016.191
59,seed_42,1,int8,68.994,89.356,0.732,1366.985

## Averaged Results (across seeds)

In [12]:
avg_df = df_trt.groupby(["cfg.backend", "cfg.model_precision", "input_bits_trained"]).agg(
    top1_mean=("res.top1_acc", "mean"),
    top1_std=("res.top1_acc", "std"),
    top5_mean=("res.top5_acc", "mean"),
    top5_std=("res.top5_acc", "std"),
    infer_ms_mean=("res.infer_ms_avg", "mean"),
    infer_ms_std=("res.infer_ms_avg", "std"),
    throughput_mean=("res.throughput_infer_sps", "mean"),
).round(3).reset_index()

avg_df = avg_df.sort_values(
    ["cfg.model_precision", "input_bits_trained"],
    ascending=[True, False],
).reset_index(drop=True)
avg_df

,cfg.backend,cfg.model_precision,input_bits_trained,top1_mean,top1_std,top5_mean,top5_std,infer_ms_mean,infer_ms_std,throughput_mean
0,tensorrt,fp16,8,77.988,0.112,93.588,0.229,0.487,0.027,2058.048
1,tensorrt,fp16,4,78.343,0.360,93.635,0.111,0.472,0.005,2120.904
2,tensorrt,fp16,2,76.868,0.413,93.139,0.060,0.484,0.009,2066.219
3,tensorrt,fp16,1,69.557,0.474,89.470,0.129,0.475,0.002,2105.526
4,tensorrt,fp32,8,77.981,0.103,93.581,0.251,0.955,0.003,1047.124
5,tensorrt,fp32,4,78.343,0.360,93.649,0.101,0.947,0.009,1055.567
6,tensorrt,fp32,2,76.861,0.424,93.132,0.071,0.947,0.012,1056.510
7,tensorrt,fp32,1,69.557,0.469,89.470,0.129,0.941,0.009,1062.943
8,tensorrt,fp8,8,77.941,0.204,93.568,0.176,0.640,0.011,1563.624
9,tensorrt,fp8,4,78.370,0.453,93.642,0.101,0.649,0.027,1543.098
10,tensorrt,fp8,2,76.687,0.352,93.260,0.161,0.634,0.012,1578.822
11,tensorrt,fp8,1,69.497,0.493,89.544,0.148,0.637,0.007,1569.463
12,tensorrt,int4,8,77.780,0.221,93.467,0.171,0.489,0.009,2047.097
13,tensorrt,int4,4,78.169,0.402,93.474,0.229,0.497,0.005,2010.495
14,tensorrt,int4,2,76.452,0.694,93.078,0.262,0.485,0.006,2063.653
15,tensorrt,int4,1,68.732,0.492,89.363,0.202,0.494,0.003,2024.508
16,tensorrt,int8,8,77.860,0.289,93.528,0.346,0.673,0.032,1489.032
17,tensorrt,int8,4,78.350,0.354,93.595,0.156,0.718,0.033,1393.707
18,tensorrt,int8,2,76.740,0.449,93.233,0.116,0.686,0.048,1462.945
19,tensorrt,int8,1,69.302,0.302,89.497,0.141,0.725,0.014,1380.136

In [13]:
bench_fp32 = PROJECT_ROOT / "results" / "latency_bench" / "tensorrt_fp32_in4b_cuda_bs1.json"
bench_int8 = PROJECT_ROOT / "results" / "latency_bench" / "tensorrt_int8_in8b_cuda_bs1.json"

with open(bench_fp32) as f:
    std_fp = np.std(json.load(f)["latencies_ms"], ddof=1)
with open(bench_int8) as f:
    std_int = np.std(json.load(f)["latencies_ms"], ddof=1)

bench_std_map = {"fp32": std_fp, "fp16": std_fp, "fp8": std_fp, "int8": std_int, "int4": std_int}

avg_df[["cfg.model_precision", "input_bits_trained",
        "top1_mean", "top1_std", "top5_mean", "top5_std",
        "infer_ms_mean"]].assign(
    top1=lambda d: d.apply(lambda r: f"{r['top1_mean']:.2f} ± {r['top1_std']:.2f}", axis=1),
    top5=lambda d: d.apply(lambda r: f"{r['top5_mean']:.2f} ± {r['top5_std']:.2f}", axis=1),
    infer_ms=lambda d: d.apply(lambda r: f"{r['infer_ms_mean']:.3f} ± {bench_std_map[r['cfg.model_precision']]:.3f}", axis=1),
)[["cfg.model_precision", "input_bits_trained", "top1", "top5", "infer_ms"]]

,cfg.model_precision,input_bits_trained,top1,top5,infer_ms
0,fp16,8,77.99 ± 0.11,93.59 ± 0.23,0.487 ± 0.136
1,fp16,4,78.34 ± 0.36,93.64 ± 0.11,0.472 ± 0.136
2,fp16,2,76.87 ± 0.41,93.14 ± 0.06,0.484 ± 0.136
3,fp16,1,69.56 ± 0.47,89.47 ± 0.13,0.475 ± 0.136
4,fp32,8,77.98 ± 0.10,93.58 ± 0.25,0.955 ± 0.136
5,fp32,4,78.34 ± 0.36,93.65 ± 0.10,0.947 ± 0.136
6,fp32,2,76.86 ± 0.42,93.13 ± 0.07,0.947 ± 0.136
7,fp32,1,69.56 ± 0.47,89.47 ± 0.13,0.941 ± 0.136
8,fp8,8,77.94 ± 0.20,93.57 ± 0.18,0.640 ± 0.136
9,fp8,4,78.37 ± 0.45,93.64 ± 0.10,0.649 ± 0.136
10,fp8,2,76.69 ± 0.35,93.26 ± 0.16,0.634 ± 0.136
11,fp8,1,69.50 ± 0.49,89.54 ± 0.15,0.637 ± 0.136
12,int4,8,77.78 ± 0.22,93.47 ± 0.17,0.489 ± 0.276
13,int4,4,78.17 ± 0.40,93.47 ± 0.23,0.497 ± 0.276
14,int4,2,76.45 ± 0.69,93.08 ± 0.26,0.485 ± 0.276
15,int4,1,68.73 ± 0.49,89.36 ± 0.20,0.494 ± 0.276
16,int8,8,77.86 ± 0.29,93.53 ± 0.35,0.673 ± 0.276
17,int8,4,78.35 ± 0.35,93.59 ± 0.16,0.718 ± 0.276
18,int8,2,76.74 ± 0.45,93.23 ± 0.12,0.686 ± 0.276
19,int8,1,69.30 ± 0.30,89.50 ± 0.14,0.725 ± 0.276

In [14]:
out_path = PROJECT_ROOT / "resultsv2" / "test_runs" / "tensorrt_avg_results_test.json"
out_path.parent.mkdir(parents=True, exist_ok=True)
avg_df.to_json(out_path, orient="records", indent=2)
print(f"Saved to {out_path}")

Saved to /home/pf4636/code/resnet/quantized_resnets/resultsv2/test_runs/tensorrt_avg_results_test.json