# 02 — TensorRT Inference Sweep

For each trained checkpoint (`seed_1`, `seed_2`, `seed_42`), sweep all 5 precisions × 4 input bit-depths.

ONNX exports (base + QDQ) are assumed to already exist from `00_qdq_export.ipynb`.

Results saved under `runs/val_infer/<seed>/`, averaged at the end.

In [14]:
from pathlib import Path
import sys

PROJECT_ROOT = Path("..").resolve()
PYFILES = PROJECT_ROOT / "pyfiles"
if str(PYFILES) not in sys.path:
    sys.path.insert(0, str(PYFILES))

In [15]:
import torch
import pandas as pd

from src.config import ExperimentConfig, with_overrides
from src.runner import run_experiment
from utils.utils import load_runs, flatten_runs

pd.set_option("display.max_columns", 200)
pd.set_option("display.float_format", "{:.3f}".format)
print("torch:", torch.__version__, "| cuda:", torch.cuda.is_available())

torch: 2.10.0+cu130 | cuda: True

In [16]:
CKPT_ROOT = PROJECT_ROOT / "checkpoints"
ONNX_ROOT = PROJECT_ROOT / "onnx"
INPUT_BITS = [8, 4, 2, 1]
TRT_PRECISIONS = ["fp32", "fp16", "int8", "fp8", "int4"]

# Discover (bits, seed) pairs from checkpoints
experiments = {}
for bits in INPUT_BITS:
    ckpt_dir = CKPT_ROOT / f"fp32_{bits}bit"
    if not ckpt_dir.exists():
        continue
    for seed_dir in sorted(ckpt_dir.iterdir()):
        if seed_dir.is_dir() and (seed_dir / "best.pth").exists():
            seed = seed_dir.name
            seed_num = seed.split("_")[-1]
            experiments[(bits, seed)] = {
                "ckpt": str(seed_dir / "best.pth"),
                "seed_num": seed_num,
            }

def make_base(bits, seed, seed_num):
    return ExperimentConfig(
        backend="tensorrt",
        device="cuda",
        batch_size=1,
        seed=42,
        num_eval_batches=500,
        trt_static_shape=True,
        trt_workspace_mb=2048,
        onnx_root=str(ONNX_ROOT / f"fp32_{bits}bit"),
        engine_root=str(PROJECT_ROOT / "engines" / f"fp32_{bits}bit" / seed),
        trt_onnx_prefix=f"resnet_{seed_num}",
        output_root=f"../runs/val_infer/fp32_{bits}bit/{seed}",
    )

print("Experiments found:")
for (bits, seed), info in experiments.items():
    print(f"  {bits}bit / {seed}: {info['ckpt']}")

Experiments found:
  8bit / seed_1: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_8bit/seed_1/best.pth
  8bit / seed_2: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_8bit/seed_2/best.pth
  8bit / seed_42: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_8bit/seed_42/best.pth
  4bit / seed_1: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_4bit/seed_1/best.pth
  4bit / seed_2: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_4bit/seed_2/best.pth
  4bit / seed_42: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_4bit/seed_42/best.pth
  2bit / seed_1: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_2bit/seed_1/best.pth
  2bit / seed_2: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_2bit/seed_2/best.pth
  2bit / seed_42: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_2bit/seed_42/best.pth
  1bit / seed_1: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_1bit/seed_1/best.pth
  1bit / seed_2: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_1bit/seed_2/best.pth
  1bit / seed_42: /home/pf4636/code/resnet/quantized_resnets/checkpoints/fp32_1bit/seed_42/best.pth

## FP32

In [17]:
fp32_records = []
print("TRT Precision: fp32")
for (bits, seed), info in experiments.items():
    onnx_base = ONNX_ROOT / f"fp32_{bits}bit" / f"resnet_{info['seed_num']}.onnx"
    if not onnx_base.exists():
        print(f"  SKIP {bits}bit / {seed}: ONNX not exported yet")
        continue

    base = make_base(bits, seed, info["seed_num"])
    cfg = with_overrides(base, model_precision="fp32", input_quant_bits=bits)

    if cfg.result_json_path().exists():
        print(f"  SKIP {bits}bit / {seed} (result exists)")
        continue

    print(f"\n  {bits}bit / {seed}:")
    payload, _ = run_experiment(cfg, save_results_flag=True, checkpoint_path=info["ckpt"])
    fp32_records.append(payload)
    r = payload["results"]
    print(f"    top1={r['top1_acc']:.2f}%  top5={r['top5_acc']:.2f}%  infer={r['infer_ms_avg']:.2f}ms")

TRT Precision: fp32
  SKIP 8bit / seed_1 (result exists)
  SKIP 8bit / seed_2 (result exists)
  SKIP 8bit / seed_42 (result exists)
  SKIP 4bit / seed_1 (result exists)
  SKIP 4bit / seed_2 (result exists)
  SKIP 4bit / seed_42 (result exists)
  SKIP 2bit / seed_1 (result exists)
  SKIP 2bit / seed_2 (result exists)
  SKIP 2bit / seed_42 (result exists)
  SKIP 1bit / seed_1 (result exists)
  SKIP 1bit / seed_2 (result exists)
  SKIP 1bit / seed_42 (result exists)

## FP16

In [18]:
fp16_records = []
print("TRT Precision: fp16")
for (bits, seed), info in experiments.items():
    onnx_base = ONNX_ROOT / f"fp32_{bits}bit" / f"resnet_{info['seed_num']}.onnx"
    if not onnx_base.exists():
        print(f"  SKIP {bits}bit / {seed}: ONNX not exported yet")
        continue

    base = make_base(bits, seed, info["seed_num"])
    cfg = with_overrides(base, model_precision="fp16", input_quant_bits=bits)

    if cfg.result_json_path().exists():
        print(f"  SKIP {bits}bit / {seed} (result exists)")
        continue

    print(f"\n  {bits}bit / {seed}:")
    payload, _ = run_experiment(cfg, save_results_flag=True, checkpoint_path=info["ckpt"])
    fp16_records.append(payload)
    r = payload["results"]
    print(f"    top1={r['top1_acc']:.2f}%  top5={r['top5_acc']:.2f}%  infer={r['infer_ms_avg']:.2f}ms")

TRT Precision: fp16
  SKIP 8bit / seed_1 (result exists)
  SKIP 8bit / seed_2 (result exists)
  SKIP 8bit / seed_42 (result exists)
  SKIP 4bit / seed_1 (result exists)
  SKIP 4bit / seed_2 (result exists)
  SKIP 4bit / seed_42 (result exists)
  SKIP 2bit / seed_1 (result exists)
  SKIP 2bit / seed_2 (result exists)
  SKIP 2bit / seed_42 (result exists)
  SKIP 1bit / seed_1 (result exists)
  SKIP 1bit / seed_2 (result exists)
  SKIP 1bit / seed_42 (result exists)

## INT8

In [19]:
int8_records = []
print("TRT Precision: int8")
for (bits, seed), info in experiments.items():
    onnx_base = ONNX_ROOT / f"fp32_{bits}bit" / f"resnet_{info['seed_num']}.onnx"
    if not onnx_base.exists():
        print(f"  SKIP {bits}bit / {seed}: ONNX not exported yet")
        continue

    base = make_base(bits, seed, info["seed_num"])
    cfg = with_overrides(base, model_precision="int8", input_quant_bits=bits)

    if cfg.result_json_path().exists():
        print(f"  SKIP {bits}bit / {seed} (result exists)")
        continue

    print(f"\n  {bits}bit / {seed}:")
    payload, _ = run_experiment(cfg, save_results_flag=True, checkpoint_path=info["ckpt"])
    int8_records.append(payload)
    r = payload["results"]
    print(f"    top1={r['top1_acc']:.2f}%  top5={r['top5_acc']:.2f}%  infer={r['infer_ms_avg']:.2f}ms")

TRT Precision: int8
  SKIP 8bit / seed_1 (result exists)
  SKIP 8bit / seed_2 (result exists)
  SKIP 8bit / seed_42 (result exists)

  4bit / seed_1:
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/fp32_4bit/resnet_1_int8_qdq.onnx
[runner] Step 2/3 — Building TRT engine (precision=int8) ...
[trt_builder] Building engine | precision=int8 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/fp32_4bit/seed_1/resnet18_tensorrt_int8_in4b_cuda_bs1.engine (11.7 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/fp32_4bit/seed_1/resnet18_tensorrt_int8_in4b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.72 ms/batch
  [50/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [60/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [70/500]  Top-1: 97.50%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [80/500]  Top-1: 98.00%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [90/500]  Top-1: 98.33%  Top-5: 100.00%  Infer: 0.76 ms/batch
  [100/500]  Top-1: 98.57%  Top-5: 100.00%  Infer: 0.76 ms/batch
  [110/500]  Top-1: 98.75%  Top-5: 100.00%  Infer: 0.77 ms/batch
  [120/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [130/500]  Top-1: 99.00%  Top-5: 100.00%  Infer: 0.78 ms/batch
  [140/500]  Top-1: 99.09%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [150/500]  Top-1: 99.17%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [160/500]  Top-1: 99.23%  Top-5: 100.00%  Infer: 0.81 ms/batch
  [170/500]  Top-1: 99.29%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [180/500]  Top-1: 98.67%  Top-5: 100.00%  Infer: 0.81 ms/batch
  [190/500]  Top-1: 98.12%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [200/500]  Top-1: 98.24%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [210/500]  Top-1: 98.33%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [220/500]  Top-1: 98.42%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [230/500]  Top-1: 98.50%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [240/500]  Top-1: 98.57%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [250/500]  Top-1: 98.64%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [260/500]  Top-1: 98.70%  Top-5: 100.00%  Infer: 0.78 ms/batch
  [270/500]  Top-1: 98.75%  Top-5: 100.00%  Infer: 0.78 ms/batch
  [280/500]  Top-1: 98.80%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [290/500]  Top-1: 98.85%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [300/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.78 ms/batch
  [310/500]  Top-1: 98.93%  Top-5: 100.00%  Infer: 0.78 ms/batch
  [320/500]  Top-1: 98.97%  Top-5: 100.00%  Infer: 0.78 ms/batch
  [330/500]  Top-1: 99.00%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [340/500]  Top-1: 99.03%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [350/500]  Top-1: 99.06%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [360/500]  Top-1: 99.09%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [370/500]  Top-1: 99.12%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [380/500]  Top-1: 98.86%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [390/500]  Top-1: 98.61%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [400/500]  Top-1: 98.65%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [410/500]  Top-1: 98.42%  Top-5: 100.00%  Infer: 0.81 ms/batch
  [420/500]  Top-1: 98.21%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [430/500]  Top-1: 98.25%  Top-5: 100.00%  Infer: 0.81 ms/batch
  [440/500]  Top-1: 98.29%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [450/500]  Top-1: 98.33%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [460/500]  Top-1: 98.37%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [470/500]  Top-1: 98.41%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [480/500]  Top-1: 98.44%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [490/500]  Top-1: 98.48%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [500/500]  Top-1: 98.51%  Top-5: 100.00%  Infer: 0.80 ms/batch
[runner] Results saved: ../runs/val_infer/fp32_4bit/seed_1/resnet18_tensorrt_int8_in4b_cuda_bs1/result.json
    top1=98.51%  top5=100.00%  infer=0.80ms
  SKIP 4bit / seed_2 (result exists)
  SKIP 4bit / seed_42 (result exists)
  SKIP 2bit / seed_1 (result exists)
  SKIP 2bit / seed_2 (result exists)
  SKIP 2bit / seed_42 (result exists)
  SKIP 1bit / seed_1 (result exists)
  SKIP 1bit / seed_2 (result exists)
  SKIP 1bit / seed_42 (result exists)

## FP8

In [20]:
fp8_records = []
print("TRT Precision: fp8")
for (bits, seed), info in experiments.items():
    onnx_base = ONNX_ROOT / f"fp32_{bits}bit" / f"resnet_{info['seed_num']}.onnx"
    if not onnx_base.exists():
        print(f"  SKIP {bits}bit / {seed}: ONNX not exported yet")
        continue

    base = make_base(bits, seed, info["seed_num"])
    cfg = with_overrides(base, model_precision="fp8", input_quant_bits=bits)

    if cfg.result_json_path().exists():
        print(f"  SKIP {bits}bit / {seed} (result exists)")
        continue

    print(f"\n  {bits}bit / {seed}:")
    payload, _ = run_experiment(cfg, save_results_flag=True, checkpoint_path=info["ckpt"])
    fp8_records.append(payload)
    r = payload["results"]
    print(f"    top1={r['top1_acc']:.2f}%  top5={r['top5_acc']:.2f}%  infer={r['infer_ms_avg']:.2f}ms")

TRT Precision: fp8
  SKIP 8bit / seed_1 (result exists)
  SKIP 8bit / seed_2 (result exists)
  SKIP 8bit / seed_42 (result exists)

  4bit / seed_1:
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/fp32_4bit/resnet_1_fp8_qdq.onnx
[runner] Step 2/3 — Building TRT engine (precision=fp8) ...
[trt_builder] Building engine | precision=fp8 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/fp32_4bit/seed_1/resnet18_tensorrt_fp8_in4b_cuda_bs1.engine (11.8 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/fp32_4bit/seed_1/resnet18_tensorrt_fp8_in4b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [50/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [60/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [70/500]  Top-1: 97.50%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [80/500]  Top-1: 98.00%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [90/500]  Top-1: 98.33%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [100/500]  Top-1: 98.57%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [110/500]  Top-1: 98.75%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [120/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [130/500]  Top-1: 99.00%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [140/500]  Top-1: 99.09%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [150/500]  Top-1: 99.17%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [160/500]  Top-1: 99.23%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [170/500]  Top-1: 99.29%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [180/500]  Top-1: 98.67%  Top-5: 100.00%  Infer: 0.65 ms/batch
  [190/500]  Top-1: 98.12%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [200/500]  Top-1: 98.24%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [210/500]  Top-1: 98.33%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [220/500]  Top-1: 98.42%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [230/500]  Top-1: 98.50%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [240/500]  Top-1: 98.57%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [250/500]  Top-1: 98.64%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [260/500]  Top-1: 98.70%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [270/500]  Top-1: 98.75%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [280/500]  Top-1: 98.80%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [290/500]  Top-1: 98.85%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [300/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [310/500]  Top-1: 98.93%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [320/500]  Top-1: 98.97%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [330/500]  Top-1: 99.00%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [340/500]  Top-1: 99.03%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [350/500]  Top-1: 99.06%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [360/500]  Top-1: 99.09%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [370/500]  Top-1: 99.12%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [380/500]  Top-1: 98.86%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [390/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [400/500]  Top-1: 98.92%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [410/500]  Top-1: 98.68%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [420/500]  Top-1: 98.46%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [430/500]  Top-1: 98.50%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [440/500]  Top-1: 98.54%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [450/500]  Top-1: 98.57%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [460/500]  Top-1: 98.60%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [470/500]  Top-1: 98.64%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [480/500]  Top-1: 98.67%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [490/500]  Top-1: 98.70%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [500/500]  Top-1: 98.72%  Top-5: 100.00%  Infer: 0.69 ms/batch
[runner] Results saved: ../runs/val_infer/fp32_4bit/seed_1/resnet18_tensorrt_fp8_in4b_cuda_bs1/result.json
    top1=98.72%  top5=100.00%  infer=0.69ms
  SKIP 4bit / seed_2 (result exists)
  SKIP 4bit / seed_42 (result exists)
  SKIP 2bit / seed_1 (result exists)
  SKIP 2bit / seed_2 (result exists)
  SKIP 2bit / seed_42 (result exists)
  SKIP 1bit / seed_1 (result exists)
  SKIP 1bit / seed_2 (result exists)
  SKIP 1bit / seed_42 (result exists)

## INT4

In [21]:
int4_records = []
print("TRT Precision: int4")
for (bits, seed), info in experiments.items():
    onnx_base = ONNX_ROOT / f"fp32_{bits}bit" / f"resnet_{info['seed_num']}.onnx"
    if not onnx_base.exists():
        print(f"  SKIP {bits}bit / {seed}: ONNX not exported yet")
        continue

    base = make_base(bits, seed, info["seed_num"])
    cfg = with_overrides(base, model_precision="int4", input_quant_bits=bits)

    if cfg.result_json_path().exists():
        print(f"  SKIP {bits}bit / {seed} (result exists)")
        continue

    print(f"\n  {bits}bit / {seed}:")
    payload, _ = run_experiment(cfg, save_results_flag=True, checkpoint_path=info["ckpt"])
    int4_records.append(payload)
    r = payload["results"]
    print(f"    top1={r['top1_acc']:.2f}%  top5={r['top5_acc']:.2f}%  infer={r['infer_ms_avg']:.2f}ms")

TRT Precision: int4
  SKIP 8bit / seed_1 (result exists)
  SKIP 8bit / seed_2 (result exists)
  SKIP 8bit / seed_42 (result exists)

  4bit / seed_1:
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/fp32_4bit/resnet_1_int4_qdq.onnx
[runner] Step 2/3 — Building TRT engine (precision=int4) ...
[trt_builder] Building engine | precision=int4 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/fp32_4bit/seed_1/resnet18_tensorrt_int4_in4b_cuda_bs1.engine (23.0 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/fp32_4bit/seed_1/resnet18_tensorrt_int4_in4b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [50/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [60/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [70/500]  Top-1: 97.50%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [80/500]  Top-1: 98.00%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [90/500]  Top-1: 98.33%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [100/500]  Top-1: 98.57%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [110/500]  Top-1: 98.75%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [120/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [130/500]  Top-1: 99.00%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [140/500]  Top-1: 99.09%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [150/500]  Top-1: 99.17%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [160/500]  Top-1: 99.23%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [170/500]  Top-1: 99.29%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [180/500]  Top-1: 98.67%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [190/500]  Top-1: 98.75%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [200/500]  Top-1: 98.82%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [210/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [220/500]  Top-1: 98.95%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [230/500]  Top-1: 99.00%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [240/500]  Top-1: 99.05%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [250/500]  Top-1: 99.09%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [260/500]  Top-1: 99.13%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [270/500]  Top-1: 99.17%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [280/500]  Top-1: 99.20%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [290/500]  Top-1: 99.23%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [300/500]  Top-1: 99.26%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [310/500]  Top-1: 99.29%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [320/500]  Top-1: 99.31%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [330/500]  Top-1: 99.33%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [340/500]  Top-1: 99.35%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [350/500]  Top-1: 99.38%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [360/500]  Top-1: 99.39%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [370/500]  Top-1: 99.41%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [380/500]  Top-1: 99.14%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [390/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [400/500]  Top-1: 98.92%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [410/500]  Top-1: 98.68%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [420/500]  Top-1: 98.72%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [430/500]  Top-1: 98.75%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [440/500]  Top-1: 98.78%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [450/500]  Top-1: 98.81%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [460/500]  Top-1: 98.84%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [470/500]  Top-1: 98.86%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [480/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [490/500]  Top-1: 98.91%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [500/500]  Top-1: 98.94%  Top-5: 100.00%  Infer: 0.51 ms/batch
[runner] Results saved: ../runs/val_infer/fp32_4bit/seed_1/resnet18_tensorrt_int4_in4b_cuda_bs1/result.json
    top1=98.94%  top5=100.00%  infer=0.51ms
  SKIP 4bit / seed_2 (result exists)
  SKIP 4bit / seed_42 (result exists)
  SKIP 2bit / seed_1 (result exists)
  SKIP 2bit / seed_2 (result exists)
  SKIP 2bit / seed_42 (result exists)
  SKIP 1bit / seed_1 (result exists)
  SKIP 1bit / seed_2 (result exists)
  SKIP 1bit / seed_42 (result exists)

## All Results (per seed)

In [22]:
all_rows = []
for bits in INPUT_BITS:
    ckpt_dir = CKPT_ROOT / f"fp32_{bits}bit"
    if not ckpt_dir.exists():
        continue
    for seed_dir in sorted(ckpt_dir.iterdir()):
        if not seed_dir.is_dir():
            continue
        run_dir = f"../runs/val_infer/fp32_{bits}bit/{seed_dir.name}"
        runs = load_runs(run_dir, status="ok")
        for r in flatten_runs(runs):
            r["seed"] = seed_dir.name
            r["input_bits_trained"] = bits
            all_rows.append(r)

df = pd.DataFrame(all_rows)
df_trt = df[df["cfg.backend"] == "tensorrt"]

display_cols = [
    "seed", "input_bits_trained", "cfg.model_precision",
    "res.top1_acc", "res.top5_acc", "res.infer_ms_avg", "res.throughput_infer_sps",
]
df_trt[display_cols].sort_values(
    ["input_bits_trained", "seed", "cfg.model_precision"],
    ascending=[False, True, True],
).reset_index(drop=True)

,seed,input_bits_trained,cfg.model_precision,res.top1_acc,res.top5_acc,res.infer_ms_avg,res.throughput_infer_sps
0,seed_1,8,fp16,98.936,100.000,0.488,2047.729
1,seed_1,8,fp32,98.936,100.000,0.965,1036.657
2,seed_1,8,fp8,98.723,100.000,0.660,1515.532
3,seed_1,8,int4,98.298,100.000,0.509,1965.832
4,seed_1,8,int8,98.936,100.000,0.665,1504.557
5,seed_2,8,fp16,98.085,100.000,0.483,2072.067
6,seed_2,8,fp32,98.085,100.000,0.957,1044.643
7,seed_2,8,fp8,98.298,100.000,0.683,1463.612
8,seed_2,8,int4,98.298,100.000,0.490,2038.849
9,seed_2,8,int8,98.298,100.000,0.719,1391.612
10,seed_42,8,fp16,86.170,98.723,0.531,1883.557
11,seed_42,8,fp32,86.383,98.723,0.957,1044.646
12,seed_42,8,fp8,86.383,98.511,0.634,1577.914
13,seed_42,8,int4,86.170,98.723,0.498,2006.225
14,seed_42,8,int8,85.745,98.298,0.687,1455.208
15,seed_1,4,fp16,98.723,100.000,0.501,1995.815
16,seed_1,4,fp32,98.723,100.000,0.934,1071.073
17,seed_1,4,fp8,98.723,100.000,0.687,1455.646
18,seed_1,4,int4,98.936,100.000,0.509,1965.826
19,seed_1,4,int8,98.511,100.000,0.804,1243.033
20,seed_2,4,fp16,97.872,100.000,0.494,2023.404
21,seed_2,4,fp32,97.872,100.000,0.949,1053.639
22,seed_2,4,fp8,97.660,100.000,0.639,1564.942
23,seed_2,4,int4,97.660,100.000,0.506,1977.222
24,seed_2,4,int8,97.660,100.000,0.717,1394.705
25,seed_42,4,fp16,87.234,98.936,0.513,1948.366
26,seed_42,4,fp32,87.234,98.936,0.972,1028.393
27,seed_42,4,fp8,86.170,98.723,0.662,1510.325
28,seed_42,4,int4,85.957,98.723,0.489,2045.984
29,seed_42,4,int8,86.596,98.936,0.742,1347.934
30,seed_1,2,fp16,92.979,100.000,0.489,2043.731
31,seed_1,2,fp32,92.979,100.000,0.952,1049.965
32,seed_1,2,fp8,93.191,100.000,0.652,1533.159
33,seed_1,2,int4,91.915,100.000,0.492,2031.857
34,seed_1,2,int8,93.191,100.000,0.699,1430.364
35,seed_2,2,fp16,93.830,100.000,0.498,2009.753
36,seed_2,2,fp32,93.830,100.000,0.971,1029.416
37,seed_2,2,fp8,93.617,100.000,0.647,1546.526
38,seed_2,2,int4,94.043,100.000,0.502,1990.429
39,seed_2,2,int8,93.404,100.000,0.683,1464.071
40,seed_42,2,fp16,84.468,97.660,0.500,1999.495
41,seed_42,2,fp32,84.681,97.660,0.971,1029.502
42,seed_42,2,fp8,84.043,97.660,0.641,1561.099
43,seed_42,2,int4,84.468,97.872,0.506,1974.425
44,seed_42,2,int8,84.255,97.660,0.699,1431.215
45,seed_1,1,fp16,90.000,98.936,0.491,2038.712
46,seed_1,1,fp32,90.000,98.936,0.962,1039.869
47,seed_1,1,fp8,90.000,98.936,0.659,1516.920
48,seed_1,1,int4,90.426,99.149,0.503,1988.287
49,seed_1,1,int8,89.787,98.723,0.689,1450.441
50,seed_2,1,fp16,88.723,99.149,0.497,2010.396
51,seed_2,1,fp32,88.723,99.149,0.959,1042.312
52,seed_2,1,fp8,89.149,99.362,0.659,1516.303
53,seed_2,1,int4,88.298,99.362,0.527,1897.969
54,seed_2,1,int8,88.936,99.362,0.760,1315.150
55,seed_42,1,fp16,79.362,95.319,0.470,2128.466
56,seed_42,1,fp32,79.362,95.319,0.935,1069.798
57,seed_42,1,fp8,78.723,95.319,0.649,1540.220
58,seed_42,1,int4,77.872,94.681,0.499,2003.455
59,seed_42,1,int8,79.787,95.532,0.725,1378.576

## Averaged Results (across seeds)

In [23]:
avg_df = df_trt.groupby(["cfg.backend", "cfg.model_precision", "input_bits_trained"]).agg(
    top1_mean=("res.top1_acc", "mean"),
    top1_std=("res.top1_acc", "std"),
    top5_mean=("res.top5_acc", "mean"),
    top5_std=("res.top5_acc", "std"),
    infer_ms_mean=("res.infer_ms_avg", "mean"),
    infer_ms_std=("res.infer_ms_avg", "std"),
    throughput_mean=("res.throughput_infer_sps", "mean"),
).round(3).reset_index()

avg_df = avg_df.sort_values(
    ["cfg.model_precision", "input_bits_trained"],
    ascending=[True, False],
).reset_index(drop=True)
avg_df

,cfg.backend,cfg.model_precision,input_bits_trained,top1_mean,top1_std,top5_mean,top5_std,infer_ms_mean,infer_ms_std,throughput_mean
0,tensorrt,fp16,8,94.397,7.137,99.574,0.737,0.501,0.026,2001.118
1,tensorrt,fp16,4,94.610,6.402,99.645,0.614,0.503,0.010,1989.195
2,tensorrt,fp16,2,90.426,5.177,99.220,1.351,0.496,0.006,2017.660
3,tensorrt,fp16,1,86.028,5.809,97.801,2.152,0.486,0.014,2059.191
4,tensorrt,fp32,8,94.468,7.015,99.574,0.737,0.960,0.004,1041.982
5,tensorrt,fp32,4,94.610,6.402,99.645,0.614,0.952,0.020,1051.035
6,tensorrt,fp32,2,90.496,5.054,99.220,1.351,0.965,0.011,1036.294
7,tensorrt,fp32,1,86.028,5.809,97.801,2.152,0.952,0.015,1050.660
8,tensorrt,fp8,8,94.468,7.005,99.504,0.860,0.659,0.025,1519.019
9,tensorrt,fp8,4,94.184,6.961,99.574,0.737,0.663,0.024,1510.304
10,tensorrt,fp8,2,90.284,5.409,99.220,1.351,0.646,0.006,1546.928
11,tensorrt,fp8,1,85.957,6.279,97.872,2.221,0.656,0.006,1524.481
12,tensorrt,int4,8,94.255,7.002,99.574,0.737,0.499,0.009,2003.635
13,tensorrt,int4,4,94.184,7.153,99.574,0.737,0.501,0.011,1996.344
14,tensorrt,int4,2,90.142,5.027,99.291,1.228,0.500,0.007,1998.903
15,tensorrt,int4,1,85.532,6.718,97.730,2.643,0.510,0.015,1963.237
16,tensorrt,int8,8,94.326,7.439,99.433,0.983,0.690,0.027,1450.459
17,tensorrt,int8,4,94.255,6.647,99.645,0.614,0.754,0.045,1328.558
18,tensorrt,int8,2,90.284,5.222,99.220,1.351,0.694,0.009,1441.883
19,tensorrt,int8,1,86.170,5.544,97.872,2.052,0.725,0.035,1381.389

In [24]:
import json, numpy as np

bench_fp32 = PROJECT_ROOT / "results" / "latency_bench" / "tensorrt_fp32_in4b_cuda_bs1.json"
bench_int8 = PROJECT_ROOT / "results" / "latency_bench" / "tensorrt_int8_in8b_cuda_bs1.json"

with open(bench_fp32) as f:
    std_fp = np.std(json.load(f)["latencies_ms"], ddof=1)
with open(bench_int8) as f:
    std_int = np.std(json.load(f)["latencies_ms"], ddof=1)

bench_std_map = {"fp32": std_fp, "fp16": std_fp, "fp8": std_fp, "int8": std_int, "int4": std_int}

avg_df[["cfg.model_precision", "input_bits_trained",
        "top1_mean", "top1_std", "top5_mean", "top5_std",
        "infer_ms_mean"]].assign(
    top1=lambda d: d.apply(lambda r: f"{r['top1_mean']:.2f} ± {r['top1_std']:.2f}", axis=1),
    top5=lambda d: d.apply(lambda r: f"{r['top5_mean']:.2f} ± {r['top5_std']:.2f}", axis=1),
    infer_ms=lambda d: d.apply(lambda r: f"{r['infer_ms_mean']:.3f} ± {bench_std_map[r['cfg.model_precision']]:.3f}", axis=1),
)[["cfg.model_precision", "input_bits_trained", "top1", "top5", "infer_ms"]]

,cfg.model_precision,input_bits_trained,top1,top5,infer_ms
0,fp16,8,94.40 ± 7.14,99.57 ± 0.74,0.501 ± 0.136
1,fp16,4,94.61 ± 6.40,99.64 ± 0.61,0.503 ± 0.136
2,fp16,2,90.43 ± 5.18,99.22 ± 1.35,0.496 ± 0.136
3,fp16,1,86.03 ± 5.81,97.80 ± 2.15,0.486 ± 0.136
4,fp32,8,94.47 ± 7.01,99.57 ± 0.74,0.960 ± 0.136
5,fp32,4,94.61 ± 6.40,99.64 ± 0.61,0.952 ± 0.136
6,fp32,2,90.50 ± 5.05,99.22 ± 1.35,0.965 ± 0.136
7,fp32,1,86.03 ± 5.81,97.80 ± 2.15,0.952 ± 0.136
8,fp8,8,94.47 ± 7.00,99.50 ± 0.86,0.659 ± 0.136
9,fp8,4,94.18 ± 6.96,99.57 ± 0.74,0.663 ± 0.136
10,fp8,2,90.28 ± 5.41,99.22 ± 1.35,0.646 ± 0.136
11,fp8,1,85.96 ± 6.28,97.87 ± 2.22,0.656 ± 0.136
12,int4,8,94.25 ± 7.00,99.57 ± 0.74,0.499 ± 0.276
13,int4,4,94.18 ± 7.15,99.57 ± 0.74,0.501 ± 0.276
14,int4,2,90.14 ± 5.03,99.29 ± 1.23,0.500 ± 0.276
15,int4,1,85.53 ± 6.72,97.73 ± 2.64,0.510 ± 0.276
16,int8,8,94.33 ± 7.44,99.43 ± 0.98,0.690 ± 0.276
17,int8,4,94.25 ± 6.65,99.64 ± 0.61,0.754 ± 0.276
18,int8,2,90.28 ± 5.22,99.22 ± 1.35,0.694 ± 0.276
19,int8,1,86.17 ± 5.54,97.87 ± 2.05,0.725 ± 0.276

In [25]:
out_path = PROJECT_ROOT / "resultsv2/val_runs/tensorrt_avg_results.json"
avg_df.to_json(out_path, orient="records", indent=2)
print(f"Saved to {out_path}")

Saved to /home/pf4636/code/resnet/quantized_resnets/resultsv2/val_runs/tensorrt_avg_results.json