# 02 — TensorRT Inference Sweep

For each trained checkpoint (`seed_1`, `seed_2`, `seed_42`), sweep all 5 precisions × 4 input bit-depths.

ONNX exports (base + QDQ) are assumed to already exist from `00_qdq_export.ipynb`.

Results saved under `runs/val_infer/<seed>/`, averaged at the end.

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path("..").resolve()
PYFILES = PROJECT_ROOT / "pyfiles"
if str(PYFILES) not in sys.path:
    sys.path.insert(0, str(PYFILES))

In [2]:
import torch
import pandas as pd

from src.config import ExperimentConfig, with_overrides
from src.runner import run_experiment
from utils.utils import load_runs, flatten_runs

pd.set_option("display.max_columns", 200)
pd.set_option("display.float_format", "{:.3f}".format)
print("torch:", torch.__version__, "| cuda:", torch.cuda.is_available())

torch: 2.10.0+cu130 | cuda: True

In [3]:
CKPT_ROOT = PROJECT_ROOT / "training" / "checkpoints" / "fp32"
SEEDS = sorted([p.name for p in CKPT_ROOT.iterdir() if p.is_dir() and (p / "best.pth").exists()])
checkpoints = {seed: str(CKPT_ROOT / seed / "best.pth") for seed in SEEDS}

INPUT_BITS = [8, 4, 2, 1]

def seed_num(seed):
    return seed.split("_")[-1]

def make_base(seed):
    prefix = f"resnet_{seed_num(seed)}"
    return ExperimentConfig(
        backend="tensorrt",
        device="cuda",
        batch_size=1,
        seed=42,
        num_eval_batches=500,
        trt_static_shape=True,
        trt_workspace_mb=2048,
        onnx_root=str(PROJECT_ROOT / "onnx"),
        engine_root=str(PROJECT_ROOT / "engines" / seed),
        trt_onnx_prefix=prefix,
        output_root=f"../runs/val_infer/{seed}",
    )

def run_precision_sweep(precision):
    records = []
    for seed, ckpt_path in checkpoints.items():
        print(f"\n  {seed}:")
        base = make_base(seed)
        for bits in INPUT_BITS:
            cfg = with_overrides(base, model_precision=precision, input_quant_bits=bits)
            payload, _ = run_experiment(cfg, save_results_flag=True, checkpoint_path=ckpt_path)
            records.append(payload)
            r = payload["results"]
            print(f"    b={bits}: top1={r['top1_acc']:.2f}%  top5={r['top5_acc']:.2f}%  infer={r['infer_ms_avg']:.2f}ms")
    return records

print(f"Seeds: {SEEDS}")
print(f"Input bits: {INPUT_BITS}")

Seeds: ['seed_1', 'seed_2', 'seed_42']
Input bits: [8, 4, 2, 1]

## FP32

In [4]:
fp32_records = run_precision_sweep("fp32")

  seed_1:
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_1.onnx
[runner] Step 2/3 — Engine exists, skipping: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp32_in8b_cuda_bs1.engine
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp32_in8b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 1.02 ms/batch
  [50/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 1.00 ms/batch
  [60/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 1.02 ms/batch
  [70/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 1.02 ms/batch
  [80/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 1.02 ms/batch
  [90/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 1.01 ms/batch
  [100/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 1.00 ms/batch
  [110/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.99 ms/batch
  [120/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.98 ms/batch
  [130/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.99 ms/batch
  [140/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.98 ms/batch
  [150/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.98 ms/batch
  [160/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.97 ms/batch
  [170/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.97 ms/batch
  [180/500]  Top-1: 99.33%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [190/500]  Top-1: 99.38%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [200/500]  Top-1: 99.41%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [210/500]  Top-1: 99.44%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [220/500]  Top-1: 99.47%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [230/500]  Top-1: 99.50%  Top-5: 100.00%  Infer: 0.97 ms/batch
  [240/500]  Top-1: 99.52%  Top-5: 100.00%  Infer: 0.97 ms/batch
  [250/500]  Top-1: 99.55%  Top-5: 100.00%  Infer: 0.97 ms/batch
  [260/500]  Top-1: 99.57%  Top-5: 100.00%  Infer: 0.97 ms/batch
  [270/500]  Top-1: 99.58%  Top-5: 100.00%  Infer: 0.97 ms/batch
  [280/500]  Top-1: 99.60%  Top-5: 100.00%  Infer: 0.97 ms/batch
  [290/500]  Top-1: 99.62%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [300/500]  Top-1: 99.63%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [310/500]  Top-1: 99.64%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [320/500]  Top-1: 99.66%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [330/500]  Top-1: 99.67%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [340/500]  Top-1: 99.68%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [350/500]  Top-1: 99.69%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [360/500]  Top-1: 99.70%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [370/500]  Top-1: 99.71%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [380/500]  Top-1: 99.71%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [390/500]  Top-1: 99.72%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [400/500]  Top-1: 99.73%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [410/500]  Top-1: 99.47%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [420/500]  Top-1: 98.97%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [430/500]  Top-1: 99.00%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [440/500]  Top-1: 98.78%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [450/500]  Top-1: 98.81%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [460/500]  Top-1: 98.84%  Top-5: 100.00%  Infer: 0.95 ms/batch
  [470/500]  Top-1: 98.86%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [480/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [490/500]  Top-1: 98.91%  Top-5: 100.00%  Infer: 0.95 ms/batch
  [500/500]  Top-1: 98.94%  Top-5: 100.00%  Infer: 0.95 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_tensorrt_fp32_in8b_cuda_bs1/result.json
    b=8: top1=98.94%  top5=100.00%  infer=0.95ms
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_1.onnx
[runner] Step 2/3 — Engine exists, skipping: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp32_in4b_cuda_bs1.engine
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp32_in4b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 90.00%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [50/500]  Top-1: 95.00%  Top-5: 100.00%  Infer: 0.92 ms/batch
  [60/500]  Top-1: 96.67%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [70/500]  Top-1: 97.50%  Top-5: 100.00%  Infer: 0.94 ms/batch
  [80/500]  Top-1: 98.00%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [90/500]  Top-1: 98.33%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [100/500]  Top-1: 98.57%  Top-5: 100.00%  Infer: 0.92 ms/batch
  [110/500]  Top-1: 98.75%  Top-5: 100.00%  Infer: 0.92 ms/batch
  [120/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [130/500]  Top-1: 99.00%  Top-5: 100.00%  Infer: 0.94 ms/batch
  [140/500]  Top-1: 99.09%  Top-5: 100.00%  Infer: 0.94 ms/batch
  [150/500]  Top-1: 98.33%  Top-5: 100.00%  Infer: 0.95 ms/batch
  [160/500]  Top-1: 98.46%  Top-5: 100.00%  Infer: 0.95 ms/batch
  [170/500]  Top-1: 98.57%  Top-5: 100.00%  Infer: 0.94 ms/batch
  [180/500]  Top-1: 98.00%  Top-5: 100.00%  Infer: 0.95 ms/batch
  [190/500]  Top-1: 98.12%  Top-5: 100.00%  Infer: 0.95 ms/batch
  [200/500]  Top-1: 98.24%  Top-5: 100.00%  Infer: 0.94 ms/batch
  [210/500]  Top-1: 97.78%  Top-5: 100.00%  Infer: 0.95 ms/batch
  [220/500]  Top-1: 97.37%  Top-5: 100.00%  Infer: 0.95 ms/batch
  [230/500]  Top-1: 97.50%  Top-5: 100.00%  Infer: 0.95 ms/batch
  [240/500]  Top-1: 97.62%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [250/500]  Top-1: 97.73%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [260/500]  Top-1: 97.83%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [270/500]  Top-1: 97.92%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [280/500]  Top-1: 97.60%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [290/500]  Top-1: 97.31%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [300/500]  Top-1: 97.04%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [310/500]  Top-1: 96.79%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [320/500]  Top-1: 96.90%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [330/500]  Top-1: 97.00%  Top-5: 100.00%  Infer: 0.95 ms/batch
  [340/500]  Top-1: 97.10%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [350/500]  Top-1: 97.19%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [360/500]  Top-1: 97.27%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [370/500]  Top-1: 97.35%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [380/500]  Top-1: 97.14%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [390/500]  Top-1: 97.22%  Top-5: 100.00%  Infer: 0.95 ms/batch
  [400/500]  Top-1: 97.30%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [410/500]  Top-1: 97.11%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [420/500]  Top-1: 96.92%  Top-5: 100.00%  Infer: 0.95 ms/batch
  [430/500]  Top-1: 97.00%  Top-5: 100.00%  Infer: 0.95 ms/batch
  [440/500]  Top-1: 96.83%  Top-5: 100.00%  Infer: 0.95 ms/batch
  [450/500]  Top-1: 96.90%  Top-5: 100.00%  Infer: 0.95 ms/batch
  [460/500]  Top-1: 96.98%  Top-5: 100.00%  Infer: 0.95 ms/batch
  [470/500]  Top-1: 97.05%  Top-5: 100.00%  Infer: 0.95 ms/batch
  [480/500]  Top-1: 97.11%  Top-5: 100.00%  Infer: 0.95 ms/batch
  [490/500]  Top-1: 97.17%  Top-5: 100.00%  Infer: 0.95 ms/batch
  [500/500]  Top-1: 97.23%  Top-5: 100.00%  Infer: 0.95 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_tensorrt_fp32_in4b_cuda_bs1/result.json
    b=4: top1=97.23%  top5=100.00%  infer=0.95ms
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_1.onnx
[runner] Step 2/3 — Engine exists, skipping: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp32_in2b_cuda_bs1.engine
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp32_in2b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 70.00%  Top-5: 70.00%  Infer: 1.01 ms/batch
  [50/500]  Top-1: 70.00%  Top-5: 80.00%  Infer: 1.03 ms/batch
  [60/500]  Top-1: 80.00%  Top-5: 86.67%  Infer: 1.07 ms/batch
  [70/500]  Top-1: 85.00%  Top-5: 90.00%  Infer: 1.06 ms/batch
  [80/500]  Top-1: 88.00%  Top-5: 92.00%  Infer: 1.06 ms/batch
  [90/500]  Top-1: 85.00%  Top-5: 93.33%  Infer: 1.07 ms/batch
  [100/500]  Top-1: 84.29%  Top-5: 94.29%  Infer: 1.06 ms/batch
  [110/500]  Top-1: 80.00%  Top-5: 92.50%  Infer: 1.06 ms/batch
  [120/500]  Top-1: 77.78%  Top-5: 90.00%  Infer: 1.05 ms/batch
  [130/500]  Top-1: 73.00%  Top-5: 90.00%  Infer: 1.06 ms/batch
  [140/500]  Top-1: 70.00%  Top-5: 89.09%  Infer: 1.05 ms/batch
  [150/500]  Top-1: 68.33%  Top-5: 88.33%  Infer: 1.05 ms/batch
  [160/500]  Top-1: 67.69%  Top-5: 88.46%  Infer: 1.04 ms/batch
  [170/500]  Top-1: 66.43%  Top-5: 88.57%  Infer: 1.03 ms/batch
  [180/500]  Top-1: 63.33%  Top-5: 86.67%  Infer: 1.03 ms/batch
  [190/500]  Top-1: 61.88%  Top-5: 85.00%  Infer: 1.02 ms/batch
  [200/500]  Top-1: 61.18%  Top-5: 84.12%  Infer: 1.01 ms/batch
  [210/500]  Top-1: 62.22%  Top-5: 84.44%  Infer: 1.01 ms/batch
  [220/500]  Top-1: 61.05%  Top-5: 84.74%  Infer: 1.00 ms/batch
  [230/500]  Top-1: 59.00%  Top-5: 85.50%  Infer: 1.00 ms/batch
  [240/500]  Top-1: 59.52%  Top-5: 86.19%  Infer: 1.00 ms/batch
  [250/500]  Top-1: 59.09%  Top-5: 85.91%  Infer: 0.99 ms/batch
  [260/500]  Top-1: 58.26%  Top-5: 84.78%  Infer: 0.99 ms/batch
  [270/500]  Top-1: 57.50%  Top-5: 83.75%  Infer: 0.99 ms/batch
  [280/500]  Top-1: 56.80%  Top-5: 83.20%  Infer: 0.98 ms/batch
  [290/500]  Top-1: 55.38%  Top-5: 82.31%  Infer: 0.98 ms/batch
  [300/500]  Top-1: 54.07%  Top-5: 81.11%  Infer: 0.98 ms/batch
  [310/500]  Top-1: 54.29%  Top-5: 81.07%  Infer: 0.97 ms/batch
  [320/500]  Top-1: 54.14%  Top-5: 80.34%  Infer: 0.97 ms/batch
  [330/500]  Top-1: 53.33%  Top-5: 80.00%  Infer: 0.97 ms/batch
  [340/500]  Top-1: 52.90%  Top-5: 80.32%  Infer: 0.97 ms/batch
  [350/500]  Top-1: 52.19%  Top-5: 79.69%  Infer: 0.97 ms/batch
  [360/500]  Top-1: 53.33%  Top-5: 80.30%  Infer: 0.97 ms/batch
  [370/500]  Top-1: 54.71%  Top-5: 80.88%  Infer: 0.97 ms/batch
  [380/500]  Top-1: 56.00%  Top-5: 81.43%  Infer: 0.96 ms/batch
  [390/500]  Top-1: 56.67%  Top-5: 81.94%  Infer: 0.96 ms/batch
  [400/500]  Top-1: 57.30%  Top-5: 82.16%  Infer: 0.96 ms/batch
  [410/500]  Top-1: 57.89%  Top-5: 82.63%  Infer: 0.96 ms/batch
  [420/500]  Top-1: 57.69%  Top-5: 82.31%  Infer: 0.96 ms/batch
  [430/500]  Top-1: 57.25%  Top-5: 81.75%  Infer: 0.96 ms/batch
  [440/500]  Top-1: 57.07%  Top-5: 81.71%  Infer: 0.96 ms/batch
  [450/500]  Top-1: 56.90%  Top-5: 81.43%  Infer: 0.96 ms/batch
  [460/500]  Top-1: 57.21%  Top-5: 81.63%  Infer: 0.96 ms/batch
  [470/500]  Top-1: 57.50%  Top-5: 81.82%  Infer: 0.96 ms/batch
  [480/500]  Top-1: 58.00%  Top-5: 81.78%  Infer: 0.96 ms/batch
  [490/500]  Top-1: 58.48%  Top-5: 82.17%  Infer: 0.96 ms/batch
  [500/500]  Top-1: 58.94%  Top-5: 82.13%  Infer: 0.95 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_tensorrt_fp32_in2b_cuda_bs1/result.json
    b=2: top1=58.94%  top5=82.13%  infer=0.95ms
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_1.onnx
[runner] Step 2/3 — Engine exists, skipping: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp32_in1b_cuda_bs1.engine
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp32_in1b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 30.00%  Top-5: 60.00%  Infer: 1.02 ms/batch
  [50/500]  Top-1: 30.00%  Top-5: 55.00%  Infer: 1.01 ms/batch
  [60/500]  Top-1: 36.67%  Top-5: 66.67%  Infer: 1.02 ms/batch
  [70/500]  Top-1: 42.50%  Top-5: 75.00%  Infer: 1.02 ms/batch
  [80/500]  Top-1: 54.00%  Top-5: 80.00%  Infer: 1.02 ms/batch
  [90/500]  Top-1: 55.00%  Top-5: 81.67%  Infer: 1.02 ms/batch
  [100/500]  Top-1: 58.57%  Top-5: 82.86%  Infer: 1.02 ms/batch
  [110/500]  Top-1: 56.25%  Top-5: 78.75%  Infer: 1.03 ms/batch
  [120/500]  Top-1: 51.11%  Top-5: 77.78%  Infer: 1.03 ms/batch
  [130/500]  Top-1: 49.00%  Top-5: 74.00%  Infer: 1.03 ms/batch
  [140/500]  Top-1: 46.36%  Top-5: 70.91%  Infer: 1.03 ms/batch
  [150/500]  Top-1: 45.83%  Top-5: 69.17%  Infer: 1.03 ms/batch
  [160/500]  Top-1: 42.31%  Top-5: 66.92%  Infer: 1.03 ms/batch
  [170/500]  Top-1: 40.00%  Top-5: 65.00%  Infer: 1.02 ms/batch
  [180/500]  Top-1: 37.33%  Top-5: 61.33%  Infer: 1.01 ms/batch
  [190/500]  Top-1: 35.00%  Top-5: 58.75%  Infer: 1.01 ms/batch
  [200/500]  Top-1: 34.12%  Top-5: 57.06%  Infer: 1.00 ms/batch
  [210/500]  Top-1: 34.44%  Top-5: 56.67%  Infer: 1.00 ms/batch
  [220/500]  Top-1: 33.68%  Top-5: 56.84%  Infer: 1.00 ms/batch
  [230/500]  Top-1: 33.00%  Top-5: 57.50%  Infer: 0.99 ms/batch
  [240/500]  Top-1: 32.86%  Top-5: 58.10%  Infer: 0.99 ms/batch
  [250/500]  Top-1: 32.27%  Top-5: 58.64%  Infer: 0.99 ms/batch
  [260/500]  Top-1: 32.17%  Top-5: 57.83%  Infer: 0.98 ms/batch
  [270/500]  Top-1: 32.08%  Top-5: 57.92%  Infer: 0.98 ms/batch
  [280/500]  Top-1: 31.20%  Top-5: 56.40%  Infer: 0.97 ms/batch
  [290/500]  Top-1: 30.77%  Top-5: 55.77%  Infer: 0.97 ms/batch
  [300/500]  Top-1: 30.37%  Top-5: 55.19%  Infer: 0.97 ms/batch
  [310/500]  Top-1: 30.36%  Top-5: 55.36%  Infer: 0.97 ms/batch
  [320/500]  Top-1: 30.00%  Top-5: 55.17%  Infer: 0.96 ms/batch
  [330/500]  Top-1: 29.00%  Top-5: 55.33%  Infer: 0.96 ms/batch
  [340/500]  Top-1: 29.35%  Top-5: 55.81%  Infer: 0.96 ms/batch
  [350/500]  Top-1: 29.38%  Top-5: 55.00%  Infer: 0.96 ms/batch
  [360/500]  Top-1: 30.00%  Top-5: 56.36%  Infer: 0.96 ms/batch
  [370/500]  Top-1: 31.18%  Top-5: 57.35%  Infer: 0.95 ms/batch
  [380/500]  Top-1: 32.29%  Top-5: 58.57%  Infer: 0.95 ms/batch
  [390/500]  Top-1: 34.17%  Top-5: 59.72%  Infer: 0.95 ms/batch
  [400/500]  Top-1: 34.59%  Top-5: 60.81%  Infer: 0.95 ms/batch
  [410/500]  Top-1: 34.21%  Top-5: 60.53%  Infer: 0.95 ms/batch
  [420/500]  Top-1: 33.59%  Top-5: 60.26%  Infer: 0.95 ms/batch
  [430/500]  Top-1: 33.00%  Top-5: 60.00%  Infer: 0.95 ms/batch
  [440/500]  Top-1: 32.68%  Top-5: 59.76%  Infer: 0.95 ms/batch
  [450/500]  Top-1: 31.90%  Top-5: 59.52%  Infer: 0.95 ms/batch
  [460/500]  Top-1: 32.33%  Top-5: 60.00%  Infer: 0.95 ms/batch
  [470/500]  Top-1: 32.50%  Top-5: 60.00%  Infer: 0.95 ms/batch
  [480/500]  Top-1: 33.11%  Top-5: 60.44%  Infer: 0.95 ms/batch
  [490/500]  Top-1: 33.48%  Top-5: 60.43%  Infer: 0.95 ms/batch
  [500/500]  Top-1: 33.62%  Top-5: 60.64%  Infer: 0.95 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_tensorrt_fp32_in1b_cuda_bs1/result.json
    b=1: top1=33.62%  top5=60.64%  infer=0.95ms

  seed_2:
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_2.onnx
[runner] Step 2/3 — Building TRT engine (precision=fp32) ...
[trt_builder] Building engine | precision=fp32 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_2/resnet18_tensorrt_fp32_in8b_cuda_bs1.engine (46.9 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_2/resnet18_tensorrt_fp32_in8b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.87 ms/batch
  [50/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.91 ms/batch
  [60/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.90 ms/batch
  [70/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.91 ms/batch
  [80/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.91 ms/batch
  [90/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.91 ms/batch
  [100/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.90 ms/batch
  [110/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.89 ms/batch
  [120/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.90 ms/batch
  [130/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.91 ms/batch
  [140/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.91 ms/batch
  [150/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.90 ms/batch
  [160/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.90 ms/batch
  [170/500]  Top-1: 99.29%  Top-5: 100.00%  Infer: 0.90 ms/batch
  [180/500]  Top-1: 98.67%  Top-5: 100.00%  Infer: 0.91 ms/batch
  [190/500]  Top-1: 98.75%  Top-5: 100.00%  Infer: 0.91 ms/batch
  [200/500]  Top-1: 98.82%  Top-5: 100.00%  Infer: 0.91 ms/batch
  [210/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.92 ms/batch
  [220/500]  Top-1: 98.95%  Top-5: 100.00%  Infer: 0.92 ms/batch
  [230/500]  Top-1: 99.00%  Top-5: 100.00%  Infer: 0.92 ms/batch
  [240/500]  Top-1: 99.05%  Top-5: 100.00%  Infer: 0.92 ms/batch
  [250/500]  Top-1: 99.09%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [260/500]  Top-1: 99.13%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [270/500]  Top-1: 99.17%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [280/500]  Top-1: 99.20%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [290/500]  Top-1: 98.46%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [300/500]  Top-1: 98.52%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [310/500]  Top-1: 98.21%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [320/500]  Top-1: 98.28%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [330/500]  Top-1: 98.33%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [340/500]  Top-1: 98.39%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [350/500]  Top-1: 98.44%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [360/500]  Top-1: 98.48%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [370/500]  Top-1: 98.53%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [380/500]  Top-1: 98.57%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [390/500]  Top-1: 98.61%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [400/500]  Top-1: 98.65%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [410/500]  Top-1: 98.16%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [420/500]  Top-1: 97.95%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [430/500]  Top-1: 97.75%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [440/500]  Top-1: 97.80%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [450/500]  Top-1: 97.86%  Top-5: 100.00%  Infer: 0.93 ms/batch
  [460/500]  Top-1: 97.91%  Top-5: 100.00%  Infer: 0.94 ms/batch
  [470/500]  Top-1: 97.95%  Top-5: 100.00%  Infer: 0.94 ms/batch
  [480/500]  Top-1: 98.00%  Top-5: 100.00%  Infer: 0.94 ms/batch
  [490/500]  Top-1: 98.04%  Top-5: 100.00%  Infer: 0.94 ms/batch
  [500/500]  Top-1: 98.09%  Top-5: 100.00%  Infer: 0.94 ms/batch
[runner] Results saved: ../runs/val_infer/seed_2/resnet18_tensorrt_fp32_in8b_cuda_bs1/result.json
    b=8: top1=98.09%  top5=100.00%  infer=0.94ms
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_2.onnx
[runner] Step 2/3 — Building TRT engine (precision=fp32) ...
[trt_builder] Building engine | precision=fp32 | batch=1 | workspace=2048 MiB

## FP16

In [5]:
fp16_records = run_precision_sweep("fp16")

  seed_1:
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_1.onnx
[runner] Step 2/3 — Building TRT engine (precision=fp16) ...
[trt_builder] Building engine | precision=fp16 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp16_in8b_cuda_bs1.engine (22.8 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp16_in8b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.58 ms/batch
  [50/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.96 ms/batch
  [60/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.83 ms/batch
  [70/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.77 ms/batch
  [80/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [90/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.64 ms/batch
  [100/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.62 ms/batch
  [110/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.60 ms/batch
  [120/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.59 ms/batch
  [130/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.58 ms/batch
  [140/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.57 ms/batch
  [150/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.56 ms/batch
  [160/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.56 ms/batch
  [170/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.55 ms/batch
  [180/500]  Top-1: 99.33%  Top-5: 100.00%  Infer: 0.55 ms/batch
  [190/500]  Top-1: 99.38%  Top-5: 100.00%  Infer: 0.55 ms/batch
  [200/500]  Top-1: 99.41%  Top-5: 100.00%  Infer: 0.54 ms/batch
  [210/500]  Top-1: 99.44%  Top-5: 100.00%  Infer: 0.53 ms/batch
  [220/500]  Top-1: 99.47%  Top-5: 100.00%  Infer: 0.53 ms/batch
  [230/500]  Top-1: 99.50%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [240/500]  Top-1: 99.52%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [250/500]  Top-1: 99.55%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [260/500]  Top-1: 99.57%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [270/500]  Top-1: 99.58%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [280/500]  Top-1: 99.60%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [290/500]  Top-1: 99.62%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [300/500]  Top-1: 99.63%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [310/500]  Top-1: 99.64%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [320/500]  Top-1: 99.66%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [330/500]  Top-1: 99.67%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [340/500]  Top-1: 99.68%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [350/500]  Top-1: 99.69%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [360/500]  Top-1: 99.70%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [370/500]  Top-1: 99.71%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [380/500]  Top-1: 99.71%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [390/500]  Top-1: 99.72%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [400/500]  Top-1: 99.73%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [410/500]  Top-1: 99.47%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [420/500]  Top-1: 98.97%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [430/500]  Top-1: 99.00%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [440/500]  Top-1: 98.78%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [450/500]  Top-1: 98.81%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [460/500]  Top-1: 98.84%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [470/500]  Top-1: 98.86%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [480/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [490/500]  Top-1: 98.91%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [500/500]  Top-1: 98.94%  Top-5: 100.00%  Infer: 0.49 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_tensorrt_fp16_in8b_cuda_bs1/result.json
    b=8: top1=98.94%  top5=100.00%  infer=0.49ms
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_1.onnx
[runner] Step 2/3 — Building TRT engine (precision=fp16) ...
[trt_builder] Building engine | precision=fp16 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp16_in4b_cuda_bs1.engine (22.8 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp16_in4b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 90.00%  Top-5: 100.00%  Infer: 0.64 ms/batch
  [50/500]  Top-1: 95.00%  Top-5: 100.00%  Infer: 0.62 ms/batch
  [60/500]  Top-1: 96.67%  Top-5: 100.00%  Infer: 0.62 ms/batch
  [70/500]  Top-1: 97.50%  Top-5: 100.00%  Infer: 0.61 ms/batch
  [80/500]  Top-1: 98.00%  Top-5: 100.00%  Infer: 0.59 ms/batch
  [90/500]  Top-1: 98.33%  Top-5: 100.00%  Infer: 0.60 ms/batch
  [100/500]  Top-1: 98.57%  Top-5: 100.00%  Infer: 0.60 ms/batch
  [110/500]  Top-1: 98.75%  Top-5: 100.00%  Infer: 0.58 ms/batch
  [120/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.58 ms/batch
  [130/500]  Top-1: 99.00%  Top-5: 100.00%  Infer: 0.58 ms/batch
  [140/500]  Top-1: 99.09%  Top-5: 100.00%  Infer: 0.57 ms/batch
  [150/500]  Top-1: 98.33%  Top-5: 100.00%  Infer: 0.56 ms/batch
  [160/500]  Top-1: 98.46%  Top-5: 100.00%  Infer: 0.55 ms/batch
  [170/500]  Top-1: 98.57%  Top-5: 100.00%  Infer: 0.55 ms/batch
  [180/500]  Top-1: 98.00%  Top-5: 100.00%  Infer: 0.54 ms/batch
  [190/500]  Top-1: 98.12%  Top-5: 100.00%  Infer: 0.53 ms/batch
  [200/500]  Top-1: 98.24%  Top-5: 100.00%  Infer: 0.53 ms/batch
  [210/500]  Top-1: 97.78%  Top-5: 100.00%  Infer: 0.53 ms/batch
  [220/500]  Top-1: 97.37%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [230/500]  Top-1: 97.50%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [240/500]  Top-1: 97.62%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [250/500]  Top-1: 97.73%  Top-5: 100.00%  Infer: 0.53 ms/batch
  [260/500]  Top-1: 97.83%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [270/500]  Top-1: 97.92%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [280/500]  Top-1: 97.60%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [290/500]  Top-1: 97.31%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [300/500]  Top-1: 97.04%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [310/500]  Top-1: 96.79%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [320/500]  Top-1: 96.90%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [330/500]  Top-1: 97.00%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [340/500]  Top-1: 97.10%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [350/500]  Top-1: 97.19%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [360/500]  Top-1: 97.27%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [370/500]  Top-1: 97.35%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [380/500]  Top-1: 97.14%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [390/500]  Top-1: 97.22%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [400/500]  Top-1: 97.30%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [410/500]  Top-1: 97.11%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [420/500]  Top-1: 96.92%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [430/500]  Top-1: 97.00%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [440/500]  Top-1: 96.83%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [450/500]  Top-1: 96.90%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [460/500]  Top-1: 96.98%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [470/500]  Top-1: 97.05%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [480/500]  Top-1: 97.11%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [490/500]  Top-1: 97.17%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [500/500]  Top-1: 97.23%  Top-5: 100.00%  Infer: 0.50 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_tensorrt_fp16_in4b_cuda_bs1/result.json
    b=4: top1=97.23%  top5=100.00%  infer=0.50ms
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_1.onnx
[runner] Step 2/3 — Building TRT engine (precision=fp16) ...
[trt_builder] Building engine | precision=fp16 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp16_in2b_cuda_bs1.engine (22.8 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp16_in2b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 70.00%  Top-5: 70.00%  Infer: 0.68 ms/batch
  [50/500]  Top-1: 70.00%  Top-5: 80.00%  Infer: 0.63 ms/batch
  [60/500]  Top-1: 80.00%  Top-5: 86.67%  Infer: 0.57 ms/batch
  [70/500]  Top-1: 85.00%  Top-5: 90.00%  Infer: 0.55 ms/batch
  [80/500]  Top-1: 88.00%  Top-5: 92.00%  Infer: 0.57 ms/batch
  [90/500]  Top-1: 85.00%  Top-5: 93.33%  Infer: 0.57 ms/batch
  [100/500]  Top-1: 84.29%  Top-5: 94.29%  Infer: 0.55 ms/batch
  [110/500]  Top-1: 80.00%  Top-5: 92.50%  Infer: 0.53 ms/batch
  [120/500]  Top-1: 77.78%  Top-5: 90.00%  Infer: 0.52 ms/batch
  [130/500]  Top-1: 73.00%  Top-5: 90.00%  Infer: 0.53 ms/batch
  [140/500]  Top-1: 70.00%  Top-5: 89.09%  Infer: 0.53 ms/batch
  [150/500]  Top-1: 68.33%  Top-5: 88.33%  Infer: 0.54 ms/batch
  [160/500]  Top-1: 67.69%  Top-5: 88.46%  Infer: 0.53 ms/batch
  [170/500]  Top-1: 66.43%  Top-5: 88.57%  Infer: 0.53 ms/batch
  [180/500]  Top-1: 63.33%  Top-5: 86.67%  Infer: 0.53 ms/batch
  [190/500]  Top-1: 61.88%  Top-5: 85.00%  Infer: 0.52 ms/batch
  [200/500]  Top-1: 61.18%  Top-5: 84.12%  Infer: 0.51 ms/batch
  [210/500]  Top-1: 62.22%  Top-5: 84.44%  Infer: 0.51 ms/batch
  [220/500]  Top-1: 61.05%  Top-5: 84.74%  Infer: 0.51 ms/batch
  [230/500]  Top-1: 59.00%  Top-5: 85.50%  Infer: 0.51 ms/batch
  [240/500]  Top-1: 59.52%  Top-5: 86.19%  Infer: 0.50 ms/batch
  [250/500]  Top-1: 59.09%  Top-5: 85.91%  Infer: 0.51 ms/batch
  [260/500]  Top-1: 58.26%  Top-5: 84.78%  Infer: 0.51 ms/batch
  [270/500]  Top-1: 57.50%  Top-5: 83.75%  Infer: 0.51 ms/batch
  [280/500]  Top-1: 56.80%  Top-5: 83.20%  Infer: 0.51 ms/batch
  [290/500]  Top-1: 55.38%  Top-5: 82.31%  Infer: 0.50 ms/batch
  [300/500]  Top-1: 54.07%  Top-5: 81.11%  Infer: 0.50 ms/batch
  [310/500]  Top-1: 54.29%  Top-5: 81.07%  Infer: 0.50 ms/batch
  [320/500]  Top-1: 54.14%  Top-5: 80.34%  Infer: 0.50 ms/batch
  [330/500]  Top-1: 53.33%  Top-5: 80.00%  Infer: 0.50 ms/batch
  [340/500]  Top-1: 52.90%  Top-5: 80.32%  Infer: 0.50 ms/batch
  [350/500]  Top-1: 52.19%  Top-5: 79.69%  Infer: 0.50 ms/batch
  [360/500]  Top-1: 53.33%  Top-5: 80.30%  Infer: 0.49 ms/batch
  [370/500]  Top-1: 54.71%  Top-5: 80.88%  Infer: 0.50 ms/batch
  [380/500]  Top-1: 56.00%  Top-5: 81.43%  Infer: 0.50 ms/batch
  [390/500]  Top-1: 56.67%  Top-5: 81.94%  Infer: 0.50 ms/batch
  [400/500]  Top-1: 57.30%  Top-5: 82.16%  Infer: 0.50 ms/batch
  [410/500]  Top-1: 57.89%  Top-5: 82.63%  Infer: 0.49 ms/batch
  [420/500]  Top-1: 57.69%  Top-5: 82.31%  Infer: 0.49 ms/batch
  [430/500]  Top-1: 57.25%  Top-5: 81.75%  Infer: 0.49 ms/batch
  [440/500]  Top-1: 57.07%  Top-5: 81.71%  Infer: 0.49 ms/batch
  [450/500]  Top-1: 56.90%  Top-5: 81.43%  Infer: 0.49 ms/batch
  [460/500]  Top-1: 57.21%  Top-5: 81.63%  Infer: 0.49 ms/batch
  [470/500]  Top-1: 57.50%  Top-5: 81.82%  Infer: 0.49 ms/batch
  [480/500]  Top-1: 58.00%  Top-5: 81.78%  Infer: 0.49 ms/batch
  [490/500]  Top-1: 58.48%  Top-5: 82.17%  Infer: 0.49 ms/batch
  [500/500]  Top-1: 58.94%  Top-5: 82.13%  Infer: 0.49 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_tensorrt_fp16_in2b_cuda_bs1/result.json
    b=2: top1=58.94%  top5=82.13%  infer=0.49ms
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_1.onnx
[runner] Step 2/3 — Building TRT engine (precision=fp16) ...
[trt_builder] Building engine | precision=fp16 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp16_in1b_cuda_bs1.engine (22.8 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp16_in1b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 30.00%  Top-5: 60.00%  Infer: 0.61 ms/batch
  [50/500]  Top-1: 30.00%  Top-5: 55.00%  Infer: 0.62 ms/batch
  [60/500]  Top-1: 36.67%  Top-5: 66.67%  Infer: 0.60 ms/batch
  [70/500]  Top-1: 42.50%  Top-5: 75.00%  Infer: 0.60 ms/batch
  [80/500]  Top-1: 54.00%  Top-5: 80.00%  Infer: 0.57 ms/batch
  [90/500]  Top-1: 55.00%  Top-5: 81.67%  Infer: 0.58 ms/batch
  [100/500]  Top-1: 58.57%  Top-5: 82.86%  Infer: 0.55 ms/batch
  [110/500]  Top-1: 56.25%  Top-5: 78.75%  Infer: 0.53 ms/batch
  [120/500]  Top-1: 51.11%  Top-5: 77.78%  Infer: 0.53 ms/batch
  [130/500]  Top-1: 49.00%  Top-5: 74.00%  Infer: 0.52 ms/batch
  [140/500]  Top-1: 46.36%  Top-5: 70.91%  Infer: 0.52 ms/batch
  [150/500]  Top-1: 45.83%  Top-5: 69.17%  Infer: 0.52 ms/batch
  [160/500]  Top-1: 42.31%  Top-5: 66.92%  Infer: 0.51 ms/batch
  [170/500]  Top-1: 40.00%  Top-5: 65.00%  Infer: 0.50 ms/batch
  [180/500]  Top-1: 37.33%  Top-5: 61.33%  Infer: 0.50 ms/batch
  [190/500]  Top-1: 35.00%  Top-5: 58.75%  Infer: 0.50 ms/batch
  [200/500]  Top-1: 34.12%  Top-5: 57.06%  Infer: 0.50 ms/batch
  [210/500]  Top-1: 34.44%  Top-5: 56.67%  Infer: 0.50 ms/batch
  [220/500]  Top-1: 33.68%  Top-5: 56.84%  Infer: 0.50 ms/batch
  [230/500]  Top-1: 33.00%  Top-5: 57.50%  Infer: 0.50 ms/batch
  [240/500]  Top-1: 32.86%  Top-5: 58.10%  Infer: 0.50 ms/batch
  [250/500]  Top-1: 32.27%  Top-5: 58.64%  Infer: 0.50 ms/batch
  [260/500]  Top-1: 32.17%  Top-5: 57.83%  Infer: 0.49 ms/batch
  [270/500]  Top-1: 32.08%  Top-5: 57.92%  Infer: 0.50 ms/batch
  [280/500]  Top-1: 31.20%  Top-5: 56.40%  Infer: 0.49 ms/batch
  [290/500]  Top-1: 30.77%  Top-5: 55.77%  Infer: 0.49 ms/batch
  [300/500]  Top-1: 30.37%  Top-5: 55.19%  Infer: 0.49 ms/batch
  [310/500]  Top-1: 30.36%  Top-5: 55.36%  Infer: 0.49 ms/batch
  [320/500]  Top-1: 30.00%  Top-5: 55.17%  Infer: 0.50 ms/batch
  [330/500]  Top-1: 29.00%  Top-5: 55.33%  Infer: 0.50 ms/batch
  [340/500]  Top-1: 29.35%  Top-5: 55.81%  Infer: 0.50 ms/batch
  [350/500]  Top-1: 29.38%  Top-5: 55.00%  Infer: 0.50 ms/batch
  [360/500]  Top-1: 30.00%  Top-5: 56.36%  Infer: 0.50 ms/batch
  [370/500]  Top-1: 31.18%  Top-5: 57.35%  Infer: 0.50 ms/batch
  [380/500]  Top-1: 32.29%  Top-5: 58.57%  Infer: 0.50 ms/batch
  [390/500]  Top-1: 34.17%  Top-5: 59.72%  Infer: 0.50 ms/batch
  [400/500]  Top-1: 34.59%  Top-5: 60.81%  Infer: 0.49 ms/batch
  [410/500]  Top-1: 34.21%  Top-5: 60.53%  Infer: 0.49 ms/batch
  [420/500]  Top-1: 33.59%  Top-5: 60.26%  Infer: 0.49 ms/batch
  [430/500]  Top-1: 33.00%  Top-5: 60.00%  Infer: 0.50 ms/batch
  [440/500]  Top-1: 32.68%  Top-5: 59.76%  Infer: 0.50 ms/batch
  [450/500]  Top-1: 31.90%  Top-5: 59.52%  Infer: 0.50 ms/batch
  [460/500]  Top-1: 32.33%  Top-5: 60.00%  Infer: 0.49 ms/batch
  [470/500]  Top-1: 32.50%  Top-5: 60.00%  Infer: 0.49 ms/batch
  [480/500]  Top-1: 33.11%  Top-5: 60.44%  Infer: 0.49 ms/batch
  [490/500]  Top-1: 33.48%  Top-5: 60.43%  Infer: 0.49 ms/batch
  [500/500]  Top-1: 33.62%  Top-5: 60.64%  Infer: 0.49 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_tensorrt_fp16_in1b_cuda_bs1/result.json
    b=1: top1=33.62%  top5=60.64%  infer=0.49ms

  seed_2:
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_2.onnx
[runner] Step 2/3 — Building TRT engine (precision=fp16) ...
[trt_builder] Building engine | precision=fp16 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_2/resnet18_tensorrt_fp16_in8b_cuda_bs1.engine (22.8 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_2/resnet18_tensorrt_fp16_in8b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [50/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.57 ms/batch
  [60/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.58 ms/batch
  [70/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.57 ms/batch
  [80/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.57 ms/batch
  [90/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.55 ms/batch
  [100/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.54 ms/batch
  [110/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.53 ms/batch
  [120/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [130/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [140/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [150/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [160/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [170/500]  Top-1: 99.29%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [180/500]  Top-1: 98.67%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [190/500]  Top-1: 98.75%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [200/500]  Top-1: 98.82%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [210/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [220/500]  Top-1: 98.95%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [230/500]  Top-1: 99.00%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [240/500]  Top-1: 99.05%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [250/500]  Top-1: 99.09%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [260/500]  Top-1: 99.13%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [270/500]  Top-1: 99.17%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [280/500]  Top-1: 99.20%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [290/500]  Top-1: 98.46%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [300/500]  Top-1: 98.52%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [310/500]  Top-1: 98.21%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [320/500]  Top-1: 98.28%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [330/500]  Top-1: 98.33%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [340/500]  Top-1: 98.39%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [350/500]  Top-1: 98.44%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [360/500]  Top-1: 98.48%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [370/500]  Top-1: 98.53%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [380/500]  Top-1: 98.57%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [390/500]  Top-1: 98.61%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [400/500]  Top-1: 98.65%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [410/500]  Top-1: 98.16%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [420/500]  Top-1: 97.95%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [430/500]  Top-1: 97.75%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [440/500]  Top-1: 97.80%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [450/500]  Top-1: 97.86%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [460/500]  Top-1: 97.91%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [470/500]  Top-1: 97.95%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [480/500]  Top-1: 98.00%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [490/500]  Top-1: 98.04%  Top-5: 100.00%  Infer: 0.49 ms/batch

## INT8

In [6]:
int8_records = run_precision_sweep("int8")

  seed_1:
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_1_int8_qdq.onnx
[runner] Step 2/3 — Building TRT engine (precision=int8) ...
[trt_builder] Building engine | precision=int8 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_int8_in8b_cuda_bs1.engine (11.7 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_int8_in8b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.72 ms/batch
  [50/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.90 ms/batch
  [60/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [70/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.78 ms/batch
  [80/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.78 ms/batch
  [90/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.78 ms/batch
  [100/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.77 ms/batch
  [110/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.74 ms/batch
  [120/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.75 ms/batch
  [130/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.73 ms/batch
  [140/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [150/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [160/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [170/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [180/500]  Top-1: 99.33%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [190/500]  Top-1: 99.38%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [200/500]  Top-1: 99.41%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [210/500]  Top-1: 99.44%  Top-5: 100.00%  Infer: 0.64 ms/batch
  [220/500]  Top-1: 99.47%  Top-5: 100.00%  Infer: 0.64 ms/batch
  [230/500]  Top-1: 99.50%  Top-5: 100.00%  Infer: 0.63 ms/batch
  [240/500]  Top-1: 99.52%  Top-5: 100.00%  Infer: 0.62 ms/batch
  [250/500]  Top-1: 99.55%  Top-5: 100.00%  Infer: 0.62 ms/batch
  [260/500]  Top-1: 99.57%  Top-5: 100.00%  Infer: 0.62 ms/batch
  [270/500]  Top-1: 99.58%  Top-5: 100.00%  Infer: 0.63 ms/batch
  [280/500]  Top-1: 99.60%  Top-5: 100.00%  Infer: 0.63 ms/batch
  [290/500]  Top-1: 99.62%  Top-5: 100.00%  Infer: 0.63 ms/batch
  [300/500]  Top-1: 99.63%  Top-5: 100.00%  Infer: 0.63 ms/batch
  [310/500]  Top-1: 99.64%  Top-5: 100.00%  Infer: 0.62 ms/batch
  [320/500]  Top-1: 99.66%  Top-5: 100.00%  Infer: 0.63 ms/batch
  [330/500]  Top-1: 99.67%  Top-5: 100.00%  Infer: 0.62 ms/batch
  [340/500]  Top-1: 99.68%  Top-5: 100.00%  Infer: 0.63 ms/batch
  [350/500]  Top-1: 99.69%  Top-5: 100.00%  Infer: 0.63 ms/batch
  [360/500]  Top-1: 99.70%  Top-5: 100.00%  Infer: 0.63 ms/batch
  [370/500]  Top-1: 99.71%  Top-5: 100.00%  Infer: 0.62 ms/batch
  [380/500]  Top-1: 99.71%  Top-5: 100.00%  Infer: 0.62 ms/batch
  [390/500]  Top-1: 99.72%  Top-5: 100.00%  Infer: 0.62 ms/batch
  [400/500]  Top-1: 99.73%  Top-5: 100.00%  Infer: 0.62 ms/batch
  [410/500]  Top-1: 99.47%  Top-5: 100.00%  Infer: 0.62 ms/batch
  [420/500]  Top-1: 98.97%  Top-5: 100.00%  Infer: 0.61 ms/batch
  [430/500]  Top-1: 99.00%  Top-5: 100.00%  Infer: 0.61 ms/batch
  [440/500]  Top-1: 98.78%  Top-5: 100.00%  Infer: 0.60 ms/batch
  [450/500]  Top-1: 98.81%  Top-5: 100.00%  Infer: 0.60 ms/batch
  [460/500]  Top-1: 98.84%  Top-5: 100.00%  Infer: 0.60 ms/batch
  [470/500]  Top-1: 98.86%  Top-5: 100.00%  Infer: 0.61 ms/batch
  [480/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.60 ms/batch
  [490/500]  Top-1: 98.91%  Top-5: 100.00%  Infer: 0.60 ms/batch
  [500/500]  Top-1: 98.94%  Top-5: 100.00%  Infer: 0.60 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_tensorrt_int8_in8b_cuda_bs1/result.json
    b=8: top1=98.94%  top5=100.00%  infer=0.60ms
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_1_int8_qdq.onnx
[runner] Step 2/3 — Building TRT engine (precision=int8) ...
[trt_builder] Building engine | precision=int8 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_int8_in4b_cuda_bs1.engine (11.8 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_int8_in4b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 90.00%  Top-5: 100.00%  Infer: 0.84 ms/batch
  [50/500]  Top-1: 95.00%  Top-5: 100.00%  Infer: 0.81 ms/batch
  [60/500]  Top-1: 96.67%  Top-5: 100.00%  Infer: 0.77 ms/batch
  [70/500]  Top-1: 97.50%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [80/500]  Top-1: 98.00%  Top-5: 100.00%  Infer: 0.74 ms/batch
  [90/500]  Top-1: 98.33%  Top-5: 100.00%  Infer: 0.72 ms/batch
  [100/500]  Top-1: 98.57%  Top-5: 100.00%  Infer: 0.78 ms/batch
  [110/500]  Top-1: 98.75%  Top-5: 100.00%  Infer: 0.77 ms/batch
  [120/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.77 ms/batch
  [130/500]  Top-1: 99.00%  Top-5: 100.00%  Infer: 0.77 ms/batch
  [140/500]  Top-1: 99.09%  Top-5: 100.00%  Infer: 0.76 ms/batch
  [150/500]  Top-1: 99.17%  Top-5: 100.00%  Infer: 0.75 ms/batch
  [160/500]  Top-1: 98.46%  Top-5: 100.00%  Infer: 0.74 ms/batch
  [170/500]  Top-1: 98.57%  Top-5: 100.00%  Infer: 0.74 ms/batch
  [180/500]  Top-1: 98.00%  Top-5: 100.00%  Infer: 0.74 ms/batch
  [190/500]  Top-1: 98.12%  Top-5: 100.00%  Infer: 0.73 ms/batch
  [200/500]  Top-1: 98.24%  Top-5: 100.00%  Infer: 0.72 ms/batch
  [210/500]  Top-1: 97.78%  Top-5: 100.00%  Infer: 0.72 ms/batch
  [220/500]  Top-1: 97.37%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [230/500]  Top-1: 97.50%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [240/500]  Top-1: 97.62%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [250/500]  Top-1: 97.73%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [260/500]  Top-1: 97.83%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [270/500]  Top-1: 97.08%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [280/500]  Top-1: 96.80%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [290/500]  Top-1: 96.54%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [300/500]  Top-1: 96.30%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [310/500]  Top-1: 96.07%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [320/500]  Top-1: 96.21%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [330/500]  Top-1: 96.33%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [340/500]  Top-1: 96.45%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [350/500]  Top-1: 96.56%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [360/500]  Top-1: 96.67%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [370/500]  Top-1: 96.76%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [380/500]  Top-1: 96.57%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [390/500]  Top-1: 96.67%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [400/500]  Top-1: 96.76%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [410/500]  Top-1: 96.58%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [420/500]  Top-1: 96.41%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [430/500]  Top-1: 96.50%  Top-5: 100.00%  Infer: 0.72 ms/batch
  [440/500]  Top-1: 96.34%  Top-5: 100.00%  Infer: 0.72 ms/batch
  [450/500]  Top-1: 96.43%  Top-5: 100.00%  Infer: 0.72 ms/batch
  [460/500]  Top-1: 96.51%  Top-5: 100.00%  Infer: 0.72 ms/batch
  [470/500]  Top-1: 96.59%  Top-5: 100.00%  Infer: 0.73 ms/batch
  [480/500]  Top-1: 96.67%  Top-5: 100.00%  Infer: 0.72 ms/batch
  [490/500]  Top-1: 96.74%  Top-5: 100.00%  Infer: 0.72 ms/batch
  [500/500]  Top-1: 96.81%  Top-5: 100.00%  Infer: 0.73 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_tensorrt_int8_in4b_cuda_bs1/result.json
    b=4: top1=96.81%  top5=100.00%  infer=0.73ms
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_1_int8_qdq.onnx
[runner] Step 2/3 — Building TRT engine (precision=int8) ...
[trt_builder] Building engine | precision=int8 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_int8_in2b_cuda_bs1.engine (11.7 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_int8_in2b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 70.00%  Top-5: 70.00%  Infer: 0.92 ms/batch
  [50/500]  Top-1: 65.00%  Top-5: 80.00%  Infer: 0.90 ms/batch
  [60/500]  Top-1: 76.67%  Top-5: 86.67%  Infer: 0.86 ms/batch
  [70/500]  Top-1: 82.50%  Top-5: 90.00%  Infer: 0.88 ms/batch
  [80/500]  Top-1: 86.00%  Top-5: 92.00%  Infer: 0.88 ms/batch
  [90/500]  Top-1: 83.33%  Top-5: 93.33%  Infer: 0.86 ms/batch
  [100/500]  Top-1: 81.43%  Top-5: 94.29%  Infer: 0.87 ms/batch
  [110/500]  Top-1: 77.50%  Top-5: 92.50%  Infer: 0.86 ms/batch
  [120/500]  Top-1: 75.56%  Top-5: 90.00%  Infer: 0.85 ms/batch
  [130/500]  Top-1: 71.00%  Top-5: 90.00%  Infer: 0.85 ms/batch
  [140/500]  Top-1: 69.09%  Top-5: 89.09%  Infer: 0.85 ms/batch
  [150/500]  Top-1: 67.50%  Top-5: 88.33%  Infer: 0.83 ms/batch
  [160/500]  Top-1: 66.92%  Top-5: 87.69%  Infer: 0.82 ms/batch
  [170/500]  Top-1: 65.71%  Top-5: 87.86%  Infer: 0.81 ms/batch
  [180/500]  Top-1: 62.67%  Top-5: 85.33%  Infer: 0.80 ms/batch
  [190/500]  Top-1: 60.62%  Top-5: 83.75%  Infer: 0.81 ms/batch
  [200/500]  Top-1: 59.41%  Top-5: 82.94%  Infer: 0.80 ms/batch
  [210/500]  Top-1: 60.56%  Top-5: 83.33%  Infer: 0.80 ms/batch
  [220/500]  Top-1: 58.95%  Top-5: 83.16%  Infer: 0.78 ms/batch
  [230/500]  Top-1: 57.00%  Top-5: 84.00%  Infer: 0.78 ms/batch
  [240/500]  Top-1: 57.62%  Top-5: 84.76%  Infer: 0.77 ms/batch
  [250/500]  Top-1: 57.27%  Top-5: 84.55%  Infer: 0.77 ms/batch
  [260/500]  Top-1: 56.96%  Top-5: 83.48%  Infer: 0.76 ms/batch
  [270/500]  Top-1: 56.25%  Top-5: 82.50%  Infer: 0.77 ms/batch
  [280/500]  Top-1: 56.00%  Top-5: 82.00%  Infer: 0.77 ms/batch
  [290/500]  Top-1: 54.23%  Top-5: 81.15%  Infer: 0.76 ms/batch
  [300/500]  Top-1: 52.96%  Top-5: 79.63%  Infer: 0.76 ms/batch
  [310/500]  Top-1: 52.86%  Top-5: 79.29%  Infer: 0.76 ms/batch
  [320/500]  Top-1: 52.76%  Top-5: 78.62%  Infer: 0.76 ms/batch
  [330/500]  Top-1: 52.00%  Top-5: 78.33%  Infer: 0.76 ms/batch
  [340/500]  Top-1: 51.61%  Top-5: 78.06%  Infer: 0.76 ms/batch
  [350/500]  Top-1: 50.94%  Top-5: 77.50%  Infer: 0.76 ms/batch
  [360/500]  Top-1: 52.12%  Top-5: 78.18%  Infer: 0.76 ms/batch
  [370/500]  Top-1: 53.53%  Top-5: 78.82%  Infer: 0.75 ms/batch
  [380/500]  Top-1: 54.86%  Top-5: 79.43%  Infer: 0.75 ms/batch
  [390/500]  Top-1: 55.56%  Top-5: 80.00%  Infer: 0.75 ms/batch
  [400/500]  Top-1: 56.22%  Top-5: 80.27%  Infer: 0.75 ms/batch
  [410/500]  Top-1: 55.79%  Top-5: 80.79%  Infer: 0.75 ms/batch
  [420/500]  Top-1: 55.64%  Top-5: 80.51%  Infer: 0.75 ms/batch
  [430/500]  Top-1: 55.25%  Top-5: 79.75%  Infer: 0.75 ms/batch
  [440/500]  Top-1: 55.12%  Top-5: 79.76%  Infer: 0.75 ms/batch
  [450/500]  Top-1: 55.00%  Top-5: 79.52%  Infer: 0.75 ms/batch
  [460/500]  Top-1: 55.35%  Top-5: 79.53%  Infer: 0.75 ms/batch
  [470/500]  Top-1: 55.68%  Top-5: 79.77%  Infer: 0.75 ms/batch
  [480/500]  Top-1: 56.22%  Top-5: 79.78%  Infer: 0.75 ms/batch
  [490/500]  Top-1: 56.52%  Top-5: 80.22%  Infer: 0.75 ms/batch
  [500/500]  Top-1: 57.02%  Top-5: 80.21%  Infer: 0.75 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_tensorrt_int8_in2b_cuda_bs1/result.json
    b=2: top1=57.02%  top5=80.21%  infer=0.75ms
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_1_int8_qdq.onnx
[runner] Step 2/3 — Building TRT engine (precision=int8) ...
[trt_builder] Building engine | precision=int8 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_int8_in1b_cuda_bs1.engine (11.7 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_int8_in1b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 20.00%  Top-5: 50.00%  Infer: 0.67 ms/batch
  [50/500]  Top-1: 30.00%  Top-5: 50.00%  Infer: 0.71 ms/batch
  [60/500]  Top-1: 36.67%  Top-5: 63.33%  Infer: 0.68 ms/batch
  [70/500]  Top-1: 42.50%  Top-5: 70.00%  Infer: 0.68 ms/batch
  [80/500]  Top-1: 52.00%  Top-5: 76.00%  Infer: 0.68 ms/batch
  [90/500]  Top-1: 53.33%  Top-5: 76.67%  Infer: 0.67 ms/batch
  [100/500]  Top-1: 52.86%  Top-5: 78.57%  Infer: 0.68 ms/batch
  [110/500]  Top-1: 50.00%  Top-5: 75.00%  Infer: 0.66 ms/batch
  [120/500]  Top-1: 44.44%  Top-5: 74.44%  Infer: 0.67 ms/batch
  [130/500]  Top-1: 43.00%  Top-5: 71.00%  Infer: 0.67 ms/batch
  [140/500]  Top-1: 40.00%  Top-5: 68.18%  Infer: 0.66 ms/batch
  [150/500]  Top-1: 39.17%  Top-5: 66.67%  Infer: 0.66 ms/batch
  [160/500]  Top-1: 36.15%  Top-5: 65.38%  Infer: 0.66 ms/batch
  [170/500]  Top-1: 34.29%  Top-5: 64.29%  Infer: 0.66 ms/batch
  [180/500]  Top-1: 32.00%  Top-5: 60.67%  Infer: 0.65 ms/batch
  [190/500]  Top-1: 30.00%  Top-5: 58.75%  Infer: 0.65 ms/batch
  [200/500]  Top-1: 30.00%  Top-5: 57.06%  Infer: 0.64 ms/batch
  [210/500]  Top-1: 30.56%  Top-5: 57.22%  Infer: 0.65 ms/batch
  [220/500]  Top-1: 29.47%  Top-5: 56.84%  Infer: 0.65 ms/batch
  [230/500]  Top-1: 29.00%  Top-5: 58.00%  Infer: 0.65 ms/batch
  [240/500]  Top-1: 29.05%  Top-5: 59.05%  Infer: 0.65 ms/batch
  [250/500]  Top-1: 29.55%  Top-5: 59.55%  Infer: 0.64 ms/batch
  [260/500]  Top-1: 29.57%  Top-5: 59.57%  Infer: 0.64 ms/batch
  [270/500]  Top-1: 29.58%  Top-5: 59.58%  Infer: 0.64 ms/batch
  [280/500]  Top-1: 28.80%  Top-5: 58.40%  Infer: 0.64 ms/batch
  [290/500]  Top-1: 28.46%  Top-5: 58.08%  Infer: 0.64 ms/batch
  [300/500]  Top-1: 28.52%  Top-5: 57.78%  Infer: 0.65 ms/batch
  [310/500]  Top-1: 28.93%  Top-5: 57.86%  Infer: 0.65 ms/batch
  [320/500]  Top-1: 28.62%  Top-5: 57.59%  Infer: 0.65 ms/batch
  [330/500]  Top-1: 28.33%  Top-5: 57.00%  Infer: 0.65 ms/batch
  [340/500]  Top-1: 29.03%  Top-5: 57.42%  Infer: 0.65 ms/batch
  [350/500]  Top-1: 28.75%  Top-5: 56.56%  Infer: 0.65 ms/batch
  [360/500]  Top-1: 29.39%  Top-5: 57.27%  Infer: 0.65 ms/batch
  [370/500]  Top-1: 30.59%  Top-5: 58.24%  Infer: 0.65 ms/batch
  [380/500]  Top-1: 31.71%  Top-5: 59.43%  Infer: 0.65 ms/batch
  [390/500]  Top-1: 32.50%  Top-5: 60.28%  Infer: 0.66 ms/batch
  [400/500]  Top-1: 32.97%  Top-5: 61.35%  Infer: 0.66 ms/batch
  [410/500]  Top-1: 32.37%  Top-5: 60.53%  Infer: 0.66 ms/batch
  [420/500]  Top-1: 31.79%  Top-5: 60.00%  Infer: 0.66 ms/batch
  [430/500]  Top-1: 31.25%  Top-5: 59.00%  Infer: 0.66 ms/batch
  [440/500]  Top-1: 30.73%  Top-5: 58.29%  Infer: 0.66 ms/batch
  [450/500]  Top-1: 30.24%  Top-5: 57.62%  Infer: 0.66 ms/batch
  [460/500]  Top-1: 30.47%  Top-5: 57.44%  Infer: 0.67 ms/batch
  [470/500]  Top-1: 30.68%  Top-5: 57.73%  Infer: 0.67 ms/batch
  [480/500]  Top-1: 31.33%  Top-5: 58.22%  Infer: 0.67 ms/batch
  [490/500]  Top-1: 31.30%  Top-5: 58.26%  Infer: 0.67 ms/batch
  [500/500]  Top-1: 31.91%  Top-5: 58.51%  Infer: 0.67 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_tensorrt_int8_in1b_cuda_bs1/result.json
    b=1: top1=31.91%  top5=58.51%  infer=0.67ms

  seed_2:
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_2_int8_qdq.onnx
[runner] Step 2/3 — Building TRT engine (precision=int8) ...
[trt_builder] Building engine | precision=int8 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_2/resnet18_tensorrt_int8_in8b_cuda_bs1.engine (11.8 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_2/resnet18_tensorrt_int8_in8b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.99 ms/batch
  [50/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 1.06 ms/batch
  [60/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.99 ms/batch
  [70/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.99 ms/batch
  [80/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.92 ms/batch
  [90/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.88 ms/batch
  [100/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.85 ms/batch
  [110/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.86 ms/batch
  [120/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.84 ms/batch
  [130/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.82 ms/batch
  [140/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.81 ms/batch
  [150/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.81 ms/batch
  [160/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [170/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [180/500]  Top-1: 99.33%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [190/500]  Top-1: 99.38%  Top-5: 100.00%  Infer: 0.81 ms/batch
  [200/500]  Top-1: 99.41%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [210/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [220/500]  Top-1: 98.95%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [230/500]  Top-1: 99.00%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [240/500]  Top-1: 99.05%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [250/500]  Top-1: 99.09%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [260/500]  Top-1: 99.13%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [270/500]  Top-1: 99.17%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [280/500]  Top-1: 99.20%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [290/500]  Top-1: 98.46%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [300/500]  Top-1: 98.52%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [310/500]  Top-1: 98.57%  Top-5: 100.00%  Infer: 0.79 ms/batch
  [320/500]  Top-1: 98.62%  Top-5: 100.00%  Infer: 0.78 ms/batch
  [330/500]  Top-1: 98.67%  Top-5: 100.00%  Infer: 0.78 ms/batch
  [340/500]  Top-1: 98.71%  Top-5: 100.00%  Infer: 0.78 ms/batch
  [350/500]  Top-1: 98.75%  Top-5: 100.00%  Infer: 0.78 ms/batch
  [360/500]  Top-1: 98.79%  Top-5: 100.00%  Infer: 0.78 ms/batch
  [370/500]  Top-1: 98.82%  Top-5: 100.00%  Infer: 0.78 ms/batch
  [380/500]  Top-1: 98.86%  Top-5: 100.00%  Infer: 0.77 ms/batch
  [390/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.77 ms/batch
  [400/500]  Top-1: 98.92%  Top-5: 100.00%  Infer: 0.77 ms/batch
  [410/500]  Top-1: 98.42%  Top-5: 100.00%  Infer: 0.77 ms/batch
  [420/500]  Top-1: 98.21%  Top-5: 100.00%  Infer: 0.77 ms/batch
  [430/500]  Top-1: 98.00%  Top-5: 100.00%  Infer: 0.77 ms/batch
  [440/500]  Top-1: 98.05%  Top-5: 100.00%  Infer: 0.77 ms/batch
  [450/500]  Top-1: 98.10%  Top-5: 100.00%  Infer: 0.77 ms/batch
  [460/500]  Top-1: 98.14%  Top-5: 100.00%  Infer: 0.77 ms/batch
  [470/500]  Top-1: 98.18%  Top-5: 100.00%  Infer: 0.77 ms/batch
  [480/500]  Top-1: 98.22%  Top-5: 100.00%  Infer: 0.76 ms/batch

## FP8

In [7]:
fp8_records = run_precision_sweep("fp8")

  seed_1:
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_1_fp8_qdq.onnx
[runner] Step 2/3 — Building TRT engine (precision=fp8) ...
[trt_builder] Building engine | precision=fp8 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp8_in8b_cuda_bs1.engine (11.7 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp8_in8b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 1.01 ms/batch
  [50/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.89 ms/batch
  [60/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.91 ms/batch
  [70/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.86 ms/batch
  [80/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.85 ms/batch
  [90/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.82 ms/batch
  [100/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.83 ms/batch
  [110/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.82 ms/batch
  [120/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.84 ms/batch
  [130/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.83 ms/batch
  [140/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [150/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.78 ms/batch
  [160/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.77 ms/batch
  [170/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.77 ms/batch
  [180/500]  Top-1: 99.33%  Top-5: 100.00%  Infer: 0.76 ms/batch
  [190/500]  Top-1: 99.38%  Top-5: 100.00%  Infer: 0.76 ms/batch
  [200/500]  Top-1: 99.41%  Top-5: 100.00%  Infer: 0.76 ms/batch
  [210/500]  Top-1: 99.44%  Top-5: 100.00%  Infer: 0.75 ms/batch
  [220/500]  Top-1: 99.47%  Top-5: 100.00%  Infer: 0.75 ms/batch
  [230/500]  Top-1: 99.50%  Top-5: 100.00%  Infer: 0.74 ms/batch
  [240/500]  Top-1: 99.52%  Top-5: 100.00%  Infer: 0.73 ms/batch
  [250/500]  Top-1: 99.55%  Top-5: 100.00%  Infer: 0.72 ms/batch
  [260/500]  Top-1: 99.57%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [270/500]  Top-1: 99.58%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [280/500]  Top-1: 99.60%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [290/500]  Top-1: 99.62%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [300/500]  Top-1: 99.63%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [310/500]  Top-1: 99.64%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [320/500]  Top-1: 99.66%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [330/500]  Top-1: 99.67%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [340/500]  Top-1: 99.68%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [350/500]  Top-1: 99.69%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [360/500]  Top-1: 99.70%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [370/500]  Top-1: 99.71%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [380/500]  Top-1: 99.71%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [390/500]  Top-1: 99.72%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [400/500]  Top-1: 99.73%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [410/500]  Top-1: 99.47%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [420/500]  Top-1: 98.97%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [430/500]  Top-1: 99.00%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [440/500]  Top-1: 98.78%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [450/500]  Top-1: 98.81%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [460/500]  Top-1: 98.84%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [470/500]  Top-1: 98.86%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [480/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [490/500]  Top-1: 98.91%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [500/500]  Top-1: 98.94%  Top-5: 100.00%  Infer: 0.67 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_tensorrt_fp8_in8b_cuda_bs1/result.json
    b=8: top1=98.94%  top5=100.00%  infer=0.67ms
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_1_fp8_qdq.onnx
[runner] Step 2/3 — Building TRT engine (precision=fp8) ...
[trt_builder] Building engine | precision=fp8 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp8_in4b_cuda_bs1.engine (11.7 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp8_in4b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.99 ms/batch
  [50/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.97 ms/batch
  [60/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.88 ms/batch
  [70/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.81 ms/batch
  [80/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.78 ms/batch
  [90/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.74 ms/batch
  [100/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.73 ms/batch
  [110/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [120/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [130/500]  Top-1: 99.00%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [140/500]  Top-1: 99.09%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [150/500]  Top-1: 98.33%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [160/500]  Top-1: 98.46%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [170/500]  Top-1: 98.57%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [180/500]  Top-1: 98.00%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [190/500]  Top-1: 98.12%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [200/500]  Top-1: 98.24%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [210/500]  Top-1: 97.78%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [220/500]  Top-1: 97.37%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [230/500]  Top-1: 97.00%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [240/500]  Top-1: 97.14%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [250/500]  Top-1: 97.27%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [260/500]  Top-1: 97.39%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [270/500]  Top-1: 97.50%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [280/500]  Top-1: 97.20%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [290/500]  Top-1: 96.92%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [300/500]  Top-1: 96.67%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [310/500]  Top-1: 96.43%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [320/500]  Top-1: 96.55%  Top-5: 100.00%  Infer: 0.65 ms/batch
  [330/500]  Top-1: 96.67%  Top-5: 100.00%  Infer: 0.65 ms/batch
  [340/500]  Top-1: 96.77%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [350/500]  Top-1: 96.88%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [360/500]  Top-1: 96.97%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [370/500]  Top-1: 97.06%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [380/500]  Top-1: 97.14%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [390/500]  Top-1: 97.22%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [400/500]  Top-1: 97.30%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [410/500]  Top-1: 97.11%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [420/500]  Top-1: 96.92%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [430/500]  Top-1: 97.00%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [440/500]  Top-1: 96.83%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [450/500]  Top-1: 96.90%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [460/500]  Top-1: 96.98%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [470/500]  Top-1: 97.05%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [480/500]  Top-1: 97.11%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [490/500]  Top-1: 97.17%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [500/500]  Top-1: 97.23%  Top-5: 100.00%  Infer: 0.67 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_tensorrt_fp8_in4b_cuda_bs1/result.json
    b=4: top1=97.23%  top5=100.00%  infer=0.67ms
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_1_fp8_qdq.onnx
[runner] Step 2/3 — Building TRT engine (precision=fp8) ...
[trt_builder] Building engine | precision=fp8 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp8_in2b_cuda_bs1.engine (11.8 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp8_in2b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 60.00%  Top-5: 70.00%  Infer: 0.82 ms/batch
  [50/500]  Top-1: 60.00%  Top-5: 80.00%  Infer: 0.81 ms/batch
  [60/500]  Top-1: 73.33%  Top-5: 86.67%  Infer: 0.92 ms/batch
  [70/500]  Top-1: 80.00%  Top-5: 90.00%  Infer: 0.90 ms/batch
  [80/500]  Top-1: 84.00%  Top-5: 92.00%  Infer: 0.84 ms/batch
  [90/500]  Top-1: 83.33%  Top-5: 93.33%  Infer: 0.80 ms/batch
  [100/500]  Top-1: 82.86%  Top-5: 94.29%  Infer: 0.78 ms/batch
  [110/500]  Top-1: 78.75%  Top-5: 91.25%  Infer: 0.76 ms/batch
  [120/500]  Top-1: 76.67%  Top-5: 88.89%  Infer: 0.75 ms/batch
  [130/500]  Top-1: 72.00%  Top-5: 89.00%  Infer: 0.73 ms/batch
  [140/500]  Top-1: 70.00%  Top-5: 87.27%  Infer: 0.72 ms/batch
  [150/500]  Top-1: 68.33%  Top-5: 86.67%  Infer: 0.71 ms/batch
  [160/500]  Top-1: 67.69%  Top-5: 86.92%  Infer: 0.70 ms/batch
  [170/500]  Top-1: 66.43%  Top-5: 86.43%  Infer: 0.69 ms/batch
  [180/500]  Top-1: 63.33%  Top-5: 84.67%  Infer: 0.69 ms/batch
  [190/500]  Top-1: 62.50%  Top-5: 83.12%  Infer: 0.68 ms/batch
  [200/500]  Top-1: 61.76%  Top-5: 81.76%  Infer: 0.68 ms/batch
  [210/500]  Top-1: 62.78%  Top-5: 82.22%  Infer: 0.68 ms/batch
  [220/500]  Top-1: 61.58%  Top-5: 82.63%  Infer: 0.67 ms/batch
  [230/500]  Top-1: 59.50%  Top-5: 83.00%  Infer: 0.67 ms/batch
  [240/500]  Top-1: 60.00%  Top-5: 83.81%  Infer: 0.67 ms/batch
  [250/500]  Top-1: 59.55%  Top-5: 83.64%  Infer: 0.67 ms/batch
  [260/500]  Top-1: 58.26%  Top-5: 82.61%  Infer: 0.66 ms/batch
  [270/500]  Top-1: 57.08%  Top-5: 81.67%  Infer: 0.66 ms/batch
  [280/500]  Top-1: 56.40%  Top-5: 81.20%  Infer: 0.66 ms/batch
  [290/500]  Top-1: 55.00%  Top-5: 80.38%  Infer: 0.66 ms/batch
  [300/500]  Top-1: 53.70%  Top-5: 79.26%  Infer: 0.66 ms/batch
  [310/500]  Top-1: 53.57%  Top-5: 78.93%  Infer: 0.66 ms/batch
  [320/500]  Top-1: 53.45%  Top-5: 78.28%  Infer: 0.66 ms/batch
  [330/500]  Top-1: 52.67%  Top-5: 78.00%  Infer: 0.66 ms/batch
  [340/500]  Top-1: 52.26%  Top-5: 78.06%  Infer: 0.66 ms/batch
  [350/500]  Top-1: 51.56%  Top-5: 77.19%  Infer: 0.66 ms/batch
  [360/500]  Top-1: 52.73%  Top-5: 77.88%  Infer: 0.66 ms/batch
  [370/500]  Top-1: 54.12%  Top-5: 78.53%  Infer: 0.65 ms/batch
  [380/500]  Top-1: 55.43%  Top-5: 79.14%  Infer: 0.66 ms/batch
  [390/500]  Top-1: 56.39%  Top-5: 79.72%  Infer: 0.66 ms/batch
  [400/500]  Top-1: 56.76%  Top-5: 80.27%  Infer: 0.66 ms/batch
  [410/500]  Top-1: 57.11%  Top-5: 80.79%  Infer: 0.66 ms/batch
  [420/500]  Top-1: 56.92%  Top-5: 80.51%  Infer: 0.66 ms/batch
  [430/500]  Top-1: 56.50%  Top-5: 80.00%  Infer: 0.65 ms/batch
  [440/500]  Top-1: 56.34%  Top-5: 80.00%  Infer: 0.65 ms/batch
  [450/500]  Top-1: 56.19%  Top-5: 79.76%  Infer: 0.65 ms/batch
  [460/500]  Top-1: 56.51%  Top-5: 79.77%  Infer: 0.65 ms/batch
  [470/500]  Top-1: 56.82%  Top-5: 80.00%  Infer: 0.65 ms/batch
  [480/500]  Top-1: 57.33%  Top-5: 80.00%  Infer: 0.65 ms/batch
  [490/500]  Top-1: 57.83%  Top-5: 80.43%  Infer: 0.65 ms/batch
  [500/500]  Top-1: 58.30%  Top-5: 80.43%  Infer: 0.66 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_tensorrt_fp8_in2b_cuda_bs1/result.json
    b=2: top1=58.30%  top5=80.43%  infer=0.66ms
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_1_fp8_qdq.onnx
[runner] Step 2/3 — Building TRT engine (precision=fp8) ...
[trt_builder] Building engine | precision=fp8 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp8_in1b_cuda_bs1.engine (11.7 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_fp8_in1b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 30.00%  Top-5: 30.00%  Infer: 1.07 ms/batch
  [50/500]  Top-1: 30.00%  Top-5: 40.00%  Infer: 1.16 ms/batch
  [60/500]  Top-1: 33.33%  Top-5: 56.67%  Infer: 1.05 ms/batch
  [70/500]  Top-1: 42.50%  Top-5: 67.50%  Infer: 1.01 ms/batch
  [80/500]  Top-1: 54.00%  Top-5: 74.00%  Infer: 0.94 ms/batch
  [90/500]  Top-1: 55.00%  Top-5: 76.67%  Infer: 0.88 ms/batch
  [100/500]  Top-1: 58.57%  Top-5: 78.57%  Infer: 0.83 ms/batch
  [110/500]  Top-1: 56.25%  Top-5: 75.00%  Infer: 0.80 ms/batch
  [120/500]  Top-1: 51.11%  Top-5: 75.56%  Infer: 0.77 ms/batch
  [130/500]  Top-1: 49.00%  Top-5: 72.00%  Infer: 0.75 ms/batch
  [140/500]  Top-1: 46.36%  Top-5: 69.09%  Infer: 0.73 ms/batch
  [150/500]  Top-1: 45.83%  Top-5: 66.67%  Infer: 0.72 ms/batch
  [160/500]  Top-1: 42.31%  Top-5: 63.85%  Infer: 0.72 ms/batch
  [170/500]  Top-1: 40.00%  Top-5: 62.14%  Infer: 0.72 ms/batch
  [180/500]  Top-1: 37.33%  Top-5: 58.67%  Infer: 0.71 ms/batch
  [190/500]  Top-1: 35.00%  Top-5: 56.88%  Infer: 0.70 ms/batch
  [200/500]  Top-1: 34.12%  Top-5: 55.29%  Infer: 0.69 ms/batch
  [210/500]  Top-1: 34.44%  Top-5: 55.56%  Infer: 0.68 ms/batch
  [220/500]  Top-1: 33.68%  Top-5: 56.32%  Infer: 0.67 ms/batch
  [230/500]  Top-1: 33.00%  Top-5: 56.50%  Infer: 0.69 ms/batch
  [240/500]  Top-1: 32.38%  Top-5: 57.14%  Infer: 0.68 ms/batch
  [250/500]  Top-1: 32.27%  Top-5: 57.73%  Infer: 0.69 ms/batch
  [260/500]  Top-1: 32.17%  Top-5: 56.96%  Infer: 0.68 ms/batch
  [270/500]  Top-1: 32.08%  Top-5: 57.08%  Infer: 0.68 ms/batch
  [280/500]  Top-1: 31.20%  Top-5: 55.60%  Infer: 0.68 ms/batch
  [290/500]  Top-1: 30.77%  Top-5: 55.00%  Infer: 0.68 ms/batch
  [300/500]  Top-1: 30.37%  Top-5: 54.44%  Infer: 0.68 ms/batch
  [310/500]  Top-1: 30.36%  Top-5: 54.64%  Infer: 0.68 ms/batch
  [320/500]  Top-1: 30.00%  Top-5: 54.14%  Infer: 0.68 ms/batch
  [330/500]  Top-1: 29.00%  Top-5: 54.00%  Infer: 0.68 ms/batch
  [340/500]  Top-1: 28.71%  Top-5: 54.52%  Infer: 0.68 ms/batch
  [350/500]  Top-1: 28.44%  Top-5: 53.75%  Infer: 0.67 ms/batch
  [360/500]  Top-1: 29.09%  Top-5: 55.15%  Infer: 0.67 ms/batch
  [370/500]  Top-1: 30.29%  Top-5: 56.18%  Infer: 0.67 ms/batch
  [380/500]  Top-1: 31.71%  Top-5: 57.43%  Infer: 0.67 ms/batch
  [390/500]  Top-1: 33.33%  Top-5: 58.61%  Infer: 0.67 ms/batch
  [400/500]  Top-1: 34.05%  Top-5: 59.73%  Infer: 0.67 ms/batch
  [410/500]  Top-1: 33.68%  Top-5: 59.47%  Infer: 0.67 ms/batch
  [420/500]  Top-1: 33.08%  Top-5: 59.23%  Infer: 0.67 ms/batch
  [430/500]  Top-1: 32.50%  Top-5: 59.00%  Infer: 0.66 ms/batch
  [440/500]  Top-1: 32.20%  Top-5: 58.54%  Infer: 0.67 ms/batch
  [450/500]  Top-1: 31.43%  Top-5: 58.10%  Infer: 0.67 ms/batch
  [460/500]  Top-1: 31.63%  Top-5: 58.14%  Infer: 0.66 ms/batch
  [470/500]  Top-1: 31.82%  Top-5: 58.18%  Infer: 0.66 ms/batch
  [480/500]  Top-1: 32.44%  Top-5: 58.67%  Infer: 0.66 ms/batch
  [490/500]  Top-1: 32.61%  Top-5: 58.48%  Infer: 0.66 ms/batch
  [500/500]  Top-1: 32.77%  Top-5: 58.72%  Infer: 0.66 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_tensorrt_fp8_in1b_cuda_bs1/result.json
    b=1: top1=32.77%  top5=58.72%  infer=0.66ms

  seed_2:
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_2_fp8_qdq.onnx
[runner] Step 2/3 — Building TRT engine (precision=fp8) ...
[trt_builder] Building engine | precision=fp8 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_2/resnet18_tensorrt_fp8_in8b_cuda_bs1.engine (11.7 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_2/resnet18_tensorrt_fp8_in8b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.92 ms/batch
  [50/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.88 ms/batch
  [60/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.85 ms/batch
  [70/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.85 ms/batch
  [80/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.83 ms/batch
  [90/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.86 ms/batch
  [100/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.83 ms/batch
  [110/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.80 ms/batch
  [120/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.77 ms/batch
  [130/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.76 ms/batch
  [140/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.74 ms/batch
  [150/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.72 ms/batch
  [160/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.71 ms/batch
  [170/500]  Top-1: 99.29%  Top-5: 100.00%  Infer: 0.70 ms/batch
  [180/500]  Top-1: 98.67%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [190/500]  Top-1: 98.75%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [200/500]  Top-1: 98.82%  Top-5: 100.00%  Infer: 0.69 ms/batch
  [210/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [220/500]  Top-1: 98.95%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [230/500]  Top-1: 99.00%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [240/500]  Top-1: 99.05%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [250/500]  Top-1: 99.09%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [260/500]  Top-1: 99.13%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [270/500]  Top-1: 99.17%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [280/500]  Top-1: 99.20%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [290/500]  Top-1: 98.85%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [300/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [310/500]  Top-1: 98.57%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [320/500]  Top-1: 98.62%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [330/500]  Top-1: 98.67%  Top-5: 100.00%  Infer: 0.66 ms/batch
  [340/500]  Top-1: 98.71%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [350/500]  Top-1: 98.75%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [360/500]  Top-1: 98.79%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [370/500]  Top-1: 98.82%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [380/500]  Top-1: 98.86%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [390/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [400/500]  Top-1: 98.92%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [410/500]  Top-1: 98.42%  Top-5: 100.00%  Infer: 0.68 ms/batch
  [420/500]  Top-1: 98.21%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [430/500]  Top-1: 98.00%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [440/500]  Top-1: 98.05%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [450/500]  Top-1: 98.10%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [460/500]  Top-1: 98.14%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [470/500]  Top-1: 98.18%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [480/500]  Top-1: 98.22%  Top-5: 100.00%  Infer: 0.67 ms/batch
  [490/500]  Top-1: 98.26%  Top-5: 100.00%  Infer: 0.67 ms/batch

## INT4

In [8]:
int4_records = run_precision_sweep("int4")

  seed_1:
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_1_int4_qdq.onnx
[runner] Step 2/3 — Building TRT engine (precision=int4) ...
[trt_builder] Building engine | precision=int4 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_int4_in8b_cuda_bs1.engine (22.9 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_int4_in8b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [50/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [60/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [70/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.54 ms/batch
  [80/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.55 ms/batch
  [90/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.53 ms/batch
  [100/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [110/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [120/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [130/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [140/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [150/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [160/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [170/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [180/500]  Top-1: 99.33%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [190/500]  Top-1: 99.38%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [200/500]  Top-1: 99.41%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [210/500]  Top-1: 99.44%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [220/500]  Top-1: 99.47%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [230/500]  Top-1: 99.50%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [240/500]  Top-1: 99.52%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [250/500]  Top-1: 99.55%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [260/500]  Top-1: 99.57%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [270/500]  Top-1: 99.58%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [280/500]  Top-1: 99.60%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [290/500]  Top-1: 99.62%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [300/500]  Top-1: 99.63%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [310/500]  Top-1: 99.64%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [320/500]  Top-1: 99.66%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [330/500]  Top-1: 99.67%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [340/500]  Top-1: 99.68%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [350/500]  Top-1: 99.69%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [360/500]  Top-1: 99.70%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [370/500]  Top-1: 99.71%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [380/500]  Top-1: 99.71%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [390/500]  Top-1: 99.72%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [400/500]  Top-1: 99.73%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [410/500]  Top-1: 99.47%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [420/500]  Top-1: 98.97%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [430/500]  Top-1: 98.75%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [440/500]  Top-1: 98.54%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [450/500]  Top-1: 98.57%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [460/500]  Top-1: 98.60%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [470/500]  Top-1: 98.64%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [480/500]  Top-1: 98.67%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [490/500]  Top-1: 98.70%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [500/500]  Top-1: 98.72%  Top-5: 100.00%  Infer: 0.50 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_tensorrt_int4_in8b_cuda_bs1/result.json
    b=8: top1=98.72%  top5=100.00%  infer=0.50ms
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_1_int4_qdq.onnx
[runner] Step 2/3 — Building TRT engine (precision=int4) ...
[trt_builder] Building engine | precision=int4 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_int4_in4b_cuda_bs1.engine (22.9 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_int4_in4b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 90.00%  Top-5: 100.00%  Infer: 0.60 ms/batch
  [50/500]  Top-1: 95.00%  Top-5: 100.00%  Infer: 0.54 ms/batch
  [60/500]  Top-1: 96.67%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [70/500]  Top-1: 97.50%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [80/500]  Top-1: 98.00%  Top-5: 100.00%  Infer: 0.50 ms/batch
  [90/500]  Top-1: 98.33%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [100/500]  Top-1: 98.57%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [110/500]  Top-1: 98.75%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [120/500]  Top-1: 97.78%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [130/500]  Top-1: 98.00%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [140/500]  Top-1: 98.18%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [150/500]  Top-1: 97.50%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [160/500]  Top-1: 97.69%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [170/500]  Top-1: 97.86%  Top-5: 100.00%  Infer: 0.47 ms/batch
  [180/500]  Top-1: 97.33%  Top-5: 100.00%  Infer: 0.47 ms/batch
  [190/500]  Top-1: 97.50%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [200/500]  Top-1: 97.65%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [210/500]  Top-1: 97.22%  Top-5: 100.00%  Infer: 0.47 ms/batch
  [220/500]  Top-1: 96.84%  Top-5: 100.00%  Infer: 0.47 ms/batch
  [230/500]  Top-1: 97.00%  Top-5: 100.00%  Infer: 0.47 ms/batch
  [240/500]  Top-1: 97.14%  Top-5: 100.00%  Infer: 0.47 ms/batch
  [250/500]  Top-1: 97.27%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [260/500]  Top-1: 96.96%  Top-5: 100.00%  Infer: 0.47 ms/batch
  [270/500]  Top-1: 96.25%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [280/500]  Top-1: 96.00%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [290/500]  Top-1: 95.77%  Top-5: 100.00%  Infer: 0.47 ms/batch
  [300/500]  Top-1: 95.19%  Top-5: 100.00%  Infer: 0.47 ms/batch
  [310/500]  Top-1: 95.00%  Top-5: 100.00%  Infer: 0.47 ms/batch
  [320/500]  Top-1: 95.17%  Top-5: 100.00%  Infer: 0.47 ms/batch
  [330/500]  Top-1: 95.33%  Top-5: 100.00%  Infer: 0.47 ms/batch
  [340/500]  Top-1: 95.48%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [350/500]  Top-1: 95.62%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [360/500]  Top-1: 95.76%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [370/500]  Top-1: 95.88%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [380/500]  Top-1: 96.00%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [390/500]  Top-1: 96.11%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [400/500]  Top-1: 96.22%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [410/500]  Top-1: 96.05%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [420/500]  Top-1: 95.64%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [430/500]  Top-1: 95.50%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [440/500]  Top-1: 95.37%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [450/500]  Top-1: 95.48%  Top-5: 100.00%  Infer: 0.48 ms/batch
  [460/500]  Top-1: 95.58%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [470/500]  Top-1: 95.68%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [480/500]  Top-1: 95.78%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [490/500]  Top-1: 95.87%  Top-5: 100.00%  Infer: 0.49 ms/batch
  [500/500]  Top-1: 95.96%  Top-5: 100.00%  Infer: 0.49 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_tensorrt_int4_in4b_cuda_bs1/result.json
    b=4: top1=95.96%  top5=100.00%  infer=0.49ms
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_1_int4_qdq.onnx
[runner] Step 2/3 — Building TRT engine (precision=int4) ...
[trt_builder] Building engine | precision=int4 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_int4_in2b_cuda_bs1.engine (22.9 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_int4_in2b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 70.00%  Top-5: 70.00%  Infer: 0.48 ms/batch
  [50/500]  Top-1: 70.00%  Top-5: 80.00%  Infer: 0.54 ms/batch
  [60/500]  Top-1: 76.67%  Top-5: 86.67%  Infer: 0.50 ms/batch
  [70/500]  Top-1: 80.00%  Top-5: 90.00%  Infer: 0.52 ms/batch
  [80/500]  Top-1: 84.00%  Top-5: 92.00%  Infer: 0.51 ms/batch
  [90/500]  Top-1: 81.67%  Top-5: 93.33%  Infer: 0.48 ms/batch
  [100/500]  Top-1: 80.00%  Top-5: 94.29%  Infer: 0.49 ms/batch
  [110/500]  Top-1: 76.25%  Top-5: 90.00%  Infer: 0.49 ms/batch
  [120/500]  Top-1: 74.44%  Top-5: 87.78%  Infer: 0.49 ms/batch
  [130/500]  Top-1: 70.00%  Top-5: 88.00%  Infer: 0.49 ms/batch
  [140/500]  Top-1: 68.18%  Top-5: 86.36%  Infer: 0.48 ms/batch
  [150/500]  Top-1: 66.67%  Top-5: 85.00%  Infer: 0.49 ms/batch
  [160/500]  Top-1: 65.38%  Top-5: 85.38%  Infer: 0.49 ms/batch
  [170/500]  Top-1: 64.29%  Top-5: 85.00%  Infer: 0.49 ms/batch
  [180/500]  Top-1: 61.33%  Top-5: 82.00%  Infer: 0.49 ms/batch
  [190/500]  Top-1: 60.00%  Top-5: 81.25%  Infer: 0.49 ms/batch
  [200/500]  Top-1: 59.41%  Top-5: 80.59%  Infer: 0.49 ms/batch
  [210/500]  Top-1: 60.56%  Top-5: 81.11%  Infer: 0.48 ms/batch
  [220/500]  Top-1: 58.95%  Top-5: 81.58%  Infer: 0.48 ms/batch
  [230/500]  Top-1: 57.50%  Top-5: 82.50%  Infer: 0.48 ms/batch
  [240/500]  Top-1: 58.10%  Top-5: 83.33%  Infer: 0.48 ms/batch
  [250/500]  Top-1: 57.27%  Top-5: 83.18%  Infer: 0.48 ms/batch
  [260/500]  Top-1: 55.65%  Top-5: 82.17%  Infer: 0.48 ms/batch
  [270/500]  Top-1: 54.58%  Top-5: 81.25%  Infer: 0.48 ms/batch
  [280/500]  Top-1: 54.00%  Top-5: 80.40%  Infer: 0.48 ms/batch
  [290/500]  Top-1: 52.31%  Top-5: 79.62%  Infer: 0.48 ms/batch
  [300/500]  Top-1: 51.11%  Top-5: 78.52%  Infer: 0.49 ms/batch
  [310/500]  Top-1: 51.07%  Top-5: 78.93%  Infer: 0.48 ms/batch
  [320/500]  Top-1: 51.03%  Top-5: 78.28%  Infer: 0.48 ms/batch
  [330/500]  Top-1: 50.33%  Top-5: 78.00%  Infer: 0.48 ms/batch
  [340/500]  Top-1: 50.00%  Top-5: 78.06%  Infer: 0.48 ms/batch
  [350/500]  Top-1: 49.38%  Top-5: 77.50%  Infer: 0.48 ms/batch
  [360/500]  Top-1: 50.61%  Top-5: 78.18%  Infer: 0.47 ms/batch
  [370/500]  Top-1: 52.06%  Top-5: 78.82%  Infer: 0.47 ms/batch
  [380/500]  Top-1: 53.43%  Top-5: 79.43%  Infer: 0.47 ms/batch
  [390/500]  Top-1: 54.17%  Top-5: 80.00%  Infer: 0.47 ms/batch
  [400/500]  Top-1: 54.59%  Top-5: 80.00%  Infer: 0.47 ms/batch
  [410/500]  Top-1: 53.68%  Top-5: 80.53%  Infer: 0.47 ms/batch
  [420/500]  Top-1: 53.08%  Top-5: 80.26%  Infer: 0.47 ms/batch
  [430/500]  Top-1: 52.75%  Top-5: 79.50%  Infer: 0.47 ms/batch
  [440/500]  Top-1: 52.44%  Top-5: 79.51%  Infer: 0.47 ms/batch
  [450/500]  Top-1: 52.14%  Top-5: 79.05%  Infer: 0.47 ms/batch
  [460/500]  Top-1: 52.56%  Top-5: 79.30%  Infer: 0.47 ms/batch
  [470/500]  Top-1: 52.95%  Top-5: 79.55%  Infer: 0.47 ms/batch
  [480/500]  Top-1: 53.56%  Top-5: 79.56%  Infer: 0.47 ms/batch
  [490/500]  Top-1: 54.13%  Top-5: 80.00%  Infer: 0.47 ms/batch
  [500/500]  Top-1: 54.68%  Top-5: 80.00%  Infer: 0.47 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_tensorrt_int4_in2b_cuda_bs1/result.json
    b=2: top1=54.68%  top5=80.00%  infer=0.47ms
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_1_int4_qdq.onnx
[runner] Step 2/3 — Building TRT engine (precision=int4) ...
[trt_builder] Building engine | precision=int4 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_int4_in1b_cuda_bs1.engine (22.9 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_1/resnet18_tensorrt_int4_in1b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 40.00%  Top-5: 60.00%  Infer: 0.47 ms/batch
  [50/500]  Top-1: 35.00%  Top-5: 55.00%  Infer: 0.46 ms/batch
  [60/500]  Top-1: 40.00%  Top-5: 66.67%  Infer: 0.54 ms/batch
  [70/500]  Top-1: 42.50%  Top-5: 72.50%  Infer: 0.52 ms/batch
  [80/500]  Top-1: 50.00%  Top-5: 78.00%  Infer: 0.52 ms/batch
  [90/500]  Top-1: 51.67%  Top-5: 78.33%  Infer: 0.52 ms/batch
  [100/500]  Top-1: 55.71%  Top-5: 80.00%  Infer: 0.52 ms/batch
  [110/500]  Top-1: 53.75%  Top-5: 76.25%  Infer: 0.52 ms/batch
  [120/500]  Top-1: 47.78%  Top-5: 74.44%  Infer: 0.51 ms/batch
  [130/500]  Top-1: 46.00%  Top-5: 70.00%  Infer: 0.50 ms/batch
  [140/500]  Top-1: 43.64%  Top-5: 67.27%  Infer: 0.49 ms/batch
  [150/500]  Top-1: 42.50%  Top-5: 65.00%  Infer: 0.49 ms/batch
  [160/500]  Top-1: 39.23%  Top-5: 63.08%  Infer: 0.50 ms/batch
  [170/500]  Top-1: 37.14%  Top-5: 61.43%  Infer: 0.50 ms/batch
  [180/500]  Top-1: 34.67%  Top-5: 57.33%  Infer: 0.50 ms/batch
  [190/500]  Top-1: 32.50%  Top-5: 55.00%  Infer: 0.50 ms/batch
  [200/500]  Top-1: 31.76%  Top-5: 53.53%  Infer: 0.50 ms/batch
  [210/500]  Top-1: 32.22%  Top-5: 53.33%  Infer: 0.50 ms/batch
  [220/500]  Top-1: 31.58%  Top-5: 53.16%  Infer: 0.50 ms/batch
  [230/500]  Top-1: 31.00%  Top-5: 53.00%  Infer: 0.49 ms/batch
  [240/500]  Top-1: 30.48%  Top-5: 53.33%  Infer: 0.49 ms/batch
  [250/500]  Top-1: 30.00%  Top-5: 54.09%  Infer: 0.49 ms/batch
  [260/500]  Top-1: 30.00%  Top-5: 53.04%  Infer: 0.49 ms/batch
  [270/500]  Top-1: 29.17%  Top-5: 53.33%  Infer: 0.49 ms/batch
  [280/500]  Top-1: 28.40%  Top-5: 52.00%  Infer: 0.49 ms/batch
  [290/500]  Top-1: 28.08%  Top-5: 50.77%  Infer: 0.50 ms/batch
  [300/500]  Top-1: 27.78%  Top-5: 50.37%  Infer: 0.50 ms/batch
  [310/500]  Top-1: 27.86%  Top-5: 50.71%  Infer: 0.50 ms/batch
  [320/500]  Top-1: 27.59%  Top-5: 50.69%  Infer: 0.50 ms/batch
  [330/500]  Top-1: 27.33%  Top-5: 51.00%  Infer: 0.50 ms/batch
  [340/500]  Top-1: 27.74%  Top-5: 51.61%  Infer: 0.50 ms/batch
  [350/500]  Top-1: 27.81%  Top-5: 50.94%  Infer: 0.50 ms/batch
  [360/500]  Top-1: 28.79%  Top-5: 52.12%  Infer: 0.50 ms/batch
  [370/500]  Top-1: 30.29%  Top-5: 52.94%  Infer: 0.50 ms/batch
  [380/500]  Top-1: 31.43%  Top-5: 54.29%  Infer: 0.50 ms/batch
  [390/500]  Top-1: 33.06%  Top-5: 55.56%  Infer: 0.50 ms/batch
  [400/500]  Top-1: 34.05%  Top-5: 56.76%  Infer: 0.50 ms/batch
  [410/500]  Top-1: 33.42%  Top-5: 56.58%  Infer: 0.50 ms/batch
  [420/500]  Top-1: 32.56%  Top-5: 56.41%  Infer: 0.50 ms/batch
  [430/500]  Top-1: 32.00%  Top-5: 55.50%  Infer: 0.50 ms/batch
  [440/500]  Top-1: 31.46%  Top-5: 55.12%  Infer: 0.50 ms/batch
  [450/500]  Top-1: 30.71%  Top-5: 54.52%  Infer: 0.50 ms/batch
  [460/500]  Top-1: 31.16%  Top-5: 54.88%  Infer: 0.50 ms/batch
  [470/500]  Top-1: 31.36%  Top-5: 55.00%  Infer: 0.50 ms/batch
  [480/500]  Top-1: 32.00%  Top-5: 55.56%  Infer: 0.50 ms/batch
  [490/500]  Top-1: 32.17%  Top-5: 55.65%  Infer: 0.50 ms/batch
  [500/500]  Top-1: 32.55%  Top-5: 55.96%  Infer: 0.50 ms/batch
[runner] Results saved: ../runs/val_infer/seed_1/resnet18_tensorrt_int4_in1b_cuda_bs1/result.json
    b=1: top1=32.55%  top5=55.96%  infer=0.50ms

  seed_2:
[runner] Step 1/3 — ONNX exists, skipping: /home/pf4636/code/resnet/quantized_resnets/onnx/resnet_2_int4_qdq.onnx
[runner] Step 2/3 — Building TRT engine (precision=int4) ...
[trt_builder] Building engine | precision=int4 | batch=1 | workspace=2048 MiB
[trt_builder] Engine saved: /home/pf4636/code/resnet/quantized_resnets/engines/seed_2/resnet18_tensorrt_int4_in8b_cuda_bs1.engine (23.0 MB)
[runner] Step 3/3 — Running TRT inference ...
[data] Train: 124,395  Holdout-Val: 5,000  (num_classes=100, val_per_class=50, seed=42)
[trt_infer] Engine: /home/pf4636/code/resnet/quantized_resnets/engines/seed_2/resnet18_tensorrt_int4_in8b_cuda_bs1.engine
[trt_infer] Input: 'images'  Output: 'logits'  Dynamic batch: False
[trt_infer] Evaluating 500 batches (first 30 are warmup) ...
[trt_infer] --- Warmup complete (30 batches) — starting metric collection ---
  [40/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.58 ms/batch
  [50/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.57 ms/batch
  [60/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.54 ms/batch
  [70/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.54 ms/batch
  [80/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [90/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [100/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [110/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [120/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [130/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.53 ms/batch
  [140/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.53 ms/batch
  [150/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [160/500]  Top-1: 100.00%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [170/500]  Top-1: 99.29%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [180/500]  Top-1: 98.67%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [190/500]  Top-1: 98.75%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [200/500]  Top-1: 98.82%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [210/500]  Top-1: 98.89%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [220/500]  Top-1: 98.95%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [230/500]  Top-1: 99.00%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [240/500]  Top-1: 99.05%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [250/500]  Top-1: 99.09%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [260/500]  Top-1: 99.13%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [270/500]  Top-1: 99.17%  Top-5: 100.00%  Infer: 0.53 ms/batch
  [280/500]  Top-1: 99.20%  Top-5: 100.00%  Infer: 0.53 ms/batch
  [290/500]  Top-1: 98.46%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [300/500]  Top-1: 98.52%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [310/500]  Top-1: 98.21%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [320/500]  Top-1: 98.28%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [330/500]  Top-1: 98.33%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [340/500]  Top-1: 98.39%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [350/500]  Top-1: 98.44%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [360/500]  Top-1: 98.48%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [370/500]  Top-1: 98.53%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [380/500]  Top-1: 98.57%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [390/500]  Top-1: 98.61%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [400/500]  Top-1: 98.65%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [410/500]  Top-1: 98.16%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [420/500]  Top-1: 97.95%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [430/500]  Top-1: 97.75%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [440/500]  Top-1: 97.80%  Top-5: 100.00%  Infer: 0.51 ms/batch
  [450/500]  Top-1: 97.86%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [460/500]  Top-1: 97.91%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [470/500]  Top-1: 97.95%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [480/500]  Top-1: 98.00%  Top-5: 100.00%  Infer: 0.52 ms/batch
  [490/500]  Top-1: 98.04%  Top-5: 100.00%  Infer: 0.52 ms/batch

## All Results (per seed)

In [9]:
all_rows = []
for seed in SEEDS:
    runs = load_runs(f"../runs/val_infer/{seed}", status="ok")
    for r in flatten_runs(runs):
        r["seed"] = seed
        all_rows.append(r)

df = pd.DataFrame(all_rows)
df_trt = df[df["cfg.backend"] == "tensorrt"]

display_cols = [
    "seed", "cfg.model_precision", "cfg.input_quant_bits",
    "res.top1_acc", "res.top5_acc", "res.infer_ms_avg", "res.throughput_infer_sps",
]
df_trt[display_cols].sort_values(
    ["seed", "cfg.model_precision", "cfg.input_quant_bits"], ascending=[True, True, False]
).reset_index(drop=True)

,seed,cfg.model_precision,cfg.input_quant_bits,res.top1_acc,res.top5_acc,res.infer_ms_avg,res.throughput_infer_sps
0,seed_1,fp16,8,98.936,100.000,0.488,2048.288
1,seed_1,fp16,4,97.234,100.000,0.504,1984.305
2,seed_1,fp16,2,58.936,82.128,0.491,2035.892
3,seed_1,fp16,1,33.617,60.638,0.495,2021.576
4,seed_1,fp32,8,98.936,100.000,0.953,1049.026
5,seed_1,fp32,4,97.234,100.000,0.951,1051.343
6,seed_1,fp32,2,58.936,82.128,0.955,1047.381
7,seed_1,fp32,1,33.617,60.638,0.946,1056.946
8,seed_1,fp8,8,98.936,100.000,0.667,1500.255
9,seed_1,fp8,4,97.234,100.000,0.672,1488.840
10,seed_1,fp8,2,58.298,80.426,0.656,1524.979
11,seed_1,fp8,1,32.766,58.723,0.663,1507.909
12,seed_1,int4,8,98.723,100.000,0.496,2016.253
13,seed_1,int4,4,95.957,100.000,0.488,2050.412
14,seed_1,int4,2,54.681,80.000,0.472,2118.269
15,seed_1,int4,1,32.553,55.957,0.497,2012.055
16,seed_1,int8,8,98.936,100.000,0.604,1655.942
17,seed_1,int8,4,96.809,100.000,0.728,1373.074
18,seed_1,int8,2,57.021,80.213,0.749,1334.264
19,seed_1,int8,1,31.915,58.511,0.668,1497.817
20,seed_2,fp16,8,98.085,100.000,0.489,2043.258
21,seed_2,fp16,4,96.596,100.000,0.485,2062.367
22,seed_2,fp16,2,57.447,80.638,0.515,1940.884
23,seed_2,fp16,1,32.340,56.809,0.499,2004.992
24,seed_2,fp32,8,98.085,100.000,0.940,1063.691
25,seed_2,fp32,4,96.596,100.000,0.969,1032.041
26,seed_2,fp32,2,57.447,80.638,0.905,1105.099
27,seed_2,fp32,1,32.340,56.809,0.938,1065.872
28,seed_2,fp8,8,98.298,100.000,0.668,1497.384
29,seed_2,fp8,4,96.383,100.000,0.672,1488.798
30,seed_2,fp8,2,56.809,81.064,0.660,1514.188
31,seed_2,fp8,1,31.064,57.021,0.679,1473.268
32,seed_2,int4,8,98.085,100.000,0.521,1920.434
33,seed_2,int4,4,96.596,100.000,0.483,2070.837
34,seed_2,int4,2,55.745,81.064,0.488,2050.002
35,seed_2,int4,1,29.574,56.809,0.508,1969.676
36,seed_2,int8,8,98.298,100.000,0.762,1312.937
37,seed_2,int8,4,96.809,100.000,0.702,1425.306
38,seed_2,int8,2,56.596,81.702,0.744,1343.619
39,seed_2,int8,1,32.340,58.511,0.691,1446.639
40,seed_42,fp16,8,86.170,98.723,0.457,2187.281
41,seed_42,fp16,4,85.745,97.872,0.481,2078.029
42,seed_42,fp16,2,51.702,78.298,0.485,2063.485
43,seed_42,fp16,1,30.638,59.149,0.518,1929.368
44,seed_42,fp32,8,86.383,98.723,1.088,919.489
45,seed_42,fp32,4,85.745,97.872,1.071,933.817
46,seed_42,fp32,2,51.489,78.298,1.024,976.740
47,seed_42,fp32,1,30.851,58.936,1.007,992.963
48,seed_42,fp8,8,85.532,98.723,0.651,1535.084
49,seed_42,fp8,4,84.681,97.447,0.661,1512.015
50,seed_42,fp8,2,50.426,78.298,0.680,1471.421
51,seed_42,fp8,1,31.064,57.234,0.652,1534.654
52,seed_42,int4,8,84.468,98.085,0.476,2102.338
53,seed_42,int4,4,85.532,97.021,0.499,2005.121
54,seed_42,int4,2,49.787,77.872,0.468,2137.033
55,seed_42,int4,1,29.574,56.596,0.505,1980.803
56,seed_42,int8,8,85.532,98.298,0.680,1471.651
57,seed_42,int8,4,84.681,97.021,0.724,1380.584
58,seed_42,int8,2,51.702,77.872,0.656,1525.429
59,seed_42,int8,1,31.489,58.511,0.721,1386.974

## Averaged Results (across seeds)

In [14]:
avg_df = df_trt.groupby(["cfg.backend", "cfg.model_precision", "cfg.input_quant_bits"]).agg(
    top1_mean=("res.top1_acc", "mean"),
    top1_std=("res.top1_acc", "std"),
    top5_mean=("res.top5_acc", "mean"),
    top5_std=("res.top5_acc", "std"),
    infer_ms_mean=("res.infer_ms_avg", "mean"),
    infer_ms_std=("res.infer_ms_avg", "std"),
    throughput_mean=("res.throughput_infer_sps", "mean"),
).round(3).reset_index()

avg_df = avg_df.sort_values(["cfg.model_precision", "cfg.input_quant_bits"], ascending=[True, False]).reset_index(drop=True)
avg_df

,cfg.backend,cfg.model_precision,cfg.input_quant_bits,top1_mean,top1_std,top5_mean,top5_std,infer_ms_mean,infer_ms_std,throughput_mean
0,tensorrt,fp16,8,94.397,7.137,99.574,0.737,0.478,0.018,2092.942
1,tensorrt,fp16,4,93.191,6.457,99.291,1.228,0.490,0.012,2041.567
2,tensorrt,fp16,2,56.028,3.820,80.355,1.931,0.497,0.016,2013.420
3,tensorrt,fp16,1,32.199,1.494,58.865,1.931,0.504,0.013,1985.312
4,tensorrt,fp32,8,94.468,7.015,99.574,0.737,0.994,0.082,1010.735
5,tensorrt,fp32,4,93.191,6.457,99.291,1.228,0.997,0.065,1005.734
6,tensorrt,fp32,2,55.957,3.940,80.355,1.931,0.961,0.060,1043.073
7,tensorrt,fp32,1,32.270,1.384,58.794,1.919,0.964,0.038,1038.594
8,tensorrt,fp8,8,94.255,7.561,99.574,0.737,0.662,0.009,1510.908
9,tensorrt,fp8,4,92.766,7.015,99.149,1.474,0.668,0.006,1496.551
10,tensorrt,fp8,2,55.177,4.182,79.929,1.448,0.665,0.013,1503.529
11,tensorrt,fp8,1,31.631,0.983,57.660,0.927,0.665,0.014,1505.277
12,tensorrt,int4,8,93.759,8.052,99.362,1.106,0.497,0.023,2013.008
13,tensorrt,int4,4,92.695,6.212,99.007,1.720,0.490,0.008,2042.123
14,tensorrt,int4,2,53.404,3.177,79.645,1.625,0.476,0.010,2101.768
15,tensorrt,int4,1,30.567,1.720,56.454,0.443,0.503,0.006,1987.511
16,tensorrt,int8,8,94.255,7.561,99.433,0.983,0.682,0.079,1480.177
17,tensorrt,int8,4,92.766,7.002,99.007,1.720,0.718,0.014,1392.988
18,tensorrt,int8,2,55.106,2.956,79.929,1.931,0.716,0.053,1401.104
19,tensorrt,int8,1,31.915,0.426,58.511,0.000,0.693,0.027,1443.810

In [15]:
avg_df[["cfg.model_precision", "cfg.input_quant_bits",
        "top1_mean", "top1_std", "top5_mean", "top5_std",
        "infer_ms_mean", "infer_ms_std"]].assign(
    top1=lambda d: d.apply(lambda r: f"{r['top1_mean']:.2f} ± {r['top1_std']:.2f}", axis=1),
    top5=lambda d: d.apply(lambda r: f"{r['top5_mean']:.2f} ± {r['top5_std']:.2f}", axis=1),
    infer_ms=lambda d: d.apply(lambda r: f"{r['infer_ms_mean']:.3f} ± {r['infer_ms_std']:.3f}", axis=1),
)[["cfg.model_precision", "cfg.input_quant_bits", "top1", "top5", "infer_ms"]]

,cfg.model_precision,cfg.input_quant_bits,top1,top5,infer_ms
0,fp16,8,94.40 ± 7.14,99.57 ± 0.74,0.478 ± 0.018
1,fp16,4,93.19 ± 6.46,99.29 ± 1.23,0.490 ± 0.012
2,fp16,2,56.03 ± 3.82,80.36 ± 1.93,0.497 ± 0.016
3,fp16,1,32.20 ± 1.49,58.87 ± 1.93,0.504 ± 0.013
4,fp32,8,94.47 ± 7.01,99.57 ± 0.74,0.994 ± 0.082
5,fp32,4,93.19 ± 6.46,99.29 ± 1.23,0.997 ± 0.065
6,fp32,2,55.96 ± 3.94,80.36 ± 1.93,0.961 ± 0.060
7,fp32,1,32.27 ± 1.38,58.79 ± 1.92,0.964 ± 0.038
8,fp8,8,94.25 ± 7.56,99.57 ± 0.74,0.662 ± 0.009
9,fp8,4,92.77 ± 7.01,99.15 ± 1.47,0.668 ± 0.006
10,fp8,2,55.18 ± 4.18,79.93 ± 1.45,0.665 ± 0.013
11,fp8,1,31.63 ± 0.98,57.66 ± 0.93,0.665 ± 0.014
12,int4,8,93.76 ± 8.05,99.36 ± 1.11,0.497 ± 0.023
13,int4,4,92.69 ± 6.21,99.01 ± 1.72,0.490 ± 0.008
14,int4,2,53.40 ± 3.18,79.64 ± 1.62,0.476 ± 0.010
15,int4,1,30.57 ± 1.72,56.45 ± 0.44,0.503 ± 0.006
16,int8,8,94.25 ± 7.56,99.43 ± 0.98,0.682 ± 0.079
17,int8,4,92.77 ± 7.00,99.01 ± 1.72,0.718 ± 0.014
18,int8,2,55.11 ± 2.96,79.93 ± 1.93,0.716 ± 0.053
19,int8,1,31.91 ± 0.43,58.51 ± 0.00,0.693 ± 0.027

In [16]:
out_path = PROJECT_ROOT / "results" / "tensorrt_avg_results.json"
avg_df.to_json(out_path, orient="records", indent=2)
print(f"Saved to {out_path}")

Saved to /home/pf4636/code/resnet/quantized_resnets/results/tensorrt_avg_results.json