## QAT Test-Set Inference using PyTorch (Multi-Seed)

Evaluate QAT checkpoints on the **test set** (ImageNet val split).

- **INT8**: `checkpoints/qat/int8_in{8,4,2,1}b/seed_{1,2,42}/`
- **INT4**: `checkpoints/qat/int4_in{8,4,2,1}b/seed_{1,2,42}/`

Only runs for which training has completed (checkpoint exists) are evaluated.

Results saved to `resultsv2/test_runs/`.

In [1]:
# ── Config ────────────────────────────────────────────────────────
SPLIT = "val"
TEST_IMAGENET = "/home/pf4636/imagenet2"
OUTPUT_ROOT = "/home/pf4636/code/resnet/quantized_resnets/runs/test/qat"
SKIP_EXISTING = True

In [2]:
from pathlib import Path
import sys

PROJECT_ROOT = Path("..").resolve()
PYFILES = PROJECT_ROOT / "pyfiles"
QAT_MOD = PYFILES / "qat_modelopt"
for p in [str(PYFILES), str(QAT_MOD)]:
    if p not in sys.path:
        sys.path.insert(0, p)

In [3]:
import json
import time
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
import modelopt.torch.opt as mto

from dataclasses import replace
from torch.utils.data import DataLoader

from src.config import ExperimentConfig, set_seed
from src.data import build_imagenet_dataset
from src.eval import evaluate
from quantize import get_model, restore_modelopt_state

pd.set_option("display.max_columns", 200)
pd.set_option("display.float_format", "{:.3f}".format)
print("torch:", torch.__version__, "| cuda:", torch.cuda.is_available())

torch: 2.10.0+cu130 | cuda: True

In [4]:
QAT_CKPT_ROOT = PROJECT_ROOT / ".checkpoints" / "qat"
FP32_CKPT_ROOT = PROJECT_ROOT / ".checkpoints"
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

QAT_CONFIGS = [
    {"qat_precision": "int8", "input_bits": [8, 4, 2, 1]},
    {"qat_precision": "int4", "input_bits": [8, 4, 2, 1]},
]

checkpoints = {}
skipped = []
for qcfg in QAT_CONFIGS:
    prec = qcfg["qat_precision"]
    for bits in qcfg["input_bits"]:
        run_name = f"{prec}_in{bits}b"
        run_dir = QAT_CKPT_ROOT / run_name
        if not run_dir.exists():
            skipped.append(f"{prec}/in{bits}b (no dir)")
            continue
        for seed_dir in sorted(run_dir.iterdir()):
            if not seed_dir.is_dir() or not seed_dir.name.startswith("seed_"):
                continue
            weights = seed_dir / "qat_modelopt_best.pth"
            mostate = seed_dir / "qat_modelopt_best_mostate.pt"
            seed_num = int(seed_dir.name.split("_")[1])
            fp32_ckpt = FP32_CKPT_ROOT / f"fp32_{bits}bit" / seed_dir.name / "best.pth"
            if not weights.exists() or not mostate.exists() or not fp32_ckpt.exists():
                skipped.append(f"{prec}/in{bits}b/{seed_dir.name}")
                continue
            checkpoints[(prec, bits, seed_dir.name)] = {
                "weights": weights,
                "mostate": mostate,
                "fp32_ckpt": fp32_ckpt,
                "seed": seed_num,
            }

print(f"QAT checkpoints found: {len(checkpoints)}")
for (prec, bits, seed), paths in checkpoints.items():
    print(f"  {prec} / in{bits}b / {seed}")
if skipped:
    print(f"\nSkipped (not complete): {', '.join(skipped)}")
print(f"Test set: {TEST_IMAGENET}")

QAT checkpoints found: 24
  int8 / in8b / seed_1
  int8 / in8b / seed_2
  int8 / in8b / seed_42
  int8 / in4b / seed_1
  int8 / in4b / seed_2
  int8 / in4b / seed_42
  int8 / in2b / seed_1
  int8 / in2b / seed_2
  int8 / in2b / seed_42
  int8 / in1b / seed_1
  int8 / in1b / seed_2
  int8 / in1b / seed_42
  int4 / in8b / seed_1
  int4 / in8b / seed_2
  int4 / in8b / seed_42
  int4 / in4b / seed_1
  int4 / in4b / seed_2
  int4 / in4b / seed_42
  int4 / in2b / seed_1
  int4 / in2b / seed_2
  int4 / in2b / seed_42
  int4 / in1b / seed_1
  int4 / in1b / seed_2
  int4 / in1b / seed_42
Test set: /home/pf4636/imagenet2

In [5]:
def load_qat_model(prec: str, bits: int, seed_name: str) -> nn.Module:
    paths = checkpoints[(prec, bits, seed_name)]
    model = get_model(str(paths["fp32_ckpt"]), num_classes=100)
    restore_modelopt_state(model, str(paths["mostate"]))
    ckpt = torch.load(paths["weights"], map_location="cpu")
    state = ckpt["model"] if "model" in ckpt else ckpt
    model.load_state_dict(state)
    model = model.to(DEVICE)
    model.eval()
    return model

def build_test_loader(cfg: ExperimentConfig) -> DataLoader:
    test_cfg = replace(cfg, imagenet_path=TEST_IMAGENET)
    dataset = build_imagenet_dataset(test_cfg, split=SPLIT)
    return DataLoader(
        dataset,
        batch_size=cfg.batch_size,
        shuffle=False,
        num_workers=cfg.num_workers,
        pin_memory=True,
        drop_last=True,
    )

## QAT Evaluation (All Seeds)

In [6]:
OUT_DIR = Path(OUTPUT_ROOT).resolve()
OUT_DIR.mkdir(parents=True, exist_ok=True)

all_records = []
criterion = nn.CrossEntropyLoss()

for (prec, bits, seed_name), paths in checkpoints.items():
    seed_num = paths["seed"]
    run_id = f"torch_qat_{prec}_b{bits}_cuda"
    result_path = OUT_DIR / seed_name / run_id / "result.json"

    if SKIP_EXISTING and result_path.exists():
        print(f"  {prec}/in{bits}b/{seed_name}: exists, skipping")
        with open(result_path) as f:
            all_records.append(json.load(f))
        continue

    print(f"\n--- QAT {prec.upper()}, input_bits={bits}, {seed_name} ---")
    cfg = ExperimentConfig(
        backend="pytorch",
        device="cuda",
        batch_size=1,
        seed=seed_num,
        num_eval_batches=None,
        input_quant_bits=bits,
        model_precision="fp32",
    )
    set_seed(cfg)

    model = load_qat_model(prec, bits, seed_name)
    test_loader = build_test_loader(cfg)

    t0 = time.perf_counter()
    tracker = evaluate(model, test_loader, cfg, criterion=criterion)
    elapsed = time.perf_counter() - t0

    r = tracker.summary()
    print(f"  top1={r['top1_acc']:.2f}%  top5={r['top5_acc']:.2f}%  infer={r['infer_ms_avg']:.2f}ms")

    payload = {
        "status": "ok",
        "run_id": run_id,
        "system": cfg.stamp(),
        "config": cfg.to_dict(),
        "config_extra": {
            "qat_precision": prec,
            "input_quant_bits": bits,
            "seed": seed_num,
        },
        "results": r,
        "error": None,
        "total_eval_time_sec": round(elapsed, 3),
    }

    result_path.parent.mkdir(parents=True, exist_ok=True)
    with open(result_path, "w") as f:
        json.dump(payload, f, indent=2, sort_keys=True)

    all_records.append(payload)
    del model
    torch.cuda.empty_cache()

print(f"\n{len(all_records)} runs complete.")

--- QAT INT8, input_bits=8, seed_1 ---
Inserted 107 quantizers

/home/pf4636/code/resnet/quantized_resnets/.venv/lib/python3.12/site-packages/modelopt/torch/quantization/nn/modules/quant_module.py:59: UserWarning: Could not identify the device for TensorQuantizer states of maxpool. Please move the model to the right device now. This can be done by calling `model.to(device)`.
  warnings.warn(
/home/pf4636/code/resnet/quantized_resnets/.venv/lib/python3.12/site-packages/modelopt/torch/quantization/nn/modules/quant_module.py:59: UserWarning: Could not identify the device for TensorQuantizer states of pool. Please move the model to the right device now. This can be done by calling `model.to(device)`.
  warnings.warn(

[data] Filtered to 5000 samples across 100 classes.
Evaluating on 5000 batches (first 30 are warmup)...
Loading extension modelopt_cuda_ext...
Loaded extension modelopt_cuda_ext in 0.4 seconds
  --- Warmup complete (30 batches) — starting metric collection ---
  Batch [40/5000] Top-1: 90.00% | Top-5: 100.00% | Infer: 8.50 ms/batch
  Batch [50/5000] Top-1: 95.00% | Top-5: 100.00% | Infer: 9.76 ms/batch
  Batch [60/5000] Top-1: 93.33% | Top-5: 100.00% | Infer: 9.49 ms/batch
  Batch [70/5000] Top-1: 90.00% | Top-5: 100.00% | Infer: 9.77 ms/batch
  Batch [80/5000] Top-1: 88.00% | Top-5: 100.00% | Infer: 9.80 ms/batch
  Batch [90/5000] Top-1: 90.00% | Top-5: 100.00% | Infer: 9.69 ms/batch
  Batch [100/5000] Top-1: 90.00% | Top-5: 100.00% | Infer: 9.68 ms/batch
  Batch [110/5000] Top-1: 90.00% | Top-5: 100.00% | Infer: 9.60 ms/batch
  Batch [120/5000] Top-1: 88.89% | Top-5: 98.89% | Infer: 9.56 ms/batch
  Batch [130/5000] Top-1: 90.00% | Top-5: 99.00% | Infer: 9.36 ms/batch
  Batch [140/5000] Top-1: 90.00% | Top-5: 99.09% | Infer: 9.21 ms/batch
  Batch [150/5000] Top-1: 88.33% | Top-5: 98.33% | Infer: 9.13 ms/batch
  Batch [160/5000] Top-1: 87.69% | Top-5: 98.46% | Infer: 9.03 ms/batch
  Batch [170/5000] Top-1: 85.00% | Top-5: 98.57% | Infer: 8.90 ms/batch
  Batch [180/5000] Top-1: 85.33% | Top-5: 98.00% | Infer: 8.85 ms/batch
  Batch [190/5000] Top-1: 84.38% | Top-5: 97.50% | Infer: 8.77 ms/batch
  Batch [200/5000] Top-1: 84.12% | Top-5: 97.06% | Infer: 8.74 ms/batch
  Batch [210/5000] Top-1: 83.89% | Top-5: 96.67% | Infer: 8.70 ms/batch
  Batch [220/5000] Top-1: 84.21% | Top-5: 96.32% | Infer: 8.67 ms/batch
  Batch [230/5000] Top-1: 84.00% | Top-5: 96.50% | Infer: 8.61 ms/batch
  Batch [240/5000] Top-1: 83.33% | Top-5: 96.67% | Infer: 8.56 ms/batch
  Batch [250/5000] Top-1: 83.18% | Top-5: 96.82% | Infer: 8.54 ms/batch
  Batch [260/5000] Top-1: 83.04% | Top-5: 96.96% | Infer: 8.50 ms/batch
  Batch [270/5000] Top-1: 81.67% | Top-5: 96.67% | Infer: 8.50 ms/batch
  Batch [280/5000] Top-1: 81.60% | Top-5: 96.80% | Infer: 8.47 ms/batch
  Batch [290/5000] Top-1: 81.92% | Top-5: 96.92% | Infer: 8.45 ms/batch
  Batch [300/5000] Top-1: 81.48% | Top-5: 96.67% | Infer: 8.45 ms/batch
  Batch [310/5000] Top-1: 80.71% | Top-5: 96.43% | Infer: 8.42 ms/batch
  Batch [320/5000] Top-1: 80.69% | Top-5: 96.55% | Infer: 8.41 ms/batch
  Batch [330/5000] Top-1: 81.00% | Top-5: 96.67% | Infer: 8.38 ms/batch
  Batch [340/5000] Top-1: 80.32% | Top-5: 96.77% | Infer: 8.38 ms/batch
  Batch [350/5000] Top-1: 80.31% | Top-5: 96.56% | Infer: 8.39 ms/batch
  Batch [360/5000] Top-1: 79.70% | Top-5: 96.67% | Infer: 8.42 ms/batch
  Batch [370/5000] Top-1: 78.82% | Top-5: 96.18% | Infer: 8.39 ms/batch
  Batch [380/5000] Top-1: 78.86% | Top-5: 96.29% | Infer: 8.39 ms/batch
  Batch [390/5000] Top-1: 79.17% | Top-5: 96.11% | Infer: 8.39 ms/batch
  Batch [400/5000] Top-1: 78.92% | Top-5: 95.95% | Infer: 8.37 ms/batch
  Batch [410/5000] Top-1: 78.95% | Top-5: 95.79% | Infer: 8.35 ms/batch
  Batch [420/5000] Top-1: 78.97% | Top-5: 95.90% | Infer: 8.35 ms/batch
  Batch [430/5000] Top-1: 79.25% | Top-5: 96.00% | Infer: 8.34 ms/batch
  Batch [440/5000] Top-1: 79.27% | Top-5: 96.10% | Infer: 8.33 ms/batch
  Batch [450/5000] Top-1: 79.52% | Top-5: 96.19% | Infer: 8.32 ms/batch
  Batch [460/5000] Top-1: 80.00% | Top-5: 96.28% | Infer: 8.34 ms/batch
  Batch [470/5000] Top-1: 80.45% | Top-5: 96.36% | Infer: 8.33 ms/batch
  Batch [480/5000] Top-1: 80.89% | Top-5: 96.44% | Infer: 8.32 ms/batch
  Batch [490/5000] Top-1: 81.09% | Top-5: 96.52% | Infer: 8.30 ms/batch
  Batch [500/5000] Top-1: 81.49% | Top-5: 96.60% | Infer: 8.30 ms/batch
  Batch [510/5000] Top-1: 81.67% | Top-5: 96.46% | Infer: 8.30 ms/batch
  Batch [520/5000] Top-1: 81.84% | Top-5: 96.53% | Infer: 8.29 ms/batch
  Batch [530/5000] Top-1: 81.80% | Top-5: 96.40% | Infer: 8.27 ms/batch
  Batch [540/5000] Top-1: 81.96% | Top-5: 96.47% | Infer: 8.27 ms/batch
  Batch [550/5000] Top-1: 81.92% | Top-5: 96.54% | Infer: 8.28 ms/batch
  Batch [560/5000] Top-1: 82.26% | Top-5: 96.60% | Infer: 8.28 ms/batch
  Batch [570/5000] Top-1: 82.59% | Top-5: 96.67% | Infer: 8.28 ms/batch
  Batch [580/5000] Top-1: 82.91% | Top-5: 96.73% | Infer: 8.28 ms/batch
  Batch [590/5000] Top-1: 83.04% | Top-5: 96.79% | Infer: 8.27 ms/batch
  Batch [600/5000] Top-1: 83.16% | Top-5: 96.84% | Infer: 8.28 ms/batch
  Batch [610/5000] Top-1: 83.10% | Top-5: 96.90% | Infer: 8.28 ms/batch
  Batch [620/5000] Top-1: 82.71% | Top-5: 96.44% | Infer: 8.27 ms/batch
  Batch [630/5000] Top-1: 83.00% | Top-5: 96.50% | Infer: 8.28 ms/batch
  Batch [640/5000] Top-1: 83.11% | Top-5: 96.56% | Infer: 8.29 ms/batch
  Batch [650/5000] Top-1: 83.23% | Top-5: 96.61% | Infer: 8.29 ms/batch
  Batch [660/5000] Top-1: 83.49% | Top-5: 96.67% | Infer: 8.32 ms/batch
  Batch [670/5000] Top-1: 83.59% | Top-5: 96.72% | Infer: 8.35 ms/batch
  Batch [680/5000] Top-1: 83.85% | Top-5: 96.77% | Infer: 8.35 ms/batch
  Batch [690/5000] Top-1: 84.09% | Top-5: 96.82% | Infer: 8.39 ms/batch
  Batch [700/5000] Top-1: 84.33% | Top-5: 96.87% | Infer: 8.42 ms/batch
  Batch [710/5000] Top-1: 84.56% | Top-5: 96.91% | Infer: 8.43 ms/batch
  Batch [720/5000] Top-1: 84.78% | Top-5: 96.96% | Infer: 8.43 ms/batch
  Batch [730/5000] Top-1: 84.71% | Top-5: 97.00% | Infer: 8.45 ms/batch
  Batch [740/5000] Top-1: 84.65% | Top-5: 96.90% | Infer: 8.49 ms/batch
  Batch [750/5000] Top-1: 84.86% | Top-5: 96.94% | Infer: 8.51 ms/batch
  Batch [760/5000] Top-1: 84.93% | Top-5: 96.99% | Infer: 8.54 ms/batch
  Batch [770/5000] Top-1: 85.00% | Top-5: 97.03% | Infer: 8.57 ms/batch
  Batch [780/5000] Top-1: 85.20% | Top-5: 97.07% | Infer: 8.59 ms/batch
  Batch [790/5000] Top-1: 85.39% | Top-5: 97.11% | Infer: 8.61 ms/batch
  Batch [800/5000] Top-1: 85.45% | Top-5: 97.14% | Infer: 8.62 ms/batch
  Batch [810/5000] Top-1: 85.51% | Top-5: 97.05% | Infer: 8.64 ms/batch
  Batch [820/5000] Top-1: 85.44% | Top-5: 96.84% | Infer: 8.65 ms/batch
  Batch [830/5000] Top-1: 85.50% | Top-5: 96.75% | Infer: 8.67 ms/batch
  Batch [840/5000] Top-1: 85.56% | Top-5: 96.79% | Infer: 8.68 ms/batch
  Batch [850/5000] Top-1: 85.49% | Top-5: 96.83% | Infer: 8.71 ms/batch
  Batch [860/5000] Top-1: 85.42% | Top-5: 96.75% | Infer: 8.71 ms/batch
  Batch [870/5000] Top-1: 85.48% | Top-5: 96.79% | Infer: 8.74 ms/batch
  Batch [880/5000] Top-1: 85.29% | Top-5: 96.82% | Infer: 8.73 ms/batch
  Batch [890/5000] Top-1: 85.47% | Top-5: 96.86% | Infer: 8.75 ms/batch
  Batch [900/5000] Top-1: 85.63% | Top-5: 96.90% | Infer: 8.74 ms/batch
  Batch [910/5000] Top-1: 85.80% | Top-5: 96.93% | Infer: 8.76 ms/batch
  Batch [920/5000] Top-1: 85.96% | Top-5: 96.97% | Infer: 8.77 ms/batch
  Batch [930/5000] Top-1: 85.89% | Top-5: 97.00% | Infer: 8.78 ms/batch
  Batch [940/5000] Top-1: 85.82% | Top-5: 96.81% | Infer: 8.80 ms/batch
  Batch [950/5000] Top-1: 85.76% | Top-5: 96.74% | Infer: 8.82 ms/batch
  Batch [960/5000] Top-1: 85.70% | Top-5: 96.67% | Infer: 8.83 ms/batch
  Batch [970/5000] Top-1: 85.74% | Top-5: 96.70% | Infer: 8.83 ms/batch
  Batch [980/5000] Top-1: 85.79% | Top-5: 96.74% | Infer: 8.85 ms/batch
  Batch [990/5000] Top-1: 85.94% | Top-5: 96.77% | Infer: 8.86 ms/batch
  Batch [1000/5000] Top-1: 85.98% | Top-5: 96.80% | Infer: 8.87 ms/batch
  Batch [1010/5000] Top-1: 86.02% | Top-5: 96.84% | Infer: 8.87 ms/batch
  Batch [1020/5000] Top-1: 86.06% | Top-5: 96.77% | Infer: 8.88 ms/batch
  Batch [1030/5000] Top-1: 86.00% | Top-5: 96.70% | Infer: 8.89 ms/batch
  Batch [1040/5000] Top-1: 85.94% | Top-5: 96.73% | Infer: 8.91 ms/batch
  Batch [1050/5000] Top-1: 85.98% | Top-5: 96.67% | Infer: 8.92 ms/batch
  Batch [1060/5000] Top-1: 85.83% | Top-5: 96.50% | Infer: 8.93 ms/batch
  Batch [1070/5000] Top-1: 85.67% | Top-5: 96.44% | Infer: 8.94 ms/batch
  Batch [1080/5000] Top-1: 85.62% | Top-5: 96.38% | Infer: 8.95 ms/batch
  Batch [1090/5000] Top-1: 85.66% | Top-5: 96.42% | Infer: 8.95 ms/batch
  Batch [1100/5000] Top-1: 85.51% | Top-5: 96.36% | Infer: 8.95 ms/batch
  Batch [1110/5000] Top-1: 85.56% | Top-5: 96.30% | Infer: 8.95 ms/batch
  Batch [1120/5000] Top-1: 85.60% | Top-5: 96.33% | Infer: 8.97 ms/batch
  Batch [1130/5000] Top-1: 85.73% | Top-5: 96.36% | Infer: 8.98 ms/batch
  Batch [1140/5000] Top-1: 85.68% | Top-5: 96.40% | Infer: 8.99 ms/batch
  Batch [1150/5000] Top-1: 85.71% | Top-5: 96.43% | Infer: 9.01 ms/batch
  Batch [1160/5000] Top-1: 85.75% | Top-5: 96.46% | Infer: 9.01 ms/batch
  Batch [1170/5000] Top-1: 85.70% | Top-5: 96.40% | Infer: 9.02 ms/batch
  Batch [1180/5000] Top-1: 85.74% | Top-5: 96.43% | Infer: 9.04 ms/batch
  Batch [1190/5000] Top-1: 85.69% | Top-5: 96.38% | Infer: 9.04 ms/batch
  Batch [1200/5000] Top-1: 85.56% | Top-5: 96.32% | Infer: 9.04 ms/batch
  Batch [1210/5000] Top-1: 85.59% | Top-5: 96.27% | Infer: 9.03 ms/batch
  Batch [1220/5000] Top-1: 85.71% | Top-5: 96.30% | Infer: 9.02 ms/batch
  Batch [1230/5000] Top-1: 85.83% | Top-5: 96.33% | Infer: 9.02 ms/batch
  Batch [1240/5000] Top-1: 85.95% | Top-5: 96.36% | Infer: 9.02 ms/batch
  Batch [1250/5000] Top-1: 86.07% | Top-5: 96.39% | Infer: 9.00 ms/batch
  Batch [1260/5000] Top-1: 86.10% | Top-5: 96.34% | Infer: 9.00 ms/batch
  Batch [1270/5000] Top-1: 86.21% | Top-5: 96.37% | Infer: 8.99 ms/batch
  Batch [1280/5000] Top-1: 86.32% | Top-5: 96.40% | Infer: 8.99 ms/batch
  Batch [1290/5000] Top-1: 86.43% | Top-5: 96.43% | Infer: 8.98 ms/batch
  Batch [1300/5000] Top-1: 86.54% | Top-5: 96.46% | Infer: 8.97 ms/batch
  Batch [1310/5000] Top-1: 86.25% | Top-5: 96.48% | Infer: 8.96 ms/batch
  Batch [1320/5000] Top-1: 86.28% | Top-5: 96.51% | Infer: 8.96 ms/batch
  Batch [1330/5000] Top-1: 85.85% | Top-5: 96.31% | Infer: 8.95 ms/batch
  Batch [1340/5000] Top-1: 85.42% | Top-5: 96.34% | Infer: 8.95 ms/batch
  Batch [1350/5000] Top-1: 85.00% | Top-5: 96.21% | Infer: 8.94 ms/batch
  Batch [1360/5000] Top-1: 84.96% | Top-5: 96.17% | Infer: 8.93 ms/batch
  Batch [1370/5000] Top-1: 84.93% | Top-5: 96.19% | Infer: 8.93 ms/batch
  Batch [1380/5000] Top-1: 84.74% | Top-5: 96.07% | Infer: 8.92 ms/batch
  Batch [1390/5000] Top-1: 84.56% | Top-5: 96.10% | Infer: 8.92 ms/batch
  Batch [1400/5000] Top-1: 84.60% | Top-5: 96.13% | Infer: 8.91 ms/batch
  Batch [1410/5000] Top-1: 84.57% | Top-5: 96.16% | Infer: 8.92 ms/batch
  Batch [1420/5000] Top-1: 84.68% | Top-5: 96.19% | Infer: 8.91 ms/batch
  Batch [1430/5000] Top-1: 84.71% | Top-5: 96.14% | Infer: 8.90 ms/batch
  Batch [1440/5000] Top-1: 84.82% | Top-5: 96.17% | Infer: 8.89 ms/batch
  Batch [1450/5000] Top-1: 84.86% | Top-5: 96.20% | Infer: 8.89 ms/batch
  Batch [1460/5000] Top-1: 84.90% | Top-5: 96.22% | Infer: 8.88 ms/batch
  Batch [1470/5000] Top-1: 84.86% | Top-5: 96.25% | Infer: 8.88 ms/batch
  Batch [1480/5000] Top-1: 84.90% | Top-5: 96.21% | Infer: 8.88 ms/batch
  Batch [1490/5000] Top-1: 84.93% | Top-5: 96.16% | Infer: 8.87 ms/batch
  Batch [1500/5000] Top-1: 84.76% | Top-5: 96.12% | Infer: 8.87 ms/batch
  Batch [1510/5000] Top-1: 84.66% | Top-5: 95.95% | Infer: 8.87 ms/batch
  Batch [1520/5000] Top-1: 84.70% | Top-5: 95.91% | Infer: 8.87 ms/batch
  Batch [1530/5000] Top-1: 84.67% | Top-5: 95.93% | Infer: 8.86 ms/batch
  Batch [1540/5000] Top-1: 84.64% | Top-5: 95.96% | Infer: 8.86 ms/batch
  Batch [1550/5000] Top-1: 84.61% | Top-5: 95.99% | Infer: 8.86 ms/batch
  Batch [1560/5000] Top-1: 84.51% | Top-5: 96.01% | Infer: 8.85 ms/batch
  Batch [1570/5000] Top-1: 84.42% | Top-5: 95.91% | Infer: 8.84 ms/batch
  Batch [1580/5000] Top-1: 84.45% | Top-5: 95.94% | Infer: 8.84 ms/batch
  Batch [1590/5000] Top-1: 84.42% | Top-5: 95.90% | Infer: 8.83 ms/batch
  Batch [1600/5000] Top-1: 84.39% | Top-5: 95.92% | Infer: 8.84 ms/batch
  Batch [1610/5000] Top-1: 84.11% | Top-5: 95.76% | Infer: 8.83 ms/batch
  Batch [1620/5000] Top-1: 83.90% | Top-5: 95.72% | Infer: 8.84 ms/batch
  Batch [1630/5000] Top-1: 83.81% | Top-5: 95.75% | Infer: 8.84 ms/batch
  Batch [1640/5000] Top-1: 83.42% | Top-5: 95.59% | Infer: 8.83 ms/batch
  Batch [1650/5000] Top-1: 83.09% | Top-5: 95.31% | Infer: 8.83 ms/batch
  Batch [1660/5000] Top-1: 83.01% | Top-5: 95.28% | Infer: 8.82 ms/batch
  Batch [1670/5000] Top-1: 83.05% | Top-5: 95.24% | Infer: 8.82 ms/batch
  Batch [1680/5000] Top-1: 83.09% | Top-5: 95.27% | Infer: 8.81 ms/batch
  Batch [1690/5000] Top-1: 83.19% | Top-5: 95.30% | Infer: 8.81 ms/batch
  Batch [1700/5000] Top-1: 83.17% | Top-5: 95.27% | Infer: 8.80 ms/batch
  Batch [1710/5000] Top-1: 83.10% | Top-5: 95.24% | Infer: 8.81 ms/batch
  Batch [1720/5000] Top-1: 83.02% | Top-5: 95.21% | Infer: 8.81 ms/batch
  Batch [1730/5000] Top-1: 82.82% | Top-5: 95.12% | Infer: 8.81 ms/batch
  Batch [1740/5000] Top-1: 82.69% | Top-5: 95.03% | Infer: 8.81 ms/batch
  Batch [1750/5000] Top-1: 82.67% | Top-5: 95.00% | Infer: 8.81 ms/batch
  Batch [1760/5000] Top-1: 82.43% | Top-5: 95.03% | Infer: 8.82 ms/batch
  Batch [1770/5000] Top-1: 82.24% | Top-5: 94.89% | Infer: 8.83 ms/batch
  Batch [1780/5000] Top-1: 82.17% | Top-5: 94.86% | Infer: 8.84 ms/batch
  Batch [1790/5000] Top-1: 81.99% | Top-5: 94.77% | Infer: 8.85 ms/batch
  Batch [1800/5000] Top-1: 81.92% | Top-5: 94.75% | Infer: 8.85 ms/batch
  Batch [1810/5000] Top-1: 81.57% | Top-5: 94.72% | Infer: 8.85 ms/batch
  Batch [1820/5000] Top-1: 81.45% | Top-5: 94.69% | Infer: 8.85 ms/batch
  Batch [1830/5000] Top-1: 81.28% | Top-5: 94.67% | Infer: 8.86 ms/batch
  Batch [1840/5000] Top-1: 81.10% | Top-5: 94.70% | Infer: 8.86 ms/batch
  Batch [1850/5000] Top-1: 81.04% | Top-5: 94.73% | Infer: 8.87 ms/batch
  Batch [1860/5000] Top-1: 80.98% | Top-5: 94.64% | Infer: 8.88 ms/batch
  Batch [1870/5000] Top-1: 81.09% | Top-5: 94.67% | Infer: 8.89 ms/batch
  Batch [1880/5000] Top-1: 81.08% | Top-5: 94.70% | Infer: 8.89 ms/batch
  Batch [1890/5000] Top-1: 81.08% | Top-5: 94.73% | Infer: 8.90 ms/batch
  Batch [1900/5000] Top-1: 81.12% | Top-5: 94.76% | Infer: 8.91 ms/batch
  Batch [1910/5000] Top-1: 81.12% | Top-5: 94.79% | Infer: 8.91 ms/batch
  Batch [1920/5000] Top-1: 81.11% | Top-5: 94.76% | Infer: 8.92 ms/batch
  Batch [1930/5000] Top-1: 81.16% | Top-5: 94.74% | Infer: 8.92 ms/batch
  Batch [1940/5000] Top-1: 81.15% | Top-5: 94.71% | Infer: 8.93 ms/batch
  Batch [1950/5000] Top-1: 81.09% | Top-5: 94.64% | Infer: 8.94 ms/batch
  Batch [1960/5000] Top-1: 81.09% | Top-5: 94.66% | Infer: 8.94 ms/batch
  Batch [1970/5000] Top-1: 81.13% | Top-5: 94.64% | Infer: 8.94 ms/batch
  Batch [1980/5000] Top-1: 81.08% | Top-5: 94.62% | Infer: 8.94 ms/batch
  Batch [1990/5000] Top-1: 81.17% | Top-5: 94.64% | Infer: 8.95 ms/batch
  Batch [2000/5000] Top-1: 81.07% | Top-5: 94.57% | Infer: 8.96 ms/batch
  Batch [2010/5000] Top-1: 81.01% | Top-5: 94.60% | Infer: 8.95 ms/batch
  Batch [2020/5000] Top-1: 80.80% | Top-5: 94.62% | Infer: 8.96 ms/batch
  Batch [2030/5000] Top-1: 80.50% | Top-5: 94.60% | Infer: 8.96 ms/batch
  Batch [2040/5000] Top-1: 80.35% | Top-5: 94.63% | Infer: 8.95 ms/batch
  Batch [2050/5000] Top-1: 80.20% | Top-5: 94.60% | Infer: 8.95 ms/batch
  Batch [2060/5000] Top-1: 80.15% | Top-5: 94.53% | Infer: 8.96 ms/batch
  Batch [2070/5000] Top-1: 80.20% | Top-5: 94.56% | Infer: 8.96 ms/batch
  Batch [2080/5000] Top-1: 80.20% | Top-5: 94.54% | Infer: 8.96 ms/batch
  Batch [2090/5000] Top-1: 80.15% | Top-5: 94.51% | Infer: 8.95 ms/batch
  Batch [2100/5000] Top-1: 80.19% | Top-5: 94.54% | Infer: 8.95 ms/batch
  Batch [2110/5000] Top-1: 80.05% | Top-5: 94.47% | Infer: 8.95 ms/batch
  Batch [2120/5000] Top-1: 80.00% | Top-5: 94.45% | Infer: 8.95 ms/batch
  Batch [2130/5000] Top-1: 80.00% | Top-5: 94.43% | Infer: 8.94 ms/batch
  Batch [2140/5000] Top-1: 80.00% | Top-5: 94.36% | Infer: 8.94 ms/batch
  Batch [2150/5000] Top-1: 80.00% | Top-5: 94.39% | Infer: 8.94 ms/batch
  Batch [2160/5000] Top-1: 80.00% | Top-5: 94.37% | Infer: 8.94 ms/batch
  Batch [2170/5000] Top-1: 79.91% | Top-5: 94.39% | Infer: 8.94 ms/batch
  Batch [2180/5000] Top-1: 79.91% | Top-5: 94.33% | Infer: 8.94 ms/batch
  Batch [2190/5000] Top-1: 80.00% | Top-5: 94.35% | Infer: 8.94 ms/batch
  Batch [2200/5000] Top-1: 80.00% | Top-5: 94.33% | Infer: 8.94 ms/batch
  Batch [2210/5000] Top-1: 80.00% | Top-5: 94.31% | Infer: 8.94 ms/batch
  Batch [2220/5000] Top-1: 79.82% | Top-5: 94.20% | Infer: 8.93 ms/batch
  Batch [2230/5000] Top-1: 79.77% | Top-5: 94.18% | Infer: 8.93 ms/batch
  Batch [2240/5000] Top-1: 79.50% | Top-5: 93.89% | Infer: 8.93 ms/batch
  Batch [2250/5000] Top-1: 79.50% | Top-5: 93.87% | Infer: 8.92 ms/batch
  Batch [2260/5000] Top-1: 79.33% | Top-5: 93.81% | Infer: 8.92 ms/batch
  Batch [2270/5000] Top-1: 79.42% | Top-5: 93.84% | Infer: 8.92 ms/batch
  Batch [2280/5000] Top-1: 79.47% | Top-5: 93.87% | Infer: 8.92 ms/batch
  Batch [2290/5000] Top-1: 79.51% | Top-5: 93.85% | Infer: 8.92 ms/batch
  Batch [2300/5000] Top-1: 79.52% | Top-5: 93.83% | Infer: 8.92 ms/batch
  Batch [2310/5000] Top-1: 79.39% | Top-5: 93.86% | Infer: 8.92 ms/batch
  Batch [2320/5000] Top-1: 79.30% | Top-5: 93.84% | Infer: 8.92 ms/batch
  Batch [2330/5000] Top-1: 79.09% | Top-5: 93.83% | Infer: 8.92 ms/batch
  Batch [2340/5000] Top-1: 79.05% | Top-5: 93.85% | Infer: 8.92 ms/batch
  Batch [2350/5000] Top-1: 78.88% | Top-5: 93.88% | Infer: 8.92 ms/batch
  Batch [2360/5000] Top-1: 78.84% | Top-5: 93.82% | Infer: 8.92 ms/batch
  Batch [2370/5000] Top-1: 78.85% | Top-5: 93.80% | Infer: 8.91 ms/batch
  Batch [2380/5000] Top-1: 78.72% | Top-5: 93.66% | Infer: 8.91 ms/batch
  Batch [2390/5000] Top-1: 78.69% | Top-5: 93.64% | Infer: 8.90 ms/batch
  Batch [2400/5000] Top-1: 78.78% | Top-5: 93.67% | Infer: 8.90 ms/batch
  Batch [2410/5000] Top-1: 78.82% | Top-5: 93.70% | Infer: 8.90 ms/batch
  Batch [2420/5000] Top-1: 78.83% | Top-5: 93.72% | Infer: 8.91 ms/batch
  Batch [2430/5000] Top-1: 78.88% | Top-5: 93.75% | Infer: 8.90 ms/batch
  Batch [2440/5000] Top-1: 78.92% | Top-5: 93.78% | Infer: 8.90 ms/batch
  Batch [2450/5000] Top-1: 79.01% | Top-5: 93.80% | Infer: 8.90 ms/batch
  Batch [2460/5000] Top-1: 78.97% | Top-5: 93.79% | Infer: 8.90 ms/batch
  Batch [2470/5000] Top-1: 78.81% | Top-5: 93.69% | Infer: 8.90 ms/batch
  Batch [2480/5000] Top-1: 78.78% | Top-5: 93.67% | Infer: 8.90 ms/batch
  Batch [2490/5000] Top-1: 78.74% | Top-5: 93.66% | Infer: 8.89 ms/batch
  Batch [2500/5000] Top-1: 78.66% | Top-5: 93.68% | Infer: 8.89 ms/batch
  Batch [2510/5000] Top-1: 78.71% | Top-5: 93.71% | Infer: 8.89 ms/batch
  Batch [2520/5000] Top-1: 78.59% | Top-5: 93.73% | Infer: 8.89 ms/batch
  Batch [2530/5000] Top-1: 78.56% | Top-5: 93.76% | Infer: 8.89 ms/batch
  Batch [2540/5000] Top-1: 78.57% | Top-5: 93.78% | Infer: 8.89 ms/batch
  Batch [2550/5000] Top-1: 78.57% | Top-5: 93.77% | Infer: 8.88 ms/batch
  Batch [2560/5000] Top-1: 78.58% | Top-5: 93.75% | Infer: 8.89 ms/batch
  Batch [2570/5000] Top-1: 78.58% | Top-5: 93.74% | Infer: 8.88 ms/batch
  Batch [2580/5000] Top-1: 78.67% | Top-5: 93.76% | Infer: 8.89 ms/batch
  Batch [2590/5000] Top-1: 78.67% | Top-5: 93.75% | Infer: 8.89 ms/batch
  Batch [2600/5000] Top-1: 78.75% | Top-5: 93.77% | Infer: 8.89 ms/batch
  Batch [2610/5000] Top-1: 78.76% | Top-5: 93.80% | Infer: 8.89 ms/batch
  Batch [2620/5000] Top-1: 78.84% | Top-5: 93.82% | Infer: 8.90 ms/batch
  Batch [2630/5000] Top-1: 78.85% | Top-5: 93.85% | Infer: 8.90 ms/batch
  Batch [2640/5000] Top-1: 78.70% | Top-5: 93.75% | Infer: 8.90 ms/batch
  Batch [2650/5000] Top-1: 78.59% | Top-5: 93.66% | Infer: 8.91 ms/batch
  Batch [2660/5000] Top-1: 78.63% | Top-5: 93.65% | Infer: 8.92 ms/batch
  Batch [2670/5000] Top-1: 78.64% | Top-5: 93.67% | Infer: 8.92 ms/batch
  Batch [2680/5000] Top-1: 78.64% | Top-5: 93.66% | Infer: 8.92 ms/batch
  Batch [2690/5000] Top-1: 78.61% | Top-5: 93.68% | Infer: 8.92 ms/batch
  Batch [2700/5000] Top-1: 78.54% | Top-5: 93.63% | Infer: 8.92 ms/batch
  Batch [2710/5000] Top-1: 78.36% | Top-5: 93.51% | Infer: 8.92 ms/batch
  Batch [2720/5000] Top-1: 78.29% | Top-5: 93.49% | Infer: 8.93 ms/batch
  Batch [2730/5000] Top-1: 78.22% | Top-5: 93.41% | Infer: 8.93 ms/batch
  Batch [2740/5000] Top-1: 78.12% | Top-5: 93.28% | Infer: 8.94 ms/batch

/home/pf4636/code/resnet/quantized_resnets/.venv/lib/python3.12/site-packages/modelopt/torch/quantization/nn/modules/quant_module.py:59: UserWarning: Could not identify the device for TensorQuantizer states of maxpool. Please move the model to the right device now. This can be done by calling `model.to(device)`.
  warnings.warn(
/home/pf4636/code/resnet/quantized_resnets/.venv/lib/python3.12/site-packages/modelopt/torch/quantization/nn/modules/quant_module.py:59: UserWarning: Could not identify the device for TensorQuantizer states of pool. Please move the model to the right device now. This can be done by calling `model.to(device)`.
  warnings.warn(

[data] Filtered to 5000 samples across 100 classes.
Evaluating on 5000 batches (first 30 are warmup)...
  --- Warmup complete (30 batches) — starting metric collection ---
  Batch [40/5000] Top-1: 80.00% | Top-5: 100.00% | Infer: 10.72 ms/batch
  Batch [50/5000] Top-1: 90.00% | Top-5: 100.00% | Infer: 10.46 ms/batch
  Batch [60/5000] Top-1: 90.00% | Top-5: 100.00% | Infer: 10.32 ms/batch
  Batch [70/5000] Top-1: 92.50% | Top-5: 100.00% | Infer: 10.26 ms/batch
  Batch [80/5000] Top-1: 92.00% | Top-5: 98.00% | Infer: 9.82 ms/batch
  Batch [90/5000] Top-1: 93.33% | Top-5: 98.33% | Infer: 9.86 ms/batch
  Batch [100/5000] Top-1: 94.29% | Top-5: 98.57% | Infer: 9.93 ms/batch
  Batch [110/5000] Top-1: 93.75% | Top-5: 98.75% | Infer: 9.88 ms/batch
  Batch [120/5000] Top-1: 92.22% | Top-5: 97.78% | Infer: 9.80 ms/batch
  Batch [130/5000] Top-1: 93.00% | Top-5: 98.00% | Infer: 9.75 ms/batch
  Batch [140/5000] Top-1: 92.73% | Top-5: 98.18% | Infer: 9.82 ms/batch
  Batch [150/5000] Top-1: 90.83% | Top-5: 97.50% | Infer: 9.90 ms/batch
  Batch [160/5000] Top-1: 88.46% | Top-5: 97.69% | Infer: 9.92 ms/batch
  Batch [170/5000] Top-1: 85.71% | Top-5: 97.86% | Infer: 9.80 ms/batch
  Batch [180/5000] Top-1: 86.00% | Top-5: 97.33% | Infer: 9.85 ms/batch
  Batch [190/5000] Top-1: 85.00% | Top-5: 96.88% | Infer: 9.89 ms/batch
  Batch [200/5000] Top-1: 84.71% | Top-5: 96.47% | Infer: 9.89 ms/batch
  Batch [210/5000] Top-1: 83.89% | Top-5: 96.11% | Infer: 9.86 ms/batch
  Batch [220/5000] Top-1: 83.68% | Top-5: 95.79% | Infer: 9.80 ms/batch
  Batch [230/5000] Top-1: 83.00% | Top-5: 96.00% | Infer: 9.80 ms/batch
  Batch [240/5000] Top-1: 82.38% | Top-5: 96.19% | Infer: 9.78 ms/batch
  Batch [250/5000] Top-1: 82.27% | Top-5: 96.36% | Infer: 9.79 ms/batch
  Batch [260/5000] Top-1: 82.17% | Top-5: 96.09% | Infer: 9.77 ms/batch
  Batch [270/5000] Top-1: 81.67% | Top-5: 95.83% | Infer: 9.74 ms/batch
  Batch [280/5000] Top-1: 81.20% | Top-5: 95.60% | Infer: 9.70 ms/batch
  Batch [290/5000] Top-1: 81.92% | Top-5: 95.77% | Infer: 9.67 ms/batch
  Batch [300/5000] Top-1: 81.48% | Top-5: 95.56% | Infer: 9.68 ms/batch
  Batch [310/5000] Top-1: 80.71% | Top-5: 95.71% | Infer: 9.73 ms/batch
  Batch [320/5000] Top-1: 80.69% | Top-5: 95.86% | Infer: 9.72 ms/batch
  Batch [330/5000] Top-1: 81.00% | Top-5: 96.00% | Infer: 9.69 ms/batch
  Batch [340/5000] Top-1: 80.32% | Top-5: 95.81% | Infer: 9.67 ms/batch
  Batch [350/5000] Top-1: 79.69% | Top-5: 95.62% | Infer: 9.64 ms/batch
  Batch [360/5000] Top-1: 79.39% | Top-5: 95.45% | Infer: 9.63 ms/batch
  Batch [370/5000] Top-1: 78.53% | Top-5: 95.29% | Infer: 9.60 ms/batch
  Batch [380/5000] Top-1: 78.29% | Top-5: 95.43% | Infer: 9.63 ms/batch
  Batch [390/5000] Top-1: 78.33% | Top-5: 95.28% | Infer: 9.70 ms/batch
  Batch [400/5000] Top-1: 78.11% | Top-5: 95.14% | Infer: 9.73 ms/batch
  Batch [410/5000] Top-1: 78.16% | Top-5: 95.26% | Infer: 9.68 ms/batch
  Batch [420/5000] Top-1: 78.21% | Top-5: 95.13% | Infer: 9.65 ms/batch
  Batch [430/5000] Top-1: 78.00% | Top-5: 95.25% | Infer: 9.62 ms/batch
  Batch [440/5000] Top-1: 77.80% | Top-5: 95.12% | Infer: 9.59 ms/batch
  Batch [450/5000] Top-1: 78.10% | Top-5: 95.24% | Infer: 9.55 ms/batch
  Batch [460/5000] Top-1: 78.60% | Top-5: 95.35% | Infer: 9.51 ms/batch
  Batch [470/5000] Top-1: 79.09% | Top-5: 95.45% | Infer: 9.46 ms/batch
  Batch [480/5000] Top-1: 79.56% | Top-5: 95.56% | Infer: 9.42 ms/batch
  Batch [490/5000] Top-1: 80.00% | Top-5: 95.65% | Infer: 9.38 ms/batch
  Batch [500/5000] Top-1: 80.21% | Top-5: 95.74% | Infer: 9.35 ms/batch
  Batch [510/5000] Top-1: 80.42% | Top-5: 95.62% | Infer: 9.32 ms/batch
  Batch [520/5000] Top-1: 80.61% | Top-5: 95.71% | Infer: 9.31 ms/batch
  Batch [530/5000] Top-1: 80.60% | Top-5: 95.60% | Infer: 9.30 ms/batch
  Batch [540/5000] Top-1: 80.78% | Top-5: 95.49% | Infer: 9.26 ms/batch
  Batch [550/5000] Top-1: 80.96% | Top-5: 95.58% | Infer: 9.24 ms/batch
  Batch [560/5000] Top-1: 81.32% | Top-5: 95.66% | Infer: 9.21 ms/batch
  Batch [570/5000] Top-1: 81.67% | Top-5: 95.74% | Infer: 9.19 ms/batch
  Batch [580/5000] Top-1: 82.00% | Top-5: 95.82% | Infer: 9.17 ms/batch
  Batch [590/5000] Top-1: 82.32% | Top-5: 95.89% | Infer: 9.14 ms/batch
  Batch [600/5000] Top-1: 82.63% | Top-5: 95.96% | Infer: 9.14 ms/batch
  Batch [610/5000] Top-1: 82.93% | Top-5: 96.03% | Infer: 9.13 ms/batch
  Batch [620/5000] Top-1: 82.88% | Top-5: 95.76% | Infer: 9.10 ms/batch
  Batch [630/5000] Top-1: 83.17% | Top-5: 95.83% | Infer: 9.10 ms/batch
  Batch [640/5000] Top-1: 83.11% | Top-5: 95.90% | Infer: 9.08 ms/batch
  Batch [650/5000] Top-1: 83.23% | Top-5: 95.97% | Infer: 9.06 ms/batch
  Batch [660/5000] Top-1: 83.33% | Top-5: 96.03% | Infer: 9.05 ms/batch
  Batch [670/5000] Top-1: 83.59% | Top-5: 96.09% | Infer: 9.06 ms/batch
  Batch [680/5000] Top-1: 83.85% | Top-5: 96.15% | Infer: 9.05 ms/batch
  Batch [690/5000] Top-1: 83.94% | Top-5: 96.21% | Infer: 9.02 ms/batch
  Batch [700/5000] Top-1: 84.18% | Top-5: 96.27% | Infer: 9.00 ms/batch
  Batch [710/5000] Top-1: 84.26% | Top-5: 96.32% | Infer: 9.01 ms/batch
  Batch [720/5000] Top-1: 84.20% | Top-5: 96.38% | Infer: 8.99 ms/batch
  Batch [730/5000] Top-1: 84.14% | Top-5: 96.43% | Infer: 8.98 ms/batch
  Batch [740/5000] Top-1: 84.23% | Top-5: 96.34% | Infer: 8.97 ms/batch
  Batch [750/5000] Top-1: 84.44% | Top-5: 96.39% | Infer: 8.95 ms/batch
  Batch [760/5000] Top-1: 84.52% | Top-5: 96.30% | Infer: 8.95 ms/batch
  Batch [770/5000] Top-1: 84.46% | Top-5: 96.35% | Infer: 8.93 ms/batch
  Batch [780/5000] Top-1: 84.67% | Top-5: 96.40% | Infer: 8.91 ms/batch
  Batch [790/5000] Top-1: 84.74% | Top-5: 96.45% | Infer: 8.88 ms/batch
  Batch [800/5000] Top-1: 84.81% | Top-5: 96.36% | Infer: 8.86 ms/batch
  Batch [810/5000] Top-1: 84.87% | Top-5: 96.28% | Infer: 8.85 ms/batch
  Batch [820/5000] Top-1: 84.81% | Top-5: 96.20% | Infer: 8.83 ms/batch
  Batch [830/5000] Top-1: 84.88% | Top-5: 96.25% | Infer: 8.81 ms/batch
  Batch [840/5000] Top-1: 84.81% | Top-5: 96.30% | Infer: 8.80 ms/batch
  Batch [850/5000] Top-1: 84.76% | Top-5: 96.34% | Infer: 8.78 ms/batch
  Batch [860/5000] Top-1: 84.70% | Top-5: 96.39% | Infer: 8.76 ms/batch
  Batch [870/5000] Top-1: 84.64% | Top-5: 96.43% | Infer: 8.75 ms/batch
  Batch [880/5000] Top-1: 84.47% | Top-5: 96.35% | Infer: 8.75 ms/batch
  Batch [890/5000] Top-1: 84.65% | Top-5: 96.40% | Infer: 8.73 ms/batch
  Batch [900/5000] Top-1: 84.71% | Top-5: 96.44% | Infer: 8.72 ms/batch
  Batch [910/5000] Top-1: 84.89% | Top-5: 96.48% | Infer: 8.72 ms/batch
  Batch [920/5000] Top-1: 84.72% | Top-5: 96.52% | Infer: 8.70 ms/batch
  Batch [930/5000] Top-1: 84.78% | Top-5: 96.56% | Infer: 8.69 ms/batch
  Batch [940/5000] Top-1: 84.73% | Top-5: 96.59% | Infer: 8.66 ms/batch
  Batch [950/5000] Top-1: 84.67% | Top-5: 96.52% | Infer: 8.67 ms/batch
  Batch [960/5000] Top-1: 84.73% | Top-5: 96.45% | Infer: 8.66 ms/batch
  Batch [970/5000] Top-1: 84.89% | Top-5: 96.49% | Infer: 8.65 ms/batch
  Batch [980/5000] Top-1: 85.05% | Top-5: 96.53% | Infer: 8.64 ms/batch
  Batch [990/5000] Top-1: 85.21% | Top-5: 96.56% | Infer: 8.62 ms/batch
  Batch [1000/5000] Top-1: 85.26% | Top-5: 96.60% | Infer: 8.62 ms/batch
  Batch [1010/5000] Top-1: 85.31% | Top-5: 96.63% | Infer: 8.62 ms/batch
  Batch [1020/5000] Top-1: 85.25% | Top-5: 96.57% | Infer: 8.62 ms/batch
  Batch [1030/5000] Top-1: 85.20% | Top-5: 96.40% | Infer: 8.63 ms/batch
  Batch [1040/5000] Top-1: 85.25% | Top-5: 96.34% | Infer: 8.63 ms/batch
  Batch [1050/5000] Top-1: 85.29% | Top-5: 96.27% | Infer: 8.64 ms/batch
  Batch [1060/5000] Top-1: 85.15% | Top-5: 96.02% | Infer: 8.65 ms/batch
  Batch [1070/5000] Top-1: 84.90% | Top-5: 95.87% | Infer: 8.65 ms/batch
  Batch [1080/5000] Top-1: 84.86% | Top-5: 95.90% | Infer: 8.65 ms/batch
  Batch [1090/5000] Top-1: 85.00% | Top-5: 95.94% | Infer: 8.66 ms/batch
  Batch [1100/5000] Top-1: 84.77% | Top-5: 95.79% | Infer: 8.67 ms/batch
  Batch [1110/5000] Top-1: 84.81% | Top-5: 95.83% | Infer: 8.68 ms/batch
  Batch [1120/5000] Top-1: 84.95% | Top-5: 95.87% | Infer: 8.67 ms/batch
  Batch [1130/5000] Top-1: 85.09% | Top-5: 95.91% | Infer: 8.69 ms/batch
  Batch [1140/5000] Top-1: 85.14% | Top-5: 95.95% | Infer: 8.70 ms/batch
  Batch [1150/5000] Top-1: 85.27% | Top-5: 95.98% | Infer: 8.70 ms/batch
  Batch [1160/5000] Top-1: 85.22% | Top-5: 96.02% | Infer: 8.70 ms/batch
  Batch [1170/5000] Top-1: 85.26% | Top-5: 96.05% | Infer: 8.70 ms/batch
  Batch [1180/5000] Top-1: 85.39% | Top-5: 96.09% | Infer: 8.71 ms/batch
  Batch [1190/5000] Top-1: 85.34% | Top-5: 96.03% | Infer: 8.72 ms/batch
  Batch [1200/5000] Top-1: 85.13% | Top-5: 95.90% | Infer: 8.73 ms/batch
  Batch [1210/5000] Top-1: 85.17% | Top-5: 95.85% | Infer: 8.73 ms/batch
  Batch [1220/5000] Top-1: 85.29% | Top-5: 95.88% | Infer: 8.74 ms/batch
  Batch [1230/5000] Top-1: 85.42% | Top-5: 95.92% | Infer: 8.76 ms/batch
  Batch [1240/5000] Top-1: 85.54% | Top-5: 95.95% | Infer: 8.76 ms/batch
  Batch [1250/5000] Top-1: 85.66% | Top-5: 95.98% | Infer: 8.75 ms/batch
  Batch [1260/5000] Top-1: 85.61% | Top-5: 95.93% | Infer: 8.76 ms/batch
  Batch [1270/5000] Top-1: 85.65% | Top-5: 95.97% | Infer: 8.76 ms/batch
  Batch [1280/5000] Top-1: 85.76% | Top-5: 96.00% | Infer: 8.76 ms/batch
  Batch [1290/5000] Top-1: 85.87% | Top-5: 96.03% | Infer: 8.77 ms/batch
  Batch [1300/5000] Top-1: 85.91% | Top-5: 96.06% | Infer: 8.78 ms/batch
  Batch [1310/5000] Top-1: 85.62% | Top-5: 96.02% | Infer: 8.78 ms/batch
  Batch [1320/5000] Top-1: 85.66% | Top-5: 96.05% | Infer: 8.79 ms/batch
  Batch [1330/5000] Top-1: 85.38% | Top-5: 95.85% | Infer: 8.80 ms/batch
  Batch [1340/5000] Top-1: 84.96% | Top-5: 95.80% | Infer: 8.80 ms/batch
  Batch [1350/5000] Top-1: 84.70% | Top-5: 95.76% | Infer: 8.79 ms/batch
  Batch [1360/5000] Top-1: 84.66% | Top-5: 95.71% | Infer: 8.81 ms/batch
  Batch [1370/5000] Top-1: 84.63% | Top-5: 95.60% | Infer: 8.81 ms/batch
  Batch [1380/5000] Top-1: 84.44% | Top-5: 95.48% | Infer: 8.82 ms/batch
  Batch [1390/5000] Top-1: 84.34% | Top-5: 95.37% | Infer: 8.82 ms/batch
  Batch [1400/5000] Top-1: 84.38% | Top-5: 95.33% | Infer: 8.83 ms/batch
  Batch [1410/5000] Top-1: 84.49% | Top-5: 95.36% | Infer: 8.83 ms/batch
  Batch [1420/5000] Top-1: 84.53% | Top-5: 95.40% | Infer: 8.84 ms/batch
  Batch [1430/5000] Top-1: 84.50% | Top-5: 95.29% | Infer: 8.83 ms/batch
  Batch [1440/5000] Top-1: 84.61% | Top-5: 95.32% | Infer: 8.84 ms/batch
  Batch [1450/5000] Top-1: 84.65% | Top-5: 95.35% | Infer: 8.85 ms/batch
  Batch [1460/5000] Top-1: 84.69% | Top-5: 95.38% | Infer: 8.85 ms/batch
  Batch [1470/5000] Top-1: 84.72% | Top-5: 95.42% | Infer: 8.86 ms/batch
  Batch [1480/5000] Top-1: 84.76% | Top-5: 95.45% | Infer: 8.87 ms/batch
  Batch [1490/5000] Top-1: 84.79% | Top-5: 95.48% | Infer: 8.88 ms/batch
  Batch [1500/5000] Top-1: 84.63% | Top-5: 95.37% | Infer: 8.89 ms/batch
  Batch [1510/5000] Top-1: 84.53% | Top-5: 95.20% | Infer: 8.88 ms/batch
  Batch [1520/5000] Top-1: 84.50% | Top-5: 95.10% | Infer: 8.88 ms/batch
  Batch [1530/5000] Top-1: 84.47% | Top-5: 95.13% | Infer: 8.88 ms/batch
  Batch [1540/5000] Top-1: 84.44% | Top-5: 95.17% | Infer: 8.89 ms/batch
  Batch [1550/5000] Top-1: 84.47% | Top-5: 95.20% | Infer: 8.90 ms/batch
  Batch [1560/5000] Top-1: 84.44% | Top-5: 95.23% | Infer: 8.89 ms/batch
  Batch [1570/5000] Top-1: 84.42% | Top-5: 95.13% | Infer: 8.89 ms/batch
  Batch [1580/5000] Top-1: 84.45% | Top-5: 95.16% | Infer: 8.87 ms/batch
  Batch [1590/5000] Top-1: 84.42% | Top-5: 95.13% | Infer: 8.88 ms/batch
  Batch [1600/5000] Top-1: 84.39% | Top-5: 95.16% | Infer: 8.89 ms/batch
  Batch [1610/5000] Top-1: 84.11% | Top-5: 95.06% | Infer: 8.89 ms/batch
  Batch [1620/5000] Top-1: 83.96% | Top-5: 94.97% | Infer: 8.89 ms/batch
  Batch [1630/5000] Top-1: 83.88% | Top-5: 95.00% | Infer: 8.90 ms/batch
  Batch [1640/5000] Top-1: 83.60% | Top-5: 94.91% | Infer: 8.90 ms/batch
  Batch [1650/5000] Top-1: 83.33% | Top-5: 94.69% | Infer: 8.89 ms/batch
  Batch [1660/5000] Top-1: 83.37% | Top-5: 94.72% | Infer: 8.90 ms/batch
  Batch [1670/5000] Top-1: 83.41% | Top-5: 94.70% | Infer: 8.90 ms/batch
  Batch [1680/5000] Top-1: 83.39% | Top-5: 94.73% | Infer: 8.90 ms/batch
  Batch [1690/5000] Top-1: 83.43% | Top-5: 94.76% | Infer: 8.90 ms/batch
  Batch [1700/5000] Top-1: 83.35% | Top-5: 94.73% | Infer: 8.90 ms/batch
  Batch [1710/5000] Top-1: 83.27% | Top-5: 94.70% | Infer: 8.90 ms/batch
  Batch [1720/5000] Top-1: 83.25% | Top-5: 94.67% | Infer: 8.89 ms/batch
  Batch [1730/5000] Top-1: 83.06% | Top-5: 94.65% | Infer: 8.89 ms/batch
  Batch [1740/5000] Top-1: 82.87% | Top-5: 94.62% | Infer: 8.89 ms/batch
  Batch [1750/5000] Top-1: 82.79% | Top-5: 94.59% | Infer: 8.90 ms/batch
  Batch [1760/5000] Top-1: 82.60% | Top-5: 94.62% | Infer: 8.91 ms/batch
  Batch [1770/5000] Top-1: 82.36% | Top-5: 94.54% | Infer: 8.91 ms/batch
  Batch [1780/5000] Top-1: 82.29% | Top-5: 94.57% | Infer: 8.90 ms/batch
  Batch [1790/5000] Top-1: 81.99% | Top-5: 94.49% | Infer: 8.90 ms/batch
  Batch [1800/5000] Top-1: 81.92% | Top-5: 94.46% | Infer: 8.90 ms/batch
  Batch [1810/5000] Top-1: 81.57% | Top-5: 94.44% | Infer: 8.90 ms/batch
  Batch [1820/5000] Top-1: 81.34% | Top-5: 94.47% | Infer: 8.91 ms/batch
  Batch [1830/5000] Top-1: 81.22% | Top-5: 94.50% | Infer: 8.91 ms/batch
  Batch [1840/5000] Top-1: 81.05% | Top-5: 94.48% | Infer: 8.90 ms/batch
  Batch [1850/5000] Top-1: 80.99% | Top-5: 94.51% | Infer: 8.90 ms/batch
  Batch [1860/5000] Top-1: 80.93% | Top-5: 94.48% | Infer: 8.90 ms/batch
  Batch [1870/5000] Top-1: 80.92% | Top-5: 94.51% | Infer: 8.89 ms/batch
  Batch [1880/5000] Top-1: 80.92% | Top-5: 94.54% | Infer: 8.88 ms/batch
  Batch [1890/5000] Top-1: 80.97% | Top-5: 94.57% | Infer: 8.88 ms/batch
  Batch [1900/5000] Top-1: 80.91% | Top-5: 94.60% | Infer: 8.88 ms/batch
  Batch [1910/5000] Top-1: 80.90% | Top-5: 94.52% | Infer: 8.87 ms/batch
  Batch [1920/5000] Top-1: 80.85% | Top-5: 94.44% | Infer: 8.87 ms/batch
  Batch [1930/5000] Top-1: 80.79% | Top-5: 94.42% | Infer: 8.87 ms/batch
  Batch [1940/5000] Top-1: 80.73% | Top-5: 94.40% | Infer: 8.86 ms/batch
  Batch [1950/5000] Top-1: 80.73% | Top-5: 94.32% | Infer: 8.86 ms/batch
  Batch [1960/5000] Top-1: 80.78% | Top-5: 94.35% | Infer: 8.85 ms/batch
  Batch [1970/5000] Top-1: 80.77% | Top-5: 94.33% | Infer: 8.84 ms/batch
  Batch [1980/5000] Top-1: 80.72% | Top-5: 94.31% | Infer: 8.84 ms/batch
  Batch [1990/5000] Top-1: 80.77% | Top-5: 94.34% | Infer: 8.83 ms/batch
  Batch [2000/5000] Top-1: 80.71% | Top-5: 94.31% | Infer: 8.83 ms/batch
  Batch [2010/5000] Top-1: 80.56% | Top-5: 94.34% | Infer: 8.83 ms/batch
  Batch [2020/5000] Top-1: 80.40% | Top-5: 94.37% | Infer: 8.83 ms/batch
  Batch [2030/5000] Top-1: 80.20% | Top-5: 94.35% | Infer: 8.82 ms/batch
  Batch [2040/5000] Top-1: 80.05% | Top-5: 94.38% | Infer: 8.82 ms/batch
  Batch [2050/5000] Top-1: 80.05% | Top-5: 94.41% | Infer: 8.81 ms/batch
  Batch [2060/5000] Top-1: 80.05% | Top-5: 94.38% | Infer: 8.81 ms/batch
  Batch [2070/5000] Top-1: 80.15% | Top-5: 94.41% | Infer: 8.80 ms/batch
  Batch [2080/5000] Top-1: 80.15% | Top-5: 94.39% | Infer: 8.79 ms/batch
  Batch [2090/5000] Top-1: 80.15% | Top-5: 94.37% | Infer: 8.79 ms/batch
  Batch [2100/5000] Top-1: 80.19% | Top-5: 94.40% | Infer: 8.79 ms/batch
  Batch [2110/5000] Top-1: 80.10% | Top-5: 94.33% | Infer: 8.78 ms/batch
  Batch [2120/5000] Top-1: 80.00% | Top-5: 94.21% | Infer: 8.78 ms/batch
  Batch [2130/5000] Top-1: 80.05% | Top-5: 94.19% | Infer: 8.77 ms/batch
  Batch [2140/5000] Top-1: 80.00% | Top-5: 94.17% | Infer: 8.77 ms/batch
  Batch [2150/5000] Top-1: 79.95% | Top-5: 94.20% | Infer: 8.76 ms/batch
  Batch [2160/5000] Top-1: 79.95% | Top-5: 94.18% | Infer: 8.76 ms/batch
  Batch [2170/5000] Top-1: 79.86% | Top-5: 94.11% | Infer: 8.75 ms/batch
  Batch [2180/5000] Top-1: 79.86% | Top-5: 94.05% | Infer: 8.74 ms/batch
  Batch [2190/5000] Top-1: 79.95% | Top-5: 94.07% | Infer: 8.74 ms/batch
  Batch [2200/5000] Top-1: 80.00% | Top-5: 94.06% | Infer: 8.74 ms/batch
  Batch [2210/5000] Top-1: 80.05% | Top-5: 94.04% | Infer: 8.74 ms/batch
  Batch [2220/5000] Top-1: 79.91% | Top-5: 93.93% | Infer: 8.73 ms/batch
  Batch [2230/5000] Top-1: 79.82% | Top-5: 93.86% | Infer: 8.73 ms/batch
  Batch [2240/5000] Top-1: 79.55% | Top-5: 93.67% | Infer: 8.72 ms/batch
  Batch [2250/5000] Top-1: 79.46% | Top-5: 93.65% | Infer: 8.72 ms/batch
  Batch [2260/5000] Top-1: 79.28% | Top-5: 93.54% | Infer: 8.72 ms/batch
  Batch [2270/5000] Top-1: 79.33% | Top-5: 93.57% | Infer: 8.72 ms/batch
  Batch [2280/5000] Top-1: 79.38% | Top-5: 93.60% | Infer: 8.71 ms/batch
  Batch [2290/5000] Top-1: 79.38% | Top-5: 93.58% | Infer: 8.71 ms/batch
  Batch [2300/5000] Top-1: 79.38% | Top-5: 93.57% | Infer: 8.70 ms/batch
  Batch [2310/5000] Top-1: 79.25% | Top-5: 93.55% | Infer: 8.70 ms/batch
  Batch [2320/5000] Top-1: 79.08% | Top-5: 93.49% | Infer: 8.70 ms/batch
  Batch [2330/5000] Top-1: 78.91% | Top-5: 93.52% | Infer: 8.70 ms/batch
  Batch [2340/5000] Top-1: 78.70% | Top-5: 93.55% | Infer: 8.70 ms/batch
  Batch [2350/5000] Top-1: 78.53% | Top-5: 93.58% | Infer: 8.70 ms/batch
  Batch [2360/5000] Top-1: 78.50% | Top-5: 93.52% | Infer: 8.70 ms/batch
  Batch [2370/5000] Top-1: 78.55% | Top-5: 93.50% | Infer: 8.69 ms/batch
  Batch [2380/5000] Top-1: 78.43% | Top-5: 93.36% | Infer: 8.69 ms/batch
  Batch [2390/5000] Top-1: 78.43% | Top-5: 93.31% | Infer: 8.69 ms/batch
  Batch [2400/5000] Top-1: 78.52% | Top-5: 93.33% | Infer: 8.68 ms/batch
  Batch [2410/5000] Top-1: 78.57% | Top-5: 93.36% | Infer: 8.68 ms/batch
  Batch [2420/5000] Top-1: 78.62% | Top-5: 93.35% | Infer: 8.67 ms/batch
  Batch [2430/5000] Top-1: 78.58% | Top-5: 93.33% | Infer: 8.67 ms/batch
  Batch [2440/5000] Top-1: 78.63% | Top-5: 93.36% | Infer: 8.66 ms/batch
  Batch [2450/5000] Top-1: 78.72% | Top-5: 93.39% | Infer: 8.66 ms/batch
  Batch [2460/5000] Top-1: 78.68% | Top-5: 93.33% | Infer: 8.66 ms/batch
  Batch [2470/5000] Top-1: 78.61% | Top-5: 93.24% | Infer: 8.65 ms/batch
  Batch [2480/5000] Top-1: 78.57% | Top-5: 93.22% | Infer: 8.65 ms/batch
  Batch [2490/5000] Top-1: 78.50% | Top-5: 93.21% | Infer: 8.65 ms/batch
  Batch [2500/5000] Top-1: 78.42% | Top-5: 93.24% | Infer: 8.64 ms/batch
  Batch [2510/5000] Top-1: 78.47% | Top-5: 93.23% | Infer: 8.64 ms/batch
  Batch [2520/5000] Top-1: 78.51% | Top-5: 93.21% | Infer: 8.64 ms/batch
  Batch [2530/5000] Top-1: 78.56% | Top-5: 93.24% | Infer: 8.64 ms/batch
  Batch [2540/5000] Top-1: 78.61% | Top-5: 93.27% | Infer: 8.63 ms/batch
  Batch [2550/5000] Top-1: 78.61% | Top-5: 93.25% | Infer: 8.63 ms/batch
  Batch [2560/5000] Top-1: 78.66% | Top-5: 93.24% | Infer: 8.62 ms/batch
  Batch [2570/5000] Top-1: 78.66% | Top-5: 93.23% | Infer: 8.62 ms/batch
  Batch [2580/5000] Top-1: 78.75% | Top-5: 93.25% | Infer: 8.62 ms/batch
  Batch [2590/5000] Top-1: 78.71% | Top-5: 93.24% | Infer: 8.62 ms/batch
  Batch [2600/5000] Top-1: 78.79% | Top-5: 93.27% | Infer: 8.62 ms/batch
  Batch [2610/5000] Top-1: 78.80% | Top-5: 93.29% | Infer: 8.62 ms/batch
  Batch [2620/5000] Top-1: 78.80% | Top-5: 93.32% | Infer: 8.61 ms/batch
  Batch [2630/5000] Top-1: 78.85% | Top-5: 93.35% | Infer: 8.61 ms/batch
  Batch [2640/5000] Top-1: 78.74% | Top-5: 93.30% | Infer: 8.61 ms/batch
  Batch [2650/5000] Top-1: 78.66% | Top-5: 93.21% | Infer: 8.60 ms/batch
  Batch [2660/5000] Top-1: 78.71% | Top-5: 93.19% | Infer: 8.60 ms/batch
  Batch [2670/5000] Top-1: 78.75% | Top-5: 93.22% | Infer: 8.59 ms/batch
  Batch [2680/5000] Top-1: 78.75% | Top-5: 93.21% | Infer: 8.60 ms/batch
  Batch [2690/5000] Top-1: 78.76% | Top-5: 93.20% | Infer: 8.59 ms/batch
  Batch [2700/5000] Top-1: 78.73% | Top-5: 93.22% | Infer: 8.59 ms/batch
  Batch [2710/5000] Top-1: 78.54% | Top-5: 93.17% | Infer: 8.58 ms/batch
  Batch [2720/5000] Top-1: 78.44% | Top-5: 93.20% | Infer: 8.58 ms/batch
  Batch [2730/5000] Top-1: 78.37% | Top-5: 93.19% | Infer: 8.58 ms/batch
  Batch [2740/5000] Top-1: 78.23% | Top-5: 93.06% | Infer: 8.58 ms/batch
  Batch [2750/5000] Top-1: 78.24% | Top-5: 93.05% | Infer: 8.59 ms/batch

## Per-Run Results

In [7]:
rows = []
for rec in all_records:
    r = rec["results"]
    extra = rec.get("config_extra", rec.get("config", {}))
    bits = extra.get("input_quant_bits", rec["config"].get("input_quant_bits", None))
    prec = extra.get("qat_precision", "int8")
    seed = extra.get("seed", 42)
    rows.append({
        "qat_precision": f"qat_{prec}",
        "input_bits": bits,
        "seed": seed,
        "top1": r["top1_acc"],
        "top5": r["top5_acc"],
        "lat_ms": r["infer_ms_avg"],
        "throughput": r.get("throughput_infer_sps", None),
    })

df_all = pd.DataFrame(rows).sort_values(
    ["qat_precision", "input_bits", "seed"], ascending=[True, True, True]
).reset_index(drop=True)
df_all

   qat_precision  input_bits  seed   top1   top5  lat_ms  throughput
0       qat_int4           1     1 69.175 89.115  10.097      99.035
1       qat_int4           1     2 69.618 88.893  10.641      93.976
2       qat_int4           1    42 68.873 89.215  10.017      99.831
3       qat_int4           2     1 76.278 92.535  10.236      97.698
4       qat_int4           2     2 76.157 93.159  10.311      96.985
5       qat_int4           2    42 75.915 92.455   9.993     100.073
6       qat_int4           4     1 77.887 93.280  11.201      89.276
7       qat_int4           4     2 77.545 93.501  10.408      96.077
8       qat_int4           4    42 77.445 93.119   9.394     106.446
9       qat_int4           8     1 77.223 93.320  10.195      98.083
10      qat_int4           8     2 77.445 93.239  10.472      95.495
11      qat_int4           8    42 77.103 93.099   9.398     106.406
12      qat_int8           1     1 69.557 89.537   9.335     107.118
13      qat_int8           1     2 69.678 89.437   8.864     112.817
14      qat_int8           1    42 68.813 89.396   8.134     122.941
15      qat_int8           2     1 76.640 92.857   9.120     109.653
16      qat_int8           2     2 77.082 93.320   9.642     103.708
17      qat_int8           2    42 76.419 93.119   8.052     124.192
18      qat_int8           4     1 78.310 93.622   8.969     111.499
19      qat_int8           4     2 78.169 93.340   9.022     110.835
20      qat_int8           4    42 78.773 93.461   8.206     121.861
21      qat_int8           8     1 77.847 93.461   9.063     110.344
22      qat_int8           8     2 78.129 93.280   8.646     115.657
23      qat_int8           8    42 78.008 93.380   8.505     117.572

## Averaged Results (mean ± std across seeds)

In [8]:
avg_df = df_all.groupby(["qat_precision", "input_bits"]).agg(
    top1_mean=("top1", "mean"),
    top1_std=("top1", "std"),
    top5_mean=("top5", "mean"),
    top5_std=("top5", "std"),
    infer_ms_mean=("lat_ms", "mean"),
    infer_ms_std=("lat_ms", "std"),
    throughput_mean=("throughput", "mean"),
    n_seeds=("seed", "count"),
).round(3).reset_index()

avg_df = avg_df.sort_values(
    ["qat_precision", "input_bits"], ascending=[True, True]
).reset_index(drop=True)
avg_df

,qat_precision,input_bits,top1_mean,top1_std,top5_mean,top5_std,infer_ms_mean,infer_ms_std,throughput_mean,n_seeds
0,qat_int4,1,69.222,0.374,89.074,0.165,10.252,0.339,97.614,3
1,qat_int4,2,76.117,0.184,92.716,0.385,10.180,0.166,98.252,3
2,qat_int4,4,77.626,0.232,93.300,0.192,10.335,0.906,97.266,3
3,qat_int4,8,77.257,0.173,93.219,0.112,10.022,0.558,99.995,3
4,qat_int8,1,69.349,0.469,89.457,0.073,8.778,0.605,114.292,3
5,qat_int8,2,76.714,0.338,93.099,0.232,8.938,0.811,112.517,3
6,qat_int8,4,78.417,0.316,93.474,0.141,8.732,0.457,114.732,3
7,qat_int8,8,77.995,0.141,93.374,0.091,8.738,0.290,114.524,3

In [9]:
out_path = PROJECT_ROOT / "resultsv2" / "test_runs" / "qat_torch_avg_test.json"
out_path.parent.mkdir(parents=True, exist_ok=True)
avg_df.to_json(out_path, orient="records", indent=2)
print(f"Saved to {out_path}")

Saved to /home/pf4636/code/resnet/quantized_resnets/resultsv2/test_runs/qat_torch_avg_test.json