# 01 — PyTorch baselines (FP32)

Runs:
- FP32 (CUDA)
- FP16 (CUDA)

Optionally without reduced bit depth.

In [4]:
from pathlib import Path
import sys, os

# ---- Path setup (adjust if your repo layout differs) ----
PROJECT_ROOT = Path("..").resolve()
SRC = PROJECT_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

In [5]:
# Purpose: Establish PyTorch FP32 baseline (and optional FP16 baseline) on ImageNet val.
import os
import json
from pathlib import Path
import pandas as pd

# project imports
from config import ExperimentConfig, with_overrides
from runner import run_experiment
from utils import load_runs, flatten_runs

pd.set_option("display.max_columns", 200)

In [6]:
# Baselines (PyTorch backend only)
base = ExperimentConfig(
    backend="pytorch",
    device="cuda",             
    batch_size=1,
    input_quant_bits=8,        
    seed=42,
    num_eval_batches=500
)

In [7]:
cfg32 = with_overrides(base, model_precision="fp32")

payload, tracker = run_experiment(cfg32, save_results_flag=True)

# quick peek
print(payload["run_id"], payload["status"], payload["results"].get("top1_acc"))

[data] Filtered to 5000 samples across 100 classes.
Evaluating on 500 batches (first 30 are warmup)...
  --- Warmup complete (30 batches) — starting metric collection ---
  Batch [40/500] Top-1: 90.00% | Top-5: 100.00% | Infer: 3.09 ms/batch
  Batch [50/500] Top-1: 95.00% | Top-5: 100.00% | Infer: 2.99 ms/batch
  Batch [60/500] Top-1: 96.67% | Top-5: 100.00% | Infer: 2.91 ms/batch
  Batch [70/500] Top-1: 97.50% | Top-5: 100.00% | Infer: 2.92 ms/batch
  Batch [80/500] Top-1: 94.00% | Top-5: 98.00% | Infer: 2.93 ms/batch
  Batch [90/500] Top-1: 95.00% | Top-5: 98.33% | Infer: 3.06 ms/batch
  Batch [100/500] Top-1: 94.29% | Top-5: 98.57% | Infer: 3.11 ms/batch
  Batch [110/500] Top-1: 95.00% | Top-5: 98.75% | Infer: 3.10 ms/batch
  Batch [120/500] Top-1: 93.33% | Top-5: 98.89% | Infer: 3.12 ms/batch
  Batch [130/500] Top-1: 94.00% | Top-5: 99.00% | Infer: 3.07 ms/batch
  Batch [140/500] Top-1: 92.73% | Top-5: 99.09% | Infer: 2.99 ms/batch
  Batch [150/500] Top-1: 91.67% | Top-5: 99.17% | Infer: 3.00 ms/batch
  Batch [160/500] Top-1: 90.77% | Top-5: 99.23% | Infer: 3.07 ms/batch
  Batch [170/500] Top-1: 87.86% | Top-5: 99.29% | Infer: 3.06 ms/batch
  Batch [180/500] Top-1: 88.00% | Top-5: 98.67% | Infer: 3.10 ms/batch
  Batch [190/500] Top-1: 86.88% | Top-5: 98.12% | Infer: 3.15 ms/batch
  Batch [200/500] Top-1: 86.47% | Top-5: 98.24% | Infer: 3.12 ms/batch
  Batch [210/500] Top-1: 86.11% | Top-5: 97.22% | Infer: 3.10 ms/batch
  Batch [220/500] Top-1: 86.32% | Top-5: 96.84% | Infer: 3.09 ms/batch
  Batch [230/500] Top-1: 85.00% | Top-5: 97.00% | Infer: 3.14 ms/batch
  Batch [240/500] Top-1: 84.76% | Top-5: 96.67% | Infer: 3.17 ms/batch
  Batch [250/500] Top-1: 85.45% | Top-5: 96.82% | Infer: 3.17 ms/batch
  Batch [260/500] Top-1: 85.65% | Top-5: 96.96% | Infer: 3.15 ms/batch
  Batch [270/500] Top-1: 85.42% | Top-5: 96.67% | Infer: 3.13 ms/batch
  Batch [280/500] Top-1: 85.60% | Top-5: 96.80% | Infer: 3.10 ms/batch
  Batch [290/500] Top-1: 85.38% | Top-5: 96.92% | Infer: 3.11 ms/batch
  Batch [300/500] Top-1: 85.19% | Top-5: 96.67% | Infer: 3.13 ms/batch
  Batch [310/500] Top-1: 85.00% | Top-5: 96.79% | Infer: 3.14 ms/batch
  Batch [320/500] Top-1: 85.17% | Top-5: 96.90% | Infer: 3.17 ms/batch
  Batch [330/500] Top-1: 84.67% | Top-5: 97.00% | Infer: 3.13 ms/batch
  Batch [340/500] Top-1: 84.19% | Top-5: 97.10% | Infer: 3.13 ms/batch
  Batch [350/500] Top-1: 83.75% | Top-5: 96.88% | Infer: 3.15 ms/batch
  Batch [360/500] Top-1: 83.33% | Top-5: 96.67% | Infer: 3.13 ms/batch
  Batch [370/500] Top-1: 82.65% | Top-5: 96.18% | Infer: 3.14 ms/batch
  Batch [380/500] Top-1: 82.29% | Top-5: 96.29% | Infer: 3.13 ms/batch
  Batch [390/500] Top-1: 82.50% | Top-5: 96.11% | Infer: 3.12 ms/batch
  Batch [400/500] Top-1: 82.16% | Top-5: 95.95% | Infer: 3.12 ms/batch
  Batch [410/500] Top-1: 81.84% | Top-5: 96.05% | Infer: 3.10 ms/batch
  Batch [420/500] Top-1: 81.79% | Top-5: 95.90% | Infer: 3.10 ms/batch
  Batch [430/500] Top-1: 82.00% | Top-5: 96.00% | Infer: 3.08 ms/batch
  Batch [440/500] Top-1: 81.71% | Top-5: 96.10% | Infer: 3.08 ms/batch
  Batch [450/500] Top-1: 82.14% | Top-5: 96.19% | Infer: 3.07 ms/batch
  Batch [460/500] Top-1: 82.56% | Top-5: 96.28% | Infer: 3.08 ms/batch
  Batch [470/500] Top-1: 82.95% | Top-5: 96.36% | Infer: 3.08 ms/batch
  Batch [480/500] Top-1: 83.33% | Top-5: 96.44% | Infer: 3.10 ms/batch
  Batch [490/500] Top-1: 83.48% | Top-5: 96.52% | Infer: 3.11 ms/batch
  Batch [500/500] Top-1: 83.83% | Top-5: 96.60% | Infer: 3.09 ms/batch
[runner] Results saved: ../runs/resnet18_pytorch_fp32_in8b_cuda_bs1/result.json
resnet18_pytorch_fp32_in8b_cuda_bs1 ok 83.82978723404256

In [8]:
# Always load from disk (the source of truth)
runs = load_runs("../runs", status="ok")
rows = flatten_runs(runs)
df = pd.DataFrame(rows)

# Filter to just this notebook’s scope (pytorch + no input quant)
df_baselines = df[
    (df["cfg.backend"] == "pytorch")
    & (df["cfg.input_quant_bits"] == 8)
    & (df["cfg.model_precision"].isin(["fp32"]))
].copy()

df_baselines[[
    "run_id",
    "cfg.backend",
    "cfg.device",
    "cfg.batch_size",
    "cfg.model_precision",
    "cfg.input_quant_bits",
    "res.top1_acc",
    "res.top5_acc",
    "res.infer_ms_avg",
    "res.throughput_infer_sps",
    "res.total_samples",
]].sort_values(["cfg.model_precision", "cfg.device"])

,run_id,cfg.backend,cfg.device,cfg.batch_size,cfg.model_precision,cfg.input_quant_bits,res.top1_acc,res.top5_acc,res.infer_ms_avg,res.throughput_infer_sps,res.total_samples
0,resnet18_pytorch_fp32_in8b_cuda_bs1,pytorch,cuda,1,fp32,8,83.829787,96.595745,3.093748,323.232546,470

In [9]:
cfg16 = with_overrides(base, model_precision="fp16")

payload, tracker = run_experiment(cfg16, save_results_flag=True)

# quick peek
print(payload["run_id"], payload["status"], payload["results"].get("top1_acc"))

[data] Filtered to 5000 samples across 100 classes.
Evaluating on 500 batches (first 30 are warmup)...
  --- Warmup complete (30 batches) — starting metric collection ---
  Batch [40/500] Top-1: 90.00% | Top-5: 100.00% | Infer: 2.34 ms/batch
  Batch [50/500] Top-1: 95.00% | Top-5: 100.00% | Infer: 2.74 ms/batch
  Batch [60/500] Top-1: 96.67% | Top-5: 100.00% | Infer: 2.71 ms/batch
  Batch [70/500] Top-1: 97.50% | Top-5: 100.00% | Infer: 2.66 ms/batch
  Batch [80/500] Top-1: 94.00% | Top-5: 98.00% | Infer: 2.77 ms/batch
  Batch [90/500] Top-1: 95.00% | Top-5: 98.33% | Infer: 2.78 ms/batch
  Batch [100/500] Top-1: 94.29% | Top-5: 98.57% | Infer: 2.64 ms/batch
  Batch [110/500] Top-1: 95.00% | Top-5: 98.75% | Infer: 2.68 ms/batch
  Batch [120/500] Top-1: 93.33% | Top-5: 98.89% | Infer: 2.72 ms/batch
  Batch [130/500] Top-1: 94.00% | Top-5: 99.00% | Infer: 2.67 ms/batch
  Batch [140/500] Top-1: 92.73% | Top-5: 99.09% | Infer: 2.61 ms/batch
  Batch [150/500] Top-1: 91.67% | Top-5: 99.17% | Infer: 2.64 ms/batch
  Batch [160/500] Top-1: 90.77% | Top-5: 99.23% | Infer: 2.68 ms/batch
  Batch [170/500] Top-1: 87.86% | Top-5: 99.29% | Infer: 2.75 ms/batch
  Batch [180/500] Top-1: 88.00% | Top-5: 98.67% | Infer: 2.79 ms/batch
  Batch [190/500] Top-1: 86.88% | Top-5: 98.12% | Infer: 2.76 ms/batch
  Batch [200/500] Top-1: 86.47% | Top-5: 98.24% | Infer: 2.73 ms/batch
  Batch [210/500] Top-1: 86.11% | Top-5: 97.22% | Infer: 2.79 ms/batch
  Batch [220/500] Top-1: 86.32% | Top-5: 96.84% | Infer: 2.84 ms/batch
  Batch [230/500] Top-1: 85.00% | Top-5: 97.00% | Infer: 2.84 ms/batch
  Batch [240/500] Top-1: 84.76% | Top-5: 96.67% | Infer: 2.87 ms/batch
  Batch [250/500] Top-1: 85.45% | Top-5: 96.82% | Infer: 2.90 ms/batch
  Batch [260/500] Top-1: 85.65% | Top-5: 96.96% | Infer: 2.89 ms/batch
  Batch [270/500] Top-1: 85.42% | Top-5: 96.67% | Infer: 2.91 ms/batch
  Batch [280/500] Top-1: 85.60% | Top-5: 96.80% | Infer: 2.90 ms/batch
  Batch [290/500] Top-1: 85.38% | Top-5: 96.92% | Infer: 2.89 ms/batch
  Batch [300/500] Top-1: 85.19% | Top-5: 96.67% | Infer: 2.88 ms/batch
  Batch [310/500] Top-1: 85.00% | Top-5: 96.79% | Infer: 2.90 ms/batch
  Batch [320/500] Top-1: 85.17% | Top-5: 96.90% | Infer: 2.90 ms/batch
  Batch [330/500] Top-1: 84.67% | Top-5: 97.00% | Infer: 2.92 ms/batch
  Batch [340/500] Top-1: 84.19% | Top-5: 97.10% | Infer: 2.91 ms/batch
  Batch [350/500] Top-1: 83.75% | Top-5: 96.88% | Infer: 2.90 ms/batch
  Batch [360/500] Top-1: 83.33% | Top-5: 96.67% | Infer: 2.92 ms/batch
  Batch [370/500] Top-1: 82.65% | Top-5: 96.18% | Infer: 2.91 ms/batch
  Batch [380/500] Top-1: 82.29% | Top-5: 96.29% | Infer: 2.93 ms/batch
  Batch [390/500] Top-1: 82.50% | Top-5: 96.11% | Infer: 2.93 ms/batch
  Batch [400/500] Top-1: 82.16% | Top-5: 95.95% | Infer: 2.92 ms/batch
  Batch [410/500] Top-1: 81.84% | Top-5: 96.05% | Infer: 2.91 ms/batch
  Batch [420/500] Top-1: 81.79% | Top-5: 95.90% | Infer: 2.90 ms/batch
  Batch [430/500] Top-1: 82.00% | Top-5: 96.00% | Infer: 2.89 ms/batch
  Batch [440/500] Top-1: 81.71% | Top-5: 96.10% | Infer: 2.88 ms/batch
  Batch [450/500] Top-1: 82.14% | Top-5: 96.19% | Infer: 2.88 ms/batch
  Batch [460/500] Top-1: 82.56% | Top-5: 96.28% | Infer: 2.89 ms/batch
  Batch [470/500] Top-1: 82.95% | Top-5: 96.36% | Infer: 2.90 ms/batch
  Batch [480/500] Top-1: 83.33% | Top-5: 96.44% | Infer: 2.89 ms/batch
  Batch [490/500] Top-1: 83.48% | Top-5: 96.52% | Infer: 2.87 ms/batch
  Batch [500/500] Top-1: 83.83% | Top-5: 96.60% | Infer: 2.89 ms/batch
[runner] Results saved: ../runs/resnet18_pytorch_fp16_in8b_cuda_bs1/result.json
resnet18_pytorch_fp16_in8b_cuda_bs1 ok 83.82978723404256

In [10]:
# Always load from disk (the source of truth)
runs = load_runs("../runs", status="ok")
rows = flatten_runs(runs)
df = pd.DataFrame(rows)

# Filter to just this notebook’s scope (pytorch + no input quant)
df_baselines = df[
    (df["cfg.backend"] == "pytorch")
    & (df["cfg.input_quant_bits"] == 8)
    & (df["cfg.model_precision"].isin(["fp16"]))
].copy()

df_baselines[[
    "run_id",
    "cfg.backend",
    "cfg.device",
    "cfg.batch_size",
    "cfg.model_precision",
    "cfg.input_quant_bits",
    "res.top1_acc",
    "res.top5_acc",
    "res.infer_ms_avg",
    "res.throughput_infer_sps",
    "res.total_samples",
]].sort_values(["cfg.model_precision", "cfg.device"])

,run_id,cfg.backend,cfg.device,cfg.batch_size,cfg.model_precision,cfg.input_quant_bits,res.top1_acc,res.top5_acc,res.infer_ms_avg,res.throughput_infer_sps,res.total_samples
0,resnet18_pytorch_fp16_in8b_cuda_bs1,pytorch,cuda,1,fp16,8,83.829787,96.595745,2.885167,346.600371,470

In [11]:
runs = load_runs("../runs", status="ok")
rows = flatten_runs(runs)
df = pd.DataFrame(rows)

df_baselines = df[
    (df["cfg.backend"] == "pytorch")
    & (df["cfg.input_quant_bits"] == 8)
    & (df["cfg.model_precision"].isin(["fp32", "fp16"]))
].copy()

df_baselines[[
    "run_id",
    "cfg.model_precision",
    "res.infer_ms_avg",
    "res.infer_ms_min",
    "res.infer_ms_max",
]].sort_values("cfg.model_precision")

,run_id,cfg.model_precision,res.infer_ms_avg,res.infer_ms_min,res.infer_ms_max
0,resnet18_pytorch_fp16_in8b_cuda_bs1,fp16,2.885167,1.041826,6.366387
1,resnet18_pytorch_fp32_in8b_cuda_bs1,fp32,3.093748,1.236312,6.725033